import type { ReviewGuideCard } from "@/lib/review-types";

/**
 * "ENTIÉNDELO FÁCIL" — the seven basics of BE ABOUT TO in the present and past.
 * Static hand-written content: never generated by AI.
 */
export const ABOUT_TO_GUIDE: ReviewGuideCard[] = [
  {
    id: "abt-1-use",
    title: "What be about to means",
    titleEs: "Qué significa be about to",
    explanation: "Something happens in seconds or minutes: I am about to sleep.",
    explanationEs:
      "Be about to = estar a punto de. Es el futuro INMEDIATO: pasa en segundos o minutos, no mañana. I am about to sleep = Estoy a punto de dormir. Se usa muchísimo hablando por teléfono y en el trabajo.",
    examples: [
      { en: "I am about to sleep.", es: "Estoy a punto de dormir." },
      { en: "The meeting is about to start.", es: "La reunión está a punto de empezar." },
      { en: "We are about to leave.", es: "Estamos a punto de salir." },
    ],
    check: {
      prompt: "Say what you are about to do after this practice.",
      promptEs: "Di qué estás a punto de hacer después de esta práctica.",
      answer: "I am about to …",
    },
  },
  {
    id: "abt-2-present",
    title: "Present: am / is / are about to + base verb",
    titleEs: "Presente: am / is / are about to + verbo base",
    explanation: "I'm about to call. She's about to leave. They're about to close.",
    explanationEs:
      "Fórmula: sujeto + am / is / are + about to + verbo en forma base (sin to extra, sin -ing). I'm about to call him. NO digas “I'm about to calling” ni “I'm about to to call”.",
    examples: [
      { en: "I'm about to call the customer.", es: "Estoy a punto de llamar al cliente." },
      { en: "She's about to finish her shift.", es: "Ella está a punto de terminar su turno." },
      { en: "The store is about to close.", es: "La tienda está a punto de cerrar." },
    ],
    check: {
      prompt: "Say: La clase está a punto de empezar.",
      promptEs: "Di en inglés: La clase está a punto de empezar.",
      answer: "The class is about to start.",
    },
  },
  {
    id: "abt-3-past",
    title: "Past: was / were about to + base verb",
    titleEs: "Pasado: was / were about to + verbo base",
    explanation: "I was about to call you. They were about to leave.",
    explanationEs:
      "Was / were about to = estaba a punto de. Casi siempre cuenta algo que NO pasó o que fue interrumpido: I was about to call you, but my phone died. Es perfecto para explicar coincidencias y excusas reales.",
    examples: [
      { en: "I was about to call you.", es: "Estaba a punto de llamarte." },
      { en: "We were about to eat when he arrived.", es: "Estábamos a punto de comer cuando él llegó." },
      { en: "She was about to answer the phone.", es: "Ella estaba a punto de contestar el teléfono." },
    ],
    check: {
      prompt: "Say: Estaba a punto de salir cuando llovió.",
      promptEs: "Di en inglés: Estaba a punto de salir cuando llovió.",
      answer: "I was about to leave when it rained.",
    },
  },
  {
    id: "abt-4-but",
    title: "The classic pattern: … was about to …, but …",
    titleEs: "El patrón clásico: … was about to …, but …",
    explanation: "I was about to sleep, but my boss called.",
    explanationEs:
      "El uso más natural del pasado es con but o when: I was about to send the email, but the system crashed. She was about to leave when the client arrived. Primero la intención, después la interrupción.",
    examples: [
      { en: "I was about to sleep, but my boss called.", es: "Estaba a punto de dormir, pero mi jefe llamó." },
      { en: "He was about to pay when he lost his card.", es: "Estaba a punto de pagar cuando perdió su tarjeta." },
      { en: "We were about to start, but the client was late.", es: "Estábamos a punto de empezar, pero el cliente llegó tarde." },
    ],
    check: {
      prompt: "Finish: I was about to study, but …",
      promptEs: "Termina la frase: I was about to study, but …",
      answer: "… but my friend arrived.",
    },
  },
  {
    id: "abt-5-negative",
    title: "Negatives and questions",
    titleEs: "Negativas y preguntas",
    explanation: "I'm not about to give up. Are you about to leave? Were you about to call?",
    explanationEs:
      "Negativo: not va después de be. I'm not about to give up (también significa “no pienso rendirme”). Pregunta: be al inicio. Are you about to leave? Was he about to say something? What were you about to say?",
    examples: [
      { en: "Are you about to leave the office?", es: "¿Estás a punto de salir de la oficina?" },
      { en: "What were you about to say?", es: "¿Qué estabas a punto de decir?" },
      { en: "I'm not about to quit my job.", es: "No estoy a punto de renunciar a mi trabajo." },
    ],
    check: {
      prompt: "Ask: ¿Estabas a punto de llamarme?",
      promptEs: "Pregunta en inglés: ¿Estabas a punto de llamarme?",
      answer: "Were you about to call me?",
    },
  },
  {
    id: "abt-6-just",
    title: "just about to and on the point of",
    titleEs: "just about to y on the point of",
    explanation: "just makes it even closer: I was just about to text you.",
    explanationEs:
      "Agrega just para decir “justo a punto”: I was just about to text you. Más formal: I was on the point of leaving. En conversación real, just about to es lo más común y suena muy natural.",
    examples: [
      { en: "I was just about to text you.", es: "Justo estaba a punto de escribirte." },
      { en: "She's just about to go on stage.", es: "Ella está justo a punto de salir al escenario." },
      { en: "He was on the point of leaving.", es: "Él estaba a punto de irse." },
    ],
    check: {
      prompt: "Say: Justo estaba a punto de mandarte el reporte.",
      promptEs: "Di en inglés: Justo estaba a punto de mandarte el reporte.",
      answer: "I was just about to send you the report.",
    },
  },
  {
    id: "abt-7-compare",
    title: "about to vs going to vs will",
    titleEs: "about to vs going to vs will",
    explanation: "about to = seconds. going to = a plan. will = a decision now.",
    explanationEs:
      "about to = ya casi, en segundos (The bus is about to leave). going to = un plan que ya tenías (I'm going to travel in July). will = decisión del momento o promesa (I'll help you). Si dices “about to” de algo de la próxima semana, suena raro.",
    examples: [
      { en: "The bus is about to leave.", es: "El bus está a punto de salir." },
      { en: "I'm going to visit my family in July.", es: "Voy a visitar a mi familia en julio." },
      { en: "I'll call you back in a minute.", es: "Te llamo en un minuto." },
    ],
    check: {
      prompt: "Which one for next month: about to or going to?",
      promptEs: "¿Cuál se usa para el próximo mes: about to o going to?",
      answer: "going to",
    },
  },
];

export const ABOUT_TO_COMMON_ERRORS: { wrong: string; right: string; es: string }[] = [
  { wrong: "I am about to sleeping.", right: "I am about to sleep.", es: "Después de about to va el verbo base, no -ing." },
  { wrong: "I about to call you.", right: "I am about to call you.", es: "Nunca olvides el verbo be: am / is / are." },
  { wrong: "I was about to called you.", right: "I was about to call you.", es: "El verbo va en base aunque la frase sea pasado." },
  { wrong: "She is about to travel next month.", right: "She is going to travel next month.", es: "About to es para segundos o minutos, no para el próximo mes." },
  { wrong: "We was about to leave.", right: "We were about to leave.", es: "Plural lleva were, no was." },
  { wrong: "Are you about leave?", right: "Are you about to leave?", es: "La expresión completa es about TO + verbo." },
];
