import type { ReviewPractice } from "@/lib/review-types";

/**
 * REVIEW · COMPARATIVES — five static practices (short -er vs long more).
 *
 * Person of the learner's MAIN answers alternates: 3rd · 1st · 3rd · 1st · 3rd.
 * Every practice mixes SHORT adjectives (+er), LONG adjectives (more …) and the
 * irregulars better / worse / farther. Hand-written content: nothing generated.
 */
export const COMPARATIVES_PRACTICES: ReviewPractice[] = [
  {
    number: 1,
    id: "cmp-1-camila-jobs",
    title: "Camila compares her two jobs",
    titleEs: "Camila compara sus dos trabajos",
    person: "third",
    character: "Camila",
    focus: "Third person comparatives with short (-er) and long (more …) adjectives plus than.",
    focusEs: "Comparativos en tercera persona con adjetivos cortos (-er) y largos (more …) y la palabra than.",
    reminder: {
      en: "Short adjective + er, long adjective with more, and always than between the two things.",
      es: "Adjetivo corto + er, adjetivo largo con more, y siempre than entre las dos cosas.",
    },
    showFullGuide: true,
    instructions: {
      en: "Camila changed jobs this year. Compare her new job with her old job.",
      es: "Camila cambió de trabajo este año. Compara su trabajo nuevo con el anterior.",
    },
    vocabulary: ["better", "cheaper", "faster", "closer", "more comfortable", "more difficult", "than", "much"],
    lines: [
      { id: "cmp1-l1", text: "Camila's new job is better than her old job.", es: "El trabajo nuevo de Camila es mejor que el anterior.", chunks: ["Camila's new job", "is better", "than her old job."] },
      { id: "cmp1-l2", text: "The new office is closer to her house.", es: "La oficina nueva está más cerca de su casa.", chunks: ["The new office", "is closer", "to her house."] },
      { id: "cmp1-l3", text: "Her trip to work is much shorter now.", es: "Su viaje al trabajo es mucho más corto ahora.", chunks: ["Her trip to work", "is much shorter", "now."] },
      { id: "cmp1-l4", text: "The salary is higher, but the tasks are more difficult.", es: "El salario es más alto, pero las tareas son más difíciles.", chunks: ["The salary is higher,", "but the tasks", "are more difficult."] },
      { id: "cmp1-l5", text: "Her new team is smaller and more organized.", es: "Su equipo nuevo es más pequeño y más organizado.", chunks: ["Her new team", "is smaller", "and more organized."] },
      { id: "cmp1-l6", text: "The chairs are more comfortable than the old ones.", es: "Las sillas son más cómodas que las anteriores.", chunks: ["The chairs", "are more comfortable", "than the old ones."] },
      { id: "cmp1-l7", text: "Her schedule is easier because she starts later.", es: "Su horario es más fácil porque empieza más tarde.", chunks: ["Her schedule is easier", "because she starts later."] },
      { id: "cmp1-l8", text: "She says the change was worse at first, but now it is great.", es: "Dice que el cambio fue peor al principio, pero ahora está genial.", chunks: ["She says the change", "was worse at first,", "but now it is great."] },
    ],
    questions: [
      { id: "cmp1-q1", question: "What is better in Camila's new job?", questionEs: "¿Qué es mejor en el trabajo nuevo de Camila?", hint: "Her new job is better because…", hintEs: "Usa better than." },
      { id: "cmp1-q2", question: "Where is her office now, closer or farther?", questionEs: "¿Dónde está su oficina ahora, más cerca o más lejos?", hint: "Her office is…", hintEs: "closer / farther than antes." },
      { id: "cmp1-q3", question: "Why are the tasks more difficult now?", questionEs: "¿Por qué son más difíciles las tareas ahora?", hint: "They are more difficult because…", hintEs: "Adjetivo largo: more difficult." },
      { id: "cmp1-q4", question: "Who has a smaller team, Camila or her old manager?", questionEs: "¿Quién tiene un equipo más pequeño, Camila o su jefe anterior?", hint: "Camila has…", hintEs: "small → smaller." },
      { id: "cmp1-q5", question: "How is her schedule different from before?", questionEs: "¿En qué es diferente su horario comparado con antes?", hint: "Her schedule is easier because…", hintEs: "easy → easier." },
      { id: "cmp1-q6", question: "What time does she start now, earlier or later?", questionEs: "¿A qué hora empieza ahora, más temprano o más tarde?", hint: "She starts…", hintEs: "earlier / later than antes." },
    ],
    finalPrompt: {
      question: "Compare Camila's new job with her old job: salary, office, team and schedule.",
      questionEs: "Compara el trabajo nuevo de Camila con el anterior: salario, oficina, equipo y horario.",
      tips: {
        en: "Use at least three short comparatives (+er), two long ones (more …) and one irregular (better / worse).",
        es: "Usa al menos tres comparativos cortos (+er), dos largos (more …) y uno irregular (better / worse).",
      },
    },
    grammarGoals: [
      "short adjectives with -er and than",
      "long adjectives with more + adjective",
      "irregular comparatives better and worse",
    ],
  },
  {
    number: 2,
    id: "cmp-2-your-life-now",
    title: "Your life now and five years ago",
    titleEs: "Tu vida ahora y hace cinco años",
    person: "first",
    character: null,
    focus: "First person comparatives about your own life, with much / a little and negatives.",
    focusEs: "Comparativos en primera persona sobre tu vida, con much / a little y negativas.",
    reminder: {
      en: "Say than, not that. And never say more better: better is already a comparative.",
      es: "Se dice than, no that. Y nunca digas more better: better ya es comparativo.",
    },
    showFullGuide: false,
    instructions: {
      en: "Compare your life today with your life five years ago.",
      es: "Compara tu vida de hoy con tu vida de hace cinco años.",
    },
    vocabulary: ["better", "worse", "busier", "cheaper", "more expensive", "much", "a little", "than"],
    lines: [
      { id: "cmp2-l1", text: "My life today is busier than five years ago.", es: "Mi vida hoy es más ocupada que hace cinco años.", chunks: ["My life today", "is busier", "than five years ago."] },
      { id: "cmp2-l2", text: "My English is much better now.", es: "Mi inglés es mucho mejor ahora.", chunks: ["My English", "is much better", "now."] },
      { id: "cmp2-l3", text: "Everything is more expensive than before.", es: "Todo es más caro que antes.", chunks: ["Everything is", "more expensive", "than before."] },
      { id: "cmp2-l4", text: "My trip to work is a little longer than in my last job.", es: "Mi viaje al trabajo es un poco más largo que en mi trabajo anterior.", chunks: ["My trip to work", "is a little longer", "than in my last job."] },
      { id: "cmp2-l5", text: "I sleep less, so some mornings are harder.", es: "Duermo menos, así que algunas mañanas son más duras.", chunks: ["I sleep less,", "so some mornings", "are harder."] },
      { id: "cmp2-l6", text: "My routine is not as simple as before, but it is better.", es: "Mi rutina no es tan simple como antes, pero es mejor.", chunks: ["My routine", "is not as simple as before,", "but it is better."] },
      { id: "cmp2-l7", text: "I am more confident when I speak English.", es: "Estoy más seguro cuando hablo inglés.", chunks: ["I am more confident", "when I speak English."] },
      { id: "cmp2-l8", text: "My weekends are shorter, but they are more fun.", es: "Mis fines de semana son más cortos, pero son más divertidos.", chunks: ["My weekends are shorter,", "but they are more fun."] },
    ],
    questions: [
      { id: "cmp2-q1", question: "How long is your trip to work compared to before?", questionEs: "¿Cuánto dura tu viaje al trabajo comparado con antes?", hint: "It is longer / shorter than…", hintEs: "Usa longer o shorter than." },
      { id: "cmp2-q2", question: "What is better in your life now than five years ago?", questionEs: "¿Qué es mejor en tu vida ahora que hace cinco años?", hint: "My … is better than…", hintEs: "Usa better than, nunca more better." },
      { id: "cmp2-q3", question: "How often do you practice English now, more or less than before?", questionEs: "¿Con qué frecuencia practicas inglés ahora, más o menos que antes?", hint: "I practice… more than…", hintEs: "Di la frecuencia y compara." },
      { id: "cmp2-q4", question: "Why is your routine busier or easier now?", questionEs: "¿Por qué tu rutina es más ocupada o más fácil ahora?", hint: "It is busier because…", hintEs: "busy → busier." },
      { id: "cmp2-q5", question: "Who is more organized, you now or you five years ago?", questionEs: "¿Quién es más organizado, tú ahora o tú hace cinco años?", hint: "I am more organized now because…", hintEs: "Adjetivo largo: more organized." },
      { id: "cmp2-q6", question: "Where do you live now, closer or farther from work?", questionEs: "¿Dónde vives ahora, más cerca o más lejos del trabajo?", hint: "I live closer / farther…", hintEs: "far → farther." },
    ],
    finalPrompt: {
      question: "Compare your life today with your life five years ago: work, money, English and free time.",
      questionEs: "Compara tu vida de hoy con la de hace cinco años: trabajo, dinero, inglés y tiempo libre.",
      tips: {
        en: "Use than in every comparison, add much or a little once, and use better and worse correctly.",
        es: "Usa than en cada comparación, agrega much o a little una vez y usa bien better y worse.",
      },
    },
    grammarGoals: [
      "first person comparatives with than",
      "much / a little + comparative",
      "not as … as for things that are not equal",
    ],
  },
  {
    number: 3,
    id: "cmp-3-andres-phones",
    title: "Andrés compares two phones",
    titleEs: "Andrés compara dos teléfonos",
    person: "third",
    character: "Andrés",
    focus: "Comparing two products: price, size, speed and quality with short and long adjectives.",
    focusEs: "Comparar dos productos: precio, tamaño, velocidad y calidad con adjetivos cortos y largos.",
    reminder: {
      en: "Cheap, big, fast take -er. Expensive, comfortable, practical take more.",
      es: "Cheap, big, fast llevan -er. Expensive, comfortable, practical llevan more.",
    },
    showFullGuide: false,
    instructions: {
      en: "Andrés is choosing between two phones in a store. Compare them.",
      es: "Andrés está eligiendo entre dos teléfonos en una tienda. Compáralos.",
    },
    vocabulary: ["cheaper", "bigger", "faster", "lighter", "more expensive", "more practical", "better", "than"],
    lines: [
      { id: "cmp3-l1", text: "The black phone is more expensive than the white one.", es: "El teléfono negro es más caro que el blanco.", chunks: ["The black phone", "is more expensive", "than the white one."] },
      { id: "cmp3-l2", text: "The white phone is cheaper, but the camera is worse.", es: "El teléfono blanco es más barato, pero la cámara es peor.", chunks: ["The white phone is cheaper,", "but the camera is worse."] },
      { id: "cmp3-l3", text: "The black phone has a bigger screen.", es: "El teléfono negro tiene una pantalla más grande.", chunks: ["The black phone", "has a bigger screen."] },
      { id: "cmp3-l4", text: "The white phone is lighter and easier to carry.", es: "El blanco es más liviano y más fácil de cargar.", chunks: ["The white phone is lighter", "and easier to carry."] },
      { id: "cmp3-l5", text: "The battery of the black phone lasts longer.", es: "La batería del negro dura más.", chunks: ["The battery", "of the black phone", "lasts longer."] },
      { id: "cmp3-l6", text: "For his work, a bigger screen is more practical.", es: "Para su trabajo, una pantalla más grande es más práctica.", chunks: ["For his work,", "a bigger screen", "is more practical."] },
      { id: "cmp3-l7", text: "The white phone is not as fast as the black one.", es: "El blanco no es tan rápido como el negro.", chunks: ["The white phone", "is not as fast", "as the black one."] },
      { id: "cmp3-l8", text: "Andrés says the black phone is better for him.", es: "Andrés dice que el negro es mejor para él.", chunks: ["Andrés says", "the black phone", "is better for him."] },
    ],
    questions: [
      { id: "cmp3-q1", question: "What is more expensive, the black phone or the white phone?", questionEs: "¿Qué es más caro, el teléfono negro o el blanco?", hint: "The black phone is…", hintEs: "Adjetivo largo: more expensive than." },
      { id: "cmp3-q2", question: "Why is the white phone easier to carry?", questionEs: "¿Por qué el teléfono blanco es más fácil de cargar?", hint: "Because it is lighter…", hintEs: "light → lighter, easy → easier." },
      { id: "cmp3-q3", question: "Who needs a bigger screen, Andrés or a student?", questionEs: "¿Quién necesita una pantalla más grande, Andrés o un estudiante?", hint: "Andrés needs…", hintEs: "big → bigger." },
      { id: "cmp3-q4", question: "How long does each battery last?", questionEs: "¿Cuánto dura cada batería?", hint: "The black battery lasts longer than…", hintEs: "Usa longer than." },
      { id: "cmp3-q5", question: "Where can he find a cheaper price?", questionEs: "¿Dónde puede encontrar un precio más barato?", hint: "He can find it…", hintEs: "cheap → cheaper." },
      { id: "cmp3-q6", question: "What is the better option for Andrés and why?", questionEs: "¿Cuál es la mejor opción para Andrés y por qué?", hint: "The better option is… because…", hintEs: "Usa better, nunca more better." },
    ],
    finalPrompt: {
      question: "Compare the two phones and say which one is better for Andrés and why.",
      questionEs: "Compara los dos teléfonos y di cuál es mejor para Andrés y por qué.",
      tips: {
        en: "Compare price, size, speed and battery, and finish with a decision using better than.",
        es: "Compara precio, tamaño, velocidad y batería, y termina con una decisión usando better than.",
      },
    },
    grammarGoals: [
      "comparatives of short adjectives with spelling changes (bigger, lighter, easier)",
      "more + long adjective (more expensive, more practical)",
      "not as … as and better for a final decision",
    ],
  },
  {
    number: 4,
    id: "cmp-4-two-options",
    title: "You compare two options",
    titleEs: "Tú comparas dos opciones",
    person: "first",
    character: null,
    focus: "First person comparatives to explain a real decision: two options, one choice.",
    focusEs: "Comparativos en primera persona para explicar una decisión real: dos opciones, una elección.",
    reminder: {
      en: "One idea per sentence: A is + comparative + than B, and then why.",
      es: "Una idea por oración: A is + comparativo + than B, y después el porqué.",
    },
    showFullGuide: false,
    instructions: {
      en: "Compare two real options in your life: two jobs, two schools, two cities or two ways to travel.",
      es: "Compara dos opciones reales de tu vida: dos trabajos, dos escuelas, dos ciudades o dos formas de viajar.",
    },
    vocabulary: ["safer", "cheaper", "faster", "more comfortable", "more useful", "better", "worse", "than"],
    lines: [
      { id: "cmp4-l1", text: "I always compare two options before I decide.", es: "Siempre comparo dos opciones antes de decidir.", chunks: ["I always compare", "two options", "before I decide."] },
      { id: "cmp4-l2", text: "The bus is cheaper than a taxi, but it is slower.", es: "El bus es más barato que un taxi, pero es más lento.", chunks: ["The bus is cheaper", "than a taxi,", "but it is slower."] },
      { id: "cmp4-l3", text: "A taxi is more comfortable and safer at night.", es: "El taxi es más cómodo y más seguro de noche.", chunks: ["A taxi is more comfortable", "and safer at night."] },
      { id: "cmp4-l4", text: "For me, saving money is more important than speed.", es: "Para mí, ahorrar dinero es más importante que la rapidez.", chunks: ["For me, saving money", "is more important", "than speed."] },
      { id: "cmp4-l5", text: "Studying online is easier than going to a school.", es: "Estudiar en línea es más fácil que ir a una escuela.", chunks: ["Studying online is easier", "than going to a school."] },
      { id: "cmp4-l6", text: "But a real class is better for my speaking.", es: "Pero una clase real es mejor para mi speaking.", chunks: ["But a real class", "is better", "for my speaking."] },
      { id: "cmp4-l7", text: "My first option is not as expensive as the second one.", es: "Mi primera opción no es tan cara como la segunda.", chunks: ["My first option", "is not as expensive", "as the second one."] },
      { id: "cmp4-l8", text: "In the end I choose the option that is better for my goals.", es: "Al final elijo la opción que es mejor para mis metas.", chunks: ["In the end I choose", "the option that is better", "for my goals."] },
    ],
    questions: [
      { id: "cmp4-q1", question: "What two options are you comparing today?", questionEs: "¿Qué dos opciones estás comparando hoy?", hint: "I am comparing… and…", hintEs: "Nombra las dos opciones." },
      { id: "cmp4-q2", question: "Why is one option cheaper or more expensive?", questionEs: "¿Por qué una opción es más barata o más cara?", hint: "It is cheaper because…", hintEs: "Usa cheaper / more expensive than." },
      { id: "cmp4-q3", question: "How long does each option take?", questionEs: "¿Cuánto tiempo toma cada opción?", hint: "The first one takes… and the second one takes…", hintEs: "Compara con longer / shorter." },
      { id: "cmp4-q4", question: "Who gives you better advice about this decision?", questionEs: "¿Quién te da mejores consejos sobre esta decisión?", hint: "My … gives me better advice.", hintEs: "good → better." },
      { id: "cmp4-q5", question: "Where is the safer option, at home or outside?", questionEs: "¿Dónde está la opción más segura, en casa o afuera?", hint: "The safer option is…", hintEs: "safe → safer." },
      { id: "cmp4-q6", question: "When is the faster option worse for you?", questionEs: "¿Cuándo es peor para ti la opción más rápida?", hint: "It is worse when…", hintEs: "bad → worse." },
    ],
    finalPrompt: {
      question: "Compare your two options and explain which one you choose and why.",
      questionEs: "Compara tus dos opciones y explica cuál eliges y por qué.",
      tips: {
        en: "Give at least four comparisons with than, mix short and long adjectives, and end with your decision.",
        es: "Da al menos cuatro comparaciones con than, mezcla adjetivos cortos y largos y termina con tu decisión.",
      },
    },
    grammarGoals: [
      "comparatives to justify a personal decision",
      "mixing -er and more + adjective in the same story",
      "better and worse used correctly",
    ],
  },
  {
    number: 5,
    id: "cmp-5-lucia-teams",
    title: "Lucía compares two teams",
    titleEs: "Lucía compara dos equipos",
    person: "third",
    character: "Lucía",
    focus: "Free description from facts: comparing two work teams with all comparative forms.",
    focusEs: "Descripción libre a partir de datos: comparar dos equipos de trabajo con todas las formas comparativas.",
    reminder: {
      en: "Build each sentence with: A is + comparative + than B.",
      es: "Arma cada oración con: A is + comparativo + than B.",
    },
    showFullGuide: false,
    instructions: {
      en: "Use the facts to compare the morning team and the night team.",
      es: "Usa los datos para comparar el equipo de la mañana y el de la noche.",
    },
    vocabulary: ["bigger", "faster", "quieter", "more experienced", "more organized", "better", "worse", "than"],
    lines: [
      { id: "cmp5-l1", text: "Lucía works with two teams in the same company.", es: "Lucía trabaja con dos equipos en la misma empresa.", chunks: ["Lucía works", "with two teams", "in the same company."] },
      { id: "cmp5-l2", text: "The morning team is bigger than the night team.", es: "El equipo de la mañana es más grande que el de la noche.", chunks: ["The morning team is bigger", "than the night team."] },
      { id: "cmp5-l3", text: "The night team is quieter and more focused.", es: "El equipo de la noche es más silencioso y más concentrado.", chunks: ["The night team is quieter", "and more focused."] },
      { id: "cmp5-l4", text: "The morning agents are faster on the phone.", es: "Los agentes de la mañana son más rápidos al teléfono.", chunks: ["The morning agents", "are faster", "on the phone."] },
      { id: "cmp5-l5", text: "The night agents are more experienced with difficult clients.", es: "Los agentes de la noche tienen más experiencia con clientes difíciles.", chunks: ["The night agents", "are more experienced", "with difficult clients."] },
      { id: "cmp5-l6", text: "The morning results are better, but the night results are improving.", es: "Los resultados de la mañana son mejores, pero los de la noche están mejorando.", chunks: ["The morning results are better,", "but the night results", "are improving."] },
      { id: "cmp5-l7", text: "The night shift is harder because the calls are longer.", es: "El turno de noche es más duro porque las llamadas son más largas.", chunks: ["The night shift is harder", "because the calls are longer."] },
      { id: "cmp5-l8", text: "Lucía says both teams are good, but they are not the same.", es: "Lucía dice que ambos equipos son buenos, pero no son iguales.", chunks: ["Lucía says both teams are good,", "but they are not the same."] },
    ],
    factSheet: [
      { en: "Morning team: 12 agents · faster calls · better weekly results", es: "Equipo de mañana: 12 agentes · llamadas más rápidas · mejores resultados semanales" },
      { en: "Night team: 7 agents · quieter office · more experienced agents", es: "Equipo de noche: 7 agentes · oficina más silenciosa · agentes con más experiencia" },
      { en: "Night calls are longer and more difficult", es: "Las llamadas de noche son más largas y más difíciles" },
      { en: "Lucía prefers the night team for training new people", es: "Lucía prefiere el equipo de noche para entrenar gente nueva" },
    ],
    questions: [
      { id: "cmp5-q1", question: "What team is bigger, the morning team or the night team?", questionEs: "¿Qué equipo es más grande, el de la mañana o el de la noche?", hint: "The morning team is…", hintEs: "big → bigger than." },
      { id: "cmp5-q2", question: "Who is more experienced with difficult clients?", questionEs: "¿Quién tiene más experiencia con clientes difíciles?", hint: "The night agents are…", hintEs: "Adjetivo largo: more experienced." },
      { id: "cmp5-q3", question: "Where is the office quieter?", questionEs: "¿Dónde es más silenciosa la oficina?", hint: "The office is quieter…", hintEs: "quiet → quieter." },
      { id: "cmp5-q4", question: "Why is the night shift harder?", questionEs: "¿Por qué el turno de noche es más duro?", hint: "It is harder because the calls are…", hintEs: "hard → harder, long → longer." },
      { id: "cmp5-q5", question: "How long are the night calls compared to the morning calls?", questionEs: "¿Cuánto duran las llamadas de noche comparadas con las de la mañana?", hint: "They are longer than…", hintEs: "Usa longer than." },
      { id: "cmp5-q6", question: "How often does Lucía train new agents at night?", questionEs: "¿Con qué frecuencia entrena Lucía a agentes nuevos de noche?", hint: "She trains them…", hintEs: "Di una frecuencia y compara los turnos." },
    ],
    finalPrompt: {
      question: "Compare the morning team and the night team, and say which one you prefer and why.",
      questionEs: "Compara el equipo de la mañana con el de la noche, y di cuál prefieres y por qué.",
      tips: {
        en: "Use at least five comparisons with than, include better or worse, and finish with your preference.",
        es: "Usa al menos cinco comparaciones con than, incluye better o worse y termina con tu preferencia.",
      },
    },
    grammarGoals: [
      "comparing two groups with short and long adjectives",
      "than in every comparison",
      "better / worse and much + comparative",
    ],
  },
];
