import type { ReviewGuideCard } from "@/lib/review-types";

/**
 * "ENTIÉNDELO FÁCIL" — the seven basics of comparatives (short -er vs long more).
 * Static hand-written content: never generated by AI, reused by every practice
 * (Practice 1 shows it inline in Step 1, practices 2–5 open it on demand).
 */
export const COMPARATIVES_GUIDE: ReviewGuideCard[] = [
  {
    id: "cmp-1-use",
    title: "What it is for",
    titleEs: "Para qué sirve",
    explanation: "A comparative compares TWO things, people or moments. The word than connects them.",
    explanationEs:
      "El comparativo compara DOS cosas, personas o momentos. La palabra than une la comparación: A es más ___ que B. En español dices “más barato QUE”; en inglés es cheaper THAN, nunca “cheaper that” ni “more cheap”.",
    examples: [
      { en: "This job is better than my old job.", es: "Este trabajo es mejor que mi trabajo anterior." },
      { en: "The bus is cheaper than a taxi.", es: "El bus es más barato que un taxi." },
      { en: "Today is more difficult than yesterday.", es: "Hoy es más difícil que ayer." },
    ],
    check: {
      prompt: "Compare two drinks you know with than.",
      promptEs: "Compara dos bebidas que conozcas usando than.",
      answer: "Coffee is cheaper than juice.",
    },
  },
  {
    id: "cmp-2-short",
    title: "Short adjectives: + er",
    titleEs: "Adjetivos cortos: + er",
    explanation: "One-syllable adjectives add -er: cheap → cheaper, fast → faster, small → smaller.",
    explanationEs:
      "Si el adjetivo es corto (una sílaba: cheap, fast, small, tall, old, young, hard), le agregas -er. NO uses more con ellos: “more cheap” está mal, se dice cheaper.",
    examples: [
      { en: "My new phone is faster than the old one.", es: "Mi teléfono nuevo es más rápido que el viejo." },
      { en: "She is taller than her brother.", es: "Ella es más alta que su hermano." },
      { en: "The night shift is harder than the morning shift.", es: "El turno de noche es más duro que el de la mañana." },
    ],
    check: {
      prompt: "Say the comparative of cheap and of old.",
      promptEs: "Di el comparativo de cheap y de old.",
      answer: "cheaper / older",
    },
  },
  {
    id: "cmp-3-spelling",
    title: "Spelling changes",
    titleEs: "Cambios de escritura",
    explanation: "big → bigger, nice → nicer, easy → easier, happy → happier.",
    explanationEs:
      "Tres reglas: 1) consonante final después de vocal se dobla: big → bigger, hot → hotter. 2) si termina en -e, solo agregas -r: nice → nicer, large → larger. 3) si termina en -y, cambia a -ier: easy → easier, busy → busier, happy → happier.",
    examples: [
      { en: "My house is bigger than my old apartment.", es: "Mi casa es más grande que mi apartamento anterior." },
      { en: "This exercise is easier than the last one.", es: "Este ejercicio es más fácil que el anterior." },
      { en: "Mondays are busier than Fridays.", es: "Los lunes son más ocupados que los viernes." },
    ],
    check: {
      prompt: "Say the comparative of easy and of big.",
      promptEs: "Di el comparativo de easy y de big.",
      answer: "easier / bigger",
    },
  },
  {
    id: "cmp-4-long",
    title: "Long adjectives: more + adjective",
    titleEs: "Adjetivos largos: more + adjetivo",
    explanation: "Two or more syllables usually take more: more expensive, more difficult, more important.",
    explanationEs:
      "Si el adjetivo es largo (dos sílabas o más: expensive, difficult, important, comfortable, interesting), usas more + adjetivo y el adjetivo NO cambia. “More expensiver” o “expensiver” están mal.",
    examples: [
      { en: "This laptop is more expensive than that one.", es: "Esta laptop es más cara que esa." },
      { en: "The new process is more complicated than before.", es: "El proceso nuevo es más complicado que antes." },
      { en: "My chair is more comfortable than yours.", es: "Mi silla es más cómoda que la tuya." },
    ],
    check: {
      prompt: "Compare two jobs with more difficult.",
      promptEs: "Compara dos trabajos usando more difficult.",
      answer: "Sales is more difficult than support.",
    },
  },
  {
    id: "cmp-5-irregular",
    title: "Irregular comparatives",
    titleEs: "Comparativos irregulares",
    explanation: "good → better, bad → worse, far → farther / further.",
    explanationEs:
      "Tres se aprenden de memoria: good → better, bad → worse, far → farther (distancia) o further. Nunca digas “more better” ni “gooder”. Better ya significa “mejor”.",
    examples: [
      { en: "My English is better than last year.", es: "Mi inglés es mejor que el año pasado." },
      { en: "Traffic today is worse than yesterday.", es: "El tráfico hoy está peor que ayer." },
      { en: "My office is farther than the store.", es: "Mi oficina está más lejos que la tienda." },
    ],
    check: {
      prompt: "Correct this: My score is more good than before.",
      promptEs: "Corrige: My score is more good than before.",
      answer: "My score is better than before.",
    },
  },
  {
    id: "cmp-6-asas",
    title: "as … as and much / a little",
    titleEs: "as … as y much / a little",
    explanation: "as + adjective + as says they are equal. Much or a little makes the difference bigger or smaller.",
    explanationEs:
      "Para decir que son iguales: as cheap as, as good as. Para decir que NO son iguales: not as expensive as. Y para medir la diferencia: much cheaper (mucho más barato), a little slower (un poco más lento).",
    examples: [
      { en: "This café is as good as the other one.", es: "Este café es tan bueno como el otro." },
      { en: "My new job is much better than my old job.", es: "Mi trabajo nuevo es mucho mejor que el anterior." },
      { en: "The bus is not as fast as the train.", es: "El bus no es tan rápido como el tren." },
    ],
    check: {
      prompt: "Say two things that are equal with as … as.",
      promptEs: "Di dos cosas iguales usando as … as.",
      answer: "Tea is as cheap as coffee.",
    },
  },
  {
    id: "cmp-7-questions",
    title: "Questions and negatives",
    titleEs: "Preguntas y negativas",
    explanation: "Which is better? Who is taller? Why is it more expensive? It isn't cheaper than that one.",
    explanationEs:
      "Para preguntar: Which is better, A or B? Who is taller? What is more useful? Why is it more expensive? En negativo: It isn't cheaper than the other one. El adjetivo comparativo no cambia en la pregunta.",
    examples: [
      { en: "What is more useful for your job, English or Excel?", es: "¿Qué es más útil para tu trabajo, inglés o Excel?" },
      { en: "Who is faster on the phone, you or your coworker?", es: "¿Quién es más rápido al teléfono, tú o tu compañero?" },
      { en: "This option isn't cheaper than the other one.", es: "Esta opción no es más barata que la otra." },
    ],
    check: {
      prompt: "Ask: ¿Qué es más difícil, hablar o escuchar?",
      promptEs: "Pregunta en inglés: ¿Qué es más difícil, hablar o escuchar?",
      answer: "What is more difficult, speaking or listening?",
    },
  },
];

export const COMPARATIVES_COMMON_ERRORS: { wrong: string; right: string; es: string }[] = [
  { wrong: "This phone is more cheap.", right: "This phone is cheaper.", es: "Los adjetivos cortos llevan -er, no more." },
  { wrong: "My job is more better now.", right: "My job is better now.", es: "Better ya es comparativo: nunca more better." },
  { wrong: "It is expensiver than that one.", right: "It is more expensive than that one.", es: "Los adjetivos largos usan more, no -er." },
  { wrong: "She is taller that her sister.", right: "She is taller than her sister.", es: "La palabra es than, no that." },
  { wrong: "Today is more bad than yesterday.", right: "Today is worse than yesterday.", es: "El comparativo de bad es worse." },
  { wrong: "This bus is as fast than the train.", right: "This bus is as fast as the train.", es: "Con as … as se repite as, no se usa than." },
];
