import type { ReviewGuideCard, ReviewModule } from "@/lib/review-types";

export const MODALS_GUIDE: ReviewGuideCard[] = [
  { id:"mod-1-form", title:"One simple form", titleEs:"Una forma sencilla", explanation:"A modal goes before the base verb. It never takes -s or to.", explanationEs:"Un modal va antes del verbo base. Nunca lleva -s ni to: she can work, he should rest.", examples:[{en:"She can help.",es:"Ella puede ayudar."},{en:"He should rest.",es:"Él debería descansar."},{en:"They must leave.",es:"Ellos deben irse."}], check:{prompt:"Correct: She can to help.",promptEs:"Corrige: She can to help.",answer:"She can help."} },
  { id:"mod-2-can", title:"can and could", titleEs:"can y could", explanation:"Use can for present ability and could for past ability or a polite request.", explanationEs:"Usa can para habilidad presente; could para habilidad pasada o una petición más cortés.", examples:[{en:"I can solve this problem.",es:"Puedo resolver este problema."},{en:"She could read at four.",es:"Ella podía leer a los cuatro años."},{en:"Could you help me?",es:"¿Podría ayudarme?"}], check:{prompt:"Ask politely for help with could.",promptEs:"Pide ayuda cortésmente con could.",answer:"Could you help me?"} },
  { id:"mod-3-possibility", title:"may, might and could", titleEs:"may, might y could", explanation:"Use them for a real possibility. Might often sounds less certain.", explanationEs:"Úsalos para una posibilidad real. Might suele sonar menos seguro. Después siempre va el verbo base.", examples:[{en:"It may rain later.",es:"Puede que llueva más tarde."},{en:"She might arrive late.",es:"Quizá ella llegue tarde."},{en:"We could work from home.",es:"Podríamos trabajar desde casa."}], check:{prompt:"Say one possibility for tomorrow with might.",promptEs:"Di una posibilidad para mañana con might.",answer:"It might rain tomorrow."} },
  { id:"mod-4-advice", title:"should and had better", titleEs:"should y had better", explanation:"Should gives normal advice. Had better gives urgent advice with a likely consequence.", explanationEs:"Should da un consejo normal. Had better da un consejo urgente porque puede haber una consecuencia. Had better no lleva to.", examples:[{en:"You should drink water.",es:"Deberías tomar agua."},{en:"You had better leave now.",es:"Será mejor que salgas ahora."},{en:"You shouldn't stay up late.",es:"No deberías desvelarte."}], check:{prompt:"Give urgent advice about an early flight.",promptEs:"Da un consejo urgente sobre un vuelo temprano.",answer:"You had better go to bed early."} },
  { id:"mod-5-must", title:"must and mustn't", titleEs:"must y mustn't", explanation:"Must expresses a strong obligation. Mustn't expresses prohibition—not a lack of necessity.", explanationEs:"Must expresa obligación fuerte. Mustn't significa prohibición, no “no es necesario”. Para “no es necesario” se usa don't have to.", examples:[{en:"Employees must protect customer data.",es:"Los empleados deben proteger los datos."},{en:"You mustn't share passwords.",es:"No debes compartir contraseñas."},{en:"You don't have to wear a tie.",es:"No tienes que usar corbata."}], check:{prompt:"Say one workplace prohibition with mustn't.",promptEs:"Di una prohibición laboral con mustn't.",answer:"You mustn't share passwords."} },
  { id:"mod-6-would", title:"would", titleEs:"would", explanation:"Use would for polite requests and imagined situations.", explanationEs:"Usa would para peticiones corteses y situaciones imaginarias. La contracción negativa es wouldn't.", examples:[{en:"Would you open the window?",es:"¿Abriría la ventana?"},{en:"I would choose the beach.",es:"Yo elegiría la playa."},{en:"She wouldn't accept that offer.",es:"Ella no aceptaría esa oferta."}], check:{prompt:"Ask politely for a glass of water.",promptEs:"Pide un vaso de agua cortésmente.",answer:"Would you bring me a glass of water?"} },
  { id:"mod-7-questions", title:"Questions and negatives", titleEs:"Preguntas y negativas", explanation:"Put the modal before the subject in questions. Add not for negatives; never use do or does.", explanationEs:"En preguntas, pon el modal antes del sujeto. Para negativas agrega not. No uses do ni does con un modal.", examples:[{en:"Can she come today?",es:"¿Puede venir hoy?"},{en:"Why should I wait?",es:"¿Por qué debería esperar?"},{en:"He might not call.",es:"Quizá él no llame."}], check:{prompt:"Correct: Does she can drive?",promptEs:"Corrige: Does she can drive?",answer:"Can she drive?"} },
];

export const MODALS_COMMON_ERRORS: ReviewModule["commonErrors"] = [
  {wrong:"She can to help.",right:"She can help.",es:"Después de un modal va el verbo base, sin to."},
  {wrong:"He musts arrive early.",right:"He must arrive early.",es:"Los modales nunca llevan -s."},
  {wrong:"You should to rest.",right:"You should rest.",es:"Should va directamente antes del verbo base."},
  {wrong:"You had better to call.",right:"You had better call.",es:"Had better tampoco lleva to."},
  {wrong:"You mustn't come early.",right:"You don't have to come early.",es:"Mustn't prohíbe; don't have to indica que no es necesario."},
  {wrong:"Does she can drive?",right:"Can she drive?",es:"La pregunta inicia con el modal, sin does."},
];
