import type { ReviewPractice } from "@/lib/review-types";
import scene1 from "@/assets/review/modal-perfects/mp-practice-1.jpg";
import scene2 from "@/assets/review/modal-perfects/mp-practice-2.jpg";
import scene3 from "@/assets/review/modal-perfects/mp-practice-3.jpg";
import scene4 from "@/assets/review/modal-perfects/mp-practice-4.jpg";
import scene5 from "@/assets/review/modal-perfects/mp-practice-5.jpg";

const img = (src: string, alt: string, altEs: string) => ({ src, alt, altEs });

export const MODAL_PERFECTS_PRACTICES: ReviewPractice[] = [
  {
    number: 1,
    id: "modal-perfects-1-andres",
    title: "Andrés missed his flight",
    titleEs: "Andrés perdió su vuelo",
    person: "third",
    character: "Andrés",
    focus: "Past regrets and deductions with should have, must have and could have.",
    focusEs: "Arrepentimientos y deducciones del pasado con should have, must have y could have.",
    reminder: { en: "modal + have + past participle: he should have left earlier.", es: "modal + have + participio: he should have left earlier." },
    showFullGuide: true,
    instructions: { en: "Describe what Andrés should have done and what must have happened at the airport.", es: "Describe qué debió hacer Andrés y qué seguramente pasó en el aeropuerto." },
    sceneImage: img(scene1, "Andrés alone in an airport terminal after missing his flight", "Andrés solo en la terminal del aeropuerto después de perder su vuelo"),
    vocabulary: ["flight", "gate", "alarm", "traffic", "should have", "must have", "could have", "might have"],
    lines: [
      { id: "mp1-l1", text: "Andrés should have left his house two hours earlier.", es: "Andrés debió haber salido de su casa dos horas antes.", chunks: ["Andrés should have left his house", "two hours earlier."] },
      { id: "mp1-l2", text: "He must have forgotten to set his alarm.", es: "Seguramente olvidó poner su alarma.", chunks: ["He must have forgotten", "to set his alarm."] },
      { id: "mp1-l3", text: "The traffic must have been terrible that morning.", es: "El tráfico seguramente estuvo terrible esa mañana.", chunks: ["The traffic must have been terrible", "that morning."] },
      { id: "mp1-l4", text: "He could have taken a taxi instead of the bus.", es: "Pudo haber tomado un taxi en lugar del autobús.", chunks: ["He could have taken a taxi", "instead of the bus."] },
      { id: "mp1-l5", text: "He shouldn't have packed his suitcase at midnight.", es: "No debió haber hecho su maleta a medianoche.", chunks: ["He shouldn't have packed his suitcase", "at midnight."] },
      { id: "mp1-l6", text: "The airline might have changed the gate without a message.", es: "Quizá la aerolínea cambió la puerta sin avisar.", chunks: ["The airline might have changed the gate", "without a message."] },
      { id: "mp1-l7", text: "He would have arrived on time with a better plan.", es: "Habría llegado a tiempo con un mejor plan.", chunks: ["He would have arrived on time", "with a better plan."] },
      { id: "mp1-l8", text: "Next time he must remember to check the schedule.", es: "La próxima vez debe recordar revisar el horario.", chunks: ["Next time he must remember", "to check the schedule."] },
    ],
    questions: [
      { id: "mp1-q1", question: "What should Andrés have done differently?", questionEs: "¿Qué debió haber hecho diferente Andrés?", hint: "He should have…", hintEs: "Usa should have + participio." },
      { id: "mp1-q2", question: "Why must he have missed the flight?", questionEs: "¿Por qué seguramente perdió el vuelo?", hint: "He must have…", hintEs: "Usa must have." },
      { id: "mp1-q3", question: "How long should he have waited at the airport?", questionEs: "¿Cuánto tiempo debió haber esperado en el aeropuerto?", hint: "He should have waited for…", hintEs: "Usa for + tiempo." },
      { id: "mp1-q4", question: "Who could have driven him to the airport?", questionEs: "¿Quién pudo haberlo llevado al aeropuerto?", hint: "His… could have…", hintEs: "Usa could have." },
      { id: "mp1-q5", question: "What might the airline have done wrong?", questionEs: "¿Qué pudo haber hecho mal la aerolínea?", hint: "They might have…", hintEs: "Usa might have." },
    ],
    finalPrompt: {
      question: "Explain what happened to Andrés and what he should, could or must have done.",
      questionEs: "Explica qué le pasó a Andrés y qué debió, pudo o seguramente hizo.",
      tips: { en: "Use should have, must have and could have at least once each.", es: "Usa should have, must have y could have al menos una vez cada uno." },
    },
    grammarGoals: ["modal + have + past participle", "should have for past regret", "must have for past deduction"],
  },
  {
    number: 2,
    id: "modal-perfects-2-interview",
    title: "My interview, one week later",
    titleEs: "Mi entrevista, una semana después",
    person: "first",
    character: null,
    focus: "Personal reflection with should have, could have and shouldn't have.",
    focusEs: "Reflexión personal con should have, could have y shouldn't have.",
    reminder: { en: "shouldn't have = you did it and you regret it.", es: "shouldn't have = sí lo hiciste y lo lamentas." },
    showFullGuide: false,
    instructions: { en: "Think about a job interview you had. Say what you should and could have done.", es: "Piensa en una entrevista de trabajo. Di qué debiste y qué pudiste haber hecho." },
    sceneImage: img(scene2, "A learner at home thinking back about a job interview", "Una estudiante en casa recordando una entrevista de trabajo"),
    vocabulary: ["interview", "prepare", "answer", "nervous", "example", "should have", "could have", "would have"],
    lines: [
      { id: "mp2-l1", text: "I should have practiced my answers out loud.", es: "Debí haber practicado mis respuestas en voz alta.", chunks: ["I should have practiced", "my answers out loud."] },
      { id: "mp2-l2", text: "I could have prepared two more examples about my experience.", es: "Pude haber preparado dos ejemplos más sobre mi experiencia.", chunks: ["I could have prepared", "two more examples", "about my experience."] },
      { id: "mp2-l3", text: "I shouldn't have arrived only five minutes early.", es: "No debí haber llegado solo cinco minutos antes.", chunks: ["I shouldn't have arrived", "only five minutes early."] },
      { id: "mp2-l4", text: "I should have asked more questions about the position.", es: "Debí haber preguntado más sobre el puesto.", chunks: ["I should have asked more questions", "about the position."] },
      { id: "mp2-l5", text: "I would have felt calmer with a good night of sleep.", es: "Me habría sentido más tranquilo con una buena noche de sueño.", chunks: ["I would have felt calmer", "with a good night of sleep."] },
      { id: "mp2-l6", text: "The recruiter might have wanted a longer answer.", es: "Quizá el reclutador quería una respuesta más larga.", chunks: ["The recruiter might have wanted", "a longer answer."] },
      { id: "mp2-l7", text: "I could have sent a thank you email the same day.", es: "Pude haber enviado un correo de agradecimiento el mismo día.", chunks: ["I could have sent", "a thank you email", "the same day."] },
      { id: "mp2-l8", text: "Next time I will prepare the way I should have prepared.", es: "La próxima vez me prepararé como debí haberme preparado.", chunks: ["Next time I will prepare", "the way I should have prepared."] },
    ],
    questions: [
      { id: "mp2-q1", question: "What could you have done better in the interview?", questionEs: "¿Qué pudiste haber hecho mejor en la entrevista?", hint: "I could have…", hintEs: "Usa could have." },
      { id: "mp2-q2", question: "How often should you have practiced before the interview?", questionEs: "¿Con qué frecuencia debiste practicar antes de la entrevista?", hint: "I should have practiced…", hintEs: "Di una frecuencia." },
      { id: "mp2-q3", question: "Who would have helped you prepare?", questionEs: "¿Quién te habría ayudado a prepararte?", hint: "My… would have…", hintEs: "Usa would have." },
      { id: "mp2-q4", question: "What shouldn't you have done that day?", questionEs: "¿Qué no debiste haber hecho ese día?", hint: "I shouldn't have…", hintEs: "Usa shouldn't have." },
      { id: "mp2-q5", question: "Why might the recruiter have wanted more details?", questionEs: "¿Por qué el reclutador pudo haber querido más detalles?", hint: "He might have… because…", hintEs: "Usa might have y because." },
    ],
    finalPrompt: {
      question: "Tell the story of that interview and everything you should, could or would have done.",
      questionEs: "Cuenta la historia de esa entrevista y todo lo que debiste, pudiste o habrías hecho.",
      tips: { en: "Use should have, shouldn't have, could have and would have.", es: "Usa should have, shouldn't have, could have y would have." },
    },
    grammarGoals: ["should have / shouldn't have for regret", "could have for unused possibility", "would have for an imagined result"],
  },
  {
    number: 3,
    id: "modal-perfects-3-laura",
    title: "Laura guesses what happened",
    titleEs: "Laura deduce qué pasó",
    person: "third",
    character: "Laura",
    focus: "Deductions about the past with must have, might have and may have.",
    focusEs: "Deducciones sobre el pasado con must have, might have y may have.",
    reminder: { en: "must have = almost sure. might have / may have = possible.", es: "must have = casi seguro. might have / may have = posible." },
    showFullGuide: false,
    instructions: { en: "Explain how Laura deduces why her teammate did not come to work.", es: "Explica cómo Laura deduce por qué su compañero no llegó al trabajo." },
    sceneImage: img(scene3, "Laura and her coworkers talking about a teammate who is missing", "Laura y sus compañeros hablando de un compañero ausente"),
    vocabulary: ["shift", "headset", "queue", "message", "must have", "might have", "may have", "couldn't have"],
    lines: [
      { id: "mp3-l1", text: "Diego's desk is empty, so he must have left early.", es: "El escritorio de Diego está vacío, así que seguramente se fue temprano.", chunks: ["Diego's desk is empty,", "so he must have left early."] },
      { id: "mp3-l2", text: "His coffee is still warm, so he can't have left long ago.", es: "Su café sigue tibio, así que no puede haberse ido hace mucho.", chunks: ["His coffee is still warm,", "so he can't have left long ago."] },
      { id: "mp3-l3", text: "He might have gone to the clinic this morning.", es: "Quizá fue a la clínica esta mañana.", chunks: ["He might have gone", "to the clinic", "this morning."] },
      { id: "mp3-l4", text: "He may have sent a message to the wrong supervisor.", es: "Puede que enviara un mensaje al supervisor equivocado.", chunks: ["He may have sent a message", "to the wrong supervisor."] },
      { id: "mp3-l5", text: "Laura thinks he must have felt sick during his shift.", es: "Laura cree que seguramente se sintió mal durante su turno.", chunks: ["Laura thinks", "he must have felt sick", "during his shift."] },
      { id: "mp3-l6", text: "He should have told the team before leaving.", es: "Debió haberle avisado al equipo antes de irse.", chunks: ["He should have told the team", "before leaving."] },
      { id: "mp3-l7", text: "Someone could have covered his calls without any problem.", es: "Alguien pudo haber cubierto sus llamadas sin ningún problema.", chunks: ["Someone could have covered his calls", "without any problem."] },
      { id: "mp3-l8", text: "Laura would have called him immediately.", es: "Laura lo habría llamado de inmediato.", chunks: ["Laura would have called him", "immediately."] },
    ],
    questions: [
      { id: "mp3-q1", question: "Where must Diego have gone?", questionEs: "¿A dónde seguramente fue Diego?", hint: "He must have gone…", hintEs: "Usa must have." },
      { id: "mp3-q2", question: "What might have happened to him?", questionEs: "¿Qué pudo haberle pasado?", hint: "He might have…", hintEs: "Usa might have." },
      { id: "mp3-q3", question: "When should he have told the team?", questionEs: "¿Cuándo debió avisarle al equipo?", hint: "He should have told them…", hintEs: "Di el momento." },
      { id: "mp3-q4", question: "Who could have covered his calls?", questionEs: "¿Quién pudo haber cubierto sus llamadas?", hint: "… could have covered…", hintEs: "Usa could have." },
      { id: "mp3-q5", question: "Why must he have felt sick?", questionEs: "¿Por qué seguramente se sintió mal?", hint: "He must have… because…", hintEs: "Explica la evidencia." },
    ],
    finalPrompt: {
      question: "Explain Laura's deductions: what must, might or may have happened to Diego.",
      questionEs: "Explica las deducciones de Laura: qué seguramente, quizá o posiblemente le pasó a Diego.",
      tips: { en: "Use must have once, might have once and may have once, with evidence.", es: "Usa must have, might have y may have una vez cada uno, con evidencia." },
    },
    grammarGoals: ["must have for strong deduction", "might have / may have for uncertain deduction", "past participle after have"],
  },
  {
    number: 4,
    id: "modal-perfects-4-choices",
    title: "The life I would have chosen",
    titleEs: "La vida que habría elegido",
    person: "first",
    character: null,
    focus: "Imagined past results with would have and could have, including if clauses.",
    focusEs: "Resultados imaginarios del pasado con would have y could have, incluyendo cláusulas con if.",
    reminder: { en: "If + had + past participle, … would have + past participle.", es: "If + had + participio, … would have + participio." },
    showFullGuide: false,
    instructions: { en: "Imagine a different past decision and describe the life you would have had.", es: "Imagina una decisión pasada diferente y describe la vida que habrías tenido." },
    sceneImage: img(scene4, "A person at a fork in the road imagining a different life", "Una persona en una bifurcación imaginando una vida diferente"),
    vocabulary: ["decision", "career", "move", "abroad", "would have", "wouldn't have", "could have", "if"],
    lines: [
      { id: "mp4-l1", text: "If I had moved to another city, my life would have changed completely.", es: "Si me hubiera mudado a otra ciudad, mi vida habría cambiado por completo.", chunks: ["If I had moved to another city,", "my life would have changed completely."] },
      { id: "mp4-l2", text: "I would have studied engineering instead of business.", es: "Habría estudiado ingeniería en lugar de negocios.", chunks: ["I would have studied engineering", "instead of business."] },
      { id: "mp4-l3", text: "I could have learned English much earlier.", es: "Pude haber aprendido inglés mucho antes.", chunks: ["I could have learned English", "much earlier."] },
      { id: "mp4-l4", text: "I wouldn't have left my first job so quickly.", es: "No habría dejado mi primer trabajo tan rápido.", chunks: ["I wouldn't have left", "my first job", "so quickly."] },
      { id: "mp4-l5", text: "My family would have missed me every weekend.", es: "Mi familia me habría extrañado cada fin de semana.", chunks: ["My family would have missed me", "every weekend."] },
      { id: "mp4-l6", text: "I might have found a job abroad after two years.", es: "Quizá habría encontrado un trabajo en el extranjero después de dos años.", chunks: ["I might have found a job abroad", "after two years."] },
      { id: "mp4-l7", text: "I should have saved more money before that decision.", es: "Debí haber ahorrado más dinero antes de esa decisión.", chunks: ["I should have saved more money", "before that decision."] },
      { id: "mp4-l8", text: "Still, I wouldn't have changed my family for anything.", es: "Aun así, no habría cambiado a mi familia por nada.", chunks: ["Still, I wouldn't have changed", "my family for anything."] },
    ],
    questions: [
      { id: "mp4-q1", question: "What would you have studied?", questionEs: "¿Qué habrías estudiado?", hint: "I would have studied…", hintEs: "Usa would have." },
      { id: "mp4-q2", question: "Where could you have lived?", questionEs: "¿Dónde habrías podido vivir?", hint: "I could have lived…", hintEs: "Usa could have." },
      { id: "mp4-q3", question: "Why wouldn't you have changed that decision?", questionEs: "¿Por qué no habrías cambiado esa decisión?", hint: "I wouldn't have… because…", hintEs: "Explica tu razón." },
      { id: "mp4-q4", question: "How long would you have stayed abroad?", questionEs: "¿Cuánto tiempo te habrías quedado en el extranjero?", hint: "I would have stayed for…", hintEs: "Usa for + tiempo." },
      { id: "mp4-q5", question: "Who would have supported your decision?", questionEs: "¿Quién habría apoyado tu decisión?", hint: "My… would have…", hintEs: "Di una persona." },
    ],
    finalPrompt: {
      question: "Describe the different life you would have had and the choices you could have made.",
      questionEs: "Describe la vida diferente que habrías tenido y las decisiones que habrías podido tomar.",
      tips: { en: "Use one if clause, would have, wouldn't have and could have.", es: "Usa una cláusula con if, would have, wouldn't have y could have." },
    },
    grammarGoals: ["would have for imagined past results", "if + had + past participle", "could have for unrealized options"],
  },
  {
    number: 5,
    id: "modal-perfects-5-team",
    title: "The team reviews a difficult launch",
    titleEs: "El equipo revisa un lanzamiento difícil",
    person: "third",
    character: "Valeria",
    focus: "Integrated should have, must have, could have and would have in a work review.",
    focusEs: "Uso integrado de should have, must have, could have y would have en una revisión de trabajo.",
    reminder: { en: "Choose by meaning: regret, deduction, possibility or imagined result.", es: "Elige por significado: arrepentimiento, deducción, posibilidad o resultado imaginario." },
    showFullGuide: false,
    instructions: { en: "Explain what the team says after a launch that did not go well.", es: "Explica qué dice el equipo después de un lanzamiento que no salió bien." },
    sceneImage: img(scene5, "A team reviewing a project after a difficult launch", "Un equipo revisando un proyecto después de un lanzamiento difícil"),
    vocabulary: ["launch", "test", "deadline", "feedback", "should have", "must have", "could have", "would have"],
    lines: [
      { id: "mp5-l1", text: "Valeria says the team should have tested the system earlier.", es: "Valeria dice que el equipo debió haber probado el sistema antes.", chunks: ["Valeria says the team", "should have tested the system earlier."] },
      { id: "mp5-l2", text: "They must have underestimated the number of users.", es: "Seguramente subestimaron la cantidad de usuarios.", chunks: ["They must have underestimated", "the number of users."] },
      { id: "mp5-l3", text: "One developer could have noticed the error last Friday.", es: "Un desarrollador pudo haber notado el error el viernes pasado.", chunks: ["One developer could have noticed the error", "last Friday."] },
      { id: "mp5-l4", text: "They shouldn't have changed the deadline twice.", es: "No debieron haber cambiado la fecha límite dos veces.", chunks: ["They shouldn't have changed", "the deadline twice."] },
      { id: "mp5-l5", text: "The launch would have been calmer with one more week.", es: "El lanzamiento habría sido más tranquilo con una semana más.", chunks: ["The launch would have been calmer", "with one more week."] },
      { id: "mp5-l6", text: "Some customers might have received the wrong confirmation.", es: "Quizá algunos clientes recibieron la confirmación equivocada.", chunks: ["Some customers might have received", "the wrong confirmation."] },
      { id: "mp5-l7", text: "Valeria should have asked for help before the last day.", es: "Valeria debió haber pedido ayuda antes del último día.", chunks: ["Valeria should have asked for help", "before the last day."] },
      { id: "mp5-l8", text: "Now they know what they must do differently next time.", es: "Ahora saben qué deben hacer diferente la próxima vez.", chunks: ["Now they know", "what they must do differently", "next time."] },
    ],
    questions: [
      { id: "mp5-q1", question: "What should the team have tested first?", questionEs: "¿Qué debió probar primero el equipo?", hint: "They should have tested…", hintEs: "Usa should have." },
      { id: "mp5-q2", question: "Who could have noticed the problem earlier?", questionEs: "¿Quién pudo haber notado el problema antes?", hint: "… could have noticed…", hintEs: "Usa could have." },
      { id: "mp5-q3", question: "How would the launch have changed with more time?", questionEs: "¿Cómo habría cambiado el lanzamiento con más tiempo?", hint: "It would have…", hintEs: "Usa would have." },
      { id: "mp5-q4", question: "Why must they have underestimated the users?", questionEs: "¿Por qué seguramente subestimaron a los usuarios?", hint: "They must have… because…", hintEs: "Usa must have." },
      { id: "mp5-q5", question: "When should Valeria have asked for help?", questionEs: "¿Cuándo debió pedir ayuda Valeria?", hint: "She should have asked…", hintEs: "Di el momento." },
    ],
    finalPrompt: {
      question: "Explain the team's review: what they should, must, could and would have done differently.",
      questionEs: "Explica la revisión del equipo: qué debieron, seguramente hicieron, pudieron y habrían hecho diferente.",
      tips: { en: "Use at least four different modal perfect forms and one negative.", es: "Usa al menos cuatro formas modales perfectas diferentes y una negativa." },
    },
    grammarGoals: ["integrated should/must/could/would have", "negatives with shouldn't have", "past participle after have"],
  },
];
