import type { ReviewGuideCard } from "@/lib/review-types";

/**
 * "ENTIÉNDELO FÁCIL" — the seven basics of the passive voice.
 * Static hand-written content: never generated by AI.
 */
export const PASSIVE_VOICE_GUIDE: ReviewGuideCard[] = [
  {
    id: "pas-1-use",
    title: "What the passive is for",
    titleEs: "Para qué sirve la voz pasiva",
    explanation: "The passive puts the important thing first: The book was written by him.",
    explanationEs:
      "En la voz activa el sujeto hace la acción (He wrote the book). En la pasiva lo importante es la COSA que recibe la acción (The book was written by him). La usas cuando no sabes quién hizo algo, no importa quién, o quieres sonar más formal.",
    examples: [
      { en: "The book was written by him.", es: "El libro fue escrito por él." },
      { en: "My car was repaired yesterday.", es: "Mi carro fue reparado ayer." },
      { en: "English is spoken in many countries.", es: "El inglés se habla en muchos países." },
    ],
    check: {
      prompt: "Make this passive: They cleaned the office.",
      promptEs: "Pásalo a pasiva: They cleaned the office.",
      answer: "The office was cleaned.",
    },
  },
  {
    id: "pas-2-formula",
    title: "The formula: be + past participle",
    titleEs: "La fórmula: be + participio pasado",
    explanation: "Subject + the correct form of BE + past participle (the third column: written, made, sent).",
    explanationEs:
      "Siempre son DOS piezas: el verbo be en el tiempo que necesitas + el participio pasado (tercera columna: write-wrote-WRITTEN, send-sent-SENT, do-did-DONE). Los regulares terminan en -ed: clean → cleaned.",
    examples: [
      { en: "The emails are sent every morning.", es: "Los correos se envían cada mañana." },
      { en: "The report was finished on time.", es: "El reporte fue terminado a tiempo." },
      { en: "The rooms are cleaned by the staff.", es: "Los cuartos son limpiados por el personal." },
    ],
    check: {
      prompt: "Say the participle of send, make and do.",
      promptEs: "Di el participio de send, make y do.",
      answer: "sent / made / done",
    },
  },
  {
    id: "pas-3-present",
    title: "Present passive: am / is / are + participle",
    titleEs: "Pasiva en presente: am / is / are + participio",
    explanation: "The calls are answered in English. The system is checked every day.",
    explanationEs:
      "Para hablar de rutinas y hechos: is / are + participio. Singular → is (The report is reviewed). Plural → are (The reports are reviewed). No olvides el verbo be: “The calls answered” está mal.",
    examples: [
      { en: "The calls are answered in English.", es: "Las llamadas se contestan en inglés." },
      { en: "The system is checked every morning.", es: "El sistema se revisa cada mañana." },
      { en: "These products are made in Mexico.", es: "Estos productos se hacen en México." },
    ],
    check: {
      prompt: "Say in passive: They clean the office every day.",
      promptEs: "Di en pasiva: They clean the office every day.",
      answer: "The office is cleaned every day.",
    },
  },
  {
    id: "pas-4-past",
    title: "Past passive: was / were + participle",
    titleEs: "Pasiva en pasado: was / were + participio",
    explanation: "The book was written in 1998. The tickets were sold in one hour.",
    explanationEs:
      "Para acciones terminadas: was (singular) / were (plural) + participio. The email was sent yesterday. The doors were closed at ten. Es el uso más común en historias y reportes.",
    examples: [
      { en: "The book was written in 1998.", es: "El libro fue escrito en 1998." },
      { en: "The tickets were sold in one hour.", es: "Los boletos se vendieron en una hora." },
      { en: "My phone was stolen last week.", es: "Mi teléfono fue robado la semana pasada." },
    ],
    check: {
      prompt: "Say in passive: Someone stole my bike.",
      promptEs: "Di en pasiva: Someone stole my bike.",
      answer: "My bike was stolen.",
    },
  },
  {
    id: "pas-5-by",
    title: "by + who did it (and when to skip it)",
    titleEs: "by + quién lo hizo (y cuándo omitirlo)",
    explanation: "Add by only when the person matters: The song was written by my brother.",
    explanationEs:
      "Usa by + persona solo cuando esa información importa: The email was sent by the manager. Si no sabes quién, o no importa, no digas nada: My wallet was stolen. Nunca uses “for” en lugar de by.",
    examples: [
      { en: "This app was designed by a small team.", es: "Esta app fue diseñada por un equipo pequeño." },
      { en: "The decision was made by the client.", es: "La decisión fue tomada por el cliente." },
      { en: "My wallet was stolen at the station.", es: "Mi cartera fue robada en la estación." },
    ],
    check: {
      prompt: "Say who wrote your favorite song, in passive.",
      promptEs: "Di quién escribió tu canción favorita, en pasiva.",
      answer: "It was written by …",
    },
  },
  {
    id: "pas-6-questions",
    title: "Questions and negatives",
    titleEs: "Preguntas y negativas",
    explanation: "Was the report sent? It wasn't sent. Are the calls recorded?",
    explanationEs:
      "En pregunta, be va primero: Was the report sent? Are the calls recorded? When was it built? En negativo, not va después de be: It wasn't sent. They aren't recorded. Nunca uses did con la pasiva: “Did it was sent?” está mal.",
    examples: [
      { en: "Was the report sent yesterday?", es: "¿El reporte fue enviado ayer?" },
      { en: "The package wasn't delivered on Monday.", es: "El paquete no fue entregado el lunes." },
      { en: "Are the calls recorded for quality?", es: "¿Las llamadas se graban por calidad?" },
    ],
    check: {
      prompt: "Ask in passive: ¿Cuándo fue construido?",
      promptEs: "Pregunta en pasiva: ¿Cuándo fue construido?",
      answer: "When was it built?",
    },
  },
  {
    id: "pas-7-other",
    title: "Passive with will, can and have",
    titleEs: "Pasiva con will, can y have",
    explanation: "It will be sent. It can be fixed. It has been approved.",
    explanationEs:
      "La fórmula no cambia: solo cambia la forma de be. Futuro: will BE sent. Modal: can BE fixed, must BE done. Presente perfecto: has BEEN approved. Progresivo: is BEING repaired.",
    examples: [
      { en: "Your order will be delivered tomorrow.", es: "Tu pedido será entregado mañana." },
      { en: "The problem can be solved today.", es: "El problema puede ser resuelto hoy." },
      { en: "The document has been approved.", es: "El documento ha sido aprobado." },
    ],
    check: {
      prompt: "Say in passive: They will fix it tonight.",
      promptEs: "Di en pasiva: They will fix it tonight.",
      answer: "It will be fixed tonight.",
    },
  },
];

export const PASSIVE_VOICE_COMMON_ERRORS: { wrong: string; right: string; es: string }[] = [
  { wrong: "The book writed by him.", right: "The book was written by him.", es: "Falta be y el participio correcto: was written." },
  { wrong: "The office cleaned every day.", right: "The office is cleaned every day.", es: "La pasiva siempre lleva el verbo be." },
  { wrong: "Did the email was sent?", right: "Was the email sent?", es: "En pasiva la pregunta empieza con be, nunca con did." },
  { wrong: "It was made for a famous chef.", right: "It was made by a famous chef.", es: "La persona que hace la acción va con by." },
  { wrong: "The reports was finished.", right: "The reports were finished.", es: "Plural lleva were, no was." },
  { wrong: "It will be send tomorrow.", right: "It will be sent tomorrow.", es: "Después de be va el participio: sent, no send." },
];
