import type { ReviewGuideCard, ReviewModule } from "@/lib/review-types";
import g1 from "@/assets/review/past-perfect/guide-1-order.jpg";
import g2 from "@/assets/review/past-perfect/guide-2-form.jpg";
import g3 from "@/assets/review/past-perfect/guide-3-duration.jpg";
import g4 from "@/assets/review/past-perfect/guide-4-contrast.jpg";
import g5 from "@/assets/review/past-perfect/guide-5-negative.jpg";
import g6 from "@/assets/review/past-perfect/guide-6-questions.jpg";
import g7 from "@/assets/review/past-perfect/guide-7-connectors.jpg";

const image = (src: string, alt: string, altEs: string) => ({ src, alt, altEs });

export const PAST_PERFECT_GUIDE: ReviewGuideCard[] = [
  { id:"pap-1-order", title:"An earlier past action", titleEs:"Una acción anterior en el pasado", explanation:"Use the past perfect for the action that happened first when you talk about two past moments.", explanationEs:"Usa past perfect para la acción que ocurrió primero cuando cuentas dos momentos del pasado.", image:image(g1,"A traveler watching the plane that had departed","Una viajera observando el avión que ya había salido"), examples:[{en:"The plane had left before Ana arrived.",es:"El avión había salido antes de que Ana llegara."},{en:"I had eaten when he called.",es:"Yo ya había comido cuando él llamó."},{en:"They had finished before noon.",es:"Habían terminado antes del mediodía."}], check:{prompt:"Say which action happened first: I had eaten when he called.",promptEs:"Di cuál acción ocurrió primero: I had eaten when he called.",answer:"I had eaten first."} },
  { id:"pap-2-form", title:"had + past participle", titleEs:"had + participio", explanation:"Had is the same for every subject. Follow it with a past participle.", explanationEs:"Had es igual para todos los sujetos. Después usa el participio pasado.", image:image(g2,"A room prepared before guests arrived","Un salón preparado antes de que llegaran los invitados"), examples:[{en:"I had prepared everything.",es:"Yo había preparado todo."},{en:"She had written the email.",es:"Ella había escrito el correo."},{en:"We had gone home.",es:"Nos habíamos ido a casa."}], check:{prompt:"Correct: She had wrote the email.",promptEs:"Corrige: She had wrote the email.",answer:"She had written the email."} },
  { id:"pap-3-progressive", title:"had been + verb-ing", titleEs:"had been + verbo-ing", explanation:"Use it for an activity that continued for some time before another past event.", explanationEs:"Úsalo para una actividad que continuó durante un tiempo antes de otro evento pasado.", image:image(g3,"A runner who had been running before the rain","Una corredora que había estado corriendo antes de la lluvia"), examples:[{en:"She had been running for an hour when it rained.",es:"Ella había estado corriendo por una hora cuando llovió."},{en:"We had been waiting since noon.",es:"Habíamos estado esperando desde el mediodía."},{en:"He had been studying all night.",es:"Él había estado estudiando toda la noche."}], check:{prompt:"Say how long he had been studying.",promptEs:"Di cuánto tiempo había estado estudiando.",answer:"He had been studying all night."} },
  { id:"pap-4-contrast", title:"Result or duration?", titleEs:"¿Resultado o duración?", explanation:"Past perfect emphasizes a completed result. Past perfect progressive emphasizes the activity or its duration.", explanationEs:"Past perfect enfatiza un resultado completo. Past perfect progressive enfatiza la actividad o su duración.", image:image(g4,"Finished boxes compared with someone still packing","Cajas terminadas comparadas con alguien que seguía empacando"), examples:[{en:"They had packed six boxes. (result)",es:"Habían empacado seis cajas. (resultado)"},{en:"They had been packing for hours. (duration)",es:"Habían estado empacando por horas. (duración)"},{en:"The floor was wet because it had been raining.",es:"El piso estaba mojado porque había estado lloviendo."}], check:{prompt:"Choose the form for a completed result.",promptEs:"Elige la forma para un resultado completo.",answer:"They had packed six boxes."} },
  { id:"pap-5-negative", title:"Negatives", titleEs:"Negativas", explanation:"Use had not (hadn't) + participle, or hadn't been + verb-ing.", explanationEs:"Usa had not (hadn't) + participio, o hadn't been + verbo-ing.", image:image(g5,"A family discovering dinner had not been prepared","Una familia descubriendo que la cena no había sido preparada"), examples:[{en:"I hadn't finished when she arrived.",es:"Yo no había terminado cuando ella llegó."},{en:"He hadn't called before the meeting.",es:"Él no había llamado antes de la reunión."},{en:"They hadn't been sleeping well.",es:"No habían estado durmiendo bien."}], check:{prompt:"Make negative: She had finished.",promptEs:"Haz negativa: She had finished.",answer:"She hadn't finished."} },
  { id:"pap-6-questions", title:"Questions", titleEs:"Preguntas", explanation:"Put had before the subject. For duration, use How long had … been + -ing?", explanationEs:"Pon had antes del sujeto. Para duración usa How long had … been + -ing?", image:image(g6,"Coworkers asking about earlier project events","Compañeros preguntando por eventos anteriores del proyecto"), examples:[{en:"What had you done before noon?",es:"¿Qué habías hecho antes del mediodía?"},{en:"Had she left before you arrived?",es:"¿Ella se había ido antes de que llegaras?"},{en:"How long had they been working?",es:"¿Cuánto tiempo habían estado trabajando?"}], check:{prompt:"Ask how long he had been waiting.",promptEs:"Pregunta cuánto tiempo había estado esperando.",answer:"How long had he been waiting?"} },
  { id:"pap-7-connectors", title:"Make the sequence clear", titleEs:"Aclara la secuencia", explanation:"Use before, after, by the time, when and because to connect the earlier action to the later event.", explanationEs:"Usa before, after, by the time, when y because para conectar la acción anterior con el evento posterior.", image:image(g7,"A traveler preparing, traveling and arriving in sequence","Un viajero preparando, viajando y llegando en secuencia"), examples:[{en:"By the time we arrived, the rain had stopped.",es:"Cuando llegamos, la lluvia ya había parado."},{en:"After I had packed, I called a taxi.",es:"Después de empacar, llamé un taxi."},{en:"She was tired because she had been driving all day.",es:"Estaba cansada porque había estado manejando todo el día."}], check:{prompt:"Connect two events with by the time.",promptEs:"Conecta dos eventos con by the time.",answer:"By the time I arrived, they had left."} },
];

export const PAST_PERFECT_COMMON_ERRORS: ReviewModule["commonErrors"] = [
  { wrong:"She had went home.", right:"She had gone home.", es:"Después de had usa el participio: gone, no went." },
  { wrong:"I have finished before he arrived.", right:"I had finished before he arrived.", es:"Para una acción anterior a otro momento pasado usa had." },
  { wrong:"They had been work all night.", right:"They had been working all night.", es:"Después de had been usa verbo con -ing." },
  { wrong:"He had working for hours.", right:"He had been working for hours.", es:"En la forma progresiva no olvides been." },
  { wrong:"Had she went before noon?", right:"Had she gone before noon?", es:"La pregunta también lleva participio." },
  { wrong:"We had been knowing him for years.", right:"We had known him for years.", es:"Know es verbo de estado; usa past perfect, no progresivo." },
];
