import type { ReviewGuideCard } from "@/lib/review-types";
import pg1 from "@/assets/review/ppast1-use.jpg";
import pg2 from "@/assets/review/ppast2-formula.jpg";
import pg3 from "@/assets/review/ppast3-waswere.jpg";
import pg4 from "@/assets/review/ppast4-negative.jpg";
import pg5 from "@/assets/review/ppast5-questions.jpg";
import pg6 from "@/assets/review/ppast6-when-while.jpg";
import pg7 from "@/assets/review/ppast7-stative.jpg";

/**
 * "ENTIÉNDELO FÁCIL" — the seven Past Progressive basics.
 * Static hand-written content: never generated by AI, reused by every practice
 * (Practice 1 shows it inline in Step 1, practices 2–5 open it on demand).
 */
export const PAST_PROGRESSIVE_GUIDE: ReviewGuideCard[] = [
  {
    id: "pg1-use",
    title: "What it is for",
    titleEs: "Para qué sirve",
    explanation: "Past Progressive describes an action that was in progress at a moment in the past.",
    explanationEs:
      "El Past Progressive sirve para una acción que estaba en progreso en un momento del pasado: a las 10 de la noche, ayer a esa hora, cuando algo pasó. No es para acciones terminadas: eso es Simple Past.",
    image: { src: pg1, alt: "A person sleeping at ten last night while it was raining", altEs: "Una persona durmiendo a las diez de la noche mientras llovía" },
    examples: [
      { en: "At 10 p.m. I was sleeping.", es: "A las 10 de la noche estaba durmiendo." },
      { en: "It was raining all night.", es: "Estuvo lloviendo toda la noche." },
      { en: "Yesterday at this time she was working.", es: "Ayer a esta hora ella estaba trabajando." },
    ],
    check: {
      prompt: "Say what you were doing last night at nine.",
      promptEs: "Di qué estabas haciendo anoche a las nueve.",
      answer: "Last night at nine I was watching TV.",
    },
  },
  {
    id: "pg2-formula",
    title: "The formula: was / were + -ing",
    titleEs: "La fórmula",
    explanation: "Two parts: the past of be (was, were) and the main verb with -ing. Never drop the was or were.",
    explanationEs:
      "Siempre dos partes: el pasado de be (was / were) más el verbo principal con -ing. Nunca digas “She working yesterday”: falta el was.",
    image: { src: pg2, alt: "Three people doing different activities yesterday", altEs: "Tres personas haciendo distintas actividades ayer" },
    examples: [
      { en: "I was cooking. / He was driving.", es: "Yo estaba cocinando. / Él estaba manejando." },
      { en: "They were talking in the kitchen.", es: "Ellos estaban hablando en la cocina." },
      { en: "She was working. (NOT: She working.)", es: "Ella estaba trabajando. (NO: She working.)" },
    ],
    check: {
      prompt: "Say the same action with I, she and they.",
      promptEs: "Di la misma acción con I, she y they.",
      answer: "I was studying. She was studying. They were studying.",
    },
  },
  {
    id: "pg3-was-were",
    title: "Was or were?",
    titleEs: "¿Was o were?",
    explanation: "Use was with I, he, she, it. Use were with you, we, they.",
    explanationEs:
      "Was va con I, he, she, it (una persona o cosa). Were va con you, we, they (y siempre con you, aunque sea una sola persona). Ojo: “You was working” está mal; es “You were working”.",
    image: { src: pg3, alt: "One person on one side and a group on the other", altEs: "Una persona de un lado y un grupo del otro" },
    examples: [
      { en: "I was waiting. / It was raining.", es: "Yo estaba esperando. / Estaba lloviendo." },
      { en: "We were studying. / They were eating.", es: "Estábamos estudiando. / Estaban comiendo." },
      { en: "You were driving. (NOT: You was driving.)", es: "Tú estabas manejando. (NO: You was driving.)" },
    ],
    check: {
      prompt: "Say one sentence with was and one with were.",
      promptEs: "Di una oración con was y otra con were.",
      answer: "She was cooking. We were helping her.",
    },
  },
  {
    id: "pg4-negative",
    title: "Negative sentences",
    titleEs: "Negativas",
    explanation: "Put not after was or were: wasn't / weren't. Never use didn't here.",
    explanationEs:
      "Para negar pones not después de was o were: I wasn't working, they weren't listening. Aquí NO se usa didn't, porque was/were ya hace la negación. “I didn't working” está mal.",
    image: { src: pg4, alt: "A woman reading and not answering the ringing phone", altEs: "Una mujer leyendo y sin contestar el teléfono" },
    examples: [
      { en: "I wasn't answering the phone.", es: "No estaba contestando el teléfono." },
      { en: "She wasn't listening to the meeting.", es: "Ella no estaba escuchando la reunión." },
      { en: "They weren't working. (NOT: They didn't working.)", es: "Ellos no estaban trabajando. (NO: They didn't working.)" },
    ],
    check: {
      prompt: "Say one thing you were not doing last night.",
      promptEs: "Di algo que no estabas haciendo anoche.",
      answer: "I wasn't studying last night.",
    },
  },
  {
    id: "pg5-questions",
    title: "Questions and short answers",
    titleEs: "Preguntas",
    explanation: "Move was / were to the front: Were you working? Question words go first: What were you doing?",
    explanationEs:
      "Para preguntar mueves was o were al inicio: Were you working? Was she waiting? Con palabra interrogativa va primero: What were you doing? Why was he calling? Respuestas cortas: Yes, I was / No, I wasn't / Yes, she was / No, they weren't.",
    image: { src: pg5, alt: "One person asking another about yesterday", altEs: "Una persona preguntándole a otra sobre ayer" },
    examples: [
      { en: "Were you working at eight? — Yes, I was.", es: "¿Estabas trabajando a las ocho? — Sí." },
      { en: "Was she waiting outside? — No, she wasn't.", es: "¿Estaba ella esperando afuera? — No." },
      { en: "What were they doing at that moment?", es: "¿Qué estaban haciendo en ese momento?" },
    ],
    check: {
      prompt: "Ask two questions: one with Were you and one with Was she.",
      promptEs: "Haz dos preguntas: una con Were you y otra con Was she.",
      answer: "Were you studying last night? Was she working late?",
    },
  },
  {
    id: "pg6-when-while",
    title: "When and while",
    titleEs: "When y while",
    explanation: "The long action takes the progressive; the short action that interrupts takes the simple past.",
    explanationEs:
      "La acción larga va en progresivo y la corta que la interrumpe va en pasado simple: I was walking home when it started to rain. Con while normalmente va la acción larga: While I was cooking, the phone rang.",
    image: { src: pg6, alt: "A person walking when it suddenly starts to rain", altEs: "Una persona caminando cuando de repente empieza a llover" },
    examples: [
      { en: "I was walking home when it started to rain.", es: "Estaba caminando a casa cuando empezó a llover." },
      { en: "While she was cooking, the phone rang.", es: "Mientras ella cocinaba, sonó el teléfono." },
      { en: "They were sleeping when the power went out.", es: "Estaban durmiendo cuando se fue la luz." },
    ],
    check: {
      prompt: "Say one sentence with was/were + -ing and when + simple past.",
      promptEs: "Di una oración con was/were + -ing y when + pasado simple.",
      answer: "I was studying when my friend called me.",
    },
  },
  {
    id: "pg7-stative",
    title: "Verbs that stay simple",
    titleEs: "Verbos que no usan -ing",
    explanation: "Feelings and states — like, want, need, know, understand — stay in the simple past.",
    explanationEs:
      "Los verbos de estado casi nunca van en -ing: like, love, want, need, know, understand y have cuando significa tener. Se dice I wanted coffee, no “I was wanting coffee”. Pero sí: I was having lunch (ahí have es acción).",
    image: { src: pg7, alt: "A man thinking about feelings and ideas", altEs: "Un hombre pensando en sentimientos e ideas" },
    examples: [
      { en: "I wanted a break. (NOT: I was wanting a break.)", es: "Quería un descanso. (NO: I was wanting a break.)" },
      { en: "She knew the answer. (NOT: She was knowing.)", es: "Ella sabía la respuesta. (NO: She was knowing.)" },
      { en: "He was having dinner at eight.", es: "Él estaba cenando a las ocho." },
    ],
    check: {
      prompt: "Say what you wanted and what you were doing.",
      promptEs: "Di qué querías y qué estabas haciendo.",
      answer: "I wanted a coffee, and I was studying English.",
    },
  },
];

/** The four errors this module keeps correcting. */
export const PAST_PROGRESSIVE_COMMON_ERRORS: { wrong: string; right: string; es: string }[] = [
  { wrong: "She working yesterday", right: "She was working yesterday", es: "Falta was/were antes del verbo -ing." },
  { wrong: "They didn't working", right: "They weren't working", es: "Para negar usas not después de was/were." },
  { wrong: "You was waiting", right: "You were waiting", es: "Con you siempre va were." },
  { wrong: "I was walking when it was starting to rain", right: "I was walking when it started to rain", es: "La acción corta que interrumpe va en pasado simple." },
];
