import type { ReviewPractice } from "@/lib/review-types";
import sceneLivingRoom from "@/assets/review/place-prepositions/scene-living-room.jpg";
import sceneKitchen from "@/assets/review/place-prepositions/scene-kitchen.jpg";
import sceneStreet from "@/assets/review/place-prepositions/scene-street.jpg";
import sceneClassroom from "@/assets/review/place-prepositions/scene-classroom.jpg";
import scenePark from "@/assets/review/place-prepositions/scene-park.jpg";

const REMINDER = {
  en: "Quick reminder: IN = inside, ON = on a surface, UNDER = below, ABOVE = higher without touching, NEXT TO = beside, BETWEEN = in the middle of two, BEHIND = at the back, IN FRONT OF = before it, NEAR = close, ACROSS FROM = on the other side.",
  es: "Recordatorio rápido: IN = adentro, ON = sobre una superficie, UNDER = debajo, ABOVE = arriba sin tocar, NEXT TO = al lado, BETWEEN = entre dos, BEHIND = detrás, IN FRONT OF = enfrente, NEAR = cerca, ACROSS FROM = al otro lado de frente.",
};

const GRAMMAR_GOALS = [
  "Correct prepositions of place: in, on, under, above, next to, between, behind, in front of, near, across from",
  "There is / There are to describe places",
  "Complete sentences with subject + be + preposition + place",
];

export const PLACE_PREPOSITIONS_PRACTICES: ReviewPractice[] = [
  {
    number: 1,
    id: "place-prep-1",
    title: "The Living Room",
    titleEs: "La Sala",
    person: "third",
    character: "Marta",
    focus: "Describe a living room with in, on, under, above and next to.",
    focusEs: "Describe una sala con in, on, under, above y next to.",
    reminder: REMINDER,
    showFullGuide: true,
    instructions: {
      en: "Look at the picture of Marta's living room. Listen, repeat and describe where everything is.",
      es: "Mira la foto de la sala de Marta. Escucha, repite y describe dónde está cada cosa.",
    },
    vocabulary: ["sofa", "lamp", "coffee table", "rug", "bookshelf", "picture", "cat"],
    lines: [
      {
        id: "p1-l1",
        text: "This is Marta's living room.",
        es: "Esta es la sala de Marta.",
        chunks: ["This is", "Marta's living room."],
      },
      {
        id: "p1-l2",
        text: "There is a cat on the sofa.",
        es: "Hay un gato sobre el sofá.",
        chunks: ["There is a cat", "on the sofa."],
      },
      {
        id: "p1-l3",
        text: "A small cat sleeps under the coffee table.",
        es: "Un gato pequeño duerme debajo de la mesa de centro.",
        chunks: ["A small cat", "sleeps", "under the coffee table."],
      },
      {
        id: "p1-l4",
        text: "The lamp is next to the sofa.",
        es: "La lámpara está al lado del sofá.",
        chunks: ["The lamp", "is next to", "the sofa."],
      },
      {
        id: "p1-l5",
        text: "There is a picture above the sofa.",
        es: "Hay un cuadro arriba del sofá.",
        chunks: ["There is a picture", "above the sofa."],
      },
      {
        id: "p1-l6",
        text: "The rug is in front of the sofa.",
        es: "La alfombra está enfrente del sofá.",
        chunks: ["The rug", "is in front of", "the sofa."],
      },
      {
        id: "p1-l7",
        text: "The bookshelf is behind the sofa.",
        es: "El librero está detrás del sofá.",
        chunks: ["The bookshelf", "is behind", "the sofa."],
      },
      {
        id: "p1-l8",
        text: "Her living room is warm and cozy.",
        es: "Su sala es cálida y acogedora.",
        chunks: ["Her living room", "is warm and cozy."],
      },
    ],
    questions: [
      {
        id: "p1-q1",
        question: "Where is the cat?",
        questionEs: "¿Dónde está el gato?",
        hint: "The cat is …",
        hintEs: "The cat is …",
      },
      {
        id: "p1-q2",
        question: "What is above the sofa?",
        questionEs: "¿Qué hay arriba del sofá?",
        hint: "There is a …",
        hintEs: "There is a …",
      },
      {
        id: "p1-q3",
        question: "How many cats are in the living room?",
        questionEs: "¿Cuántos gatos hay en la sala?",
        hint: "There are … cats.",
        hintEs: "There are … cats.",
      },
      {
        id: "p1-q4",
        question: "What is under the coffee table?",
        questionEs: "¿Qué hay debajo de la mesa de centro?",
        hint: "A small cat …",
        hintEs: "A small cat …",
      },
      {
        id: "p1-q5",
        question: "Do you like Marta's living room? Why?",
        questionEs: "¿Te gusta la sala de Marta? ¿Por qué?",
        hint: "Yes, I like it because …",
        hintEs: "Yes, I like it because …",
      },
    ],
    sceneImage: {
      src: sceneLivingRoom,
      alt: "A cozy living room with a sofa, lamp, cats, rug and bookshelf",
      altEs: "Una sala acogedora con sofá, lámpara, gatos, alfombra y librero",
    },
    finalPrompt: {
      question: "Describe Marta's living room. Where are five things?",
      questionEs: "Describe la sala de Marta. ¿Dónde están cinco cosas?",
      tips: {
        en: "Use in, on, under, above, next to, behind and in front of. Say at least five sentences with 'There is'.",
        es: "Usa in, on, under, above, next to, behind e in front of. Di al menos cinco oraciones con 'There is'.",
      },
    },
    grammarGoals: GRAMMAR_GOALS,
  },
  {
    number: 2,
    id: "place-prep-2",
    title: "My Kitchen",
    titleEs: "Mi Cocina",
    person: "first",
    character: null,
    focus: "Describe your kitchen with on, in, next to, above and in front of.",
    focusEs: "Describe tu cocina con on, in, next to, above e in front of.",
    reminder: REMINDER,
    showFullGuide: false,
    instructions: {
      en: "Look at the kitchen. Now describe YOUR kitchen: where are the things you use every day?",
      es: "Mira la cocina. Ahora describe TU cocina: ¿dónde están las cosas que usas todos los días?",
    },
    vocabulary: ["stove", "fridge", "sink", "counter", "bowl", "pot", "clock", "window"],
    lines: [
      {
        id: "p2-l1",
        text: "This is my kitchen.",
        es: "Esta es mi cocina.",
        chunks: ["This is", "my kitchen."],
      },
      {
        id: "p2-l2",
        text: "There is a pot on the stove.",
        es: "Hay una olla en la estufa.",
        chunks: ["There is a pot", "on the stove."],
      },
      {
        id: "p2-l3",
        text: "The apples are in a bowl on the counter.",
        es: "Las manzanas están en un tazón sobre el mesón.",
        chunks: ["The apples", "are in a bowl", "on the counter."],
      },
      {
        id: "p2-l4",
        text: "The trash bin is next to the fridge.",
        es: "El basurero está al lado del refrigerador.",
        chunks: ["The trash bin", "is next to", "the fridge."],
      },
      {
        id: "p2-l5",
        text: "There is a clock above the window.",
        es: "Hay un reloj arriba de la ventana.",
        chunks: ["There is a clock", "above the window."],
      },
      {
        id: "p2-l6",
        text: "The rug is in front of the sink.",
        es: "La alfombra está enfrente del lavaplatos.",
        chunks: ["The rug", "is in front of", "the sink."],
      },
      {
        id: "p2-l7",
        text: "The dishes are in the sink.",
        es: "Los platos están en el lavaplatos.",
        chunks: ["The dishes", "are in the sink."],
      },
      {
        id: "p2-l8",
        text: "I cook dinner in my kitchen every night.",
        es: "Yo cocino la cena en mi cocina cada noche.",
        chunks: ["I cook dinner", "in my kitchen", "every night."],
      },
    ],
    questions: [
      {
        id: "p2-q1",
        question: "Where is the pot?",
        questionEs: "¿Dónde está la olla?",
        hint: "The pot is …",
        hintEs: "The pot is …",
      },
      {
        id: "p2-q2",
        question: "What is next to the fridge?",
        questionEs: "¿Qué hay al lado del refrigerador?",
        hint: "The trash bin is …",
        hintEs: "The trash bin is …",
      },
      {
        id: "p2-q3",
        question: "How often do you cook in your kitchen?",
        questionEs: "¿Con qué frecuencia cocinas en tu cocina?",
        hint: "I cook …",
        hintEs: "I cook …",
      },
      {
        id: "p2-q4",
        question: "Where are the apples?",
        questionEs: "¿Dónde están las manzanas?",
        hint: "The apples are …",
        hintEs: "The apples are …",
      },
      {
        id: "p2-q5",
        question: "What is above the window in your kitchen?",
        questionEs: "¿Qué hay arriba de la ventana en tu cocina?",
        hint: "There is a …",
        hintEs: "There is a …",
      },
    ],
    sceneImage: {
      src: sceneKitchen,
      alt: "A kitchen with a stove, sink, fridge, bowl of apples and a clock above the window",
      altEs: "Una cocina con estufa, lavaplatos, refrigerador, tazón de manzanas y un reloj arriba de la ventana",
    },
    finalPrompt: {
      question: "Describe your kitchen. Where are five things you use every day?",
      questionEs: "Describe tu cocina. ¿Dónde están cinco cosas que usas todos los días?",
      tips: {
        en: "Speak in first person: 'In my kitchen, there is…'. Use at least five different prepositions.",
        es: "Habla en primera persona: 'In my kitchen, there is…'. Usa al menos cinco preposiciones diferentes.",
      },
    },
    grammarGoals: GRAMMAR_GOALS,
  },
  {
    number: 3,
    id: "place-prep-3",
    title: "On the Street",
    titleEs: "En la Calle",
    person: "third",
    character: "Luis",
    focus: "Describe a street with next to, between, behind, in front of and across from.",
    focusEs: "Describe una calle con next to, between, behind, in front of y across from.",
    reminder: REMINDER,
    showFullGuide: false,
    instructions: {
      en: "Look at Luis's street. Describe where the buildings and things are.",
      es: "Mira la calle de Luis. Describe dónde están los edificios y las cosas.",
    },
    vocabulary: ["bank", "pharmacy", "bus stop", "store", "tree", "bench", "dog", "across from"],
    lines: [
      {
        id: "p3-l1",
        text: "Luis lives on a quiet street.",
        es: "Luis vive en una calle tranquila.",
        chunks: ["Luis lives", "on a quiet street."],
      },
      {
        id: "p3-l2",
        text: "The bank is next to the pharmacy.",
        es: "El banco está al lado de la farmacia.",
        chunks: ["The bank", "is next to", "the pharmacy."],
      },
      {
        id: "p3-l3",
        text: "There is a big tree between the two stores.",
        es: "Hay un árbol grande entre las dos tiendas.",
        chunks: ["There is a big tree", "between the two stores."],
      },
      {
        id: "p3-l4",
        text: "The bus stop is in front of the bank.",
        es: "La parada de bus está enfrente del banco.",
        chunks: ["The bus stop", "is in front of", "the bank."],
      },
      {
        id: "p3-l5",
        text: "A dog is behind the bench.",
        es: "Un perro está detrás de la banca.",
        chunks: ["A dog", "is behind", "the bench."],
      },
      {
        id: "p3-l6",
        text: "The pharmacy is across from the supermarket.",
        es: "La farmacia está enfrente del supermercado.",
        chunks: ["The pharmacy", "is across from", "the supermarket."],
      },
      {
        id: "p3-l7",
        text: "There are clouds above the buildings.",
        es: "Hay nubes arriba de los edificios.",
        chunks: ["There are clouds", "above the buildings."],
      },
      {
        id: "p3-l8",
        text: "His house is near the bus stop.",
        es: "Su casa está cerca de la parada de bus.",
        chunks: ["His house", "is near", "the bus stop."],
      },
    ],
    questions: [
      {
        id: "p3-q1",
        question: "Where is the bank?",
        questionEs: "¿Dónde está el banco?",
        hint: "The bank is …",
        hintEs: "The bank is …",
      },
      {
        id: "p3-q2",
        question: "What is between the two stores?",
        questionEs: "¿Qué hay entre las dos tiendas?",
        hint: "There is a …",
        hintEs: "There is a …",
      },
      {
        id: "p3-q3",
        question: "Who is behind the bench?",
        questionEs: "¿Quién está detrás de la banca?",
        hint: "A dog is …",
        hintEs: "A dog is …",
      },
      {
        id: "p3-q4",
        question: "What is across from the pharmacy?",
        questionEs: "¿Qué hay enfrente de la farmacia?",
        hint: "The supermarket is …",
        hintEs: "The supermarket is …",
      },
      {
        id: "p3-q5",
        question: "Is there a bus stop near your house?",
        questionEs: "¿Hay una parada de bus cerca de tu casa?",
        hint: "Yes, there is … / No, there isn't …",
        hintEs: "Yes, there is … / No, there isn't …",
      },
    ],
    sceneImage: {
      src: sceneStreet,
      alt: "A small town street with a bank, stores, a tree, a bench and a dog",
      altEs: "Una calle pequeña con un banco, tiendas, un árbol, una banca y un perro",
    },
    finalPrompt: {
      question: "Describe Luis's street. Where are five places or things?",
      questionEs: "Describe la calle de Luis. ¿Dónde están cinco lugares o cosas?",
      tips: {
        en: "Use next to, between, behind, in front of and across from. Describe at least five places.",
        es: "Usa next to, between, behind, in front of y across from. Describe al menos cinco lugares.",
      },
    },
    grammarGoals: GRAMMAR_GOALS,
  },
  {
    number: 4,
    id: "place-prep-4",
    title: "My Classroom",
    titleEs: "Mi Salón de Clases",
    person: "first",
    character: null,
    focus: "Describe your classroom or workspace with on, under, above, between and near.",
    focusEs: "Describe tu salón o espacio de trabajo con on, under, above, between y near.",
    reminder: REMINDER,
    showFullGuide: false,
    instructions: {
      en: "Look at the classroom. Describe YOUR classroom, office or study space.",
      es: "Mira el salón. Describe TU salón, oficina o espacio de estudio.",
    },
    vocabulary: ["desk", "board", "globe", "backpack", "clock", "plant", "window", "chair"],
    lines: [
      {
        id: "p4-l1",
        text: "This is my classroom.",
        es: "Este es mi salón de clases.",
        chunks: ["This is", "my classroom."],
      },
      {
        id: "p4-l2",
        text: "The globe is on the teacher's desk.",
        es: "El globo está sobre el escritorio del profesor.",
        chunks: ["The globe", "is on", "the teacher's desk."],
      },
      {
        id: "p4-l3",
        text: "My backpack is under my chair.",
        es: "Mi mochila está debajo de mi silla.",
        chunks: ["My backpack", "is under", "my chair."],
      },
      {
        id: "p4-l4",
        text: "The clock is above the board.",
        es: "El reloj está arriba de la pizarra.",
        chunks: ["The clock", "is above", "the board."],
      },
      {
        id: "p4-l5",
        text: "My pencil case is between two books.",
        es: "Mi cartuchera está entre dos libros.",
        chunks: ["My pencil case", "is between", "two books."],
      },
      {
        id: "p4-l6",
        text: "There is a plant near the window.",
        es: "Hay una planta cerca de la ventana.",
        chunks: ["There is a plant", "near the window."],
      },
      {
        id: "p4-l7",
        text: "My desk is in front of the board.",
        es: "Mi escritorio está enfrente de la pizarra.",
        chunks: ["My desk", "is in front of", "the board."],
      },
      {
        id: "p4-l8",
        text: "I study English in this room every day.",
        es: "Estudio inglés en este salón todos los días.",
        chunks: ["I study English", "in this room", "every day."],
      },
    ],
    questions: [
      {
        id: "p4-q1",
        question: "Where is your backpack?",
        questionEs: "¿Dónde está tu mochila?",
        hint: "My backpack is …",
        hintEs: "My backpack is …",
      },
      {
        id: "p4-q2",
        question: "What is above the board?",
        questionEs: "¿Qué hay arriba de la pizarra?",
        hint: "The clock is …",
        hintEs: "The clock is …",
      },
      {
        id: "p4-q3",
        question: "How long do you study English every day?",
        questionEs: "¿Cuánto tiempo estudias inglés cada día?",
        hint: "I study for …",
        hintEs: "I study for …",
      },
      {
        id: "p4-q4",
        question: "Where is the plant?",
        questionEs: "¿Dónde está la planta?",
        hint: "The plant is …",
        hintEs: "The plant is …",
      },
      {
        id: "p4-q5",
        question: "What is between the two books?",
        questionEs: "¿Qué hay entre los dos libros?",
        hint: "The pencil case is …",
        hintEs: "The pencil case is …",
      },
    ],
    sceneImage: {
      src: sceneClassroom,
      alt: "A classroom with desks, a board, a clock, a globe, a backpack and a plant",
      altEs: "Un salón con escritorios, pizarra, reloj, globo, mochila y planta",
    },
    finalPrompt: {
      question: "Describe your classroom or study space. Where are five things?",
      questionEs: "Describe tu salón o espacio de estudio. ¿Dónde están cinco cosas?",
      tips: {
        en: "Speak in first person: 'My desk is…'. Use on, under, above, between, near and in front of.",
        es: "Habla en primera persona: 'My desk is…'. Usa on, under, above, between, near e in front of.",
      },
    },
    grammarGoals: GRAMMAR_GOALS,
  },
  {
    number: 5,
    id: "place-prep-5",
    title: "At the Park",
    titleEs: "En el Parque",
    person: "third",
    character: "Sofia",
    focus: "Describe a park with under, in front of, between, behind and above.",
    focusEs: "Describe un parque con under, in front of, between, behind y above.",
    reminder: REMINDER,
    showFullGuide: false,
    instructions: {
      en: "Look at the park where Sofia plays. Describe the park from the key facts.",
      es: "Mira el parque donde juega Sofía. Describe el parque con los datos clave.",
    },
    vocabulary: ["bench", "fountain", "swing", "flower bed", "ball", "bird", "grass"],
    factSheet: [
      { en: "A bench is under the big tree.", es: "Una banca está debajo del árbol grande." },
      { en: "A ball is on the grass in front of the bench.", es: "Una pelota está en el pasto enfrente de la banca." },
      { en: "The fountain is between two flower beds.", es: "La fuente está entre dos jardineras." },
      { en: "Sofia is on the swing behind the fountain.", es: "Sofía está en el columpio detrás de la fuente." },
      { en: "A bird is above the tree.", es: "Un pájaro está arriba del árbol." },
    ],
    lines: [
      {
        id: "p5-l1",
        text: "Sofia goes to the park every weekend.",
        es: "Sofía va al parque cada fin de semana.",
        chunks: ["Sofia goes to the park", "every weekend."],
      },
      {
        id: "p5-l2",
        text: "There is a bench under the big tree.",
        es: "Hay una banca debajo del árbol grande.",
        chunks: ["There is a bench", "under the big tree."],
      },
      {
        id: "p5-l3",
        text: "A ball is on the grass in front of the bench.",
        es: "Una pelota está en el pasto enfrente de la banca.",
        chunks: ["A ball", "is on the grass", "in front of the bench."],
      },
      {
        id: "p5-l4",
        text: "The fountain is between two flower beds.",
        es: "La fuente está entre dos jardineras.",
        chunks: ["The fountain", "is between", "two flower beds."],
      },
      {
        id: "p5-l5",
        text: "Sofia is on the swing behind the fountain.",
        es: "Sofía está en el columpio detrás de la fuente.",
        chunks: ["Sofia is on the swing", "behind the fountain."],
      },
      {
        id: "p5-l6",
        text: "A bird is above the tree.",
        es: "Un pájaro está arriba del árbol.",
        chunks: ["A bird", "is above the tree."],
      },
      {
        id: "p5-l7",
        text: "Her brother sits next to the fountain.",
        es: "Su hermano se sienta al lado de la fuente.",
        chunks: ["Her brother", "sits next to", "the fountain."],
      },
      {
        id: "p5-l8",
        text: "The park is her favorite place in the city.",
        es: "El parque es su lugar favorito de la ciudad.",
        chunks: ["The park is", "her favorite place", "in the city."],
      },
    ],
    questions: [
      {
        id: "p5-q1",
        question: "Where is the bench?",
        questionEs: "¿Dónde está la banca?",
        hint: "The bench is …",
        hintEs: "The bench is …",
      },
      {
        id: "p5-q2",
        question: "What is between the two flower beds?",
        questionEs: "¿Qué hay entre las dos jardineras?",
        hint: "The fountain is …",
        hintEs: "The fountain is …",
      },
      {
        id: "p5-q3",
        question: "Who is on the swing?",
        questionEs: "¿Quién está en el columpio?",
        hint: "Sofia is …",
        hintEs: "Sofia is …",
      },
      {
        id: "p5-q4",
        question: "What is above the tree?",
        questionEs: "¿Qué hay arriba del árbol?",
        hint: "A bird is …",
        hintEs: "A bird is …",
      },
      {
        id: "p5-q5",
        question: "Is there a park near your house? Describe it.",
        questionEs: "¿Hay un parque cerca de tu casa? Descríbelo.",
        hint: "Yes, there is a park … It has …",
        hintEs: "Yes, there is a park … It has …",
      },
    ],
    sceneImage: {
      src: scenePark,
      alt: "A park with a bench under a tree, a fountain, a swing, flowers and a bird",
      altEs: "Un parque con una banca bajo un árbol, una fuente, un columpio, flores y un pájaro",
    },
    finalPrompt: {
      question: "Describe Sofia's park. Where are five things? Use the key facts and the picture.",
      questionEs: "Describe el parque de Sofía. ¿Dónde están cinco cosas? Usa los datos clave y la imagen.",
      tips: {
        en: "Use under, on, in front of, between, behind and above. Say at least five complete sentences.",
        es: "Usa under, on, in front of, between, behind y above. Di al menos cinco oraciones completas.",
      },
    },
    grammarGoals: GRAMMAR_GOALS,
  },
];
