import type { ReviewPractice } from "@/lib/review-types";
import scene1 from "@/assets/review/prepositions/prep-practice-1.jpg";
import scene2 from "@/assets/review/prepositions/prep-practice-2.jpg";
import scene3 from "@/assets/review/prepositions/prep-practice-3.jpg";
import scene4 from "@/assets/review/prepositions/prep-practice-4.jpg";
import scene5 from "@/assets/review/prepositions/prep-practice-5.jpg";

const img = (src: string, alt: string, altEs: string) => ({ src, alt, altEs });

/**
 * REVIEW · PREPOSITIONS OF TIME AND PLACE — five static practices.
 *
 * Person of the learner's MAIN answers alternates: 3rd · 1st · 3rd · 1st · 3rd.
 * Practices 1–2 focus on TIME (in / on / at / for / since / from … to / until),
 * practices 3–4 on PLACE and movement, practice 5 mixes both.
 * Hand-written content: nothing generated by AI.
 */
export const PREPOSITIONS_PRACTICES: ReviewPractice[] = [
  {
    number: 1,
    id: "prep-1-marcela-week",
    title: "Marcela's week",
    titleEs: "La semana de Marcela",
    person: "third",
    character: "Marcela",
    focus: "Time prepositions in the third person: in for months and parts of the day, on for days, at for exact times.",
    focusEs: "Preposiciones de tiempo en tercera persona: in para meses y partes del día, on para días, at para horas exactas.",
    reminder: {
      en: "in + month or part of the day, on + day or date, at + exact time.",
      es: "in + mes o parte del día, on + día o fecha, at + hora exacta.",
    },
    showFullGuide: true,
    instructions: {
      en: "Describe Marcela's weekly schedule. Say when she does each thing.",
      es: "Describe el horario semanal de Marcela. Di cuándo hace cada cosa.",
    },
    sceneImage: img(scene1, "Marcela planning her week with a calendar and a clock", "Marcela planificando su semana con un calendario y un reloj"),
    vocabulary: ["in the morning", "on Monday", "at 8:00", "at night", "on weekends", "in July", "until", "from … to"],
    lines: [
      { id: "prep1-l1", text: "Marcela starts work at eight in the morning.", es: "Marcela empieza a trabajar a las ocho de la mañana.", chunks: ["Marcela starts work", "at eight", "in the morning."] },
      { id: "prep1-l2", text: "She has a team meeting on Monday and on Thursday.", es: "Tiene reunión de equipo el lunes y el jueves.", chunks: ["She has a team meeting", "on Monday", "and on Thursday."] },
      { id: "prep1-l3", text: "She takes her lunch break at noon.", es: "Toma su almuerzo al mediodía.", chunks: ["She takes her lunch break", "at noon."] },
      { id: "prep1-l4", text: "She works from nine to six every weekday.", es: "Trabaja de nueve a seis cada día de semana.", chunks: ["She works", "from nine to six", "every weekday."] },
      { id: "prep1-l5", text: "She studies English in the evening, after dinner.", es: "Estudia inglés en la noche, después de cenar.", chunks: ["She studies English", "in the evening,", "after dinner."] },
      { id: "prep1-l6", text: "She visits her mother on Saturday afternoon.", es: "Visita a su mamá el sábado por la tarde.", chunks: ["She visits her mother", "on Saturday afternoon."] },
      { id: "prep1-l7", text: "She rests at night and sleeps until six.", es: "Descansa en la noche y duerme hasta las seis.", chunks: ["She rests at night", "and sleeps until six."] },
      { id: "prep1-l8", text: "In December she takes two weeks of vacation.", es: "En diciembre toma dos semanas de vacaciones.", chunks: ["In December", "she takes", "two weeks of vacation."] },
    ],
    questions: [
      { id: "prep1-q1", question: "When does Marcela visit her mother?", questionEs: "¿Cuándo visita Marcela a su mamá?", hint: "She visits her mother on…", hintEs: "Usa on + día." },
      { id: "prep1-q2", question: "What time does she start work?", questionEs: "¿A qué hora empieza a trabajar?", hint: "She starts at…", hintEs: "Usa at + hora." },
      { id: "prep1-q3", question: "Where is she at noon?", questionEs: "¿Dónde está al mediodía?", hint: "She is at…", hintEs: "Usa at + lugar." },
      { id: "prep1-q4", question: "How often does she have team meetings?", questionEs: "¿Con qué frecuencia tiene reuniones de equipo?", hint: "She has meetings on…", hintEs: "Usa on + días." },
      { id: "prep1-q5", question: "Why does she study in the evening?", questionEs: "¿Por qué estudia en la noche?", hint: "Because she works…", hintEs: "Explica con because." },
    ],
    finalPrompt: {
      question: "Describe Marcela's complete week: her times, her days and her free moments.",
      questionEs: "Describe la semana completa de Marcela: sus horas, sus días y sus momentos libres.",
      tips: { en: "Use in, on and at at least once each, plus from … to.", es: "Usa in, on y at al menos una vez cada uno, y from … to." },
    },
    grammarGoals: ["at + exact clock time", "on + day of the week", "in + month or part of the day", "from … to for a period"],
  },
  {
    number: 2,
    id: "prep-2-my-routine",
    title: "My routine and my times",
    titleEs: "Mi rutina y mis horarios",
    person: "first",
    character: null,
    focus: "First person time prepositions plus duration with for, since, during and until.",
    focusEs: "Preposiciones de tiempo en primera persona más duración con for, since, during y until.",
    reminder: {
      en: "for + how long, since + when it started, during + event, until + the limit.",
      es: "for + cuánto tiempo, since + desde cuándo, during + evento, until + hasta cuándo.",
    },
    showFullGuide: false,
    instructions: {
      en: "Talk about your own day: your times, your days and how long you have done things.",
      es: "Habla de tu propio día: tus horarios, tus días y cuánto tiempo llevas haciendo las cosas.",
    },
    sceneImage: img(scene2, "A learner's daily routine: waking up, taking the bus and studying at night", "La rutina diaria de un estudiante: levantarse, tomar el bus y estudiar de noche"),
    vocabulary: ["for", "since", "during", "until", "at", "on", "in", "every day"],
    lines: [
      { id: "prep2-l1", text: "I wake up at five thirty every morning.", es: "Me despierto a las cinco y media cada mañana.", chunks: ["I wake up", "at five thirty", "every morning."] },
      { id: "prep2-l2", text: "I have studied English for two years.", es: "He estudiado inglés por dos años.", chunks: ["I have studied English", "for two years."] },
      { id: "prep2-l3", text: "I have lived in this city since 2022.", es: "Vivo en esta ciudad desde 2022.", chunks: ["I have lived in this city", "since 2022."] },
      { id: "prep2-l4", text: "I practice speaking during my lunch break.", es: "Practico speaking durante mi hora de almuerzo.", chunks: ["I practice speaking", "during my lunch break."] },
      { id: "prep2-l5", text: "I work from Monday to Friday, from eight to five.", es: "Trabajo de lunes a viernes, de ocho a cinco.", chunks: ["I work from Monday to Friday,", "from eight to five."] },
      { id: "prep2-l6", text: "On Sundays I rest until ten in the morning.", es: "Los domingos descanso hasta las diez de la mañana.", chunks: ["On Sundays", "I rest until ten", "in the morning."] },
      { id: "prep2-l7", text: "In the evening I review my notes for thirty minutes.", es: "En la noche repaso mis apuntes por treinta minutos.", chunks: ["In the evening", "I review my notes", "for thirty minutes."] },
      { id: "prep2-l8", text: "At night I turn off my phone and go to bed.", es: "En la noche apago mi teléfono y me voy a dormir.", chunks: ["At night", "I turn off my phone", "and go to bed."] },
    ],
    questions: [
      { id: "prep2-q1", question: "How long have you studied English?", questionEs: "¿Cuánto tiempo llevas estudiando inglés?", hint: "I have studied English for…", hintEs: "Usa for + duración." },
      { id: "prep2-q2", question: "How often do you practice speaking?", questionEs: "¿Con qué frecuencia practicas speaking?", hint: "I practice…", hintEs: "Di una frecuencia." },
      { id: "prep2-q3", question: "What time do you wake up?", questionEs: "¿A qué hora te despiertas?", hint: "I wake up at…", hintEs: "Usa at + hora." },
      { id: "prep2-q4", question: "When do you rest?", questionEs: "¿Cuándo descansas?", hint: "I rest on…", hintEs: "Usa on + día." },
      { id: "prep2-q5", question: "Where do you study in the evening?", questionEs: "¿Dónde estudias en la noche?", hint: "I study at / in…", hintEs: "Usa at o in + lugar." },
    ],
    finalPrompt: {
      question: "Describe your normal day and say how long you have done your main activities.",
      questionEs: "Describe tu día normal y di cuánto tiempo llevas haciendo tus actividades principales.",
      tips: { en: "Use for and since correctly, and at least three of in, on, at, until.", es: "Usa for y since correctamente, y al menos tres de in, on, at, until." },
    },
    grammarGoals: ["for + duration vs since + starting point", "at / on / in with times, days and parts of the day", "until and from … to"],
  },
  {
    number: 3,
    id: "prep-3-diego-office",
    title: "Diego's office",
    titleEs: "La oficina de Diego",
    person: "third",
    character: "Diego",
    focus: "Place prepositions in the third person: in, on, at plus position words.",
    focusEs: "Preposiciones de lugar en tercera persona: in, on, at más palabras de posición.",
    reminder: {
      en: "in = inside, on = on a surface, at = a point or an activity.",
      es: "in = adentro, on = sobre una superficie, at = un punto o una actividad.",
    },
    showFullGuide: false,
    instructions: {
      en: "Describe where Diego is and where the things in his office are.",
      es: "Describe dónde está Diego y dónde están las cosas de su oficina.",
    },
    sceneImage: img(scene3, "Diego working at a desk with a laptop, a printer next to him and a plant near the window", "Diego trabajando en un escritorio con una laptop, una impresora a su lado y una planta cerca de la ventana"),
    vocabulary: ["on the desk", "next to", "in front of", "behind", "under", "between", "at work", "near"],
    lines: [
      { id: "prep3-l1", text: "Diego is at work in a small office.", es: "Diego está en el trabajo, en una oficina pequeña.", chunks: ["Diego is at work", "in a small office."] },
      { id: "prep3-l2", text: "His laptop is on the desk, next to his notebook.", es: "Su laptop está sobre el escritorio, al lado de su cuaderno.", chunks: ["His laptop is on the desk,", "next to his notebook."] },
      { id: "prep3-l3", text: "The printer is behind him, near the window.", es: "La impresora está detrás de él, cerca de la ventana.", chunks: ["The printer is behind him,", "near the window."] },
      { id: "prep3-l4", text: "There is a plant under the window.", es: "Hay una planta debajo de la ventana.", chunks: ["There is a plant", "under the window."] },
      { id: "prep3-l5", text: "Two pictures hang on the wall in front of his desk.", es: "Dos cuadros cuelgan en la pared enfrente de su escritorio.", chunks: ["Two pictures hang on the wall", "in front of his desk."] },
      { id: "prep3-l6", text: "His office is between the kitchen and the meeting room.", es: "Su oficina está entre la cocina y la sala de reuniones.", chunks: ["His office is between", "the kitchen", "and the meeting room."] },
      { id: "prep3-l7", text: "The building is on Third Street, in the center of the city.", es: "El edificio está en la Tercera Calle, en el centro de la ciudad.", chunks: ["The building is on Third Street,", "in the center of the city."] },
      { id: "prep3-l8", text: "At six he leaves the office and goes home.", es: "A las seis sale de la oficina y se va a casa.", chunks: ["At six he leaves the office", "and goes home."] },
    ],
    questions: [
      { id: "prep3-q1", question: "Where is Diego's laptop?", questionEs: "¿Dónde está la laptop de Diego?", hint: "It is on…", hintEs: "Usa on + superficie." },
      { id: "prep3-q2", question: "What is under the window?", questionEs: "¿Qué hay debajo de la ventana?", hint: "There is…", hintEs: "Usa There is + under." },
      { id: "prep3-q3", question: "Who sits in front of the pictures?", questionEs: "¿Quién se sienta enfrente de los cuadros?", hint: "Diego sits…", hintEs: "Usa in front of." },
      { id: "prep3-q4", question: "How long does he stay at the office?", questionEs: "¿Cuánto tiempo se queda en la oficina?", hint: "He stays for…", hintEs: "Usa for + duración." },
      { id: "prep3-q5", question: "Why is his office comfortable?", questionEs: "¿Por qué es cómoda su oficina?", hint: "Because it is…", hintEs: "Explica con because." },
    ],
    finalPrompt: {
      question: "Describe Diego's office completely: where he is and where every object is.",
      questionEs: "Describe la oficina de Diego completa: dónde está él y dónde está cada objeto.",
      tips: { en: "Use in, on and at plus three position words.", es: "Usa in, on y at más tres palabras de posición." },
    },
    grammarGoals: ["in / on / at for place", "position words: next to, behind, under, between, in front of", "there is / there are with places"],
  },
  {
    number: 4,
    id: "prep-4-my-neighborhood",
    title: "My neighborhood and my route",
    titleEs: "Mi colonia y mi ruta",
    person: "first",
    character: null,
    focus: "First person place and movement prepositions: to, from, across, through, into.",
    focusEs: "Preposiciones de lugar y movimiento en primera persona: to, from, across, through, into.",
    reminder: {
      en: "go TO a place, come FROM a place, but go HOME with no preposition.",
      es: "go TO un lugar, come FROM un lugar, pero go HOME sin preposición.",
    },
    showFullGuide: false,
    instructions: {
      en: "Explain where you live and how you go from your house to work or school.",
      es: "Explica dónde vives y cómo vas de tu casa al trabajo o a la escuela.",
    },
    sceneImage: img(scene4, "A neighborhood with a person walking from a house across the street to a bus stop", "Una colonia con una persona caminando de su casa al otro lado de la calle hacia la parada de bus"),
    vocabulary: ["from", "to", "across", "through", "into", "out of", "near", "opposite"],
    lines: [
      { id: "prep4-l1", text: "I live in a small house on a quiet street.", es: "Vivo en una casa pequeña en una calle tranquila.", chunks: ["I live in a small house", "on a quiet street."] },
      { id: "prep4-l2", text: "My house is opposite a park and next to a store.", es: "Mi casa está enfrente de un parque y al lado de una tienda.", chunks: ["My house is opposite a park", "and next to a store."] },
      { id: "prep4-l3", text: "I walk from my house to the bus stop.", es: "Camino de mi casa a la parada de bus.", chunks: ["I walk from my house", "to the bus stop."] },
      { id: "prep4-l4", text: "I cross the street and walk across the park.", es: "Cruzo la calle y camino a través del parque.", chunks: ["I cross the street", "and walk across the park."] },
      { id: "prep4-l5", text: "I get on the bus at seven and get off downtown.", es: "Me subo al bus a las siete y me bajo en el centro.", chunks: ["I get on the bus at seven", "and get off downtown."] },
      { id: "prep4-l6", text: "The bus goes through a long tunnel.", es: "El bus pasa por un túnel largo.", chunks: ["The bus goes", "through a long tunnel."] },
      { id: "prep4-l7", text: "I walk into the building and take the elevator.", es: "Entro al edificio y tomo el elevador.", chunks: ["I walk into the building", "and take the elevator."] },
      { id: "prep4-l8", text: "After work I go home and stay at home all evening.", es: "Después del trabajo me voy a casa y me quedo en casa toda la noche.", chunks: ["After work I go home", "and stay at home", "all evening."] },
    ],
    questions: [
      { id: "prep4-q1", question: "How do you go to work?", questionEs: "¿Cómo vas al trabajo?", hint: "I walk / I take…", hintEs: "Explica el transporte." },
      { id: "prep4-q2", question: "Where is your house?", questionEs: "¿Dónde está tu casa?", hint: "My house is on / near…", hintEs: "Usa on, near u opposite." },
      { id: "prep4-q3", question: "Why do you like your neighborhood?", questionEs: "¿Por qué te gusta tu colonia?", hint: "Because it is…", hintEs: "Explica con because." },
      { id: "prep4-q4", question: "What time do you get on the bus?", questionEs: "¿A qué hora te subes al bus?", hint: "I get on the bus at…", hintEs: "Usa at + hora." },
      { id: "prep4-q5", question: "How long is your trip?", questionEs: "¿Cuánto dura tu viaje?", hint: "It takes…", hintEs: "Usa for o It takes + tiempo." },
    ],
    finalPrompt: {
      question: "Describe your neighborhood and your complete route from home to work or school.",
      questionEs: "Describe tu colonia y tu ruta completa desde tu casa al trabajo o a la escuela.",
      tips: { en: "Use from … to, across or through, and two position words.", es: "Usa from … to, across o through, y dos palabras de posición." },
    },
    grammarGoals: ["movement: to, from, into, out of, across, through", "go home without to", "place: in / on / at with houses, streets and buildings"],
  },
  {
    number: 5,
    id: "prep-5-sofia-trip",
    title: "Sofía's trip",
    titleEs: "El viaje de Sofía",
    person: "third",
    character: "Sofía",
    focus: "Time and place prepositions together in a real travel schedule.",
    focusEs: "Preposiciones de tiempo y lugar juntas en un itinerario real de viaje.",
    reminder: {
      en: "Time and place in the same sentence: at 6:00 at the airport, in June in Miami.",
      es: "Tiempo y lugar en la misma oración: at 6:00 at the airport, in June in Miami.",
    },
    showFullGuide: false,
    instructions: {
      en: "Describe Sofía's trip: when each step happens and where she is.",
      es: "Describe el viaje de Sofía: cuándo pasa cada paso y dónde está ella.",
    },
    sceneImage: img(scene5, "Sofía waiting at an airport gate with a suitcase and a clock on the wall", "Sofía esperando en la puerta del aeropuerto con una maleta y un reloj en la pared"),
    vocabulary: ["at the airport", "in June", "on Friday", "until", "for", "from … to", "near", "between"],
    lines: [
      { id: "prep5-l1", text: "Sofía travels to Miami in June, on Friday morning.", es: "Sofía viaja a Miami en junio, el viernes por la mañana.", chunks: ["Sofía travels to Miami", "in June,", "on Friday morning."] },
      { id: "prep5-l2", text: "She arrives at the airport at four in the morning.", es: "Llega al aeropuerto a las cuatro de la mañana.", chunks: ["She arrives at the airport", "at four", "in the morning."] },
      { id: "prep5-l3", text: "She waits at gate twelve for two hours.", es: "Espera en la puerta doce por dos horas.", chunks: ["She waits at gate twelve", "for two hours."] },
      { id: "prep5-l4", text: "Her suitcase is next to her, between two chairs.", es: "Su maleta está a su lado, entre dos sillas.", chunks: ["Her suitcase is next to her,", "between two chairs."] },
      { id: "prep5-l5", text: "The flight leaves at six and lands at ten.", es: "El vuelo sale a las seis y aterriza a las diez.", chunks: ["The flight leaves at six", "and lands at ten."] },
      { id: "prep5-l6", text: "She stays in a hotel near the beach for one week.", es: "Se queda en un hotel cerca de la playa por una semana.", chunks: ["She stays in a hotel", "near the beach", "for one week."] },
      { id: "prep5-l7", text: "She works from Monday to Wednesday, and rests on the weekend.", es: "Trabaja de lunes a miércoles y descansa el fin de semana.", chunks: ["She works from Monday to Wednesday,", "and rests on the weekend."] },
      { id: "prep5-l8", text: "She returns home on Sunday night, at eleven.", es: "Regresa a casa el domingo en la noche, a las once.", chunks: ["She returns home", "on Sunday night,", "at eleven."] },
    ],
    questions: [
      { id: "prep5-q1", question: "When does Sofía travel to Miami?", questionEs: "¿Cuándo viaja Sofía a Miami?", hint: "She travels in… on…", hintEs: "Usa in + mes y on + día." },
      { id: "prep5-q2", question: "Where does she stay?", questionEs: "¿Dónde se queda?", hint: "She stays in a hotel…", hintEs: "Usa in y near." },
      { id: "prep5-q3", question: "How long does she wait at the gate?", questionEs: "¿Cuánto tiempo espera en la puerta?", hint: "She waits for…", hintEs: "Usa for + duración." },
      { id: "prep5-q4", question: "What time does her flight leave?", questionEs: "¿A qué hora sale su vuelo?", hint: "It leaves at…", hintEs: "Usa at + hora." },
      { id: "prep5-q5", question: "Who travels with her?", questionEs: "¿Quién viaja con ella?", hint: "She travels with…", hintEs: "Usa with + persona." },
    ],
    finalPrompt: {
      question: "Tell Sofía's complete trip: every time and every place, from the airport to her return.",
      questionEs: "Cuenta el viaje completo de Sofía: cada hora y cada lugar, desde el aeropuerto hasta su regreso.",
      tips: { en: "Mix time and place prepositions in the same sentences.", es: "Mezcla preposiciones de tiempo y lugar en las mismas oraciones." },
    },
    grammarGoals: ["time and place prepositions in one sentence", "for + duration", "at + exact time, in + month, on + day"],
  },
];
