import type { ReviewGuideCard } from "@/lib/review-types";

/**
 * "ENTIÉNDELO FÁCIL" — the seven basics of prepositions of TIME and PLACE.
 * Static hand-written content: never generated by AI, reused by every practice
 * (Practice 1 shows it inline in Step 1, practices 2–5 open it on demand).
 */
export const PREPOSITIONS_GUIDE: ReviewGuideCard[] = [
  {
    id: "prep-1-use",
    title: "What prepositions are for",
    titleEs: "Para qué sirven las preposiciones",
    explanation: "Prepositions connect an action with a time or a place: in July, on Monday, at 8:00, in Miami, on the table, at work.",
    explanationEs:
      "Las preposiciones conectan la acción con un tiempo o un lugar. Las tres grandes son in, on y at, y se usan tanto para tiempo como para lugar. El truco: van de lo GRANDE (in) a lo EXACTO (at).",
    examples: [
      { en: "I start work at 8:00.", es: "Empiezo a trabajar a las 8:00." },
      { en: "She travels in December.", es: "Ella viaja en diciembre." },
      { en: "The keys are on the table.", es: "Las llaves están sobre la mesa." },
    ],
    check: {
      prompt: "Say one time and one place with a preposition.",
      promptEs: "Di una hora y un lugar usando preposición.",
      answer: "I work at home at 9:00.",
    },
  },
  {
    id: "prep-2-in-time",
    title: "IN for long time: months, years, seasons",
    titleEs: "IN para tiempos largos: meses, años, estaciones",
    explanation: "in July, in 2026, in the summer, in the morning, in two hours.",
    explanationEs:
      "Usa in con periodos largos: meses (in July), años (in 2026), estaciones (in the winter), partes del día (in the morning / in the afternoon / in the evening) y tiempo futuro (in two hours = dentro de dos horas). Excepción: at night, no “in the night”.",
    examples: [
      { en: "My brother arrives in October.", es: "Mi hermano llega en octubre." },
      { en: "I study English in the evening.", es: "Estudio inglés en la noche." },
      { en: "The meeting starts in ten minutes.", es: "La reunión empieza en diez minutos." },
    ],
    check: {
      prompt: "Say the month and the part of the day you practice.",
      promptEs: "Di el mes y la parte del día en que practicas.",
      answer: "I practice in March, in the morning.",
    },
  },
  {
    id: "prep-3-on-time",
    title: "ON for days and dates",
    titleEs: "ON para días y fechas",
    explanation: "on Monday, on Fridays, on July 4th, on my birthday, on the weekend.",
    explanationEs:
      "Usa on con días y fechas: on Monday, on Tuesdays (todos los martes), on March 12th, on my birthday, on Christmas Day. También on Monday morning: cuando el día aparece, gana on.",
    examples: [
      { en: "We have a team meeting on Wednesday.", es: "Tenemos reunión de equipo el miércoles." },
      { en: "She was born on May 9th.", es: "Ella nació el 9 de mayo." },
      { en: "I rest on Sunday morning.", es: "Descanso el domingo por la mañana." },
    ],
    check: {
      prompt: "Say the day you rest.",
      promptEs: "Di el día en que descansas.",
      answer: "I rest on Saturday.",
    },
  },
  {
    id: "prep-4-at-time",
    title: "AT for exact moments",
    titleEs: "AT para momentos exactos",
    explanation: "at 7:30, at noon, at midnight, at night, at the moment, at the same time.",
    explanationEs:
      "Usa at con la hora exacta y con momentos puntuales: at 6:00, at noon, at midnight, at night, at lunchtime, at the weekend (inglés británico). Nunca digas “in 8:00”.",
    examples: [
      { en: "My shift starts at 2:00 p.m.", es: "Mi turno empieza a las 2:00 p. m." },
      { en: "I call my family at night.", es: "Llamo a mi familia en la noche." },
      { en: "We take a break at noon.", es: "Tomamos un descanso al mediodía." },
    ],
    check: {
      prompt: "Say the exact time you start your day.",
      promptEs: "Di la hora exacta en que empiezas tu día.",
      answer: "I start at 6:15.",
    },
  },
  {
    id: "prep-5-place",
    title: "IN, ON, AT for place",
    titleEs: "IN, ON, AT para lugar",
    explanation: "in a country or room, on a surface or street, at a point or activity: at work, at school, at home.",
    explanationEs:
      "in = adentro de algo cerrado o grande: in Guatemala, in the kitchen, in the car. on = sobre una superficie o línea: on the table, on the wall, on Main Street, on the bus. at = un punto o una actividad: at work, at school, at home, at the door, at the bus stop.",
    examples: [
      { en: "My laptop is on the desk in my room.", es: "Mi laptop está sobre el escritorio en mi cuarto." },
      { en: "She is at work until six.", es: "Ella está en el trabajo hasta las seis." },
      { en: "They live in Houston, on Green Street.", es: "Ellos viven en Houston, en la calle Green." },
    ],
    check: {
      prompt: "Say where you are right now with in, on or at.",
      promptEs: "Di dónde estás ahora con in, on o at.",
      answer: "I am at home, in the living room.",
    },
  },
  {
    id: "prep-6-position",
    title: "Position and movement",
    titleEs: "Posición y movimiento",
    explanation: "next to, in front of, behind, between, under, over, near; to, from, into, out of, across, through.",
    explanationEs:
      "Posición: next to (al lado de), in front of (enfrente de), behind (detrás), between (entre dos), among (entre varios), under, over, near, opposite. Movimiento: go TO work (no “go to home”: se dice go home), come FROM, walk INTO, get OUT OF, walk ACROSS the street, drive THROUGH the tunnel.",
    examples: [
      { en: "The bank is next to the pharmacy.", es: "El banco está al lado de la farmacia." },
      { en: "I walk from my house to the bus stop.", es: "Camino de mi casa a la parada del bus." },
      { en: "The store is between the school and the park.", es: "La tienda está entre la escuela y el parque." },
    ],
    check: {
      prompt: "Describe one place near your house.",
      promptEs: "Describe un lugar cerca de tu casa.",
      answer: "The park is in front of my house.",
    },
  },
  {
    id: "prep-7-duration",
    title: "Duration and questions: for, since, during, until",
    titleEs: "Duración y preguntas: for, since, during, until",
    explanation: "for + period, since + starting point, during + event, from … to, until.",
    explanationEs:
      "for + duración (for two hours, for five years). since + punto de inicio (since 2020, since Monday). during + evento (during the call, during the summer). from … to (from 8 to 5). until = hasta (until six). Preguntas: Where do you work? When do you start? What time is the call? How long have you lived there? How often do you travel?",
    examples: [
      { en: "I have worked here for three years.", es: "He trabajado aquí por tres años." },
      { en: "She has lived in Miami since 2021.", es: "Ella vive en Miami desde 2021." },
      { en: "I study from seven to nine, during the week.", es: "Estudio de siete a nueve, durante la semana." },
    ],
    check: {
      prompt: "Ask: ¿Cuánto tiempo llevas en tu trabajo?",
      promptEs: "Pregunta en inglés: ¿Cuánto tiempo llevas en tu trabajo?",
      answer: "How long have you worked at your job?",
    },
  },
];

export const PREPOSITIONS_COMMON_ERRORS: { wrong: string; right: string; es: string }[] = [
  { wrong: "The class starts in 8:00.", right: "The class starts at 8:00.", es: "La hora exacta siempre lleva at." },
  { wrong: "I work in Monday.", right: "I work on Monday.", es: "Los días de la semana llevan on." },
  { wrong: "She lives at Guatemala.", right: "She lives in Guatemala.", es: "Países y ciudades llevan in." },
  { wrong: "I go to home after work.", right: "I go home after work.", es: "Con home no se usa to." },
  { wrong: "I have worked here since three years.", right: "I have worked here for three years.", es: "for + duración; since + punto de inicio." },
  { wrong: "The bank is in front the school.", right: "The bank is in front of the school.", es: "La expresión completa es in front OF." },
];
