import type { ReviewPractice } from "@/lib/review-types";

/**
 * REVIEW · PRESENT PERFECT (have / has + past participle) — five static practices.
 *
 * Person of the learner's MAIN answers alternates: 3rd · 1st · 3rd · 1st · 3rd.
 * Andrea, Ricardo and Lucía are fictional characters. All content is
 * hand-written: nothing here is generated at load.
 */
export const PRESENT_PERFECT_PRACTICES: ReviewPractice[] = [
  {
    number: 1,
    id: "pperf-1-andrea",
    title: "Andrea's experiences",
    titleEs: "Las experiencias de Andrea",
    person: "third",
    character: "Andrea",
    focus: "Third person experiences with has + past participle, ever and never.",
    focusEs: "Experiencias en tercera persona con has + participio, ever y never.",
    reminder: {
      en: "With she it is always has + past participle: she has worked, she has gone.",
      es: "Con she siempre es has + participio: she has worked, she has gone. Nunca “she have”.",
    },
    showFullGuide: true,
    instructions: {
      en: "Andrea is telling her life experiences. Tell them with has + past participle.",
      es: "Andrea cuenta sus experiencias de vida. Cuéntalas con has + participio.",
    },
    vocabulary: ["has worked", "has lived", "has traveled", "has never", "ever", "twice", "many times", "so far"],
    lines: [
      { id: "pperf1-l1", text: "Andrea has worked in customer service for six years.", es: "Andrea ha trabajado en servicio al cliente por seis años.", chunks: ["Andrea has worked", "in customer service", "for six years."] },
      { id: "pperf1-l2", text: "She has lived in three different cities.", es: "Ella ha vivido en tres ciudades diferentes.", chunks: ["She has lived", "in three different cities."] },
      { id: "pperf1-l3", text: "She has traveled to Mexico twice.", es: "Ha viajado a México dos veces.", chunks: ["She has traveled", "to Mexico", "twice."] },
      { id: "pperf1-l4", text: "She has never been to Canada.", es: "Nunca ha estado en Canadá.", chunks: ["She has never been", "to Canada."] },
      { id: "pperf1-l5", text: "She has taken two English courses since 2022.", es: "Ha tomado dos cursos de inglés desde 2022.", chunks: ["She has taken", "two English courses", "since 2022."] },
      { id: "pperf1-l6", text: "She has already trained many new agents.", es: "Ya ha capacitado a muchos agentes nuevos.", chunks: ["She has already trained", "many new agents."] },
      { id: "pperf1-l7", text: "She hasn't changed her job this year.", es: "No ha cambiado de trabajo este año.", chunks: ["She hasn't changed", "her job", "this year."] },
      { id: "pperf1-l8", text: "She has learned a lot from her clients.", es: "Ha aprendido mucho de sus clientes.", chunks: ["She has learned a lot", "from her clients."] },
    ],
    questions: [
      { id: "pperf1-q1", question: "What has Andrea done in customer service?", questionEs: "¿Qué ha hecho Andrea en servicio al cliente?", hint: "She has…", hintEs: "Usa has + participio." },
      { id: "pperf1-q2", question: "Where has she traveled?", questionEs: "¿A dónde ha viajado?", hint: "She has traveled to…", hintEs: "Di el lugar." },
      { id: "pperf1-q3", question: "How many cities has she lived in?", questionEs: "¿En cuántas ciudades ha vivido?", hint: "She has lived in…", hintEs: "Di el número." },
      { id: "pperf1-q4", question: "What has she never done?", questionEs: "¿Qué nunca ha hecho?", hint: "She has never…", hintEs: "Never ya es negativo." },
      { id: "pperf1-q5", question: "Why has she learned a lot?", questionEs: "¿Por qué ha aprendido mucho?", hint: "Because she has…", hintEs: "Usa because + has." },
      { id: "pperf1-q6", question: "When has she taken English courses?", questionEs: "¿Cuándo ha tomado cursos de inglés?", hint: "She has taken… since…", hintEs: "Usa since." },
    ],
    finalPrompt: {
      question: "Tell me about Andrea's experiences: her work, her travels and what she has never done.",
      questionEs: "Cuéntame las experiencias de Andrea: su trabajo, sus viajes y lo que nunca ha hecho.",
      tips: {
        en: "Use at least five sentences with has + past participle, one with never and one with for or since.",
        es: "Usa al menos cinco oraciones con has + participio, una con never y una con for o since.",
      },
    },
    grammarGoals: [
      "third person with has + past participle",
      "never and already in the right position",
      "for and since with the present perfect",
    ],
  },
  {
    number: 2,
    id: "pperf-2-your-life",
    title: "Your life experiences",
    titleEs: "Tus experiencias de vida",
    person: "first",
    character: null,
    focus: "First person experiences with have + past participle, ever, never, for and since.",
    focusEs: "Experiencias en primera persona con have + participio, ever, never, for y since.",
    reminder: {
      en: "I have + past participle. Say gone, not went. Never is already negative.",
      es: "I have + participio. Di gone, no went. Never ya es negativo: no lo mezcles con haven't.",
    },
    showFullGuide: false,
    instructions: {
      en: "Talk about your own experiences. Do not say the exact date — that is simple past.",
      es: "Habla de tus propias experiencias. No digas la fecha exacta: eso sería pasado simple.",
    },
    vocabulary: ["I have", "I haven't", "never", "ever", "for", "since", "many times", "so far"],
    lines: [
      { id: "pperf2-l1", text: "I have studied English for two years.", es: "He estudiado inglés por dos años.", chunks: ["I have studied English", "for two years."] },
      { id: "pperf2-l2", text: "I have worked in two different companies.", es: "He trabajado en dos empresas diferentes.", chunks: ["I have worked", "in two different companies."] },
      { id: "pperf2-l3", text: "I have never lived in another country.", es: "Nunca he vivido en otro país.", chunks: ["I have never lived", "in another country."] },
      { id: "pperf2-l4", text: "I have met a lot of interesting people.", es: "He conocido a mucha gente interesante.", chunks: ["I have met", "a lot of interesting people."] },
      { id: "pperf2-l5", text: "I have already finished my training.", es: "Ya terminé mi capacitación.", chunks: ["I have already finished", "my training."] },
      { id: "pperf2-l6", text: "I haven't traveled by plane yet.", es: "Todavía no he viajado en avión.", chunks: ["I haven't traveled", "by plane", "yet."] },
      { id: "pperf2-l7", text: "I have lived in this city since I was a child.", es: "He vivido en esta ciudad desde que era niño.", chunks: ["I have lived", "in this city", "since I was a child."] },
      { id: "pperf2-l8", text: "I have learned that practice is the only way.", es: "He aprendido que la práctica es el único camino.", chunks: ["I have learned", "that practice", "is the only way."] },
    ],
    questions: [
      { id: "pperf2-q1", question: "What have you done in your career so far?", questionEs: "¿Qué has hecho en tu carrera hasta ahora?", hint: "I have…", hintEs: "Usa have + participio." },
      { id: "pperf2-q2", question: "How long have you lived in your city?", questionEs: "¿Cuánto tiempo has vivido en tu ciudad?", hint: "I have lived here for / since…", hintEs: "For + duración; since + inicio." },
      { id: "pperf2-q3", question: "Why have you studied English?", questionEs: "¿Por qué has estudiado inglés?", hint: "I have studied English because…", hintEs: "Usa because." },
      { id: "pperf2-q4", question: "What have you never done?", questionEs: "¿Qué nunca has hecho?", hint: "I have never…", hintEs: "Never va después de have." },
      { id: "pperf2-q5", question: "Where have you traveled?", questionEs: "¿A dónde has viajado?", hint: "I have traveled to…", hintEs: "Di el lugar o di never." },
      { id: "pperf2-q6", question: "What have you already finished this month?", questionEs: "¿Qué ya terminaste este mes?", hint: "I have already…", hintEs: "Already va entre have y el participio." },
    ],
    finalPrompt: {
      question: "Tell me about your experiences: your work, your studies and something you have never done.",
      questionEs: "Cuéntame tus experiencias: tu trabajo, tus estudios y algo que nunca has hecho.",
      tips: {
        en: "Use at least five sentences with have + past participle, one with never and one with for or since.",
        es: "Usa al menos cinco oraciones con have + participio, una con never y una con for o since.",
      },
    },
    grammarGoals: [
      "first person with have + past participle",
      "never, already and yet in the right position",
      "for and since without mixing them",
    ],
  },
  {
    number: 3,
    id: "pperf-3-ricardo",
    title: "Ricardo's day at work",
    titleEs: "El día de Ricardo en el trabajo",
    person: "third",
    character: "Ricardo",
    focus: "Third person results today with has + participle, already, yet and just.",
    focusEs: "Resultados de hoy en tercera persona con has + participio, already, yet y just.",
    reminder: {
      en: "Already goes before the participle. Yet goes at the end of negatives and questions.",
      es: "Already va antes del participio. Yet va al final en negativas y preguntas.",
    },
    showFullGuide: false,
    instructions: {
      en: "Ricardo is in the middle of his shift. Say what he has done and what he hasn't done yet.",
      es: "Ricardo está a la mitad de su turno. Di qué ha hecho y qué no ha hecho todavía.",
    },
    vocabulary: ["has already", "hasn't … yet", "has just", "so far", "today", "this morning", "twice", "again"],
    lines: [
      { id: "pperf3-l1", text: "Ricardo has answered twenty calls so far today.", es: "Ricardo ha contestado veinte llamadas hoy.", chunks: ["Ricardo has answered", "twenty calls", "so far today."] },
      { id: "pperf3-l2", text: "He has already sent the morning report.", es: "Ya envió el reporte de la mañana.", chunks: ["He has already sent", "the morning report."] },
      { id: "pperf3-l3", text: "He has just finished a difficult call.", es: "Apenas terminó una llamada difícil.", chunks: ["He has just finished", "a difficult call."] },
      { id: "pperf3-l4", text: "He hasn't taken his break yet.", es: "Todavía no ha tomado su descanso.", chunks: ["He hasn't taken", "his break", "yet."] },
      { id: "pperf3-l5", text: "He has helped two customers with the same problem.", es: "Ha ayudado a dos clientes con el mismo problema.", chunks: ["He has helped", "two customers", "with the same problem."] },
      { id: "pperf3-l6", text: "His supervisor has given him good feedback this week.", es: "Su supervisor le ha dado buen feedback esta semana.", chunks: ["His supervisor has given him", "good feedback", "this week."] },
      { id: "pperf3-l7", text: "He hasn't made any mistakes today.", es: "No ha cometido ningún error hoy.", chunks: ["He hasn't made", "any mistakes", "today."] },
      { id: "pperf3-l8", text: "He has worked in this team since January.", es: "Ha trabajado en este equipo desde enero.", chunks: ["He has worked", "in this team", "since January."] },
    ],
    questions: [
      { id: "pperf3-q1", question: "Who has given Ricardo good feedback?", questionEs: "¿Quién le ha dado buen feedback a Ricardo?", hint: "His supervisor has…", hintEs: "Usa has + participio." },
      { id: "pperf3-q2", question: "How often has he helped customers today?", questionEs: "¿Con qué frecuencia ha ayudado a clientes hoy?", hint: "He has helped… times", hintEs: "Di cuántas veces." },
      { id: "pperf3-q3", question: "What time has he started his shift?", questionEs: "¿A qué hora ha empezado su turno?", hint: "He has started at…", hintEs: "Di la hora." },
      { id: "pperf3-q4", question: "What hasn't he done yet?", questionEs: "¿Qué no ha hecho todavía?", hint: "He hasn't… yet", hintEs: "Yet va al final." },
      { id: "pperf3-q5", question: "Why has his supervisor been happy?", questionEs: "¿Por qué su supervisor ha estado contento?", hint: "Because he has…", hintEs: "Usa because." },
      { id: "pperf3-q6", question: "Where has he worked since January?", questionEs: "¿Dónde ha trabajado desde enero?", hint: "He has worked in…", hintEs: "Usa since." },
    ],
    finalPrompt: {
      question: "Tell me what Ricardo has done today and what he hasn't done yet.",
      questionEs: "Cuéntame qué ha hecho Ricardo hoy y qué no ha hecho todavía.",
      tips: {
        en: "Use already, just and yet at least once each, and two negative sentences.",
        es: "Usa already, just y yet al menos una vez cada uno, y dos oraciones negativas.",
      },
    },
    grammarGoals: [
      "has + past participle for results today",
      "already, just and yet in the right position",
      "negatives with hasn't + participle",
    ],
  },
  {
    number: 4,
    id: "pperf-4-your-day",
    title: "What you have done today",
    titleEs: "Lo que has hecho hoy",
    person: "first",
    character: null,
    focus: "First person results today with have + participle, already, yet and just.",
    focusEs: "Resultados de hoy en primera persona con have + participio, already, yet y just.",
    reminder: {
      en: "I have already… / I haven't … yet. The participle never changes.",
      es: "I have already… / I haven't … yet. El participio nunca cambia.",
    },
    showFullGuide: false,
    instructions: {
      en: "Talk about today, from the morning until this moment.",
      es: "Habla de hoy, desde la mañana hasta este momento.",
    },
    vocabulary: ["I have already", "I haven't … yet", "I have just", "today", "so far", "this morning", "twice", "again"],
    lines: [
      { id: "pperf4-l1", text: "I have woken up early today.", es: "Me he levantado temprano hoy.", chunks: ["I have woken up early", "today."] },
      { id: "pperf4-l2", text: "I have already had breakfast and coffee.", es: "Ya desayuné y tomé café.", chunks: ["I have already had", "breakfast and coffee."] },
      { id: "pperf4-l3", text: "I have answered three messages this morning.", es: "He contestado tres mensajes esta mañana.", chunks: ["I have answered", "three messages", "this morning."] },
      { id: "pperf4-l4", text: "I haven't finished my work yet.", es: "Todavía no he terminado mi trabajo.", chunks: ["I haven't finished", "my work", "yet."] },
      { id: "pperf4-l5", text: "I have just started this English practice.", es: "Apenas empecé esta práctica de inglés.", chunks: ["I have just started", "this English practice."] },
      { id: "pperf4-l6", text: "I have practiced English every day this week.", es: "He practicado inglés todos los días esta semana.", chunks: ["I have practiced English", "every day", "this week."] },
      { id: "pperf4-l7", text: "I haven't called my family today.", es: "No he llamado a mi familia hoy.", chunks: ["I haven't called", "my family", "today."] },
      { id: "pperf4-l8", text: "I have felt good about my progress so far.", es: "Me he sentido bien con mi progreso hasta ahora.", chunks: ["I have felt good", "about my progress", "so far."] },
    ],
    questions: [
      { id: "pperf4-q1", question: "What have you done today?", questionEs: "¿Qué has hecho hoy?", hint: "I have…", hintEs: "Usa have + participio." },
      { id: "pperf4-q2", question: "When have you practiced English this week?", questionEs: "¿Cuándo has practicado inglés esta semana?", hint: "I have practiced…", hintEs: "Di los días o momentos." },
      { id: "pperf4-q3", question: "How long have you been awake today?", questionEs: "¿Cuánto tiempo llevas despierto hoy?", hint: "I have been awake for…", hintEs: "For + duración." },
      { id: "pperf4-q4", question: "What haven't you done yet?", questionEs: "¿Qué no has hecho todavía?", hint: "I haven't… yet", hintEs: "Yet va al final." },
      { id: "pperf4-q5", question: "Why have you felt good about your progress?", questionEs: "¿Por qué te has sentido bien con tu progreso?", hint: "Because I have…", hintEs: "Usa because." },
      { id: "pperf4-q6", question: "Where have you been today?", questionEs: "¿Dónde has estado hoy?", hint: "I have been at…", hintEs: "Been es el participio de be." },
    ],
    finalPrompt: {
      question: "Tell me everything you have done today and what you haven't done yet.",
      questionEs: "Cuéntame todo lo que has hecho hoy y lo que no has hecho todavía.",
      tips: {
        en: "Use already, just and yet at least once each, and finish with something you have learned.",
        es: "Usa already, just y yet al menos una vez cada uno, y termina con algo que has aprendido.",
      },
    },
    grammarGoals: [
      "have + past participle for today's results",
      "already, just and yet in the right position",
      "negatives with haven't + participle",
    ],
  },
  {
    number: 5,
    id: "pperf-5-lucia",
    title: "Lucía's story so far",
    titleEs: "La historia de Lucía hasta hoy",
    person: "third",
    character: "Lucía",
    focus: "Free third person retelling of a life story with has + participle, for and since.",
    focusEs: "Relato libre en tercera persona con has + participio, for y since.",
    reminder: {
      en: "Build the story with the facts. Use has + participle and never say the exact date.",
      es: "Arma la historia con los datos. Usa has + participio y no digas la fecha exacta.",
    },
    showFullGuide: false,
    instructions: {
      en: "You have the key facts about Lucía. Build her story out loud in the present perfect.",
      es: "Tienes los datos clave de Lucía. Arma su historia en voz alta en present perfect.",
    },
    vocabulary: ["has studied", "has worked", "has moved", "has never", "already", "for", "since", "so far"],
    factSheet: [
      { en: "Lucía · call center agent · four years in the industry", es: "Lucía · agente de call center · cuatro años en la industria" },
      { en: "Two companies · one promotion · trains new agents", es: "Dos empresas · un ascenso · capacita agentes nuevos" },
      { en: "Studies English since 2021 · never studied abroad", es: "Estudia inglés desde 2021 · nunca ha estudiado en el extranjero" },
      { en: "Moved to the capital · lives alone · has a dog", es: "Se mudó a la capital · vive sola · tiene un perro" },
      { en: "Dream: to work with international clients", es: "Sueño: trabajar con clientes internacionales" },
    ],
    lines: [
      { id: "pperf5-l1", text: "Lucía has worked in call centers for four years.", es: "Lucía ha trabajado en call centers por cuatro años.", chunks: ["Lucía has worked", "in call centers", "for four years."] },
      { id: "pperf5-l2", text: "She has worked for two different companies.", es: "Ha trabajado para dos empresas diferentes.", chunks: ["She has worked", "for two different companies."] },
      { id: "pperf5-l3", text: "She has received one promotion.", es: "Ha recibido un ascenso.", chunks: ["She has received", "one promotion."] },
      { id: "pperf5-l4", text: "She has studied English since 2021.", es: "Ha estudiado inglés desde 2021.", chunks: ["She has studied English", "since 2021."] },
      { id: "pperf5-l5", text: "She has never studied in another country.", es: "Nunca ha estudiado en otro país.", chunks: ["She has never studied", "in another country."] },
      { id: "pperf5-l6", text: "She has moved to the capital and now she lives alone.", es: "Se ha mudado a la capital y ahora vive sola.", chunks: ["She has moved", "to the capital", "and now she lives alone."] },
      { id: "pperf5-l7", text: "She has already trained six new agents.", es: "Ya ha capacitado a seis agentes nuevos.", chunks: ["She has already trained", "six new agents."] },
      { id: "pperf5-l8", text: "She hasn't reached her big dream yet.", es: "Todavía no ha alcanzado su gran sueño.", chunks: ["She hasn't reached", "her big dream", "yet."] },
    ],
    questions: [
      { id: "pperf5-q1", question: "Where has Lucía worked?", questionEs: "¿Dónde ha trabajado Lucía?", hint: "She has worked in…", hintEs: "Usa has + participio." },
      { id: "pperf5-q2", question: "Why has she studied English?", questionEs: "¿Por qué ha estudiado inglés?", hint: "Because she has…", hintEs: "Usa because." },
      { id: "pperf5-q3", question: "How many agents has she trained?", questionEs: "¿A cuántos agentes ha capacitado?", hint: "She has trained…", hintEs: "Di el número." },
      { id: "pperf5-q4", question: "What has she never done?", questionEs: "¿Qué nunca ha hecho?", hint: "She has never…", hintEs: "Never va después de has." },
      { id: "pperf5-q5", question: "What hasn't she reached yet?", questionEs: "¿Qué no ha alcanzado todavía?", hint: "She hasn't… yet", hintEs: "Yet va al final." },
      { id: "pperf5-q6", question: "When has she lived in the capital?", questionEs: "¿Desde cuándo vive en la capital?", hint: "She has lived there since…", hintEs: "Usa since." },
    ],
    finalPrompt: {
      question: "Tell me Lucía's story so far: her work, her English, her life and her dream.",
      questionEs: "Cuéntame la historia de Lucía hasta hoy: su trabajo, su inglés, su vida y su sueño.",
      tips: {
        en: "Use at least six sentences with has + past participle, one with never and one with yet.",
        es: "Usa al menos seis oraciones con has + participio, una con never y una con yet.",
      },
    },
    grammarGoals: [
      "third person with has + past participle in a connected story",
      "for and since used correctly",
      "never, already and yet in the right position",
    ],
  },
];
