import type { ReviewGuideCard } from "@/lib/review-types";

/**
 * "ENTIÉNDELO FÁCIL" — the seven Present Perfect basics (have / has + participle).
 * Static hand-written content: never generated by AI, reused by every practice
 * (Practice 1 shows it inline in Step 1, practices 2–5 open it on demand).
 */
export const PRESENT_PERFECT_GUIDE: ReviewGuideCard[] = [
  {
    id: "pp-1-use",
    title: "What it is for",
    titleEs: "Para qué sirve",
    explanation:
      "The present perfect connects the past with now: experiences in your life and actions with a result today.",
    explanationEs:
      "El present perfect conecta el pasado con el ahora: experiencias de tu vida y acciones que tienen resultado hoy. No dice CUÁNDO pasó exactamente; si dices el momento exacto (yesterday, in 2019), usas pasado simple.",
    examples: [
      { en: "I have worked in a call center.", es: "He trabajado en un call center." },
      { en: "She has finished the report.", es: "Ella ha terminado el reporte." },
      { en: "We have lived here for five years.", es: "Hemos vivido aquí por cinco años." },
    ],
    check: {
      prompt: "Say one experience from your life with I have.",
      promptEs: "Di en voz alta una experiencia de tu vida con I have.",
      answer: "I have traveled to another country.",
    },
  },
  {
    id: "pp-2-formula",
    title: "have / has + past participle",
    titleEs: "have / has + participio",
    explanation: "I / you / we / they have. He / she / it has. The verb after it never changes.",
    explanationEs:
      "I, you, we, they → have. He, she, it → has. Después va el participio y ya no cambia: worked, studied, gone, seen, done. “He have worked” y “She has work” están mal.",
    examples: [
      { en: "I have studied English for two years.", es: "He estudiado inglés por dos años." },
      { en: "He has sent the email.", es: "Él ha enviado el correo." },
      { en: "They have seen that movie.", es: "Ellos han visto esa película." },
    ],
    check: {
      prompt: "Change to he: I have finished my work.",
      promptEs: "Cambia a he: I have finished my work.",
      answer: "He has finished his work.",
    },
  },
  {
    id: "pp-3-participles",
    title: "The past participle",
    titleEs: "El participio",
    explanation: "Regular verbs add -ed. Irregular verbs have their own form and you learn them by using them.",
    explanationEs:
      "Verbos regulares: work → worked, study → studied. Irregulares: go → gone, see → seen, do → done, be → been, take → taken, write → written, eat → eaten, speak → spoken. Ojo: “I have went” está mal; es “I have gone”.",
    examples: [
      { en: "I have gone to that store many times.", es: "He ido a esa tienda muchas veces." },
      { en: "She has written three emails today.", es: "Ella ha escrito tres correos hoy." },
      { en: "We have done everything.", es: "Hemos hecho todo." },
    ],
    check: {
      prompt: "Say the participle of go, see and do.",
      promptEs: "Di el participio de go, see y do.",
      answer: "gone, seen, done",
    },
  },
  {
    id: "pp-4-ever-never",
    title: "ever / never",
    titleEs: "ever / never",
    explanation: "Use ever in questions about your whole life, and never for no experience.",
    explanationEs:
      "Have you ever…? = ¿Alguna vez has…? La respuesta corta: Yes, I have / No, I haven't. Never ya es negativo: no digas “I haven't never”.",
    examples: [
      { en: "Have you ever worked at night?", es: "¿Alguna vez has trabajado de noche?" },
      { en: "I have never been to Canada.", es: "Nunca he estado en Canadá." },
      { en: "He has never called a client in English.", es: "Él nunca ha llamado a un cliente en inglés." },
    ],
    check: {
      prompt: "Ask a classmate about an experience with ever.",
      promptEs: "Pregunta sobre una experiencia con ever.",
      answer: "Have you ever traveled by plane?",
    },
  },
  {
    id: "pp-5-already-yet-just",
    title: "already / yet / just",
    titleEs: "already / yet / just",
    explanation: "Already = it is done. Yet = not until now (negatives and questions). Just = a moment ago.",
    explanationEs:
      "Already = ya (afirmativo). Yet = todavía / ya, y va al final en negativas y preguntas: I haven't finished yet. Have you finished yet? Just = apenas: I have just arrived.",
    examples: [
      { en: "I have already sent the report.", es: "Ya envié el reporte." },
      { en: "She hasn't answered yet.", es: "Ella todavía no ha contestado." },
      { en: "They have just started the meeting.", es: "Apenas empezaron la reunión." },
    ],
    check: {
      prompt: "Say one thing you have already done today.",
      promptEs: "Di una cosa que ya hiciste hoy con already.",
      answer: "I have already had breakfast.",
    },
  },
  {
    id: "pp-6-for-since",
    title: "for / since",
    titleEs: "for / since",
    explanation: "For + a period of time. Since + the moment it started.",
    explanationEs:
      "For + tiempo que dura: for two years, for six months, for a long time. Since + momento en que empezó: since 2020, since Monday, since I was a child.",
    examples: [
      { en: "I have worked here for three years.", es: "He trabajado aquí por tres años." },
      { en: "She has lived in this city since 2019.", es: "Ella ha vivido en esta ciudad desde 2019." },
      { en: "We have known each other since school.", es: "Nos conocemos desde la escuela." },
    ],
    check: {
      prompt: "Complete: I have studied English ___ two years.",
      promptEs: "Completa: I have studied English ___ two years.",
      answer: "for",
    },
  },
  {
    id: "pp-7-questions-negatives",
    title: "Questions and negatives",
    titleEs: "Preguntas y negativas",
    explanation: "Have / Has goes first in questions. Haven't / hasn't for negatives.",
    explanationEs:
      "Pregunta: Have you finished? Has he called? What have you done today? Negativa: I haven't finished. He hasn't called. El participio nunca cambia.",
    examples: [
      { en: "Have you finished the training?", es: "¿Ya terminaste la capacitación?" },
      { en: "What has she done today?", es: "¿Qué ha hecho ella hoy?" },
      { en: "I haven't taken my break yet.", es: "Todavía no he tomado mi descanso." },
    ],
    check: {
      prompt: "Ask: ¿Qué has hecho hoy?",
      promptEs: "Pregunta en inglés: ¿Qué has hecho hoy?",
      answer: "What have you done today?",
    },
  },
];

export const PRESENT_PERFECT_COMMON_ERRORS: { wrong: string; right: string; es: string }[] = [
  { wrong: "He have finished.", right: "He has finished.", es: "Con he, she, it se usa has, nunca have." },
  { wrong: "I have went to Mexico.", right: "I have gone to Mexico.", es: "El participio de go es gone, no went." },
  { wrong: "She has work here for two years.", right: "She has worked here for two years.", es: "Después de has va el participio: worked." },
  { wrong: "I have lived here since five years.", right: "I have lived here for five years.", es: "For + duración; since + momento de inicio." },
  { wrong: "I haven't never called a client.", right: "I have never called a client.", es: "Never ya es negativo: no se usa con haven't." },
  { wrong: "I have finished my work yesterday.", right: "I finished my work yesterday.", es: "Con un momento exacto del pasado se usa pasado simple." },
];
