import type { ReviewGuideCard } from "@/lib/review-types";
import pp1 from "@/assets/review/pp1-use.jpg";
import pp2 from "@/assets/review/pp2-formula.jpg";
import pp3 from "@/assets/review/pp3-spelling.jpg";
import pp4 from "@/assets/review/pp4-negative.jpg";
import pp5 from "@/assets/review/pp5-questions.jpg";
import pp6 from "@/assets/review/pp6-now-vs-usually.jpg";
import pp7 from "@/assets/review/pp7-stative.jpg";

/**
 * "ENTIÉNDELO FÁCIL" — the seven Present Progressive basics.
 * Static hand-written content: never generated by AI, reused by every practice
 * (Practice 1 shows it inline in Step 1, practices 2–5 open it on demand).
 */
export const PRESENT_PROGRESSIVE_GUIDE: ReviewGuideCard[] = [
  {
    id: "pp1-use",
    title: "What it is for",
    titleEs: "Para qué sirve",
    explanation: "Present Progressive is for actions happening right now or around this period of time.",
    explanationEs:
      "El Present Progressive sirve para lo que está pasando ahora mismo o en este período (esta semana, estos días). No es para rutinas: eso es Simple Present.",
    image: { src: pp1, alt: "A woman talking on a call right now", altEs: "Una mujer hablando en una llamada ahora mismo" },
    examples: [
      { en: "I am working right now.", es: "Estoy trabajando ahora mismo." },
      { en: "She is talking to a customer.", es: "Ella está hablando con un cliente." },
      { en: "We are studying English this month.", es: "Estamos estudiando inglés este mes." },
    ],
    check: {
      prompt: "Say what you are doing right now.",
      promptEs: "Di en voz alta qué estás haciendo ahora mismo.",
      answer: "I am practicing English right now.",
    },
  },
  {
    id: "pp2-formula",
    title: "The formula: am / is / are + -ing",
    titleEs: "La fórmula",
    explanation: "Always two parts: the verb be (am, is, are) and the main verb with -ing. Never drop the be.",
    explanationEs:
      "Siempre son dos partes: el verbo be (am con I, is con he/she/it, are con you/we/they) más el verbo principal con -ing. Nunca digas “She working”: falta el is.",
    image: { src: pp2, alt: "Three people reading at the same moment", altEs: "Tres personas leyendo en el mismo momento" },
    examples: [
      { en: "I am eating. / You are eating.", es: "Estoy comiendo. / Estás comiendo." },
      { en: "He is eating. / They are eating.", es: "Él está comiendo. / Ellos están comiendo." },
      { en: "She is working. (NOT: She working.)", es: "Ella está trabajando. (NO: She working.)" },
    ],
    check: {
      prompt: "Say the same action with I, she and they.",
      promptEs: "Di la misma acción con I, she y they.",
      answer: "I am reading. She is reading. They are reading.",
    },
  },
  {
    id: "pp3-spelling",
    title: "Spelling of -ing",
    titleEs: "Ortografía del -ing",
    explanation: "Most verbs just add -ing. Drop a final silent e, and double the last consonant in short stressed verbs.",
    explanationEs:
      "A casi todos los verbos solo les agregas -ing (work → working). Si termina en -e muda, quitas la e (make → making, write → writing). En verbos cortos con vocal + consonante, doblas la consonante (run → running, sit → sitting, get → getting). Ojo: study → studying (la y no cambia).",
    image: { src: pp3, alt: "Making a cake, running and studying", altEs: "Haciendo un pastel, corriendo y estudiando" },
    examples: [
      { en: "make → making · take → taking", es: "make → making · take → taking" },
      { en: "run → running · put → putting", es: "run → running · put → putting" },
      { en: "study → studying · say → saying", es: "study → studying · say → saying" },
    ],
    check: {
      prompt: "Say the -ing form of: make, run, study, take.",
      promptEs: "Di la forma -ing de: make, run, study, take.",
      answer: "making, running, studying, taking",
    },
  },
  {
    id: "pp4-negative",
    title: "Negative sentences",
    titleEs: "Negativas",
    explanation: "Put not after am / is / are. Never use don't or doesn't here.",
    explanationEs:
      "Para negar pones not después de am, is o are: I'm not working, she isn't working, they aren't working. Aquí NO se usa don't ni doesn't, porque el verbo be ya hace la negación.",
    image: { src: pp4, alt: "A woman not answering the ringing phone", altEs: "Una mujer que no está contestando el teléfono" },
    examples: [
      { en: "I'm not working today.", es: "Hoy no estoy trabajando." },
      { en: "She isn't answering the phone.", es: "Ella no está contestando el teléfono." },
      { en: "They aren't listening. (NOT: They don't listening.)", es: "Ellos no están escuchando. (NO: They don't listening.)" },
    ],
    check: {
      prompt: "Say one thing you are not doing right now.",
      promptEs: "Di algo que no estás haciendo ahora mismo.",
      answer: "I'm not watching TV right now.",
    },
  },
  {
    id: "pp5-questions",
    title: "Questions and short answers",
    titleEs: "Preguntas",
    explanation: "Move am / is / are to the front: Is she working? Question words go first: What is he doing?",
    explanationEs:
      "Para preguntar mueves am, is o are al inicio: Are you working? Is she working? Con palabra interrogativa va primero: What are you doing? Why is he calling? Respuestas cortas: Yes, I am / No, I'm not / Yes, she is / No, she isn't.",
    image: { src: pp5, alt: "One person asking another a question", altEs: "Una persona haciéndole una pregunta a otra" },
    examples: [
      { en: "Are you working now? — Yes, I am.", es: "¿Estás trabajando ahora? — Sí." },
      { en: "Is she talking to a client? — No, she isn't.", es: "¿Está hablando con un cliente? — No." },
      { en: "What are they doing? / Why is he waiting?", es: "¿Qué están haciendo? / ¿Por qué está esperando él?" },
    ],
    check: {
      prompt: "Ask two questions: one with Are you and one with Is she.",
      promptEs: "Haz dos preguntas: una con Are you y otra con Is she.",
      answer: "Are you working today? Is she helping the customer?",
    },
  },
  {
    id: "pp6-vs-simple",
    title: "Now vs. usually",
    titleEs: "Ahora vs. normalmente",
    explanation: "Use Present Progressive for now, and Simple Present for routines. Time words tell you which one.",
    explanationEs:
      "Usa el progresivo para AHORA (right now, at the moment, today, this week) y el Simple Present para RUTINAS (every day, usually, on Mondays). La palabra de tiempo te dice cuál usar.",
    image: { src: pp6, alt: "Working at night usually and in the morning today", altEs: "Trabaja de noche normalmente y hoy en la mañana" },
    examples: [
      { en: "I usually work at night, but today I am working in the morning.", es: "Normalmente trabajo de noche, pero hoy estoy trabajando en la mañana." },
      { en: "She studies every day. Right now she is studying grammar.", es: "Ella estudia todos los días. Ahora mismo está estudiando gramática." },
      { en: "We are training this week. We train twice a month.", es: "Estamos entrenando esta semana. Entrenamos dos veces al mes." },
    ],
    check: {
      prompt: "Say one routine and one thing happening now.",
      promptEs: "Di una rutina y algo que pasa ahora.",
      answer: "I usually study at night, but right now I am speaking English.",
    },
  },
  {
    id: "pp7-stative",
    title: "Verbs that stay simple",
    titleEs: "Verbos que no usan -ing",
    explanation: "Feelings and states — like, want, need, know, have (possess) — normally stay in Simple Present.",
    explanationEs:
      "Algunos verbos de estado casi nunca van en -ing: like, love, want, need, know, understand y have cuando significa tener. Se dice I want coffee, no “I am wanting coffee”. Pero sí se usa -ing cuando have es una acción: I am having lunch.",
    image: { src: pp7, alt: "A man wanting coffee while having lunch", altEs: "Un hombre que quiere café mientras está almorzando" },
    examples: [
      { en: "I want a break. (NOT: I am wanting a break.)", es: "Quiero un descanso. (NO: I am wanting a break.)" },
      { en: "She knows the answer. (NOT: She is knowing.)", es: "Ella sabe la respuesta. (NO: She is knowing.)" },
      { en: "He is having lunch right now.", es: "Él está almorzando ahora mismo." },
    ],
    check: {
      prompt: "Say what you want and what you are doing.",
      promptEs: "Di qué quieres y qué estás haciendo.",
      answer: "I want a coffee, and I am studying English.",
    },
  },
];

/** The four errors this module keeps correcting. */
export const PRESENT_PROGRESSIVE_COMMON_ERRORS: { wrong: string; right: string; es: string }[] = [
  { wrong: "She working", right: "She is working", es: "Falta el verbo be (am/is/are)." },
  { wrong: "They don't working", right: "They aren't working", es: "Para negar usas not después de be." },
  { wrong: "I am makeing", right: "I am making", es: "Los verbos con -e muda pierden la e." },
  { wrong: "Right now I work", right: "Right now I am working", es: "Con right now se usa el progresivo." },
];
