import type { ReviewPractice } from "@/lib/review-types";
import scenePperfp1 from "@/assets/review/scene-pperfp1-mateo.jpg";
import scenePperfp3 from "@/assets/review/scene-pperfp3-valeria.jpg";
import scenePperfp5 from "@/assets/review/scene-pperfp5-julio.jpg";

/**
 * REVIEW · PRESENT PERFECT PROGRESSIVE (have / has been + -ing) — five static
 * practices. Person of the learner's MAIN answers alternates:
 * 3rd · 1st · 3rd · 1st · 3rd. Mateo, Valeria and Julio are fictional.
 */
export const PRESENT_PERFECT_PROGRESSIVE_PRACTICES: ReviewPractice[] = [
  {
    number: 1,
    id: "pperfp-1-mateo",
    title: "Mateo has been studying",
    titleEs: "Mateo ha estado estudiando",
    person: "third",
    character: "Mateo",
    focus: "Third person duration with has been + -ing, for and since.",
    focusEs: "Duración en tercera persona con has been + -ing, for y since.",
    reminder: {
      en: "Three parts, always: has + been + verb-ing. Never drop been.",
      es: "Siempre tres partes: has + been + verbo-ing. Nunca quites been.",
    },
    showFullGuide: true,
    sceneImage: { src: scenePperfp1, alt: "Mateo studying English at night and preparing for an interview", altEs: "Mateo estudiando inglés de noche y preparándose para una entrevista" },
    instructions: {
      en: "Mateo is preparing for an interview. Say how long he has been doing each thing.",
      es: "Mateo se prepara para una entrevista. Di cuánto tiempo lleva haciendo cada cosa.",
    },
    vocabulary: ["has been", "for", "since", "all morning", "lately", "these days", "every night", "so far"],
    lines: [
      { id: "pperfp1-l1", text: "Mateo has been studying English since January.", es: "Mateo lleva estudiando inglés desde enero.", chunks: ["Mateo has been studying English", "since January."] },
      { id: "pperfp1-l2", text: "He has been practicing his pronunciation every night.", es: "Ha estado practicando su pronunciación cada noche.", chunks: ["He has been practicing", "his pronunciation", "every night."] },
      { id: "pperfp1-l3", text: "He has been working in a call center for two years.", es: "Lleva dos años trabajando en un call center.", chunks: ["He has been working", "in a call center", "for two years."] },
      { id: "pperfp1-l4", text: "He has been preparing for an interview all week.", es: "Ha estado preparándose para una entrevista toda la semana.", chunks: ["He has been preparing", "for an interview", "all week."] },
      { id: "pperfp1-l5", text: "He hasn't been sleeping well lately.", es: "No ha estado durmiendo bien últimamente.", chunks: ["He hasn't been sleeping well", "lately."] },
      { id: "pperfp1-l6", text: "He has been listening to podcasts on the bus.", es: "Ha estado escuchando podcasts en el bus.", chunks: ["He has been listening", "to podcasts", "on the bus."] },
      { id: "pperfp1-l7", text: "He has been talking to his coach twice a week.", es: "Ha estado hablando con su coach dos veces por semana.", chunks: ["He has been talking", "to his coach", "twice a week."] },
      { id: "pperfp1-l8", text: "He has known his coach for a long time.", es: "Conoce a su coach desde hace mucho.", chunks: ["He has known his coach", "for a long time."] },
    ],
    questions: [
      { id: "pperfp1-q1", question: "What has Mateo been doing every night?", questionEs: "¿Qué ha estado haciendo Mateo cada noche?", hint: "He has been…", hintEs: "Usa has been + verbo-ing." },
      { id: "pperfp1-q2", question: "How long has he been working in a call center?", questionEs: "¿Cuánto tiempo lleva trabajando en un call center?", hint: "He has been working for…", hintEs: "For + duración." },
      { id: "pperfp1-q3", question: "Where has he been listening to podcasts?", questionEs: "¿Dónde ha estado escuchando podcasts?", hint: "He has been listening…", hintEs: "Di el lugar." },
      { id: "pperfp1-q4", question: "Why has he been preparing so much?", questionEs: "¿Por qué se ha estado preparando tanto?", hint: "Because he has been…", hintEs: "Usa because." },
      { id: "pperfp1-q5", question: "What hasn't he been doing well?", questionEs: "¿Qué no ha estado haciendo bien?", hint: "He hasn't been…", hintEs: "Negativa: hasn't been + verbo-ing." },
      { id: "pperfp1-q6", question: "How often has he been talking to his coach?", questionEs: "¿Con qué frecuencia ha estado hablando con su coach?", hint: "He has been talking… a week", hintEs: "Di la frecuencia." },
    ],
    finalPrompt: {
      question: "Tell me what Mateo has been doing to prepare for his interview, and for how long.",
      questionEs: "Cuéntame qué ha estado haciendo Mateo para prepararse y desde cuándo.",
      tips: {
        en: "Use at least five sentences with has been + -ing, one with for and one with since.",
        es: "Usa al menos cinco oraciones con has been + -ing, una con for y una con since.",
      },
    },
    grammarGoals: [
      "third person with has been + -ing",
      "for and since without mixing them",
      "negatives with hasn't been + -ing",
    ],
  },
  {
    number: 2,
    id: "pperfp-2-your-lately",
    title: "What you have been doing lately",
    titleEs: "Lo que has estado haciendo últimamente",
    person: "first",
    character: null,
    focus: "First person duration with have been + -ing, for, since and lately.",
    focusEs: "Duración en primera persona con have been + -ing, for, since y lately.",
    reminder: {
      en: "I have been + verb-ing. Say for two hours, not since two hours.",
      es: "I have been + verbo-ing. Di for two hours, no since two hours.",
    },
    showFullGuide: false,
    instructions: {
      en: "Talk about the things you have been doing these weeks and how long.",
      es: "Habla de lo que has estado haciendo estas semanas y por cuánto tiempo.",
    },
    vocabulary: ["I have been", "for", "since", "lately", "these days", "all week", "every day", "recently"],
    lines: [
      { id: "pperfp2-l1", text: "I have been studying English for two years.", es: "Llevo dos años estudiando inglés.", chunks: ["I have been studying English", "for two years."] },
      { id: "pperfp2-l2", text: "I have been working a lot these days.", es: "He estado trabajando mucho estos días.", chunks: ["I have been working a lot", "these days."] },
      { id: "pperfp2-l3", text: "I have been practicing speaking every morning.", es: "He estado practicando speaking cada mañana.", chunks: ["I have been practicing speaking", "every morning."] },
      { id: "pperfp2-l4", text: "I have been trying to speak without translating.", es: "He estado tratando de hablar sin traducir.", chunks: ["I have been trying", "to speak", "without translating."] },
      { id: "pperfp2-l5", text: "I haven't been going out much lately.", es: "No he estado saliendo mucho últimamente.", chunks: ["I haven't been going out much", "lately."] },
      { id: "pperfp2-l6", text: "I have been sleeping better since last week.", es: "He estado durmiendo mejor desde la semana pasada.", chunks: ["I have been sleeping better", "since last week."] },
      { id: "pperfp2-l7", text: "I have been thinking about my next goal.", es: "He estado pensando en mi próxima meta.", chunks: ["I have been thinking", "about my next goal."] },
      { id: "pperfp2-l8", text: "I have wanted this for a long time.", es: "He querido esto desde hace mucho.", chunks: ["I have wanted this", "for a long time."] },
    ],
    questions: [
      { id: "pperfp2-q1", question: "How long have you been studying English?", questionEs: "¿Cuánto tiempo llevas estudiando inglés?", hint: "I have been studying for / since…", hintEs: "For + duración; since + inicio." },
      { id: "pperfp2-q2", question: "What have you been doing lately?", questionEs: "¿Qué has estado haciendo últimamente?", hint: "I have been…", hintEs: "Usa have been + verbo-ing." },
      { id: "pperfp2-q3", question: "Why have you been practicing every day?", questionEs: "¿Por qué has estado practicando cada día?", hint: "Because I have been…", hintEs: "Usa because." },
      { id: "pperfp2-q4", question: "Where have you been practicing your English?", questionEs: "¿Dónde has estado practicando tu inglés?", hint: "I have been practicing at…", hintEs: "Di el lugar." },
      { id: "pperfp2-q5", question: "What haven't you been doing lately?", questionEs: "¿Qué no has estado haciendo últimamente?", hint: "I haven't been…", hintEs: "Negativa: haven't been + verbo-ing." },
      { id: "pperfp2-q6", question: "When have you been sleeping better?", questionEs: "¿Desde cuándo has estado durmiendo mejor?", hint: "I have been sleeping better since…", hintEs: "Usa since." },
    ],
    finalPrompt: {
      question: "Tell me what you have been doing lately and how long you have been doing it.",
      questionEs: "Cuéntame qué has estado haciendo últimamente y desde hace cuánto.",
      tips: {
        en: "Use at least five sentences with have been + -ing, one negative, one with for and one with since.",
        es: "Usa al menos cinco oraciones con have been + -ing, una negativa, una con for y una con since.",
      },
    },
    grammarGoals: [
      "first person with have been + -ing",
      "for and since with duration",
      "negatives with haven't been + -ing",
    ],
  },
  {
    number: 3,
    id: "pperfp-3-valeria",
    title: "Valeria's busy month",
    titleEs: "El mes ocupado de Valeria",
    person: "third",
    character: "Valeria",
    focus: "Third person duration and repeated actions with has been + -ing.",
    focusEs: "Duración y acciones repetidas en tercera persona con has been + -ing.",
    reminder: {
      en: "State verbs like know and have (possession) do not take -ing.",
      es: "Los verbos de estado como know y have (posesión) no llevan -ing.",
    },
    showFullGuide: false,
    sceneImage: { src: scenePperfp3, alt: "Valeria training new agents during her busy month", altEs: "Valeria capacitando agentes nuevos en su mes ocupado" },
    instructions: {
      en: "Valeria has had a very busy month. Say what she has been doing and for how long.",
      es: "Valeria ha tenido un mes muy ocupado. Di qué ha estado haciendo y por cuánto tiempo.",
    },
    vocabulary: ["has been", "since", "for", "all month", "three times a week", "lately", "every weekend", "still"],
    lines: [
      { id: "pperfp3-l1", text: "Valeria has been training new agents since the first of the month.", es: "Valeria lleva capacitando agentes nuevos desde el primero del mes.", chunks: ["Valeria has been training", "new agents", "since the first of the month."] },
      { id: "pperfp3-l2", text: "She has been working extra hours every weekend.", es: "Ha estado trabajando horas extra cada fin de semana.", chunks: ["She has been working", "extra hours", "every weekend."] },
      { id: "pperfp3-l3", text: "She has been taking English classes three times a week.", es: "Ha estado tomando clases de inglés tres veces por semana.", chunks: ["She has been taking English classes", "three times a week."] },
      { id: "pperfp3-l4", text: "She has been feeling tired, but she is happy.", es: "Se ha estado sintiendo cansada, pero está contenta.", chunks: ["She has been feeling tired,", "but she is happy."] },
      { id: "pperfp3-l5", text: "She hasn't been eating well because of her schedule.", es: "No ha estado comiendo bien por su horario.", chunks: ["She hasn't been eating well", "because of her schedule."] },
      { id: "pperfp3-l6", text: "She has been saving money for a trip.", es: "Ha estado ahorrando dinero para un viaje.", chunks: ["She has been saving money", "for a trip."] },
      { id: "pperfp3-l7", text: "She has known her manager for three years.", es: "Conoce a su gerente desde hace tres años.", chunks: ["She has known her manager", "for three years."] },
      { id: "pperfp3-l8", text: "She has been sleeping only five hours a night.", es: "Ha estado durmiendo solo cinco horas por noche.", chunks: ["She has been sleeping", "only five hours", "a night."] },
    ],
    questions: [
      { id: "pperfp3-q1", question: "Who has she been training this month?", questionEs: "¿A quiénes ha estado capacitando este mes?", hint: "She has been training…", hintEs: "Usa has been + verbo-ing." },
      { id: "pperfp3-q2", question: "How often has she been taking English classes?", questionEs: "¿Con qué frecuencia ha estado tomando clases de inglés?", hint: "She has been taking classes… a week", hintEs: "Di la frecuencia." },
      { id: "pperfp3-q3", question: "How long has she been working extra hours?", questionEs: "¿Cuánto tiempo lleva trabajando horas extra?", hint: "She has been working extra hours for / since…", hintEs: "For + duración; since + inicio." },
      { id: "pperfp3-q4", question: "Why has she been feeling tired?", questionEs: "¿Por qué se ha estado sintiendo cansada?", hint: "Because she has been…", hintEs: "Usa because." },
      { id: "pperfp3-q5", question: "What hasn't she been doing well?", questionEs: "¿Qué no ha estado haciendo bien?", hint: "She hasn't been…", hintEs: "Negativa con hasn't been." },
      { id: "pperfp3-q6", question: "What has she been saving money for?", questionEs: "¿Para qué ha estado ahorrando dinero?", hint: "She has been saving money for…", hintEs: "Di el objetivo." },
    ],
    finalPrompt: {
      question: "Tell me about Valeria's month: what she has been doing, for how long and how she has been feeling.",
      questionEs: "Cuéntame el mes de Valeria: qué ha estado haciendo, por cuánto tiempo y cómo se ha sentido.",
      tips: {
        en: "Use at least five sentences with has been + -ing, one negative and one with a state verb like know.",
        es: "Usa al menos cinco oraciones con has been + -ing, una negativa y una con un verbo de estado como know.",
      },
    },
    grammarGoals: [
      "has been + -ing for duration and repeated actions",
      "state verbs without -ing (has known)",
      "for and since used correctly",
    ],
  },
  {
    number: 4,
    id: "pperfp-4-your-work",
    title: "How long you have been working",
    titleEs: "Cuánto llevas trabajando",
    person: "first",
    character: null,
    focus: "First person answers to How long…? in a job interview style.",
    focusEs: "Respuestas en primera persona a How long…?, estilo entrevista de trabajo.",
    reminder: {
      en: "How long have you been…? Answer with for or since, never with a simple present.",
      es: "How long have you been…? Contesta con for o since, no con presente simple.",
    },
    showFullGuide: false,
    instructions: {
      en: "Answer like in a job interview: how long you have been doing each thing.",
      es: "Contesta como en una entrevista de trabajo: cuánto tiempo llevas haciendo cada cosa.",
    },
    vocabulary: ["I have been", "for", "since", "so far", "currently", "recently", "every day", "at the moment"],
    lines: [
      { id: "pperfp4-l1", text: "I have been working in customer service for three years.", es: "Llevo tres años trabajando en servicio al cliente.", chunks: ["I have been working", "in customer service", "for three years."] },
      { id: "pperfp4-l2", text: "I have been learning English since I finished school.", es: "He estado aprendiendo inglés desde que terminé la escuela.", chunks: ["I have been learning English", "since I finished school."] },
      { id: "pperfp4-l3", text: "I have been improving my speaking every week.", es: "He estado mejorando mi speaking cada semana.", chunks: ["I have been improving", "my speaking", "every week."] },
      { id: "pperfp4-l4", text: "I have been looking for a better opportunity.", es: "He estado buscando una mejor oportunidad.", chunks: ["I have been looking", "for a better opportunity."] },
      { id: "pperfp4-l5", text: "I haven't been working in sales, only in support.", es: "No he estado trabajando en ventas, solo en soporte.", chunks: ["I haven't been working in sales,", "only in support."] },
      { id: "pperfp4-l6", text: "I have been taking notes to improve my accent.", es: "He estado tomando notas para mejorar mi acento.", chunks: ["I have been taking notes", "to improve my accent."] },
      { id: "pperfp4-l7", text: "I have been preparing for this interview all week.", es: "Me he estado preparando para esta entrevista toda la semana.", chunks: ["I have been preparing", "for this interview", "all week."] },
      { id: "pperfp4-l8", text: "I have wanted a job like this for a long time.", es: "He querido un trabajo así desde hace mucho.", chunks: ["I have wanted", "a job like this", "for a long time."] },
    ],
    questions: [
      { id: "pperfp4-q1", question: "What have you been doing in your current job?", questionEs: "¿Qué has estado haciendo en tu trabajo actual?", hint: "I have been…", hintEs: "Usa have been + verbo-ing." },
      { id: "pperfp4-q2", question: "How long have you been learning English?", questionEs: "¿Cuánto tiempo llevas aprendiendo inglés?", hint: "I have been learning English for / since…", hintEs: "For + duración; since + inicio." },
      { id: "pperfp4-q3", question: "When have you been practicing your speaking?", questionEs: "¿Cuándo has estado practicando tu speaking?", hint: "I have been practicing…", hintEs: "Di el momento del día." },
      { id: "pperfp4-q4", question: "Why have you been looking for a new job?", questionEs: "¿Por qué has estado buscando un trabajo nuevo?", hint: "Because I have been…", hintEs: "Usa because." },
      { id: "pperfp4-q5", question: "What haven't you been doing at work?", questionEs: "¿Qué no has estado haciendo en el trabajo?", hint: "I haven't been…", hintEs: "Negativa con haven't been." },
      { id: "pperfp4-q6", question: "Where have you been working recently?", questionEs: "¿Dónde has estado trabajando últimamente?", hint: "I have been working at…", hintEs: "Di el lugar." },
    ],
    finalPrompt: {
      question: "A recruiter asks: how long have you been working and learning English, and what have you been doing to improve?",
      questionEs: "Un reclutador pregunta: ¿cuánto llevas trabajando y aprendiendo inglés, y qué has estado haciendo para mejorar?",
      tips: {
        en: "Use at least five sentences with have been + -ing, and answer the how long question with for or since.",
        es: "Usa al menos cinco oraciones con have been + -ing y contesta el how long con for o since.",
      },
    },
    grammarGoals: [
      "answering How long…? with have been + -ing",
      "for and since in professional answers",
      "negatives with haven't been + -ing",
    ],
  },
  {
    number: 5,
    id: "pperfp-5-julio",
    title: "Julio's new routine",
    titleEs: "La nueva rutina de Julio",
    person: "third",
    character: "Julio",
    focus: "Free third person retelling with has been + -ing and a contrast with the present perfect.",
    focusEs: "Relato libre en tercera persona con has been + -ing y contraste con present perfect.",
    reminder: {
      en: "Duration = has been + -ing. Result = has + past participle.",
      es: "Duración = has been + -ing. Resultado = has + participio.",
    },
    showFullGuide: false,
    sceneImage: { src: scenePperfp5, alt: "Julio's new daily routine: running, sleeping, studying and working at night", altEs: "La nueva rutina de Julio: correr, dormir, estudiar y trabajar de noche" },
    instructions: {
      en: "You have the key facts about Julio. Build his story out loud.",
      es: "Tienes los datos clave de Julio. Arma su historia en voz alta.",
    },
    vocabulary: ["has been", "has finished", "since", "for", "every morning", "lately", "so far", "already"],
    factSheet: [
      { en: "Julio · night shift agent · new routine since October", es: "Julio · agente de turno nocturno · rutina nueva desde octubre" },
      { en: "Runs every morning · sleeps in the afternoon", es: "Corre cada mañana · duerme en la tarde" },
      { en: "Studying English for eight months · already finished level 2", es: "Estudia inglés desde hace ocho meses · ya terminó el nivel 2" },
      { en: "Saving money for a laptop · has not bought it yet", es: "Ahorra para una laptop · todavía no la compra" },
      { en: "Feels better · has more energy than before", es: "Se siente mejor · tiene más energía que antes" },
    ],
    lines: [
      { id: "pperfp5-l1", text: "Julio has been following a new routine since October.", es: "Julio ha estado siguiendo una rutina nueva desde octubre.", chunks: ["Julio has been following", "a new routine", "since October."] },
      { id: "pperfp5-l2", text: "He has been running every morning before he sleeps.", es: "Ha estado corriendo cada mañana antes de dormir.", chunks: ["He has been running", "every morning", "before he sleeps."] },
      { id: "pperfp5-l3", text: "He has been working the night shift for a year.", es: "Lleva un año trabajando en el turno nocturno.", chunks: ["He has been working", "the night shift", "for a year."] },
      { id: "pperfp5-l4", text: "He has been studying English for eight months.", es: "Lleva ocho meses estudiando inglés.", chunks: ["He has been studying English", "for eight months."] },
      { id: "pperfp5-l5", text: "He has already finished level two.", es: "Ya terminó el nivel dos.", chunks: ["He has already finished", "level two."] },
      { id: "pperfp5-l6", text: "He has been saving money for a laptop.", es: "Ha estado ahorrando dinero para una laptop.", chunks: ["He has been saving money", "for a laptop."] },
      { id: "pperfp5-l7", text: "He hasn't bought it yet.", es: "Todavía no la ha comprado.", chunks: ["He hasn't bought it", "yet."] },
      { id: "pperfp5-l8", text: "He has been feeling better and he has more energy now.", es: "Se ha estado sintiendo mejor y ahora tiene más energía.", chunks: ["He has been feeling better", "and he has more energy", "now."] },
    ],
    questions: [
      { id: "pperfp5-q1", question: "Where has Julio been working this year?", questionEs: "¿Dónde ha estado trabajando Julio este año?", hint: "He has been working…", hintEs: "Usa has been + verbo-ing." },
      { id: "pperfp5-q2", question: "Why has he been running every morning?", questionEs: "¿Por qué ha estado corriendo cada mañana?", hint: "Because he has been…", hintEs: "Usa because." },
      { id: "pperfp5-q3", question: "How long has he been studying English?", questionEs: "¿Cuánto tiempo lleva estudiando inglés?", hint: "He has been studying for…", hintEs: "For + duración." },
      { id: "pperfp5-q4", question: "What has he already finished?", questionEs: "¿Qué ya terminó?", hint: "He has already…", hintEs: "Resultado: has + participio." },
      { id: "pperfp5-q5", question: "What hasn't he bought yet?", questionEs: "¿Qué no ha comprado todavía?", hint: "He hasn't… yet", hintEs: "Yet va al final." },
      { id: "pperfp5-q6", question: "How has he been feeling lately?", questionEs: "¿Cómo se ha estado sintiendo últimamente?", hint: "He has been feeling…", hintEs: "Usa has been + feeling." },
    ],
    finalPrompt: {
      question: "Tell me about Julio's new routine: what he has been doing, for how long, and what he has already achieved.",
      questionEs: "Cuéntame la nueva rutina de Julio: qué ha estado haciendo, por cuánto tiempo y qué ya logró.",
      tips: {
        en: "Use at least five sentences with has been + -ing and two with has + past participle for results.",
        es: "Usa al menos cinco oraciones con has been + -ing y dos con has + participio para los resultados.",
      },
    },
    grammarGoals: [
      "has been + -ing for duration in a connected story",
      "contrast with has + past participle for results",
      "for, since, already and yet in the right position",
    ],
  },
];
