import type { ReviewGuideCard } from "@/lib/review-types";

/**
 * "ENTIÉNDELO FÁCIL" — the seven Simple Past basics.
 * Static hand-written content: never generated by AI, reused by every practice
 * (Practice 1 shows it inline in Step 1, practices 2–5 open it on demand).
 */
export const SIMPLE_PAST_GUIDE: ReviewGuideCard[] = [
  {
    id: "sp-past-1-use",
    title: "What it is for",
    titleEs: "Para qué sirve",
    explanation: "Simple Past is for finished actions at a finished time: yesterday, last week, in 2019, two hours ago.",
    explanationEs:
      "El Simple Past sirve para acciones terminadas en un tiempo terminado: yesterday, last week, last night, in 2019, two hours ago. Si ya pasó y ya cerró, va en pasado.",
    examples: [
      { en: "I worked yesterday.", es: "Trabajé ayer." },
      { en: "She traveled to Mexico last year.", es: "Ella viajó a México el año pasado." },
      { en: "We finished the project two days ago.", es: "Terminamos el proyecto hace dos días." },
    ],
    check: {
      prompt: "Say one thing you did yesterday.",
      promptEs: "Di en voz alta una cosa que hiciste ayer.",
      answer: "I studied English yesterday.",
    },
  },
  {
    id: "sp-past-2-regular",
    title: "Regular verbs: -ed",
    titleEs: "Verbos regulares: -ed",
    explanation: "Regular verbs add -ed. The form is the same for I, you, he, she, we and they.",
    explanationEs:
      "A los verbos regulares les agregas -ed: work → worked, call → called, study → studied, stop → stopped. La forma es igual para todas las personas: no existe “he workeds”.",
    examples: [
      { en: "work → worked · call → called", es: "work → worked · call → called" },
      { en: "study → studied · stop → stopped", es: "study → studied · stop → stopped" },
      { en: "He worked. / They worked. (same form)", es: "Él trabajó. / Ellos trabajaron. (misma forma)" },
    ],
    check: {
      prompt: "Say the past of: work, call, study, travel.",
      promptEs: "Di el pasado de: work, call, study, travel.",
      answer: "worked, called, studied, traveled",
    },
  },
  {
    id: "sp-past-3-irregular",
    title: "Irregular verbs",
    titleEs: "Verbos irregulares",
    explanation: "The most common verbs change completely. You have to memorize them.",
    explanationEs:
      "Los verbos más comunes cambian por completo y hay que memorizarlos: go → went, have → had, do → did, say → said, get → got, take → took, make → made, see → saw, eat → ate, buy → bought, come → came, tell → told.",
    examples: [
      { en: "go → went · have → had · do → did", es: "go → went · have → had · do → did" },
      { en: "get → got · take → took · make → made", es: "get → got · take → took · make → made" },
      { en: "I went to the beach and had lunch there.", es: "Fui a la playa y almorcé ahí." },
    ],
    check: {
      prompt: "Say the past of: go, have, take, buy.",
      promptEs: "Di el pasado de: go, have, take, buy.",
      answer: "went, had, took, bought",
    },
  },
  {
    id: "sp-past-4-negative",
    title: "Negative: didn't + base verb",
    titleEs: "Negativas: didn't + verbo base",
    explanation: "Use didn't and go back to the base verb. Never keep the past form after didn't.",
    explanationEs:
      "Para negar usas didn't y el verbo vuelve a su forma base: I didn't work (NO “didn't worked”), She didn't go (NO “didn't went”). El didn't ya lleva el pasado.",
    examples: [
      { en: "I didn't work on Sunday.", es: "No trabajé el domingo." },
      { en: "She didn't go to the party.", es: "Ella no fue a la fiesta." },
      { en: "We didn't have time. (NOT: didn't had)", es: "No tuvimos tiempo. (NO: didn't had)" },
    ],
    check: {
      prompt: "Say one thing you didn't do yesterday.",
      promptEs: "Di algo que no hiciste ayer.",
      answer: "I didn't watch TV yesterday.",
    },
  },
  {
    id: "sp-past-5-questions",
    title: "Questions with did",
    titleEs: "Preguntas con did",
    explanation: "Did + subject + base verb. What did you do? Where did she go?",
    explanationEs:
      "Las preguntas empiezan con Did: Did you work yesterday? Con palabra interrogativa va primero: What did you do? Where did she go? How long did it take? El verbo siempre en forma base. Respuestas cortas: Yes, I did / No, I didn't.",
    examples: [
      { en: "Did you travel last year? — Yes, I did.", es: "¿Viajaste el año pasado? — Sí." },
      { en: "What did you do yesterday?", es: "¿Qué hiciste ayer?" },
      { en: "Where did he go? (NOT: Where did he went?)", es: "¿Adónde fue? (NO: Where did he went?)" },
    ],
    check: {
      prompt: "Ask two past questions: one with Did you and one with What did.",
      promptEs: "Haz dos preguntas en pasado: una con Did you y otra con What did.",
      answer: "Did you work yesterday? What did you do last weekend?",
    },
  },
  {
    id: "sp-past-6-was-were",
    title: "was / were",
    titleEs: "was / were",
    explanation: "The verb be has its own past: was (I, he, she, it) and were (you, we, they). No did with was/were.",
    explanationEs:
      "El verbo be tiene su propio pasado: was con I, he, she, it; were con you, we, they. Con was/were NO se usa did: se dice Was it fun? y I wasn't tired, no “Did it was”.",
    examples: [
      { en: "I was tired. / They were happy.", es: "Yo estaba cansado. / Ellos estaban felices." },
      { en: "It wasn't easy. / We weren't ready.", es: "No fue fácil. / No estábamos listos." },
      { en: "Was the trip good? — Yes, it was.", es: "¿Estuvo bueno el viaje? — Sí." },
    ],
    check: {
      prompt: "Say how you felt yesterday with was.",
      promptEs: "Di cómo te sentiste ayer usando was.",
      answer: "I was tired but I was happy.",
    },
  },
  {
    id: "sp-past-7-time",
    title: "Time words that ask for the past",
    titleEs: "Palabras de tiempo del pasado",
    explanation: "Yesterday, last night, last week, two days ago, in 2020, when I was a kid — all of them need Simple Past.",
    explanationEs:
      "Estas palabras te obligan a usar pasado: yesterday, last night, last week, last year, two days ago, in 2020, when I was a kid. Ponlas al inicio o al final de la oración y ordena la historia con first, then, after that, finally.",
    examples: [
      { en: "Last weekend I visited my family.", es: "El fin de semana pasado visité a mi familia." },
      { en: "Two hours ago he called me.", es: "Hace dos horas él me llamó." },
      { en: "First we ate, then we walked to the park.", es: "Primero comimos, luego caminamos al parque." },
    ],
    check: {
      prompt: "Tell two things in order with first and then.",
      promptEs: "Cuenta dos cosas en orden con first y then.",
      answer: "First I woke up early, then I went to work.",
    },
  },
];

/** The four errors this module keeps correcting. */
export const SIMPLE_PAST_COMMON_ERRORS: { wrong: string; right: string; es: string }[] = [
  { wrong: "I didn't went", right: "I didn't go", es: "Después de didn't el verbo va en forma base." },
  { wrong: "Where did she went?", right: "Where did she go?", es: "Con did la pregunta usa el verbo base." },
  { wrong: "Yesterday I go to work", right: "Yesterday I went to work", es: "Con yesterday necesitas el pasado." },
  { wrong: "It was very fun, we was happy", right: "It was very fun, we were happy", es: "Con we / you / they se usa were." },
];
