import type { ReviewPractice } from "@/lib/review-types";

/**
 * REVIEW · SIMPLE PRESENT — five static practices.
 *
 * Person of the learner's MAIN answers alternates: 3rd · 1st · 3rd · 1st · 3rd.
 * Elena, Marco and Sofía are fictional practice characters with different
 * subjects, situations and wording — never the same activity with a new name.
 * All content is hand-written: nothing here is generated at page load.
 */
export const SIMPLE_PRESENT_PRACTICES: ReviewPractice[] = [
  {
    number: 1,
    id: "sp-1-elena",
    title: "Elena's everyday routine",
    titleEs: "La rutina diaria de Elena",
    person: "third",
    character: "Elena",
    focus: "Third person affirmative and negative: she works, she doesn't work.",
    focusEs: "Tercera persona: afirmaciones y negativas (she works / she doesn't work).",
    reminder: {
      en: "With she, the verb takes -s. After doesn't, the verb goes back to its base form.",
      es: "Con she el verbo lleva -s. Después de doesn't el verbo vuelve a su forma base.",
    },
    showFullGuide: true,
    instructions: {
      en: "Elena is a student. Learn her weekday routine and then describe it out loud.",
      es: "Elena es estudiante. Aprende su rutina entre semana y después descríbela en voz alta.",
    },
    vocabulary: ["wake up", "take the bus", "class", "homework", "cook dinner", "on Sundays", "early", "at home"],
    lines: [
      { id: "p1-l1", text: "Elena wakes up at six in the morning.", es: "Elena se despierta a las seis de la mañana.", chunks: ["Elena wakes up", "at six", "in the morning."] },
      { id: "p1-l2", text: "She takes the bus to the university.", es: "Ella toma el bus a la universidad.", chunks: ["She takes the bus", "to the university."] },
      { id: "p1-l3", text: "She studies English every weekday.", es: "Ella estudia inglés todos los días entre semana.", chunks: ["She studies English", "every weekday."] },
      { id: "p1-l4", text: "She has two classes in the afternoon.", es: "Ella tiene dos clases por la tarde.", chunks: ["She has two classes", "in the afternoon."] },
      { id: "p1-l5", text: "She doesn't study on Sundays.", es: "Ella no estudia los domingos.", chunks: ["She doesn't study", "on Sundays."] },
      { id: "p1-l6", text: "She doesn't drive, so she walks home.", es: "Ella no maneja, así que camina a casa.", chunks: ["She doesn't drive,", "so she walks home."] },
      { id: "p1-l7", text: "She cooks dinner and does her homework at home.", es: "Ella cocina la cena y hace su tarea en casa.", chunks: ["She cooks dinner", "and does her homework", "at home."] },
      { id: "p1-l8", text: "She goes to bed early because she starts early.", es: "Ella se acuesta temprano porque empieza temprano.", chunks: ["She goes to bed early", "because she starts early."] },
    ],
    questions: [
      { id: "p1-q1", question: "What time does Elena wake up?", questionEs: "¿A qué hora se despierta Elena?", hint: "She wakes up at…", hintEs: "Usa wakes up + la hora." },
      { id: "p1-q2", question: "How does she go to the university?", questionEs: "¿Cómo va a la universidad?", hint: "She takes…", hintEs: "Usa takes the bus." },
      { id: "p1-q3", question: "What does she study?", questionEs: "¿Qué estudia?", hint: "She studies…", hintEs: "Recuerda: study → studies." },
      { id: "p1-q4", question: "What doesn't she do on Sundays?", questionEs: "¿Qué no hace los domingos?", hint: "She doesn't…", hintEs: "Después de doesn't, verbo base." },
      { id: "p1-q5", question: "What does she do at home in the evening?", questionEs: "¿Qué hace en casa por la noche?", hint: "She cooks… and she…", hintEs: "Une dos ideas con and." },
      { id: "p1-q6", question: "Why does she go to bed early?", questionEs: "¿Por qué se acuesta temprano?", hint: "Because she…", hintEs: "Usa because para dar la razón." },
    ],
    finalPrompt: {
      question: "Walk me through Elena's typical weekday. What does she do, and what doesn't she do?",
      questionEs: "Cuéntame el día típico de Elena entre semana. ¿Qué hace y qué no hace?",
      tips: {
        en: "Use she + verb with -s, and at least one sentence with doesn't.",
        es: "Usa she + verbo con -s, y al menos una oración con doesn't.",
      },
    },
    grammarGoals: [
      "third person -s / -es / -ies on affirmative verbs (she works, she studies, she goes)",
      "negatives with doesn't + base verb",
      "everyday routine vocabulary and simple connectors (and, so, because)",
    ],
  },
  {
    number: 2,
    id: "sp-2-my-life",
    title: "My everyday life",
    titleEs: "Mi vida diaria",
    person: "first",
    character: null,
    focus: "First person: base verb, don't, like + because.",
    focusEs: "Primera persona: verbo base, don't, like y because.",
    reminder: {
      en: "With I the verb never takes -s. Negatives use don't + base verb, and because explains your reason.",
      es: "Con I el verbo nunca lleva -s. Para negar usas don't + verbo base, y because da la razón.",
    },
    showFullGuide: false,
    instructions: {
      en: "Now it's about you: where you live, what you do and what you enjoy. You don't need a job to answer.",
      es: "Ahora es sobre ti: dónde vives, qué haces y qué disfrutas. No necesitas tener trabajo para responder.",
    },
    vocabulary: ["live", "study", "in the evening", "help at home", "relax", "because", "don't", "on weekends"],
    lines: [
      { id: "p2-l1", text: "I live in a small city with my family.", es: "Vivo en una ciudad pequeña con mi familia.", chunks: ["I live in a small city", "with my family."] },
      { id: "p2-l2", text: "I study English in the evening.", es: "Estudio inglés por la noche.", chunks: ["I study English", "in the evening."] },
      { id: "p2-l3", text: "I help at home before my classes.", es: "Ayudo en casa antes de mis clases.", chunks: ["I help at home", "before my classes."] },
      { id: "p2-l4", text: "I don't drive, so I walk or take the bus.", es: "No manejo, así que camino o tomo el bus.", chunks: ["I don't drive,", "so I walk", "or take the bus."] },
      { id: "p2-l5", text: "I like music because it helps me relax.", es: "Me gusta la música porque me ayuda a relajarme.", chunks: ["I like music", "because it helps me relax."] },
      { id: "p2-l6", text: "I don't watch TV during the week.", es: "No veo tele entre semana.", chunks: ["I don't watch TV", "during the week."] },
      { id: "p2-l7", text: "On weekends I meet my friends.", es: "Los fines de semana veo a mis amigos.", chunks: ["On weekends", "I meet my friends."] },
      { id: "p2-l8", text: "I practice English every day because I want a better job.", es: "Practico inglés todos los días porque quiero un mejor trabajo.", chunks: ["I practice English", "every day", "because I want a better job."] },
    ],
    questions: [
      { id: "p2-q1", question: "Where do you live?", questionEs: "¿Dónde vives?", hint: "I live in…", hintEs: "Usa I live in + lugar." },
      { id: "p2-q2", question: "What do you study or do every day?", questionEs: "¿Qué estudias o haces cada día?", hint: "I study… / I work…", hintEs: "Con I, verbo base." },
      { id: "p2-q3", question: "What don't you do during the week?", questionEs: "¿Qué no haces entre semana?", hint: "I don't…", hintEs: "don't + verbo base." },
      { id: "p2-q4", question: "What do you like, and why?", questionEs: "¿Qué te gusta y por qué?", hint: "I like… because…", hintEs: "Une gusto y razón con because." },
      { id: "p2-q5", question: "What do you do on weekends?", questionEs: "¿Qué haces los fines de semana?", hint: "On weekends I…", hintEs: "Empieza con la expresión de tiempo." },
      { id: "p2-q6", question: "Why do you practice English?", questionEs: "¿Por qué practicas inglés?", hint: "I practice English because…", hintEs: "Da una razón real." },
    ],
    finalPrompt: {
      question: "Describe your everyday life. What do you do, what don't you do, and what do you enjoy?",
      questionEs: "Describe tu vida diaria. ¿Qué haces, qué no haces y qué disfrutas?",
      tips: {
        en: "Use I + base verb, one sentence with don't and one reason with because.",
        es: "Usa I + verbo base, una oración con don't y una razón con because.",
      },
    },
    grammarGoals: [
      "first person affirmatives with the base verb (no -s)",
      "negatives with don't + base verb",
      "like + noun / because to give a reason",
    ],
  },
  {
    number: 3,
    id: "sp-3-marco",
    title: "Marco's habits",
    titleEs: "Los hábitos de Marco",
    person: "third",
    character: "Marco",
    focus: "Frequency with third person: usually, sometimes, never, twice a week.",
    focusEs: "Frecuencia en tercera persona: usually, sometimes, never, twice a week.",
    reminder: {
      en: "Frequency words go before the main verb. Never is already negative, so it never takes doesn't.",
      es: "Los adverbios de frecuencia van antes del verbo principal. Never ya es negativo, no lleva doesn't.",
    },
    showFullGuide: false,
    instructions: {
      en: "Marco studies at night and loves cooking and exercising. Learn how often he does things.",
      es: "Marco estudia de noche y le encanta cocinar y hacer ejercicio. Aprende con qué frecuencia hace cada cosa.",
    },
    vocabulary: ["usually", "sometimes", "never", "twice a week", "cook at home", "exercise", "healthy", "how often"],
    lines: [
      { id: "p3-l1", text: "Marco usually cooks at home.", es: "Marco normalmente cocina en casa.", chunks: ["Marco usually cooks", "at home."] },
      { id: "p3-l2", text: "He exercises twice a week in the park.", es: "Él hace ejercicio dos veces por semana en el parque.", chunks: ["He exercises", "twice a week", "in the park."] },
      { id: "p3-l3", text: "He sometimes eats out with his coworkers.", es: "A veces come fuera con sus compañeros.", chunks: ["He sometimes eats out", "with his coworkers."] },
      { id: "p3-l4", text: "He never drinks coffee after seven.", es: "Él nunca toma café después de las siete.", chunks: ["He never drinks coffee", "after seven."] },
      { id: "p3-l5", text: "He studies English every night for one hour.", es: "Él estudia inglés cada noche por una hora.", chunks: ["He studies English", "every night", "for one hour."] },
      { id: "p3-l6", text: "He doesn't skip breakfast because he wakes up early.", es: "Él no se salta el desayuno porque se levanta temprano.", chunks: ["He doesn't skip breakfast", "because he wakes up early."] },
      { id: "p3-l7", text: "He often watches videos in English.", es: "Él ve videos en inglés con frecuencia.", chunks: ["He often watches videos", "in English."] },
      { id: "p3-l8", text: "He always prepares his food on Sundays.", es: "Él siempre prepara su comida los domingos.", chunks: ["He always prepares his food", "on Sundays."] },
    ],
    questions: [
      { id: "p3-q1", question: "How often does Marco cook at home?", questionEs: "¿Con qué frecuencia cocina Marco en casa?", hint: "He usually…", hintEs: "El adverbio va antes del verbo." },
      { id: "p3-q2", question: "How often does he exercise?", questionEs: "¿Con qué frecuencia hace ejercicio?", hint: "He exercises… a week.", hintEs: "Usa twice a week." },
      { id: "p3-q3", question: "What does he sometimes do with his coworkers?", questionEs: "¿Qué hace a veces con sus compañeros?", hint: "He sometimes…", hintEs: "sometimes + verbo con -s." },
      { id: "p3-q4", question: "What does he never do?", questionEs: "¿Qué no hace nunca?", hint: "He never…", hintEs: "never no lleva doesn't." },
      { id: "p3-q5", question: "How often does he study English?", questionEs: "¿Con qué frecuencia estudia inglés?", hint: "He studies English every…", hintEs: "Usa every night." },
      { id: "p3-q6", question: "Why doesn't he skip breakfast?", questionEs: "¿Por qué no se salta el desayuno?", hint: "Because he…", hintEs: "Da la razón con because." },
    ],
    finalPrompt: {
      question: "Explain Marco's habits. What does he usually do? What does he sometimes do, and what does he never do?",
      questionEs: "Explica los hábitos de Marco. ¿Qué hace normalmente? ¿Qué hace a veces y qué no hace nunca?",
      tips: {
        en: "Use usually, sometimes and never, plus one expression like twice a week.",
        es: "Usa usually, sometimes y never, y una expresión como twice a week.",
      },
    },
    grammarGoals: [
      "frequency adverbs placed before the main verb",
      "third person -s with frequency (he usually cooks, he often watches)",
      "never as a negative without doesn't; expressions like every day / twice a week",
    ],
  },
  {
    number: 4,
    id: "sp-4-my-week",
    title: "My week and my preferences",
    titleEs: "Mi semana y mis preferencias",
    person: "first",
    character: null,
    focus: "Questions with Do and question words; short answers plus extra information.",
    focusEs: "Preguntas con Do y palabras interrogativas; respuestas cortas más información extra.",
    reminder: {
      en: "Do + you + base verb. Answer short (Yes, I do) and then add one more detail.",
      es: "Do + you + verbo base. Responde corto (Yes, I do) y después agrega un detalle más.",
    },
    showFullGuide: false,
    instructions: {
      en: "Talk about your weekdays and weekends — and ask at least two questions to know someone else's habits.",
      es: "Habla de tus días entre semana y fines de semana, y haz al menos dos preguntas para conocer los hábitos de otra persona.",
    },
    vocabulary: ["weekdays", "weekends", "prefer", "usually", "how often", "what time", "rest", "go out"],
    lines: [
      { id: "p4-l1", text: "Do you work on weekends? — No, I don't. I rest at home.", es: "¿Trabajas los fines de semana? — No. Descanso en casa.", chunks: ["Do you work on weekends?", "No, I don't.", "I rest at home."] },
      { id: "p4-l2", text: "What time do you start your day?", es: "¿A qué hora empiezas tu día?", chunks: ["What time", "do you start", "your day?"] },
      { id: "p4-l3", text: "I start at seven because my classes begin at eight.", es: "Empiezo a las siete porque mis clases empiezan a las ocho.", chunks: ["I start at seven", "because my classes", "begin at eight."] },
      { id: "p4-l4", text: "How often do you go out during the week?", es: "¿Con qué frecuencia sales entre semana?", chunks: ["How often", "do you go out", "during the week?"] },
      { id: "p4-l5", text: "I don't go out on weekdays, but I go out on Saturdays.", es: "No salgo entre semana, pero salgo los sábados.", chunks: ["I don't go out on weekdays,", "but I go out", "on Saturdays."] },
      { id: "p4-l6", text: "I prefer mornings because I have more energy.", es: "Prefiero las mañanas porque tengo más energía.", chunks: ["I prefer mornings", "because I have", "more energy."] },
      { id: "p4-l7", text: "Where do you study English? — At home, with my phone.", es: "¿Dónde estudias inglés? — En casa, con mi teléfono.", chunks: ["Where do you study English?", "At home,", "with my phone."] },
      { id: "p4-l8", text: "Yes, I do. I practice speaking every day.", es: "Sí. Practico hablar todos los días.", chunks: ["Yes, I do.", "I practice speaking", "every day."] },
    ],
    questions: [
      { id: "p4-q1", question: "What do you usually do on weekdays?", questionEs: "¿Qué haces normalmente entre semana?", hint: "I usually…", hintEs: "Con I, verbo base." },
      { id: "p4-q2", question: "Do you work or study on weekends? Answer short, then add information.", questionEs: "¿Trabajas o estudias los fines de semana? Responde corto y luego agrega información.", hint: "Yes, I do. / No, I don't. Then: I…", hintEs: "Respuesta corta + un detalle." },
      { id: "p4-q3", question: "Now ask me a question with Do you…?", questionEs: "Ahora hazme una pregunta con Do you…?", hint: "Do you… ?", hintEs: "Do + you + verbo base." },
      { id: "p4-q4", question: "Ask a second question with How often do you…?", questionEs: "Haz una segunda pregunta con How often do you…?", hint: "How often do you…?", hintEs: "Palabra interrogativa + do + you + verbo base." },
      { id: "p4-q5", question: "What do you prefer: mornings or nights? Why?", questionEs: "¿Qué prefieres: mañanas o noches? ¿Por qué?", hint: "I prefer… because…", hintEs: "Usa because." },
      { id: "p4-q6", question: "What don't you do on weekends?", questionEs: "¿Qué no haces los fines de semana?", hint: "I don't…", hintEs: "don't + verbo base." },
    ],
    finalPrompt: {
      question: "Explain how you spend your weekdays and weekends. Include your habits, preferences and reasons.",
      questionEs: "Explica cómo pasas tus días entre semana y tus fines de semana. Incluye hábitos, preferencias y razones.",
      tips: {
        en: "Speak about yourself with I, add frequency and give at least one reason with because.",
        es: "Habla de ti con I, agrega frecuencia y da al menos una razón con because.",
      },
    },
    grammarGoals: [
      "first person habits with frequency and time expressions",
      "questions with Do / question words and correct short answers",
      "preferences with prefer / like and reasons with because",
    ],
  },
  {
    number: 5,
    id: "sp-5-sofia",
    title: "Sofía's weekend",
    titleEs: "El fin de semana de Sofía",
    person: "third",
    character: "Sofía",
    focus: "Third person applied with less support: routine, negatives, frequency and connectors.",
    focusEs: "Tercera persona con menos ayuda: rutina, negativas, frecuencia y conectores.",
    reminder: {
      en: "Watch the four classic mistakes: she work, she doesn't works, does she studies, I am work.",
      es: "Cuidado con los cuatro errores clásicos: she work, she doesn't works, does she studies, I am work.",
    },
    showFullGuide: false,
    instructions: {
      en: "You get facts about Sofía, not a full model answer. Build the description yourself.",
      es: "Recibes datos sobre Sofía, no un monólogo completo. Tú construyes la descripción.",
    },
    vocabulary: ["weekend", "responsibilities", "take care of", "clean", "visit", "prefer", "rarely", "in the morning"],
    factSheet: [
      { en: "Sofía · 28 · lives with her sister", es: "Sofía · 28 años · vive con su hermana" },
      { en: "Saturday morning: cleans the apartment", es: "Sábado por la mañana: limpia el apartamento" },
      { en: "Twice a month: visits her parents", es: "Dos veces al mes: visita a sus papás" },
      { en: "Always: takes care of her dog", es: "Siempre: cuida a su perro" },
      { en: "Never: works on Sundays", es: "Nunca: trabaja los domingos" },
      { en: "Prefers: cooking at home, not restaurants", es: "Prefiere: cocinar en casa, no restaurantes" },
      { en: "Doesn't like: waking up early on weekends", es: "No le gusta: levantarse temprano los fines de semana" },
    ],
    lines: [
      { id: "p5-l1", text: "Sofía cleans the apartment on Saturday morning.", es: "Sofía limpia el apartamento el sábado por la mañana.", chunks: ["Sofía cleans the apartment", "on Saturday morning."] },
      { id: "p5-l2", text: "She takes care of her dog every day.", es: "Ella cuida a su perro todos los días.", chunks: ["She takes care of her dog", "every day."] },
      { id: "p5-l3", text: "She visits her parents twice a month.", es: "Ella visita a sus papás dos veces al mes.", chunks: ["She visits her parents", "twice a month."] },
      { id: "p5-l4", text: "She never works on Sundays.", es: "Ella nunca trabaja los domingos.", chunks: ["She never works", "on Sundays."] },
      { id: "p5-l5", text: "She doesn't like waking up early on weekends.", es: "A ella no le gusta levantarse temprano los fines de semana.", chunks: ["She doesn't like", "waking up early", "on weekends."] },
      { id: "p5-l6", text: "She prefers cooking at home because it's cheaper.", es: "Ella prefiere cocinar en casa porque es más barato.", chunks: ["She prefers cooking at home", "because it's cheaper."] },
      { id: "p5-l7", text: "She rarely goes to restaurants, but she loves coffee shops.", es: "Ella casi nunca va a restaurantes, pero le encantan las cafeterías.", chunks: ["She rarely goes to restaurants,", "but she loves coffee shops."] },
      { id: "p5-l8", text: "She lives with her sister, so they share the housework.", es: "Ella vive con su hermana, así que comparten los quehaceres.", chunks: ["She lives with her sister,", "so they share the housework."] },
    ],
    questions: [
      { id: "p5-q1", question: "What does Sofía do on Saturday morning?", questionEs: "¿Qué hace Sofía el sábado por la mañana?", hint: "She cleans…", hintEs: "Tercera persona con -s." },
      { id: "p5-q2", question: "What responsibility does she have every day?", questionEs: "¿Qué responsabilidad tiene todos los días?", hint: "She takes care of…", hintEs: "Usa takes care of." },
      { id: "p5-q3", question: "How often does she visit her parents?", questionEs: "¿Con qué frecuencia visita a sus papás?", hint: "She visits… a month.", hintEs: "twice a month." },
      { id: "p5-q4", question: "What does she never do?", questionEs: "¿Qué no hace nunca?", hint: "She never…", hintEs: "never sin doesn't." },
      { id: "p5-q5", question: "What doesn't she like?", questionEs: "¿Qué no le gusta?", hint: "She doesn't like…", hintEs: "doesn't + verbo base." },
      { id: "p5-q6", question: "Why does she prefer cooking at home?", questionEs: "¿Por qué prefiere cocinar en casa?", hint: "Because…", hintEs: "Da la razón con because." },
    ],
    finalPrompt: {
      question: "Introduce Sofía to someone who doesn't know her. Explain her weekend habits, responsibilities and preferences.",
      questionEs: "Preséntale Sofía a alguien que no la conoce. Explica sus hábitos de fin de semana, responsabilidades y preferencias.",
      tips: {
        en: "Use she + verb with -s, one negative, one frequency word and connectors like and, but, because.",
        es: "Usa she + verbo con -s, una negativa, una palabra de frecuencia y conectores como and, but, because.",
      },
    },
    grammarGoals: [
      "third person applied with little support (affirmative and negative)",
      "frequency (always, never, rarely, twice a month) in the right position",
      "basic connectors (and, but, so, because) linking ideas",
    ],
  },
];
