import type { ReviewGuideCard } from "@/lib/review-types";

/**
 * "ENTIÉNDELO FÁCIL" — the seven Simple Present basics.
 * Static hand-written content: never generated by AI, reused by every practice
 * (Practice 1 shows it inline in Step 1, practices 2–5 open it on demand).
 */
export const SIMPLE_PRESENT_GUIDE: ReviewGuideCard[] = [
  {
    id: "g1-use",
    title: "What it is for",
    titleEs: "Para qué sirve",
    explanation: "Simple Present is for routines, habits, things you like and facts that are true now.",
    explanationEs:
      "El Simple Present sirve para rutinas, hábitos, gustos y hechos del presente. No es para lo que pasa justo en este segundo, sino para lo que pasa normalmente.",
    examples: [
      { en: "I work from Monday to Friday.", es: "Trabajo de lunes a viernes." },
      { en: "She likes coffee.", es: "A ella le gusta el café." },
      { en: "The office opens at 8:00.", es: "La oficina abre a las 8:00." },
    ],
    check: {
      prompt: "Say one true routine about your week.",
      promptEs: "Di en voz alta una rutina real de tu semana.",
      answer: "I study English every day.",
    },
  },
  {
    id: "g2-affirmative",
    title: "Affirmative sentences",
    titleEs: "Afirmaciones",
    explanation: "I / you / we / they use the base verb. He / she / it use the third person form.",
    explanationEs:
      "Con I, you, we y they usas el verbo base, sin cambios. Con he, she e it el verbo cambia: casi siempre se le agrega una -s.",
    examples: [
      { en: "I work in a call center.", es: "Trabajo en un call center." },
      { en: "We study together.", es: "Estudiamos juntos." },
      { en: "She works in a call center.", es: "Ella trabaja en un call center." },
    ],
    check: {
      prompt: "Say the same sentence with I and then with she.",
      promptEs: "Di la misma oración con I y luego con she.",
      answer: "I work at night. / She works at night.",
    },
  },
  {
    id: "g3-third-person",
    title: "Third person: -s, -es, -ies",
    titleEs: "Tercera persona",
    explanation: "Add -s to most verbs, -es after ch, sh, s, x or o, and change consonant + y to -ies.",
    explanationEs:
      "Con he/she/it: a la mayoría de verbos les agregas -s (work → works). Si el verbo termina en ch, sh, s, x u o, agregas -es (watch → watches). Si termina en consonante + y, la y cambia a -ies (study → studies). Si termina en vocal + y, solo agregas -s (play → plays). Dos verbos muy comunes son irregulares: go → goes y have → has.",
    examples: [
      { en: "He works at home. / She watches the news.", es: "Él trabaja en casa. / Ella ve las noticias." },
      { en: "She studies English. / He plays soccer.", es: "Ella estudia inglés. / Él juega fútbol." },
      { en: "She goes to the gym. / He has two brothers.", es: "Ella va al gimnasio. / Él tiene dos hermanos." },
    ],
    check: {
      prompt: "Say: study, watch, go, have — with she.",
      promptEs: "Di en voz alta: study, watch, go, have — con she.",
      answer: "She studies. She watches. She goes. She has.",
    },
  },
  {
    id: "g4-negative",
    title: "Negative sentences",
    titleEs: "Negativas",
    explanation: "Use don't with I / you / we / they and doesn't with he / she / it. The verb goes back to its base form.",
    explanationEs:
      "Para negar usas don't (I, you, we, they) o doesn't (he, she, it) + verbo base. Muy importante: después de doesn't el verbo NO lleva -s, porque la -s ya está dentro de doesn't.",
    examples: [
      { en: "I don't work on Sundays.", es: "No trabajo los domingos." },
      { en: "She doesn't work on Sundays.", es: "Ella no trabaja los domingos." },
      { en: "They don't study at night.", es: "Ellos no estudian de noche." },
    ],
    check: {
      prompt: "Say one thing you don't do and one thing she doesn't do.",
      promptEs: "Di algo que tú no haces y algo que ella no hace.",
      answer: "I don't drive. She doesn't drive.",
    },
  },
  {
    id: "g5-questions",
    title: "Questions and short answers",
    titleEs: "Preguntas",
    explanation: "Do / does + subject + base verb. Question words go first: what, where, when, how often.",
    explanationEs:
      "Las preguntas empiezan con Do (I, you, we, they) o Does (he, she, it) + sujeto + verbo base. Después de does el verbo va en forma base, sin -s. Puedes poner una palabra interrogativa al inicio: what, where, when, how often. Las respuestas cortas son: Yes, I do / No, I don't / Yes, she does / No, she doesn't.",
    examples: [
      { en: "Do you work on Saturdays? — Yes, I do.", es: "¿Trabajas los sábados? — Sí." },
      { en: "Does she study English? — No, she doesn't.", es: "¿Ella estudia inglés? — No." },
      { en: "Where do you live? / How often does he exercise?", es: "¿Dónde vives? / ¿Con qué frecuencia hace ejercicio él?" },
    ],
    check: {
      prompt: "Ask two questions: one with do and one with does.",
      promptEs: "Haz dos preguntas: una con do y otra con does.",
      answer: "Do you live near here? Does she work from home?",
    },
  },
  {
    id: "g6-frequency",
    title: "Frequency",
    titleEs: "Frecuencia",
    explanation: "Always, usually, often, sometimes, never go before the main verb — but after the verb be.",
    explanationEs:
      "Los adverbios de frecuencia (always, usually, often, sometimes, never) van antes del verbo principal, pero después del verbo be. También puedes usar expresiones al final: every day, on Sundays, twice a week. Ojo: never ya es negativo, así que no lleva don't.",
    examples: [
      { en: "I usually study at night.", es: "Normalmente estudio de noche." },
      { en: "She is usually busy on Mondays.", es: "Ella normalmente está ocupada los lunes." },
      { en: "I never drink coffee. / He exercises twice a week.", es: "Nunca tomo café. / Él hace ejercicio dos veces por semana." },
    ],
    check: {
      prompt: "Say one thing you always do and one thing you never do.",
      promptEs: "Di algo que siempre haces y algo que nunca haces.",
      answer: "I always check my email. I never work on Sundays.",
    },
  },
  {
    id: "g7-to-be",
    title: "The special case: to be",
    titleEs: "El caso de to be",
    explanation: "Am / is / are do not use do or does, and they never appear next to another main verb.",
    explanationEs:
      "El verbo be (am, is, are) funciona diferente: no usa do ni does. Para negar agregas not (I'm not, she isn't) y para preguntar cambias el orden (Is she…?). Nunca combines be con otro verbo principal: se dice I work, no “I am work”.",
    examples: [
      { en: "I am a student. / She isn't tired.", es: "Soy estudiante. / Ella no está cansada." },
      { en: "Is she a student? — Yes, she is.", es: "¿Ella es estudiante? — Sí." },
      { en: "I work at night. (NOT: I am work at night.)", es: "Trabajo de noche. (NO: I am work at night.)" },
    ],
    check: {
      prompt: "Say who you are and what you do.",
      promptEs: "Di quién eres y qué haces.",
      answer: "I am a student and I work in the evening.",
    },
  },
];

/** The four errors this module keeps correcting. */
export const SIMPLE_PRESENT_COMMON_ERRORS: { wrong: string; right: string; es: string }[] = [
  { wrong: "She work", right: "She works", es: "Con he/she/it el verbo lleva -s." },
  { wrong: "She doesn't works", right: "She doesn't work", es: "Después de doesn't el verbo va en base." },
  { wrong: "Does she studies?", right: "Does she study?", es: "Después de does el verbo va en base." },
  { wrong: "I am work", right: "I work", es: "No mezcles be con otro verbo principal." },
];
