import type { ReviewPractice } from "@/lib/review-types";

/**
 * REVIEW · SIMPLE PAST — five static practices.
 *
 * Person of the learner's MAIN answers alternates: 3rd · 1st · 3rd · 1st · 3rd.
 * Every practice mixes REGULAR (-ed) and IRREGULAR verbs on purpose.
 * Ricardo, Valeria and Óscar are fictional practice characters with different
 * situations. All content is hand-written: nothing here is generated at load.
 */
export const SIMPLE_PAST_PRACTICES: ReviewPractice[] = [
  {
    number: 1,
    id: "spast-1-ricardo",
    title: "Ricardo's day yesterday",
    titleEs: "El día de Ricardo ayer",
    person: "third",
    character: "Ricardo",
    focus: "Third person affirmative past with a mix of regular (-ed) and irregular verbs.",
    focusEs: "Pasado afirmativo en tercera persona con mezcla de verbos regulares (-ed) e irregulares.",
    reminder: {
      en: "In the past the form is the same for everybody: he worked, they worked, he went, they went.",
      es: "En pasado la forma es igual para todos: he worked, they worked, he went, they went. No agregues -s.",
    },
    showFullGuide: true,
    instructions: {
      en: "Ricardo had a normal working day yesterday. Tell the story in the past.",
      es: "Ricardo tuvo un día normal de trabajo ayer. Cuenta la historia en pasado.",
    },
    vocabulary: ["yesterday", "woke up", "worked", "went", "had", "called", "finished", "got home"],
    lines: [
      { id: "spast1-l1", text: "Ricardo woke up at six o'clock yesterday.", es: "Ricardo se despertó a las seis ayer.", chunks: ["Ricardo woke up", "at six o'clock", "yesterday."] },
      { id: "spast1-l2", text: "He walked to the bus stop and waited ten minutes.", es: "Caminó a la parada del bus y esperó diez minutos.", chunks: ["He walked", "to the bus stop", "and waited ten minutes."] },
      { id: "spast1-l3", text: "He started work at eight and answered many emails.", es: "Empezó a trabajar a las ocho y contestó muchos correos.", chunks: ["He started work at eight", "and answered many emails."] },
      { id: "spast1-l4", text: "His manager gave him a difficult report.", es: "Su jefe le dio un reporte difícil.", chunks: ["His manager", "gave him", "a difficult report."] },
      { id: "spast1-l5", text: "He had lunch with two coworkers at noon.", es: "Almorzó con dos compañeros al mediodía.", chunks: ["He had lunch", "with two coworkers", "at noon."] },
      { id: "spast1-l6", text: "In the afternoon he called three clients.", es: "En la tarde llamó a tres clientes.", chunks: ["In the afternoon", "he called", "three clients."] },
      { id: "spast1-l7", text: "He finished the report and sent it at five.", es: "Terminó el reporte y lo envió a las cinco.", chunks: ["He finished the report", "and sent it", "at five."] },
      { id: "spast1-l8", text: "He got home late, but he was happy with his day.", es: "Llegó tarde a casa, pero estuvo contento con su día.", chunks: ["He got home late,", "but he was happy", "with his day."] },
    ],
    questions: [
      { id: "spast1-q1", question: "What time did Ricardo wake up yesterday?", questionEs: "¿A qué hora se despertó Ricardo ayer?", hint: "He woke up at…", hintEs: "Usa woke up (irregular)." },
      { id: "spast1-q2", question: "What did he do in the morning?", questionEs: "¿Qué hizo en la mañana?", hint: "He started… and answered…", hintEs: "Mezcla verbos regulares e irregulares." },
      { id: "spast1-q3", question: "Who did he have lunch with?", questionEs: "¿Con quién almorzó?", hint: "He had lunch with…", hintEs: "have → had." },
      { id: "spast1-q4", question: "How many clients did he call?", questionEs: "¿A cuántos clientes llamó?", hint: "He called…", hintEs: "call → called." },
      { id: "spast1-q5", question: "When did he finish the report?", questionEs: "¿Cuándo terminó el reporte?", hint: "He finished it at…", hintEs: "Di la hora." },
      { id: "spast1-q6", question: "How did he feel at the end of the day?", questionEs: "¿Cómo se sintió al final del día?", hint: "He was…", hintEs: "Usa was para el sentimiento." },
    ],
    finalPrompt: {
      question: "Tell me about Ricardo's day yesterday, from the morning to the night.",
      questionEs: "Cuéntame el día de Ricardo ayer, desde la mañana hasta la noche.",
      tips: {
        en: "Use at least three regular verbs (-ed) and three irregular verbs, and order the story with first, then, after that.",
        es: "Usa al menos tres verbos regulares (-ed) y tres irregulares, y ordena la historia con first, then, after that.",
      },
    },
    grammarGoals: [
      "affirmative simple past with regular -ed verbs",
      "common irregular verbs: wake up/woke up, have/had, give/gave, get/got, send/sent",
      "the past form never takes -s in third person",
    ],
  },
  {
    number: 2,
    id: "spast-2-yesterday",
    title: "What did you do yesterday?",
    titleEs: "¿Qué hiciste ayer?",
    person: "first",
    character: null,
    focus: "First person past, negatives with didn't + base verb, and was / were.",
    focusEs: "Pasado en primera persona, negativas con didn't + verbo base y was / were.",
    reminder: {
      en: "After didn't the verb goes back to base: I didn't go, I didn't have. And be has its own past: was / were.",
      es: "Después de didn't el verbo vuelve a la base: I didn't go, I didn't have. Y be tiene su propio pasado: was / were.",
    },
    showFullGuide: false,
    instructions: {
      en: "Talk about your day yesterday: what you did, what you didn't do, and how you felt.",
      es: "Habla de tu día de ayer: qué hiciste, qué no hiciste y cómo te sentiste.",
    },
    vocabulary: ["yesterday", "last night", "didn't", "was", "were", "cooked", "went", "took", "studied"],
    lines: [
      { id: "spast2-l1", text: "Yesterday I woke up early and made breakfast.", es: "Ayer me desperté temprano e hice el desayuno.", chunks: ["Yesterday I woke up early", "and made breakfast."] },
      { id: "spast2-l2", text: "I studied English for thirty minutes.", es: "Estudié inglés por treinta minutos.", chunks: ["I studied English", "for thirty minutes."] },
      { id: "spast2-l3", text: "I didn't go to the gym because I was tired.", es: "No fui al gimnasio porque estaba cansado.", chunks: ["I didn't go to the gym", "because I was tired."] },
      { id: "spast2-l4", text: "In the afternoon I took a short break and drank coffee.", es: "En la tarde tomé un descanso corto y me tomé un café.", chunks: ["In the afternoon", "I took a short break", "and drank coffee."] },
      { id: "spast2-l5", text: "I talked to my family for twenty minutes.", es: "Hablé con mi familia veinte minutos.", chunks: ["I talked to my family", "for twenty minutes."] },
      { id: "spast2-l6", text: "I didn't have much free time, but the day was good.", es: "No tuve mucho tiempo libre, pero el día estuvo bien.", chunks: ["I didn't have", "much free time,", "but the day was good."] },
      { id: "spast2-l7", text: "Last night I cooked dinner and watched a movie.", es: "Anoche cociné la cena y vi una película.", chunks: ["Last night I cooked dinner", "and watched a movie."] },
      { id: "spast2-l8", text: "I went to bed at eleven and I slept well.", es: "Me acosté a las once y dormí bien.", chunks: ["I went to bed at eleven", "and I slept well."] },
    ],
    questions: [
      { id: "spast2-q1", question: "What did you do yesterday morning?", questionEs: "¿Qué hiciste ayer en la mañana?", hint: "Yesterday morning I…", hintEs: "Empieza con la expresión de tiempo." },
      { id: "spast2-q2", question: "What did you eat yesterday?", questionEs: "¿Qué comiste ayer?", hint: "I ate… / I had…", hintEs: "eat → ate, have → had." },
      { id: "spast2-q3", question: "What didn't you do yesterday?", questionEs: "¿Qué no hiciste ayer?", hint: "I didn't…", hintEs: "didn't + verbo base, nunca didn't went." },
      { id: "spast2-q4", question: "How long did you study or work yesterday?", questionEs: "¿Cuánto tiempo estudiaste o trabajaste ayer?", hint: "I studied for…", hintEs: "Usa for + tiempo." },
      { id: "spast2-q5", question: "Who did you talk to last night?", questionEs: "¿Con quién hablaste anoche?", hint: "I talked to…", hintEs: "talk → talked." },
      { id: "spast2-q6", question: "How were you at the end of the day?", questionEs: "¿Cómo estabas al final del día?", hint: "I was…", hintEs: "Usa was + adjetivo." },
    ],
    finalPrompt: {
      question: "Tell me about your day yesterday. What did you do, what didn't you do, and how did you feel?",
      questionEs: "Cuéntame tu día de ayer. ¿Qué hiciste, qué no hiciste y cómo te sentiste?",
      tips: {
        en: "Use at least one negative with didn't + base verb, one was / were sentence, and both regular and irregular verbs.",
        es: "Usa al menos una negativa con didn't + verbo base, una oración con was / were, y verbos regulares e irregulares.",
      },
    },
    grammarGoals: [
      "first person simple past with a mix of regular and irregular verbs",
      "negatives with didn't + base verb (never didn't went / didn't had)",
      "was / were for states and feelings",
    ],
  },
  {
    number: 3,
    id: "spast-3-valeria",
    title: "Valeria's happy moment",
    titleEs: "El momento feliz de Valeria",
    person: "third",
    character: "Valeria",
    focus: "Telling someone else's story in the past with was / were and sequence words.",
    focusEs: "Contar la historia de otra persona en pasado con was / were y palabras de secuencia.",
    reminder: {
      en: "Order the story: first, then, after that, finally. Use was / were for feelings and situations.",
      es: "Ordena la historia: first, then, after that, finally. Usa was / were para sentimientos y situaciones.",
    },
    showFullGuide: false,
    instructions: {
      en: "Valeria graduated last December. Tell the story of that happy day.",
      es: "Valeria se graduó en diciembre pasado. Cuenta la historia de ese día feliz.",
    },
    vocabulary: ["last December", "graduated", "was proud", "were there", "took photos", "surprised", "celebrated", "finally"],
    lines: [
      { id: "spast3-l1", text: "Valeria graduated from university last December.", es: "Valeria se graduó de la universidad en diciembre pasado.", chunks: ["Valeria graduated", "from university", "last December."] },
      { id: "spast3-l2", text: "Her parents traveled six hours to see the ceremony.", es: "Sus papás viajaron seis horas para ver la ceremonia.", chunks: ["Her parents traveled", "six hours", "to see the ceremony."] },
      { id: "spast3-l3", text: "She was very nervous in the morning.", es: "Ella estaba muy nerviosa en la mañana.", chunks: ["She was very nervous", "in the morning."] },
      { id: "spast3-l4", text: "Then she walked on the stage and received her diploma.", es: "Luego caminó al escenario y recibió su diploma.", chunks: ["Then she walked", "on the stage", "and received her diploma."] },
      { id: "spast3-l5", text: "All her friends were there and they took a lot of photos.", es: "Todos sus amigos estaban ahí y tomaron muchas fotos.", chunks: ["All her friends were there", "and they took", "a lot of photos."] },
      { id: "spast3-l6", text: "After that, her brother gave her a surprise gift.", es: "Después de eso, su hermano le dio un regalo sorpresa.", chunks: ["After that,", "her brother gave her", "a surprise gift."] },
      { id: "spast3-l7", text: "They celebrated with dinner at her favorite restaurant.", es: "Celebraron con una cena en su restaurante favorito.", chunks: ["They celebrated", "with dinner", "at her favorite restaurant."] },
      { id: "spast3-l8", text: "Finally she went home and she felt proud of herself.", es: "Finalmente se fue a casa y se sintió orgullosa de sí misma.", chunks: ["Finally she went home", "and she felt proud", "of herself."] },
    ],
    questions: [
      { id: "spast3-q1", question: "When did Valeria graduate?", questionEs: "¿Cuándo se graduó Valeria?", hint: "She graduated…", hintEs: "Di la expresión de tiempo." },
      { id: "spast3-q2", question: "How did she feel in the morning?", questionEs: "¿Cómo se sentía en la mañana?", hint: "She was…", hintEs: "Usa was + adjetivo." },
      { id: "spast3-q3", question: "Who was there with her?", questionEs: "¿Quién estaba ahí con ella?", hint: "Her… were there.", hintEs: "Con plural usas were." },
      { id: "spast3-q4", question: "What did her brother give her?", questionEs: "¿Qué le dio su hermano?", hint: "He gave her…", hintEs: "give → gave." },
      { id: "spast3-q5", question: "How did they celebrate?", questionEs: "¿Cómo celebraron?", hint: "They celebrated with…", hintEs: "celebrate → celebrated." },
      { id: "spast3-q6", question: "Why was that day special for her?", questionEs: "¿Por qué ese día fue especial para ella?", hint: "Because she…", hintEs: "Da la razón con because." },
    ],
    finalPrompt: {
      question: "Tell me the story of Valeria's graduation day, from the morning to the celebration.",
      questionEs: "Cuéntame la historia del día de graduación de Valeria, desde la mañana hasta la celebración.",
      tips: {
        en: "Order the story with first, then, after that, finally, and use was / were at least twice.",
        es: "Ordena la historia con first, then, after that, finally, y usa was / were al menos dos veces.",
      },
    },
    grammarGoals: [
      "third person narrative past mixing regular and irregular verbs",
      "was / were for feelings, people and situations",
      "sequence words: first, then, after that, finally",
    ],
  },
  {
    number: 4,
    id: "spast-4-happy-moment",
    title: "Tell me about a happy moment",
    titleEs: "Cuéntame un momento feliz",
    person: "first",
    character: null,
    focus: "First person personal story: what happened, who was there and why it mattered.",
    focusEs: "Historia personal en primera persona: qué pasó, quién estaba y por qué fue importante.",
    reminder: {
      en: "Say when it happened, what you did, and how you felt: I was so happy because…",
      es: "Di cuándo pasó, qué hiciste y cómo te sentiste: I was so happy because…",
    },
    showFullGuide: false,
    instructions: {
      en: "Think of a real happy moment in your life and tell the story in the past.",
      es: "Piensa en un momento feliz real de tu vida y cuenta la historia en pasado.",
    },
    vocabulary: ["a few years ago", "when I was", "I felt", "we laughed", "I remember", "it was", "because", "the best part"],
    lines: [
      { id: "spast4-l1", text: "One of my happiest moments happened three years ago.", es: "Uno de mis momentos más felices pasó hace tres años.", chunks: ["One of my happiest moments", "happened", "three years ago."] },
      { id: "spast4-l2", text: "I got my first job in a call center.", es: "Conseguí mi primer trabajo en un call center.", chunks: ["I got my first job", "in a call center."] },
      { id: "spast4-l3", text: "I remember I called my mom immediately.", es: "Recuerdo que llamé a mi mamá de inmediato.", chunks: ["I remember", "I called my mom", "immediately."] },
      { id: "spast4-l4", text: "She was so proud, and we both cried a little.", es: "Ella estaba muy orgullosa y los dos lloramos un poco.", chunks: ["She was so proud,", "and we both cried", "a little."] },
      { id: "spast4-l5", text: "That night my friends came to my house.", es: "Esa noche mis amigos vinieron a mi casa.", chunks: ["That night", "my friends came", "to my house."] },
      { id: "spast4-l6", text: "We ordered pizza, we laughed and we talked for hours.", es: "Pedimos pizza, nos reímos y hablamos por horas.", chunks: ["We ordered pizza,", "we laughed", "and we talked for hours."] },
      { id: "spast4-l7", text: "The best part was the feeling of finally getting an opportunity.", es: "La mejor parte fue la sensación de por fin tener una oportunidad.", chunks: ["The best part was", "the feeling of finally", "getting an opportunity."] },
      { id: "spast4-l8", text: "I never forgot that day because it changed my life.", es: "Nunca olvidé ese día porque cambió mi vida.", chunks: ["I never forgot that day", "because it changed my life."] },
    ],
    questions: [
      { id: "spast4-q1", question: "When did this happy moment happen?", questionEs: "¿Cuándo pasó ese momento feliz?", hint: "It happened…", hintEs: "Usa ago, last year o when I was…" },
      { id: "spast4-q2", question: "What happened exactly?", questionEs: "¿Qué pasó exactamente?", hint: "I got… / I won… / I met…", hintEs: "Usa verbos irregulares en pasado." },
      { id: "spast4-q3", question: "Who was with you that day?", questionEs: "¿Quién estaba contigo ese día?", hint: "My… was / were with me.", hintEs: "was para singular, were para plural." },
      { id: "spast4-q4", question: "How did you feel in that moment?", questionEs: "¿Cómo te sentiste en ese momento?", hint: "I felt… / I was…", hintEs: "feel → felt." },
      { id: "spast4-q5", question: "What did you do to celebrate?", questionEs: "¿Qué hiciste para celebrar?", hint: "We celebrated…", hintEs: "Cuenta dos acciones." },
      { id: "spast4-q6", question: "Why do you still remember that day?", questionEs: "¿Por qué todavía recuerdas ese día?", hint: "Because it…", hintEs: "Da la razón con because." },
    ],
    finalPrompt: {
      question: "Tell me about a happy moment in your life. What happened, who was there, and why was it special?",
      questionEs: "Cuéntame un momento feliz de tu vida. ¿Qué pasó, quién estaba y por qué fue especial?",
      tips: {
        en: "Start with when it happened, tell three actions in order, and finish with how you felt.",
        es: "Empieza diciendo cuándo pasó, cuenta tres acciones en orden y termina con cómo te sentiste.",
      },
    },
    grammarGoals: [
      "personal narrative in first person simple past",
      "irregular verbs: got, came, felt, went, told, made",
      "was / were plus because for feelings and reasons",
    ],
  },
  {
    number: 5,
    id: "spast-5-oscar-trip",
    title: "Óscar's last trip",
    titleEs: "El último viaje de Óscar",
    person: "third",
    character: "Óscar",
    focus: "Free production in the past: a complete trip story with questions using did.",
    focusEs: "Producción libre en pasado: una historia completa de viaje con preguntas usando did.",
    reminder: {
      en: "In questions the verb stays in base form: Where did he go? What did they eat?",
      es: "En las preguntas el verbo va en forma base: Where did he go? What did they eat?",
    },
    showFullGuide: false,
    instructions: {
      en: "Here are the facts of Óscar's last trip. Build the story yourself in the past — there is no model paragraph this time.",
      es: "Aquí están los datos del último viaje de Óscar. Construye tú la historia en pasado: esta vez no hay párrafo modelo.",
    },
    vocabulary: ["last summer", "flew", "stayed", "visited", "tried", "bought", "lost", "came back"],
    factSheet: [
      { en: "Last summer · five days in Guatemala · with his sister", es: "El verano pasado · cinco días en Guatemala · con su hermana" },
      { en: "They flew on Friday morning and stayed in a small hotel.", es: "Volaron el viernes en la mañana y se quedaron en un hotel pequeño." },
      { en: "They visited Antigua and took a boat on Lake Atitlán.", es: "Visitaron Antigua y tomaron un bote en el Lago de Atitlán." },
      { en: "He tried new food and bought gifts for his parents.", es: "Probó comida nueva y compró regalos para sus papás." },
      { en: "Problem: he lost his phone on the second day.", es: "Problema: perdió su teléfono el segundo día." },
      { en: "They came back on Wednesday and he said it was the best trip of the year.", es: "Regresaron el miércoles y él dijo que fue el mejor viaje del año." },
    ],
    lines: [
      { id: "spast5-l1", text: "Óscar traveled to Guatemala last summer.", es: "Óscar viajó a Guatemala el verano pasado.", chunks: ["Óscar traveled", "to Guatemala", "last summer."] },
      { id: "spast5-l2", text: "He went with his sister for five days.", es: "Fue con su hermana por cinco días.", chunks: ["He went", "with his sister", "for five days."] },
      { id: "spast5-l3", text: "They stayed in a small hotel near the center.", es: "Se quedaron en un hotel pequeño cerca del centro.", chunks: ["They stayed", "in a small hotel", "near the center."] },
      { id: "spast5-l4", text: "They visited Antigua and took a boat on the lake.", es: "Visitaron Antigua y tomaron un bote en el lago.", chunks: ["They visited Antigua", "and took a boat", "on the lake."] },
      { id: "spast5-l5", text: "He tried new food and bought gifts for his parents.", es: "Probó comida nueva y compró regalos para sus papás.", chunks: ["He tried new food", "and bought gifts", "for his parents."] },
      { id: "spast5-l6", text: "He lost his phone, but he didn't lose his good mood.", es: "Perdió su teléfono, pero no perdió su buen humor.", chunks: ["He lost his phone,", "but he didn't lose", "his good mood."] },
      { id: "spast5-l7", text: "The weather wasn't perfect, but the trip was amazing.", es: "El clima no estuvo perfecto, pero el viaje estuvo increíble.", chunks: ["The weather wasn't perfect,", "but the trip was amazing."] },
      { id: "spast5-l8", text: "They came back on Wednesday and he said it was the best trip of the year.", es: "Regresaron el miércoles y él dijo que fue el mejor viaje del año.", chunks: ["They came back on Wednesday", "and he said it was", "the best trip of the year."] },
    ],
    questions: [
      { id: "spast5-q1", question: "Where did Óscar go last summer?", questionEs: "¿Adónde fue Óscar el verano pasado?", hint: "He went to…", hintEs: "go → went." },
      { id: "spast5-q2", question: "Who did he travel with?", questionEs: "¿Con quién viajó?", hint: "He traveled with…", hintEs: "travel → traveled." },
      { id: "spast5-q3", question: "How long did the trip take?", questionEs: "¿Cuánto duró el viaje?", hint: "It took…", hintEs: "take → took." },
      { id: "spast5-q4", question: "What did they do there?", questionEs: "¿Qué hicieron allá?", hint: "They visited… and took…", hintEs: "Cuenta dos actividades." },
      { id: "spast5-q5", question: "What problem did he have?", questionEs: "¿Qué problema tuvo?", hint: "He lost…", hintEs: "lose → lost." },
      { id: "spast5-q6", question: "Why was it a good trip?", questionEs: "¿Por qué fue un buen viaje?", hint: "Because they…", hintEs: "Da la razón con because." },
    ],
    finalPrompt: {
      question: "Tell the story of Óscar's last trip: where he went, what he did, what problem he had, and how it ended.",
      questionEs: "Cuenta la historia del último viaje de Óscar: adónde fue, qué hizo, qué problema tuvo y cómo terminó.",
      tips: {
        en: "Use the facts, mix regular and irregular verbs, include one negative with didn't, and close with was / were.",
        es: "Usa los datos, mezcla verbos regulares e irregulares, incluye una negativa con didn't y cierra con was / were.",
      },
    },
    grammarGoals: [
      "free narrative past from facts, mixing regular and irregular verbs",
      "questions and negatives with did / didn't + base verb",
      "was / were to describe the trip and the weather",
    ],
  },
];
