import type { ReviewGuideCard } from "@/lib/review-types";

/**
 * "ENTIÉNDELO FÁCIL" — the seven Simple Future basics (will + be going to).
 * Static hand-written content: never generated by AI, reused by every practice
 * (Practice 1 shows it inline in Step 1, practices 2–5 open it on demand).
 */
export const SIMPLE_FUTURE_GUIDE: ReviewGuideCard[] = [
  {
    id: "sf-1-use",
    title: "What it is for",
    titleEs: "Para qué sirve",
    explanation: "The future talks about things that are not real yet: plans, predictions, promises and decisions.",
    explanationEs:
      "El futuro habla de lo que todavía no pasa: planes, predicciones, promesas y decisiones. En inglés hay dos formas principales: be going to y will. Las dos son correctas, pero se usan en momentos distintos.",
    examples: [
      { en: "I am going to study tonight.", es: "Voy a estudiar esta noche." },
      { en: "It will rain tomorrow.", es: "Va a llover mañana." },
      { en: "We are going to travel in December.", es: "Vamos a viajar en diciembre." },
    ],
    check: {
      prompt: "Say one thing you are going to do tomorrow.",
      promptEs: "Di en voz alta una cosa que vas a hacer mañana.",
      answer: "I am going to work tomorrow.",
    },
  },
  {
    id: "sf-2-going-to",
    title: "be going to = plan",
    titleEs: "be going to = plan",
    explanation: "Use am / is / are + going to + base verb for plans you already decided.",
    explanationEs:
      "Usa am / is / are + going to + verbo base para planes que YA decidiste: I am going to, he is going to, they are going to. Nunca quites el verbo be: “I going to study” está mal.",
    examples: [
      { en: "I am going to call my boss at nine.", es: "Voy a llamar a mi jefe a las nueve." },
      { en: "She is going to start a new job.", es: "Ella va a empezar un trabajo nuevo." },
      { en: "They are going to move to another city.", es: "Ellos se van a mudar a otra ciudad." },
    ],
    check: {
      prompt: "Say a plan for this weekend with going to.",
      promptEs: "Di un plan para este fin de semana con going to.",
      answer: "I am going to visit my family this weekend.",
    },
  },
  {
    id: "sf-3-will",
    title: "will = decision, prediction, promise",
    titleEs: "will = decisión, predicción, promesa",
    explanation: "Will + base verb, the same for everybody. No -s, no to.",
    explanationEs:
      "Will + verbo base, igual para todas las personas: I will, he will, they will. No lleva -s ni to: “he will works” y “he will to work” están mal. Se usa para decisiones del momento, predicciones y promesas.",
    examples: [
      { en: "I will help you. (decision now)", es: "Yo te ayudo. (decisión del momento)" },
      { en: "He will be a great teacher. (prediction)", es: "Él va a ser un gran maestro. (predicción)" },
      { en: "I will call you tonight. (promise)", es: "Te llamo esta noche. (promesa)" },
    ],
    check: {
      prompt: "Make one prediction about next year with will.",
      promptEs: "Haz una predicción sobre el próximo año con will.",
      answer: "Next year I will speak better English.",
    },
  },
  {
    id: "sf-4-will-vs-going",
    title: "will vs. going to",
    titleEs: "will vs. going to",
    explanation: "Going to = decided before. Will = decided right now, or something you only think or believe.",
    explanationEs:
      "Going to = ya lo tenías decidido o hay evidencia (look at those clouds, it is going to rain). Will = lo decides en el momento o solo lo crees (I think he will like it). En conversación normal las dos suenan bien; lo importante es la forma correcta.",
    examples: [
      { en: "I am going to study tonight. (plan)", es: "Voy a estudiar esta noche. (plan)" },
      { en: "The phone is ringing — I will answer it. (now)", es: "Está sonando el teléfono: yo contesto. (ahora)" },
      { en: "I think she will pass the interview.", es: "Creo que ella va a pasar la entrevista." },
    ],
    check: {
      prompt: "Say one plan with going to and one opinion with I think… will.",
      promptEs: "Di un plan con going to y una opinión con I think… will.",
      answer: "I am going to practice tonight. I think I will improve fast.",
    },
  },
  {
    id: "sf-5-negative",
    title: "Negatives",
    titleEs: "Negativas",
    explanation: "won't = will not. For going to, the not goes with am / is / are.",
    explanationEs:
      "Con will: I won't work (won't = will not). Con going to el not va con el verbo be: I am not going to work, she isn't going to come, they aren't going to travel. El verbo siempre queda en forma base.",
    examples: [
      { en: "I won't be late again.", es: "No voy a llegar tarde otra vez." },
      { en: "She isn't going to work on Sunday.", es: "Ella no va a trabajar el domingo." },
      { en: "We aren't going to buy a car this year.", es: "No vamos a comprar carro este año." },
    ],
    check: {
      prompt: "Say one thing you won't do next week.",
      promptEs: "Di una cosa que no harás la próxima semana.",
      answer: "I won't miss my English practice next week.",
    },
  },
  {
    id: "sf-6-questions",
    title: "Questions",
    titleEs: "Preguntas",
    explanation: "Will + subject + base verb. Am / is / are + subject + going to + base verb.",
    explanationEs:
      "Con will: Will you help me? What will you do? Con going to el be va primero: Are you going to study? What is she going to do? Respuestas cortas: Yes, I will / No, I won't · Yes, I am / No, I'm not.",
    examples: [
      { en: "Will you call me tomorrow? — Yes, I will.", es: "¿Me llamarás mañana? — Sí." },
      { en: "What are you going to do this weekend?", es: "¿Qué vas a hacer este fin de semana?" },
      { en: "How long is he going to stay?", es: "¿Cuánto tiempo se va a quedar?" },
    ],
    check: {
      prompt: "Ask two future questions: one with will and one with going to.",
      promptEs: "Haz dos preguntas de futuro: una con will y otra con going to.",
      answer: "Will you come with me? What are you going to do tonight?",
    },
  },
  {
    id: "sf-7-time",
    title: "Future time words",
    titleEs: "Palabras de tiempo del futuro",
    explanation: "Tomorrow, tonight, next week, next month, in two years, this weekend, later.",
    explanationEs:
      "Estas palabras piden futuro: tomorrow, tonight, next week, next month, next year, in two years, this weekend, later, soon. Ponlas al inicio o al final: Next month I am going to travel. / I am going to travel next month.",
    examples: [
      { en: "Tomorrow I am going to start early.", es: "Mañana voy a empezar temprano." },
      { en: "In two years I will have a better job.", es: "En dos años tendré un mejor trabajo." },
      { en: "We will talk about it later.", es: "Hablaremos de eso más tarde." },
    ],
    check: {
      prompt: "Say two plans: one for tonight and one for next year.",
      promptEs: "Di dos planes: uno para esta noche y uno para el próximo año.",
      answer: "Tonight I am going to rest. Next year I will study more.",
    },
  },
];

/** The four errors this module keeps correcting. */
export const SIMPLE_FUTURE_COMMON_ERRORS: { wrong: string; right: string; es: string }[] = [
  { wrong: "I going to study", right: "I am going to study", es: "Going to siempre necesita am / is / are." },
  { wrong: "He will works tomorrow", right: "He will work tomorrow", es: "Después de will el verbo va en forma base." },
  { wrong: "She will to call you", right: "She will call you", es: "Will nunca lleva to." },
  { wrong: "They no going to come", right: "They aren't going to come", es: "La negativa va con el verbo be: isn't / aren't going to." },
];
