import type { ReviewGuideCard } from "@/lib/review-types";

/**
 * "ENTIÉNDELO FÁCIL" — the seven basics of tag questions.
 * Static hand-written content: never generated by AI.
 */
export const TAG_QUESTIONS_GUIDE: ReviewGuideCard[] = [
  {
    id: "tag-1-use",
    title: "What a tag question is",
    titleEs: "Qué es una tag question",
    explanation: "A short question at the end to confirm something: You ate pizza, didn't you?",
    explanationEs:
      "Es la pregunta corta al final de una oración para confirmar algo, como el “¿verdad?” o “¿no?” del español. You ate pizza, didn't you? = Comiste pizza, ¿verdad? Suena natural y educado en conversación.",
    examples: [
      { en: "You ate pizza, didn't you?", es: "Comiste pizza, ¿verdad?" },
      { en: "She works here, doesn't she?", es: "Ella trabaja aquí, ¿verdad?" },
      { en: "It's cold today, isn't it?", es: "Hace frío hoy, ¿no?" },
    ],
    check: {
      prompt: "Add a tag: You speak Spanish, …?",
      promptEs: "Agrega la tag: You speak Spanish, …?",
      answer: "don't you?",
    },
  },
  {
    id: "tag-2-positive",
    title: "Positive sentence → negative tag",
    titleEs: "Oración positiva → tag negativa",
    explanation: "You ate pizza, didn't you? She is happy, isn't she?",
    explanationEs:
      "Regla de oro: si la oración es POSITIVA, la tag es NEGATIVA. Repites el auxiliar en negativo + el pronombre. You ate pizza → didn't you? He can drive → can't he?",
    examples: [
      { en: "You finished the report, didn't you?", es: "Terminaste el reporte, ¿verdad?" },
      { en: "He can drive, can't he?", es: "Él puede manejar, ¿verdad?" },
      { en: "They have arrived, haven't they?", es: "Ya llegaron, ¿verdad?" },
    ],
    check: {
      prompt: "Add a tag: They will call, …?",
      promptEs: "Agrega la tag: They will call, …?",
      answer: "won't they?",
    },
  },
  {
    id: "tag-3-negative",
    title: "Negative sentence → positive tag",
    titleEs: "Oración negativa → tag positiva",
    explanation: "You didn't eat pizza, did you? She isn't here, is she?",
    explanationEs:
      "Al revés también: si la oración es NEGATIVA, la tag es POSITIVA. You didn't call, did you? He isn't ready, is he? Nunca pongas dos negativos: “didn't you?” después de una negativa está mal.",
    examples: [
      { en: "You didn't call the client, did you?", es: "No llamaste al cliente, ¿verdad?" },
      { en: "She isn't working today, is she?", es: "Ella no está trabajando hoy, ¿verdad?" },
      { en: "They can't come, can they?", es: "Ellos no pueden venir, ¿verdad?" },
    ],
    check: {
      prompt: "Add a tag: He doesn't smoke, …?",
      promptEs: "Agrega la tag: He doesn't smoke, …?",
      answer: "does he?",
    },
  },
  {
    id: "tag-4-be",
    title: "Tags with the verb BE",
    titleEs: "Tags con el verbo BE",
    explanation: "It's Monday, isn't it? They were late, weren't they?",
    explanationEs:
      "Si la oración usa am / is / are / was / were, repites ese mismo verbo en la tag. It's expensive, isn't it? You were tired, weren't you? Con I am la tag especial es aren't I? (You are late, aren't you? / I'm late, aren't I?).",
    examples: [
      { en: "The meeting is at three, isn't it?", es: "La reunión es a las tres, ¿verdad?" },
      { en: "You were at the office, weren't you?", es: "Estabas en la oficina, ¿verdad?" },
      { en: "I'm next, aren't I?", es: "Sigo yo, ¿verdad?" },
    ],
    check: {
      prompt: "Add a tag: She was busy, …?",
      promptEs: "Agrega la tag: She was busy, …?",
      answer: "wasn't she?",
    },
  },
  {
    id: "tag-5-do",
    title: "Tags with do, does and did",
    titleEs: "Tags con do, does y did",
    explanation: "When there is no auxiliary, use do / does / did.",
    explanationEs:
      "Si la oración no tiene auxiliar (no hay be, can, will, have), usas do / does / did. Presente: You work here, don't you? / She lives here, doesn't she? Pasado: You ate pizza, didn't you? El tiempo de la tag es el mismo del verbo.",
    examples: [
      { en: "You work on weekends, don't you?", es: "Trabajas los fines de semana, ¿verdad?" },
      { en: "She lives near the office, doesn't she?", es: "Ella vive cerca de la oficina, ¿verdad?" },
      { en: "They started at eight, didn't they?", es: "Empezaron a las ocho, ¿verdad?" },
    ],
    check: {
      prompt: "Add a tag: You called her, …?",
      promptEs: "Agrega la tag: You called her, …?",
      answer: "didn't you?",
    },
  },
  {
    id: "tag-6-special",
    title: "Special cases",
    titleEs: "Casos especiales",
    explanation: "Let's go, shall we? Close the door, will you? There is time, isn't there?",
    explanationEs:
      "Cinco que se memorizan: 1) Let's go, shall we? 2) Orden: Close the door, will you? 3) There is a problem, isn't there? 4) Nobody / everybody usan they: Everybody came, didn't they? 5) I'm right, aren't I?",
    examples: [
      { en: "Let's take a break, shall we?", es: "Tomemos un descanso, ¿va?" },
      { en: "Send the email, will you?", es: "Envía el correo, ¿sí?" },
      { en: "There isn't a meeting today, is there?", es: "No hay reunión hoy, ¿verdad?" },
    ],
    check: {
      prompt: "Add a tag: Let's start, …?",
      promptEs: "Agrega la tag: Let's start, …?",
      answer: "shall we?",
    },
  },
  {
    id: "tag-7-answer",
    title: "Intonation and answers",
    titleEs: "Entonación y respuestas",
    explanation: "Voice down = I'm sure. Voice up = I'm really asking. Answer with Yes/No + auxiliary.",
    explanationEs:
      "Si bajas la voz al final, solo buscas confirmación (ya lo sabes). Si subes la voz, de verdad estás preguntando. Se responde corto: Yes, I did. / No, I didn't. / Yes, she is. Y ojo: si la pregunta es negativa, responde según el hecho, no según la forma.",
    examples: [
      { en: "You're from Guatemala, aren't you? — Yes, I am.", es: "Eres de Guatemala, ¿verdad? — Sí, lo soy." },
      { en: "You didn't finish, did you? — No, I didn't.", es: "No terminaste, ¿verdad? — No, no terminé." },
      { en: "She called you, didn't she? — Yes, she did.", es: "Ella te llamó, ¿verdad? — Sí, me llamó." },
    ],
    check: {
      prompt: "Answer: You work here, don't you?",
      promptEs: "Responde: You work here, don't you?",
      answer: "Yes, I do. / No, I don't.",
    },
  },
];

export const TAG_QUESTIONS_COMMON_ERRORS: { wrong: string; right: string; es: string }[] = [
  { wrong: "You ate pizza, don't you?", right: "You ate pizza, didn't you?", es: "La tag copia el tiempo del verbo: pasado → didn't." },
  { wrong: "She isn't here, isn't she?", right: "She isn't here, is she?", es: "Después de una negativa la tag es positiva." },
  { wrong: "You are ready, no?", right: "You are ready, aren't you?", es: "En inglés no se usa “no?”; se repite el auxiliar." },
  { wrong: "I'm late, amn't I?", right: "I'm late, aren't I?", es: "Con I am la tag correcta es aren't I." },
  { wrong: "Let's go, don't we?", right: "Let's go, shall we?", es: "Con Let's la tag siempre es shall we." },
  { wrong: "He can swim, can he?", right: "He can swim, can't he?", es: "Positiva → tag negativa: can't he." },
];
