import type { ReviewGuideCard, ReviewModule } from "@/lib/review-types";

export const USED_TO_GUIDE: ReviewGuideCard[] = [
  { id:"uto-1-past", title:"used to + base verb", titleEs:"used to + verbo base", explanation:"Use used to for a repeated past habit or state that is no longer true.", explanationEs:"Usa used to para un hábito o estado repetido del pasado que ya cambió.", examples:[{en:"I used to wake up late.",es:"Antes me despertaba tarde."},{en:"She used to live downtown.",es:"Antes ella vivía en el centro."},{en:"They used to take the bus.",es:"Antes tomaban el autobús."}], check:{prompt:"Say a past habit that changed.",promptEs:"Di un hábito pasado que cambió.",answer:"I used to wake up late."} },
  { id:"uto-2-questions", title:"didn't use to / Did … use to?", titleEs:"didn't use to / Did … use to?", explanation:"After did or didn't, write and say use to without -d.", explanationEs:"Después de did o didn't, usa use to sin -d.", examples:[{en:"I didn't use to exercise.",es:"Antes no hacía ejercicio."},{en:"Did you use to cook?",es:"¿Antes cocinabas?"},{en:"Where did she use to work?",es:"¿Dónde trabajaba antes?"}], check:{prompt:"Correct: Did he used to drive?",promptEs:"Corrige: Did he used to drive?",answer:"Did he use to drive?"} },
  { id:"uto-3-be", title:"be used to + -ing", titleEs:"be used to + -ing", explanation:"Be used to means that something is already normal or familiar.", explanationEs:"Be used to significa estar acostumbrado: algo ya es normal o familiar.", examples:[{en:"I am used to working at night.",es:"Estoy acostumbrado a trabajar de noche."},{en:"She is used to busy calls.",es:"Ella está acostumbrada a llamadas ocupadas."},{en:"They were used to commuting.",es:"Estaban acostumbrados a viajar al trabajo."}], check:{prompt:"Say that night work is normal for you.",promptEs:"Di que trabajar de noche es normal para ti.",answer:"I am used to working at night."} },
  { id:"uto-4-get", title:"get used to + -ing", titleEs:"get used to + -ing", explanation:"Get used to describes the process of becoming comfortable with something new.", explanationEs:"Get used to describe el proceso de acostumbrarse a algo nuevo.", examples:[{en:"I am getting used to waking up early.",es:"Me estoy acostumbrando a levantarme temprano."},{en:"He got used to the rain.",es:"Él se acostumbró a la lluvia."},{en:"You will get used to speaking English.",es:"Te acostumbrarás a hablar inglés."}], check:{prompt:"Describe one new routine you are adapting to.",promptEs:"Describe una rutina nueva a la que te estás adaptando.",answer:"I am getting used to waking up early."} },
  { id:"uto-5-ing", title:"Why the -ing form?", titleEs:"¿Por qué usamos -ing?", explanation:"In be/get used to, to is a preposition, so a following action uses the -ing form.", explanationEs:"En be/get used to, to es una preposición; por eso la acción siguiente lleva -ing.", examples:[{en:"She is used to speaking English.",es:"Ella está acostumbrada a hablar inglés."},{en:"We got used to cooking at home.",es:"Nos acostumbramos a cocinar en casa."},{en:"He isn't used to driving in rain.",es:"Él no está acostumbrado a conducir bajo la lluvia."}], check:{prompt:"Correct: I am used to work early.",promptEs:"Corrige: I am used to work early.",answer:"I am used to working early."} },
  { id:"uto-6-difference", title:"Past habit or familiar now?", titleEs:"¿Hábito pasado o algo familiar ahora?", explanation:"Used to + verb is about the past. Be used to + -ing describes what feels normal now.", explanationEs:"Used to + verbo habla del pasado. Be used to + -ing describe lo que ya se siente normal.", examples:[{en:"I used to work at night.",es:"Antes trabajaba de noche."},{en:"I am used to working at night.",es:"Estoy acostumbrado a trabajar de noche."},{en:"I am getting used to working at night.",es:"Me estoy acostumbrando a trabajar de noche."}], check:{prompt:"Choose the form for something that is becoming familiar.",promptEs:"Elige la forma para algo que se está volviendo familiar.",answer:"I am getting used to it."} },
  { id:"uto-7-time", title:"Match the time and meaning", titleEs:"Conecta el tiempo y el significado", explanation:"Use used to for before, be used to for an established state, and get used to for change over time.", explanationEs:"Usa used to para antes, be used to para un estado establecido y get used to para un cambio gradual.", examples:[{en:"Sofia used to feel nervous.",es:"Antes Sofía se sentía nerviosa."},{en:"Now she is used to leading meetings.",es:"Ahora está acostumbrada a dirigir reuniones."},{en:"At first, she had to get used to speaking online.",es:"Al principio tuvo que acostumbrarse a hablar en línea."}], check:{prompt:"Describe one before, during and now change.",promptEs:"Describe un cambio: antes, durante y ahora.",answer:"I used to feel nervous, but I got used to speaking and now I am used to it."} },
];

export const USED_TO_COMMON_ERRORS: ReviewModule["commonErrors"] = [
  {wrong:"I use to wake up late.",right:"I used to wake up late.",es:"En afirmativo pasado usa used to."},
  {wrong:"Did you used to work here?",right:"Did you use to work here?",es:"Después de did usa use to sin -d."},
  {wrong:"I didn't used to cook.",right:"I didn't use to cook.",es:"Después de didn't usa use to."},
  {wrong:"I am used to work at night.",right:"I am used to working at night.",es:"Después de be used to, el verbo lleva -ing."},
  {wrong:"I am get used to the schedule.",right:"I am getting used to the schedule.",es:"Para un proceso actual usa am/is/are getting used to."},
  {wrong:"She used to working from home.",right:"She used to work from home.",es:"Used to para hábito pasado lleva verbo base."},
];