/** 100 most common everyday phrasal verbs, present + past, with Spanish meaning and an example in each tense. */
export type PhrasalVerb = {
  phrase: string;
  past: string;
  es: string;
  example: string;
  pastExample: string;
};

export const PHRASAL_VERBS: PhrasalVerb[] = [
  { phrase: "get up", past: "got up", es: "levantarse", example: "I get up at six every morning.", pastExample: "I got up early yesterday." },
  { phrase: "wake up", past: "woke up", es: "despertarse", example: "She wakes up before the alarm rings.", pastExample: "She woke up late this morning." },
  { phrase: "get dressed up", past: "got dressed up", es: "arreglarse / vestirse elegante", example: "They get dressed up for special dinners.", pastExample: "They got dressed up for the wedding." },
  { phrase: "get along", past: "got along", es: "llevarse bien", example: "I get along with all my coworkers.", pastExample: "I got along with my new boss." },
  { phrase: "get back", past: "got back", es: "regresar", example: "He gets back from work at seven.", pastExample: "He got back home very late." },
  { phrase: "get in", past: "got in", es: "entrar / subir (a un carro)", example: "We get in the car and drive to school.", pastExample: "We got in the car quickly." },
  { phrase: "get off", past: "got off", es: "bajarse (de un bus)", example: "I get off the bus at the second stop.", pastExample: "I got off the bus at the mall." },
  { phrase: "get on", past: "got on", es: "subirse (a un bus)", example: "She gets on the train at eight.", pastExample: "She got on the wrong bus." },
  { phrase: "get over", past: "got over", es: "superar", example: "He gets over problems very quickly.", pastExample: "He got over the flu in a week." },
  { phrase: "get together", past: "got together", es: "reunirse", example: "We get together every Friday night.", pastExample: "We got together last weekend." },
  { phrase: "give up", past: "gave up", es: "rendirse / dejar de hacer algo", example: "I never give up when the class is hard.", pastExample: "I never gave up on my dream." },
  { phrase: "give back", past: "gave back", es: "devolver", example: "She gives back the money on Monday.", pastExample: "She gave back the book yesterday." },
  { phrase: "look for", past: "looked for", es: "buscar", example: "I look for my keys every morning.", pastExample: "I looked for my phone everywhere." },
  { phrase: "look after", past: "looked after", es: "cuidar", example: "He looks after his little brother.", pastExample: "He looked after his sister all day." },
  { phrase: "look up", past: "looked up", es: "buscar información", example: "I look up new words in the dictionary.", pastExample: "I looked up the word online." },
  { phrase: "look forward to", past: "looked forward to", es: "tener ganas de / esperar con ilusión", example: "We look forward to the weekend.", pastExample: "We looked forward to the trip." },
  { phrase: "look out", past: "looked out", es: "tener cuidado", example: "You look out for cars on that street.", pastExample: "He looked out for the cars." },
  { phrase: "take off", past: "took off", es: "quitarse / despegar", example: "I take off my shoes at the door.", pastExample: "The plane took off on time." },
  { phrase: "take out", past: "took out", es: "sacar", example: "He takes out the trash every night.", pastExample: "He took out the trash last night." },
  { phrase: "take care of", past: "took care of", es: "encargarse de / cuidar", example: "She takes care of the customers.", pastExample: "She took care of her mom." },
  { phrase: "take over", past: "took over", es: "tomar el control", example: "The manager takes over when we are busy.", pastExample: "She took over the project." },
  { phrase: "put on", past: "put on", es: "ponerse (ropa)", example: "I put on my jacket before I leave.", pastExample: "I put on my uniform at seven." },
  { phrase: "put off", past: "put off", es: "posponer", example: "They put off the meeting until Friday.", pastExample: "They put off the game because of rain." },
  { phrase: "put away", past: "put away", es: "guardar", example: "She puts away the dishes after dinner.", pastExample: "She put away her clothes." },
  { phrase: "put up with", past: "put up with", es: "aguantar / soportar", example: "I put up with the noise at work.", pastExample: "I put up with the noise all day." },
  { phrase: "turn on", past: "turned on", es: "encender", example: "He turns on the computer at eight.", pastExample: "He turned on the TV last night." },
  { phrase: "turn off", past: "turned off", es: "apagar", example: "I turn off the lights before bed.", pastExample: "I turned off my phone in class." },
  { phrase: "turn up", past: "turned up", es: "subir el volumen / aparecer", example: "She turns up the music in the car.", pastExample: "She turned up late to the party." },
  { phrase: "turn down", past: "turned down", es: "bajar el volumen / rechazar", example: "I turn down the offer because it is far.", pastExample: "I turned down the job offer." },
  { phrase: "turn around", past: "turned around", es: "dar la vuelta", example: "We turn around and go back home.", pastExample: "We turned around at the corner." },
  { phrase: "come back", past: "came back", es: "volver", example: "He comes back at five o'clock.", pastExample: "He came back from Mexico on Sunday." },
  { phrase: "come in", past: "came in", es: "entrar", example: "Customers come in all day long.", pastExample: "A customer came in at nine." },
  { phrase: "come over", past: "came over", es: "venir a visitar", example: "My friends come over on Sundays.", pastExample: "My friends came over last night." },
  { phrase: "come up with", past: "came up with", es: "ocurrírsele una idea", example: "She comes up with great ideas.", pastExample: "She came up with a great plan." },
  { phrase: "go on", past: "went on", es: "continuar / suceder", example: "The class goes on for two hours.", pastExample: "The meeting went on for hours." },
  { phrase: "go out", past: "went out", es: "salir", example: "We go out for dinner on Saturdays.", pastExample: "We went out last Friday." },
  { phrase: "go back", past: "went back", es: "regresar", example: "I go back to the office after lunch.", pastExample: "I went back home after work." },
  { phrase: "go over", past: "went over", es: "repasar", example: "He goes over his notes before the test.", pastExample: "He went over his notes yesterday." },
  { phrase: "go through", past: "went through", es: "pasar por / revisar", example: "She goes through her email every morning.", pastExample: "She went through a hard time." },
  { phrase: "run out of", past: "ran out of", es: "quedarse sin", example: "We run out of coffee every week.", pastExample: "We ran out of milk this morning." },
  { phrase: "run into", past: "ran into", es: "encontrarse por casualidad", example: "I run into my neighbor at the store.", pastExample: "I ran into an old friend at the mall." },
  { phrase: "run late", past: "ran late", es: "ir tarde", example: "He runs late when traffic is bad.", pastExample: "He ran late to the meeting." },
  { phrase: "call back", past: "called back", es: "devolver la llamada", example: "I call back the client in ten minutes.", pastExample: "I called back my mom at noon." },
  { phrase: "call off", past: "called off", es: "cancelar", example: "They call off the trip when it rains.", pastExample: "They called off the game yesterday." },
  { phrase: "hang up", past: "hung up", es: "colgar el teléfono", example: "She hangs up after she says goodbye.", pastExample: "She hung up the phone angrily." },
  { phrase: "hang out", past: "hung out", es: "pasar el rato", example: "We hang out at the park on Sundays.", pastExample: "We hung out all afternoon." },
  { phrase: "pick up", past: "picked up", es: "recoger", example: "I pick up my daughter at three.", pastExample: "I picked up my son from school." },
  { phrase: "drop off", past: "dropped off", es: "dejar (a alguien o algo)", example: "He drops off the kids at school.", pastExample: "He dropped off the kids at seven." },
  { phrase: "check in", past: "checked in", es: "registrarse", example: "Guests check in at the front desk.", pastExample: "We checked in at the hotel at two." },
  { phrase: "check out", past: "checked out", es: "revisar / dejar el hotel", example: "We check out at eleven in the morning.", pastExample: "We checked out on Sunday." },
  { phrase: "find out", past: "found out", es: "averiguar", example: "I find out the answer online.", pastExample: "I found out the truth yesterday." },
  { phrase: "figure out", past: "figured out", es: "resolver / entender", example: "She figures out the problem alone.", pastExample: "She figured out the answer." },
  { phrase: "work out", past: "worked out", es: "hacer ejercicio / resultar bien", example: "I work out three times a week.", pastExample: "I worked out this morning." },
  { phrase: "fill out", past: "filled out", es: "llenar (un formulario)", example: "You fill out the form with your name.", pastExample: "I filled out the application." },
  { phrase: "fill in", past: "filled in", es: "completar", example: "He fills in the missing information.", pastExample: "He filled in the blanks." },
  { phrase: "write down", past: "wrote down", es: "anotar", example: "I write down every new word.", pastExample: "I wrote down her phone number." },
  { phrase: "slow down", past: "slowed down", es: "ir más despacio", example: "She slows down when she speaks English.", pastExample: "The car slowed down at the corner." },
  { phrase: "speed up", past: "sped up", es: "acelerar", example: "They speed up at the end of the shift.", pastExample: "The driver sped up on the highway." },
  { phrase: "wake up early", past: "woke up early", es: "despertarse temprano", example: "I wake up early to study.", pastExample: "I woke up early on Monday." },
  { phrase: "sit down", past: "sat down", es: "sentarse", example: "Please sit down and relax.", pastExample: "We sat down at the table." },
  { phrase: "stand up", past: "stood up", es: "ponerse de pie", example: "We stand up when the manager arrives.", pastExample: "Everyone stood up for the song." },
  { phrase: "grow up", past: "grew up", es: "crecer", example: "Children grow up very fast.", pastExample: "I grew up in El Salvador." },
  { phrase: "clean up", past: "cleaned up", es: "limpiar", example: "He cleans up the kitchen after dinner.", pastExample: "He cleaned up the mess." },
  { phrase: "wash up", past: "washed up", es: "lavarse", example: "I wash up before I eat.", pastExample: "I washed up before dinner." },
  { phrase: "eat out", past: "ate out", es: "comer fuera", example: "We eat out once a month.", pastExample: "We ate out on my birthday." },
  { phrase: "order in", past: "ordered in", es: "pedir comida a domicilio", example: "They order in when nobody cooks.", pastExample: "They ordered in pizza last night." },
  { phrase: "try on", past: "tried on", es: "probarse (ropa)", example: "She tries on the shoes before buying.", pastExample: "She tried on three dresses." },
  { phrase: "try out", past: "tried out", es: "probar algo nuevo", example: "I try out a new app every week.", pastExample: "I tried out the new app yesterday." },
  { phrase: "throw away", past: "threw away", es: "botar / tirar", example: "He throws away the old papers.", pastExample: "He threw away the old box." },
  { phrase: "give in", past: "gave in", es: "ceder", example: "I give in when my son asks nicely.", pastExample: "I gave in and bought the toy." },
  { phrase: "break down", past: "broke down", es: "descomponerse", example: "My car breaks down all the time.", pastExample: "My car broke down yesterday." },
  { phrase: "break up", past: "broke up", es: "terminar una relación", example: "They break up and get back together.", pastExample: "They broke up last month." },
  { phrase: "bring up", past: "brought up", es: "mencionar", example: "She brings up the topic in the meeting.", pastExample: "She brought up a good point." },
  { phrase: "bring back", past: "brought back", es: "traer de vuelta", example: "He brings back souvenirs from his trips.", pastExample: "He brought back coffee from Colombia." },
  { phrase: "carry on", past: "carried on", es: "continuar", example: "We carry on with the plan.", pastExample: "We carried on without him." },
  { phrase: "catch up", past: "caught up", es: "ponerse al día", example: "I catch up on emails on Mondays.", pastExample: "I caught up with my friend." },
  { phrase: "cut down on", past: "cut down on", es: "reducir", example: "She cuts down on sugar every year.", pastExample: "She cut down on soda last year." },
  { phrase: "count on", past: "counted on", es: "contar con", example: "You count on your team every day.", pastExample: "I counted on my brother's help." },
  { phrase: "deal with", past: "dealt with", es: "lidiar con", example: "I deal with difficult customers.", pastExample: "I dealt with a hard problem." },
  { phrase: "depend on", past: "depended on", es: "depender de", example: "It depends on the weather.", pastExample: "It depended on the price." },
  { phrase: "end up", past: "ended up", es: "terminar (de cierta forma)", example: "We end up working late on Fridays.", pastExample: "We ended up eating at home." },
  { phrase: "focus on", past: "focused on", es: "enfocarse en", example: "He focuses on pronunciation.", pastExample: "He focused on grammar last week." },
  { phrase: "hold on", past: "held on", es: "esperar un momento", example: "Please hold on for one second.", pastExample: "She held on to my arm." },
  { phrase: "keep on", past: "kept on", es: "seguir haciendo algo", example: "I keep on practicing every day.", pastExample: "I kept on trying until it worked." },
  { phrase: "keep up with", past: "kept up with", es: "mantener el ritmo", example: "She keeps up with the class easily.", pastExample: "She kept up with the group." },
  { phrase: "let down", past: "let down", es: "decepcionar", example: "He never lets down his friends.", pastExample: "He let down his team." },
  { phrase: "log in", past: "logged in", es: "iniciar sesión", example: "I log in to the system at nine.", pastExample: "I logged in this morning." },
  { phrase: "log out", past: "logged out", es: "cerrar sesión", example: "We log out at the end of the shift.", pastExample: "We logged out at six." },
  { phrase: "move in", past: "moved in", es: "mudarse a un lugar", example: "They move in next month.", pastExample: "They moved in last year." },
  { phrase: "move out", past: "moved out", es: "mudarse fuera", example: "She moves out in December.", pastExample: "She moved out in June." },
  { phrase: "pay back", past: "paid back", es: "pagar de vuelta", example: "I pay back the loan every month.", pastExample: "I paid back the money on Friday." },
  { phrase: "point out", past: "pointed out", es: "señalar", example: "The teacher points out my mistakes.", pastExample: "The teacher pointed out the error." },
  { phrase: "set up", past: "set up", es: "configurar / organizar", example: "He sets up the meeting room.", pastExample: "He set up the new computer." },
  { phrase: "show up", past: "showed up", es: "aparecer / llegar", example: "She shows up on time every day.", pastExample: "She showed up ten minutes late." },
  { phrase: "shut down", past: "shut down", es: "apagar / cerrar", example: "We shut down the computers at six.", pastExample: "We shut down the system." },
  { phrase: "sign up", past: "signed up", es: "inscribirse", example: "I sign up for the class today.", pastExample: "I signed up for the course." },
  { phrase: "stay up", past: "stayed up", es: "quedarse despierto", example: "They stay up late on weekends.", pastExample: "They stayed up until two." },
  { phrase: "warm up", past: "warmed up", es: "calentar / calentarse", example: "I warm up my voice before speaking.", pastExample: "I warmed up before the game." },
  { phrase: "watch out", past: "watched out", es: "tener cuidado", example: "Watch out for the wet floor.", pastExample: "He watched out for the cars." },
  { phrase: "wrap up", past: "wrapped up", es: "terminar / cerrar algo", example: "We wrap up the meeting at noon.", pastExample: "We wrapped up early yesterday." },
];
