/** 50 common English idioms with Spanish meaning and one everyday example. */
export type Idiom = {
  phrase: string;
  es: string;
  example: string;
};

export const IDIOMS: Idiom[] = [
  { phrase: "break the ice", es: "romper el hielo", example: "I tell a joke to break the ice in meetings." },
  { phrase: "a piece of cake", es: "muy fácil", example: "This exercise is a piece of cake for her." },
  { phrase: "once in a while", es: "de vez en cuando", example: "We eat pizza once in a while." },
  { phrase: "hit the books", es: "ponerse a estudiar", example: "He hits the books every night after work." },
  { phrase: "hit the road", es: "salir / ponerse en marcha", example: "We hit the road at five in the morning." },
  { phrase: "under the weather", es: "sentirse mal", example: "She feels under the weather today." },
  { phrase: "on the same page", es: "estar de acuerdo", example: "The team is on the same page about the plan." },
  { phrase: "call it a day", es: "terminar por hoy", example: "We call it a day at six o'clock." },
  { phrase: "keep an eye on", es: "vigilar", example: "I keep an eye on the kids at the park." },
  { phrase: "cost an arm and a leg", es: "costar muy caro", example: "That phone costs an arm and a leg." },
  { phrase: "get the hang of it", es: "agarrarle el modo", example: "You get the hang of it after a week." },
  { phrase: "make up your mind", es: "decidirse", example: "He makes up his mind very quickly." },
  { phrase: "out of the blue", es: "de la nada", example: "She calls me out of the blue sometimes." },
  { phrase: "on the go", es: "muy ocupado / en movimiento", example: "I am always on the go during the week." },
  { phrase: "in a nutshell", es: "en resumen", example: "In a nutshell, the job is simple." },
  { phrase: "no big deal", es: "no es gran cosa", example: "A small mistake is no big deal." },
  { phrase: "take it easy", es: "tomarlo con calma", example: "I take it easy on Sundays." },
  { phrase: "give someone a hand", es: "echar una mano", example: "He gives me a hand with the boxes." },
  { phrase: "the bottom line", es: "lo más importante", example: "The bottom line is that we need practice." },
  { phrase: "around the clock", es: "las 24 horas", example: "The store is open around the clock." },
  { phrase: "better late than never", es: "más vale tarde que nunca", example: "She studies at night; better late than never." },
  { phrase: "back to square one", es: "volver al inicio", example: "We are back to square one with the plan." },
  { phrase: "hang in there", es: "aguanta / no te rindas", example: "Hang in there, the test is almost over." },
  { phrase: "long story short", es: "para resumir", example: "Long story short, I get the job." },
  { phrase: "speak your mind", es: "decir lo que piensas", example: "He speaks his mind in every meeting." },
  { phrase: "on time", es: "puntual", example: "She arrives on time every day." },
  { phrase: "in the long run", es: "a la larga", example: "Practice helps you in the long run." },
  { phrase: "keep in touch", es: "mantenerse en contacto", example: "We keep in touch by message." },
  { phrase: "get to the point", es: "ir al grano", example: "Please get to the point quickly." },
  { phrase: "a rip-off", es: "un robo / muy caro", example: "That price is a rip-off." },
  { phrase: "so far so good", es: "hasta ahora todo bien", example: "So far so good with the new job." },
  { phrase: "it's up to you", es: "tú decides", example: "The schedule is up to you." },
  { phrase: "on second thought", es: "pensándolo bien", example: "On second thought, I stay home." },
  { phrase: "sooner or later", es: "tarde o temprano", example: "Sooner or later he learns the rule." },
  { phrase: "little by little", es: "poco a poco", example: "Little by little I speak faster." },
  { phrase: "for the time being", es: "por ahora", example: "For the time being, I work from home." },
  { phrase: "run late", es: "ir con retraso", example: "I run late when the bus is slow." },
  { phrase: "a heads-up", es: "un aviso", example: "She gives me a heads-up before the call." },
  { phrase: "over the top", es: "exagerado", example: "His reaction is over the top." },
  { phrase: "off the top of my head", es: "sin pensarlo mucho", example: "Off the top of my head, I know three names." },
  { phrase: "up in the air", es: "sin decidir", example: "The trip is still up in the air." },
  { phrase: "the last straw", es: "el colmo", example: "That excuse is the last straw." },
  { phrase: "cut corners", es: "hacer las cosas a medias", example: "We never cut corners with quality." },
  { phrase: "pull someone's leg", es: "tomar el pelo", example: "He pulls my leg all the time." },
  { phrase: "on the house", es: "cortesía de la casa", example: "The coffee is on the house today." },
  { phrase: "day in, day out", es: "día tras día", example: "She practices day in, day out." },
  { phrase: "in the meantime", es: "mientras tanto", example: "In the meantime, I review my notes." },
  { phrase: "a close call", es: "por poco", example: "That was a close call with the car." },
  { phrase: "take your time", es: "tómate tu tiempo", example: "Take your time with the answer." },
  { phrase: "worth it", es: "vale la pena", example: "The extra practice is worth it." },
];
