/** 100 most common everyday English verbs: base, past, past participle, Spanish meaning, example sentence + Spanish translation. */
export type CommonVerb = {
  base: string;
  past: string;
  participle: string;
  es: string;
  irregular: boolean;
  example: string;
  exampleEs: string;
};

export const COMMON_VERBS: CommonVerb[] = [
  { base: "be", past: "was / were", participle: "been", es: "ser / estar", irregular: true, example: "I am happy at work.", exampleEs: "Soy feliz / estoy contento en el trabajo." },
  { base: "have", past: "had", participle: "had", es: "tener / haber", irregular: true, example: "I have two children.", exampleEs: "Tengo dos hijos." },
  { base: "do", past: "did", participle: "done", es: "hacer", irregular: true, example: "I do my homework at night.", exampleEs: "Hago mi tarea en la noche." },
  { base: "say", past: "said", participle: "said", es: "decir", irregular: true, example: "She says good morning to everyone.", exampleEs: "Ella le dice buenos días a todos." },
  { base: "go", past: "went", participle: "gone", es: "ir", irregular: true, example: "I go to work by bus.", exampleEs: "Voy al trabajo en bus." },
  { base: "get", past: "got", participle: "gotten / got", es: "conseguir / obtener", irregular: true, example: "I get coffee every morning.", exampleEs: "Consigo café todas las mañanas." },
  { base: "make", past: "made", participle: "made", es: "hacer / fabricar", irregular: true, example: "She makes breakfast for the family.", exampleEs: "Ella hace el desayuno para la familia." },
  { base: "know", past: "knew", participle: "known", es: "saber / conocer", irregular: true, example: "I know the answer.", exampleEs: "Sé la respuesta." },
  { base: "think", past: "thought", participle: "thought", es: "pensar", irregular: true, example: "I think English is important.", exampleEs: "Pienso que el inglés es importante." },
  { base: "take", past: "took", participle: "taken", es: "tomar / llevar", irregular: true, example: "I take the bus at seven.", exampleEs: "Tomo el bus a las siete." },
  { base: "see", past: "saw", participle: "seen", es: "ver", irregular: true, example: "I see my friends on weekends.", exampleEs: "Veo a mis amigos los fines de semana." },
  { base: "come", past: "came", participle: "come", es: "venir", irregular: true, example: "He comes to class on time.", exampleEs: "Él viene a clase a tiempo." },
  { base: "want", past: "wanted", participle: "wanted", es: "querer", irregular: false, example: "I want a better job.", exampleEs: "Quiero un mejor trabajo." },
  { base: "look", past: "looked", participle: "looked", es: "mirar / parecer", irregular: false, example: "She looks at her phone a lot.", exampleEs: "Ella mira mucho su teléfono." },
  { base: "use", past: "used", participle: "used", es: "usar", irregular: false, example: "I use my phone for work.", exampleEs: "Uso mi teléfono para el trabajo." },
  { base: "find", past: "found", participle: "found", es: "encontrar", irregular: true, example: "I find new words every day.", exampleEs: "Encuentro palabras nuevas todos los días." },
  { base: "give", past: "gave", participle: "given", es: "dar", irregular: true, example: "She gives me good advice.", exampleEs: "Ella me da buenos consejos." },
  { base: "tell", past: "told", participle: "told", es: "contar / decir", irregular: true, example: "He tells me funny stories.", exampleEs: "Él me cuenta historias graciosas." },
  { base: "work", past: "worked", participle: "worked", es: "trabajar / funcionar", irregular: false, example: "I work from Monday to Friday.", exampleEs: "Trabajo de lunes a viernes." },
  { base: "call", past: "called", participle: "called", es: "llamar", irregular: false, example: "I call my mom every Sunday.", exampleEs: "Llamo a mi mamá todos los domingos." },
  { base: "try", past: "tried", participle: "tried", es: "intentar / probar", irregular: false, example: "I try to speak English every day.", exampleEs: "Intento hablar inglés todos los días." },
  { base: "ask", past: "asked", participle: "asked", es: "preguntar / pedir", irregular: false, example: "She asks many questions in class.", exampleEs: "Ella hace muchas preguntas en clase." },
  { base: "need", past: "needed", participle: "needed", es: "necesitar", irregular: false, example: "I need more practice.", exampleEs: "Necesito más práctica." },
  { base: "feel", past: "felt", participle: "felt", es: "sentir", irregular: true, example: "I feel happy when I speak English.", exampleEs: "Me siento feliz cuando hablo inglés." },
  { base: "become", past: "became", participle: "become", es: "convertirse en / llegar a ser", irregular: true, example: "She wants to become a manager.", exampleEs: "Ella quiere llegar a ser gerente." },
  { base: "leave", past: "left", participle: "left", es: "salir / dejar", irregular: true, example: "I leave home at six thirty.", exampleEs: "Salgo de casa a las seis y media." },
  { base: "put", past: "put", participle: "put", es: "poner", irregular: true, example: "I put my keys on the table.", exampleEs: "Pongo mis llaves en la mesa." },
  { base: "mean", past: "meant", participle: "meant", es: "significar / querer decir", irregular: true, example: "This word means something good.", exampleEs: "Esta palabra significa algo bueno." },
  { base: "keep", past: "kept", participle: "kept", es: "mantener / guardar", irregular: true, example: "I keep my promises.", exampleEs: "Cumplo mis promesas." },
  { base: "let", past: "let", participle: "let", es: "dejar / permitir", irregular: true, example: "My boss lets me leave early on Fridays.", exampleEs: "Mi jefe me deja salir temprano los viernes." },
  { base: "begin", past: "began", participle: "begun", es: "empezar", irregular: true, example: "The class begins at seven.", exampleEs: "La clase empieza a las siete." },
  { base: "seem", past: "seemed", participle: "seemed", es: "parecer", irregular: false, example: "English seems hard at first.", exampleEs: "El inglés parece difícil al principio." },
  { base: "help", past: "helped", participle: "helped", es: "ayudar", irregular: false, example: "I help my coworkers every day.", exampleEs: "Ayudo a mis compañeros todos los días." },
  { base: "talk", past: "talked", participle: "talked", es: "hablar / conversar", irregular: false, example: "We talk about our families.", exampleEs: "Hablamos de nuestras familias." },
  { base: "turn", past: "turned", participle: "turned", es: "girar / volverse", irregular: false, example: "Turn left at the corner.", exampleEs: "Gira a la izquierda en la esquina." },
  { base: "start", past: "started", participle: "started", es: "empezar", irregular: false, example: "I start work at eight.", exampleEs: "Empiezo a trabajar a las ocho." },
  { base: "show", past: "showed", participle: "shown", es: "mostrar", irregular: true, example: "She shows me her photos.", exampleEs: "Ella me muestra sus fotos." },
  { base: "hear", past: "heard", participle: "heard", es: "oír", irregular: true, example: "I hear English at work every day.", exampleEs: "Oigo inglés en el trabajo todos los días." },
  { base: "play", past: "played", participle: "played", es: "jugar / tocar (música)", irregular: false, example: "My son plays soccer on Saturdays.", exampleEs: "Mi hijo juega fútbol los sábados." },
  { base: "run", past: "ran", participle: "run", es: "correr", irregular: true, example: "I run in the park on Sundays.", exampleEs: "Corro en el parque los domingos." },
  { base: "move", past: "moved", participle: "moved", es: "mover / mudarse", irregular: false, example: "We move to a new house next year.", exampleEs: "Nos mudamos a una casa nueva el próximo año." },
  { base: "like", past: "liked", participle: "liked", es: "gustar", irregular: false, example: "I like coffee in the morning.", exampleEs: "Me gusta el café en la mañana." },
  { base: "live", past: "lived", participle: "lived", es: "vivir", irregular: false, example: "I live with my family.", exampleEs: "Vivo con mi familia." },
  { base: "believe", past: "believed", participle: "believed", es: "creer", irregular: false, example: "I believe practice is important.", exampleEs: "Creo que la práctica es importante." },
  { base: "hold", past: "held", participle: "held", es: "sostener / sujetar", irregular: true, example: "She holds her baby carefully.", exampleEs: "Ella sostiene a su bebé con cuidado." },
  { base: "bring", past: "brought", participle: "brought", es: "traer", irregular: true, example: "I bring my lunch to work.", exampleEs: "Traigo mi almuerzo al trabajo." },
  { base: "happen", past: "happened", participle: "happened", es: "pasar / suceder", irregular: false, example: "Good things happen every day.", exampleEs: "Cosas buenas pasan todos los días." },
  { base: "write", past: "wrote", participle: "written", es: "escribir", irregular: true, example: "I write emails in English.", exampleEs: "Escribo correos en inglés." },
  { base: "provide", past: "provided", participle: "provided", es: "proporcionar", irregular: false, example: "The company provides free lunch.", exampleEs: "La empresa proporciona almuerzo gratis." },
  { base: "sit", past: "sat", participle: "sat", es: "sentarse", irregular: true, example: "I sit near the window.", exampleEs: "Me siento cerca de la ventana." },
  { base: "stand", past: "stood", participle: "stood", es: "estar de pie / pararse", irregular: true, example: "I stand in line at the bank.", exampleEs: "Hago fila de pie en el banco." },
  { base: "lose", past: "lost", participle: "lost", es: "perder", irregular: true, example: "I never lose my keys.", exampleEs: "Nunca pierdo mis llaves." },
  { base: "pay", past: "paid", participle: "paid", es: "pagar", irregular: true, example: "I pay my bills online.", exampleEs: "Pago mis facturas en línea." },
  { base: "meet", past: "met", participle: "met", es: "conocer / reunirse", irregular: true, example: "I meet new people at work.", exampleEs: "Conozco gente nueva en el trabajo." },
  { base: "include", past: "included", participle: "included", es: "incluir", irregular: false, example: "The price includes breakfast.", exampleEs: "El precio incluye el desayuno." },
  { base: "continue", past: "continued", participle: "continued", es: "continuar", irregular: false, example: "I continue practicing after class.", exampleEs: "Continúo practicando después de clase." },
  { base: "set", past: "set", participle: "set", es: "poner / establecer", irregular: true, example: "I set my alarm for six.", exampleEs: "Pongo mi alarma a las seis." },
  { base: "learn", past: "learned", participle: "learned", es: "aprender", irregular: false, example: "I learn new words every day.", exampleEs: "Aprendo palabras nuevas todos los días." },
  { base: "change", past: "changed", participle: "changed", es: "cambiar", irregular: false, example: "I change my clothes after work.", exampleEs: "Me cambio de ropa después del trabajo." },
  { base: "lead", past: "led", participle: "led", es: "liderar / guiar", irregular: true, example: "She leads a small team.", exampleEs: "Ella lidera un equipo pequeño." },
  { base: "understand", past: "understood", participle: "understood", es: "entender", irregular: true, example: "I understand the lesson.", exampleEs: "Entiendo la lección." },
  { base: "watch", past: "watched", participle: "watched", es: "ver / observar", irregular: false, example: "I watch movies in English.", exampleEs: "Veo películas en inglés." },
  { base: "follow", past: "followed", participle: "followed", es: "seguir", irregular: false, example: "I follow the instructions carefully.", exampleEs: "Sigo las instrucciones con cuidado." },
  { base: "stop", past: "stopped", participle: "stopped", es: "parar / detener", irregular: false, example: "The bus stops in front of my house.", exampleEs: "El bus para enfrente de mi casa." },
  { base: "create", past: "created", participle: "created", es: "crear", irregular: false, example: "She creates beautiful designs.", exampleEs: "Ella crea diseños hermosos." },
  { base: "speak", past: "spoke", participle: "spoken", es: "hablar", irregular: true, example: "I speak English with my clients.", exampleEs: "Hablo inglés con mis clientes." },
  { base: "read", past: "read", participle: "read", es: "leer", irregular: true, example: "I read the news every morning.", exampleEs: "Leo las noticias todas las mañanas." },
  { base: "spend", past: "spent", participle: "spent", es: "gastar / pasar tiempo", irregular: true, example: "I spend time with my family on weekends.", exampleEs: "Paso tiempo con mi familia los fines de semana." },
  { base: "grow", past: "grew", participle: "grown", es: "crecer / cultivar", irregular: true, example: "My children grow up fast.", exampleEs: "Mis hijos crecen rápido." },
  { base: "open", past: "opened", participle: "opened", es: "abrir", irregular: false, example: "The store opens at nine.", exampleEs: "La tienda abre a las nueve." },
  { base: "walk", past: "walked", participle: "walked", es: "caminar", irregular: false, example: "I walk to work every day.", exampleEs: "Camino al trabajo todos los días." },
  { base: "win", past: "won", participle: "won", es: "ganar", irregular: true, example: "Our team wins many games.", exampleEs: "Nuestro equipo gana muchos partidos." },
  { base: "teach", past: "taught", participle: "taught", es: "enseñar", irregular: true, example: "She teaches English to children.", exampleEs: "Ella enseña inglés a niños." },
  { base: "offer", past: "offered", participle: "offered", es: "ofrecer", irregular: false, example: "They offer good customer service.", exampleEs: "Ellos ofrecen buen servicio al cliente." },
  { base: "remember", past: "remembered", participle: "remembered", es: "recordar", irregular: false, example: "I remember new words easily.", exampleEs: "Recuerdo las palabras nuevas fácilmente." },
  { base: "consider", past: "considered", participle: "considered", es: "considerar", irregular: false, example: "I consider English very important.", exampleEs: "Considero el inglés muy importante." },
  { base: "buy", past: "bought", participle: "bought", es: "comprar", irregular: true, example: "I buy groceries on Saturdays.", exampleEs: "Compro la comida los sábados." },
  { base: "serve", past: "served", participle: "served", es: "servir / atender", irregular: false, example: "The waiter serves the food quickly.", exampleEs: "El mesero sirve la comida rápido." },
  { base: "send", past: "sent", participle: "sent", es: "enviar", irregular: true, example: "I send messages to my family.", exampleEs: "Envío mensajes a mi familia." },
  { base: "build", past: "built", participle: "built", es: "construir", irregular: true, example: "They build houses in my city.", exampleEs: "Ellos construyen casas en mi ciudad." },
  { base: "stay", past: "stayed", participle: "stayed", es: "quedarse", irregular: false, example: "I stay home on rainy days.", exampleEs: "Me quedo en casa en días de lluvia." },
  { base: "fall", past: "fell", participle: "fallen", es: "caer", irregular: true, example: "Leaves fall in autumn.", exampleEs: "Las hojas caen en otoño." },
  { base: "cut", past: "cut", participle: "cut", es: "cortar", irregular: true, example: "I cut vegetables for dinner.", exampleEs: "Corto verduras para la cena." },
  { base: "reach", past: "reached", participle: "reached", es: "alcanzar / llegar a", irregular: false, example: "I reach my goals with practice.", exampleEs: "Alcanzo mis metas con práctica." },
  { base: "raise", past: "raised", participle: "raised", es: "levantar / criar", irregular: false, example: "She raises three children.", exampleEs: "Ella cría a tres hijos." },
  { base: "pass", past: "passed", participle: "passed", es: "pasar / aprobar", irregular: false, example: "I pass the park on my way to work.", exampleEs: "Paso por el parque camino al trabajo." },
  { base: "sell", past: "sold", participle: "sold", es: "vender", irregular: true, example: "They sell fresh fruit at the market.", exampleEs: "Ellos venden fruta fresca en el mercado." },
  { base: "decide", past: "decided", participle: "decided", es: "decidir", irregular: false, example: "I decide my schedule every week.", exampleEs: "Decido mi horario cada semana." },
  { base: "return", past: "returned", participle: "returned", es: "regresar / devolver", irregular: false, example: "I return home at six.", exampleEs: "Regreso a casa a las seis." },
  { base: "explain", past: "explained", participle: "explained", es: "explicar", irregular: false, example: "The teacher explains the grammar clearly.", exampleEs: "El profesor explica la gramática claramente." },
  { base: "hope", past: "hoped", participle: "hoped", es: "esperar (deseo)", irregular: false, example: "I hope to speak English fluently.", exampleEs: "Espero hablar inglés con fluidez." },
  { base: "develop", past: "developed", participle: "developed", es: "desarrollar", irregular: false, example: "Practice develops good habits.", exampleEs: "La práctica desarrolla buenos hábitos." },
  { base: "carry", past: "carried", participle: "carried", es: "cargar / llevar", irregular: false, example: "I carry my bag to work.", exampleEs: "Llevo mi bolso al trabajo." },
  { base: "break", past: "broke", participle: "broken", es: "romper", irregular: true, example: "Be careful, glass breaks easily.", exampleEs: "Ten cuidado, el vidrio se rompe fácil." },
  { base: "receive", past: "received", participle: "received", es: "recibir", irregular: false, example: "I receive my salary every two weeks.", exampleEs: "Recibo mi salario cada dos semanas." },
  { base: "agree", past: "agreed", participle: "agreed", es: "estar de acuerdo", irregular: false, example: "I agree with your idea.", exampleEs: "Estoy de acuerdo con tu idea." },
  { base: "drive", past: "drove", participle: "driven", es: "manejar / conducir", irregular: true, example: "I drive to work every day.", exampleEs: "Manejo al trabajo todos los días." },
  { base: "eat", past: "ate", participle: "eaten", es: "comer", irregular: true, example: "I eat lunch at noon.", exampleEs: "Como el almuerzo al mediodía." },
  { base: "sleep", past: "slept", participle: "slept", es: "dormir", irregular: true, example: "I sleep eight hours every night.", exampleEs: "Duermo ocho horas cada noche." },
  { base: "wait", past: "waited", participle: "waited", es: "esperar", irregular: false, example: "I wait for the bus in the morning.", exampleEs: "Espero el bus en la mañana." },
];
