/** 100 most common everyday phrasal verbs in present tense, with Spanish meaning and one example. */
export type PhrasalVerb = {
  phrase: string;
  es: string;
  example: string;
};

export const PHRASAL_VERBS: PhrasalVerb[] = [
  { phrase: "get up", es: "levantarse", example: "I get up at six every morning." },
  { phrase: "wake up", es: "despertarse", example: "She wakes up before the alarm rings." },
  { phrase: "get dressed up", es: "arreglarse / vestirse elegante", example: "They get dressed up for special dinners." },
  { phrase: "get along", es: "llevarse bien", example: "I get along with all my coworkers." },
  { phrase: "get back", es: "regresar", example: "He gets back from work at seven." },
  { phrase: "get in", es: "entrar / subir (a un carro)", example: "We get in the car and drive to school." },
  { phrase: "get off", es: "bajarse (de un bus)", example: "I get off the bus at the second stop." },
  { phrase: "get on", es: "subirse (a un bus)", example: "She gets on the train at eight." },
  { phrase: "get over", es: "superar", example: "He gets over problems very quickly." },
  { phrase: "get together", es: "reunirse", example: "We get together every Friday night." },
  { phrase: "give up", es: "rendirse / dejar de hacer algo", example: "I never give up when the class is hard." },
  { phrase: "give back", es: "devolver", example: "She gives back the money on Monday." },
  { phrase: "look for", es: "buscar", example: "I look for my keys every morning." },
  { phrase: "look after", es: "cuidar", example: "He looks after his little brother." },
  { phrase: "look up", es: "buscar información", example: "I look up new words in the dictionary." },
  { phrase: "look forward to", es: "tener ganas de / esperar con ilusión", example: "We look forward to the weekend." },
  { phrase: "look out", es: "tener cuidado", example: "You look out for cars on that street." },
  { phrase: "take off", es: "quitarse / despegar", example: "I take off my shoes at the door." },
  { phrase: "take out", es: "sacar", example: "He takes out the trash every night." },
  { phrase: "take care of", es: "encargarse de / cuidar", example: "She takes care of the customers." },
  { phrase: "take over", es: "tomar el control", example: "The manager takes over when we are busy." },
  { phrase: "put on", es: "ponerse (ropa)", example: "I put on my jacket before I leave." },
  { phrase: "put off", es: "posponer", example: "They put off the meeting until Friday." },
  { phrase: "put away", es: "guardar", example: "She puts away the dishes after dinner." },
  { phrase: "put up with", es: "aguantar / soportar", example: "I put up with the noise at work." },
  { phrase: "turn on", es: "encender", example: "He turns on the computer at eight." },
  { phrase: "turn off", es: "apagar", example: "I turn off the lights before bed." },
  { phrase: "turn up", es: "subir el volumen / aparecer", example: "She turns up the music in the car." },
  { phrase: "turn down", es: "bajar el volumen / rechazar", example: "I turn down the offer because it is far." },
  { phrase: "turn around", es: "dar la vuelta", example: "We turn around and go back home." },
  { phrase: "come back", es: "volver", example: "He comes back at five o'clock." },
  { phrase: "come in", es: "entrar", example: "Customers come in all day long." },
  { phrase: "come over", es: "venir a visitar", example: "My friends come over on Sundays." },
  { phrase: "come up with", es: "ocurrírsele una idea", example: "She comes up with great ideas." },
  { phrase: "go on", es: "continuar / suceder", example: "The class goes on for two hours." },
  { phrase: "go out", es: "salir", example: "We go out for dinner on Saturdays." },
  { phrase: "go back", es: "regresar", example: "I go back to the office after lunch." },
  { phrase: "go over", es: "repasar", example: "He goes over his notes before the test." },
  { phrase: "go through", es: "pasar por / revisar", example: "She goes through her email every morning." },
  { phrase: "run out of", es: "quedarse sin", example: "We run out of coffee every week." },
  { phrase: "run into", es: "encontrarse por casualidad", example: "I run into my neighbor at the store." },
  { phrase: "run late", es: "ir tarde", example: "He runs late when traffic is bad." },
  { phrase: "call back", es: "devolver la llamada", example: "I call back the client in ten minutes." },
  { phrase: "call off", es: "cancelar", example: "They call off the trip when it rains." },
  { phrase: "hang up", es: "colgar el teléfono", example: "She hangs up after she says goodbye." },
  { phrase: "hang out", es: "pasar el rato", example: "We hang out at the park on Sundays." },
  { phrase: "pick up", es: "recoger", example: "I pick up my daughter at three." },
  { phrase: "drop off", es: "dejar (a alguien o algo)", example: "He drops off the kids at school." },
  { phrase: "check in", es: "registrarse", example: "Guests check in at the front desk." },
  { phrase: "check out", es: "revisar / dejar el hotel", example: "We check out at eleven in the morning." },
  { phrase: "find out", es: "averiguar", example: "I find out the answer online." },
  { phrase: "figure out", es: "resolver / entender", example: "She figures out the problem alone." },
  { phrase: "work out", es: "hacer ejercicio / resultar bien", example: "I work out three times a week." },
  { phrase: "fill out", es: "llenar (un formulario)", example: "You fill out the form with your name." },
  { phrase: "fill in", es: "completar", example: "He fills in the missing information." },
  { phrase: "write down", es: "anotar", example: "I write down every new word." },
  { phrase: "slow down", es: "ir más despacio", example: "She slows down when she speaks English." },
  { phrase: "speed up", es: "acelerar", example: "They speed up at the end of the shift." },
  { phrase: "wake up early", es: "despertarse temprano", example: "I wake up early to study." },
  { phrase: "sit down", es: "sentarse", example: "Please sit down and relax." },
  { phrase: "stand up", es: "ponerse de pie", example: "We stand up when the manager arrives." },
  { phrase: "grow up", es: "crecer", example: "Children grow up very fast." },
  { phrase: "clean up", es: "limpiar", example: "He cleans up the kitchen after dinner." },
  { phrase: "wash up", es: "lavarse", example: "I wash up before I eat." },
  { phrase: "eat out", es: "comer fuera", example: "We eat out once a month." },
  { phrase: "order in", es: "pedir comida a domicilio", example: "They order in when nobody cooks." },
  { phrase: "try on", es: "probarse (ropa)", example: "She tries on the shoes before buying." },
  { phrase: "try out", es: "probar algo nuevo", example: "I try out a new app every week." },
  { phrase: "throw away", es: "botar / tirar", example: "He throws away the old papers." },
  { phrase: "give in", es: "ceder", example: "I give in when my son asks nicely." },
  { phrase: "break down", es: "descomponerse", example: "My car breaks down all the time." },
  { phrase: "break up", es: "terminar una relación", example: "They break up and get back together." },
  { phrase: "bring up", es: "mencionar", example: "She brings up the topic in the meeting." },
  { phrase: "bring back", es: "traer de vuelta", example: "He brings back souvenirs from his trips." },
  { phrase: "carry on", es: "continuar", example: "We carry on with the plan." },
  { phrase: "catch up", es: "ponerse al día", example: "I catch up on emails on Mondays." },
  { phrase: "cut down on", es: "reducir", example: "She cuts down on sugar every year." },
  { phrase: "count on", es: "contar con", example: "You count on your team every day." },
  { phrase: "deal with", es: "lidiar con", example: "I deal with difficult customers." },
  { phrase: "depend on", es: "depender de", example: "It depends on the weather." },
  { phrase: "end up", es: "terminar (de cierta forma)", example: "We end up working late on Fridays." },
  { phrase: "focus on", es: "enfocarse en", example: "He focuses on pronunciation." },
  { phrase: "hold on", es: "esperar un momento", example: "Please hold on for one second." },
  { phrase: "keep on", es: "seguir haciendo algo", example: "I keep on practicing every day." },
  { phrase: "keep up with", es: "mantener el ritmo", example: "She keeps up with the class easily." },
  { phrase: "let down", es: "decepcionar", example: "He never lets down his friends." },
  { phrase: "log in", es: "iniciar sesión", example: "I log in to the system at nine." },
  { phrase: "log out", es: "cerrar sesión", example: "We log out at the end of the shift." },
  { phrase: "move in", es: "mudarse a un lugar", example: "They move in next month." },
  { phrase: "move out", es: "mudarse fuera", example: "She moves out in December." },
  { phrase: "pay back", es: "pagar de vuelta", example: "I pay back the loan every month." },
  { phrase: "point out", es: "señalar", example: "The teacher points out my mistakes." },
  { phrase: "set up", es: "configurar / organizar", example: "He sets up the meeting room." },
  { phrase: "show up", es: "aparecer / llegar", example: "She shows up on time every day." },
  { phrase: "shut down", es: "apagar / cerrar", example: "We shut down the computers at six." },
  { phrase: "sign up", es: "inscribirse", example: "I sign up for the class today." },
  { phrase: "stay up", es: "quedarse despierto", example: "They stay up late on weekends." },
  { phrase: "warm up", es: "calentar / calentarse", example: "I warm up my voice before speaking." },
  { phrase: "watch out", es: "tener cuidado", example: "Watch out for the wet floor." },
  { phrase: "wrap up", es: "terminar / cerrar algo", example: "We wrap up the meeting at noon." },
];
