/** 100 most common everyday English verbs: base, past, past participle, Spanish meaning. */
export type CommonVerb = {
  base: string;
  past: string;
  participle: string;
  es: string;
  irregular: boolean;
};

export const COMMON_VERBS: CommonVerb[] = [
  { base: "be", past: "was / were", participle: "been", es: "ser / estar", irregular: true },
  { base: "have", past: "had", participle: "had", es: "tener / haber", irregular: true },
  { base: "do", past: "did", participle: "done", es: "hacer", irregular: true },
  { base: "say", past: "said", participle: "said", es: "decir", irregular: true },
  { base: "go", past: "went", participle: "gone", es: "ir", irregular: true },
  { base: "get", past: "got", participle: "gotten / got", es: "conseguir / obtener", irregular: true },
  { base: "make", past: "made", participle: "made", es: "hacer / fabricar", irregular: true },
  { base: "know", past: "knew", participle: "known", es: "saber / conocer", irregular: true },
  { base: "think", past: "thought", participle: "thought", es: "pensar", irregular: true },
  { base: "take", past: "took", participle: "taken", es: "tomar / llevar", irregular: true },
  { base: "see", past: "saw", participle: "seen", es: "ver", irregular: true },
  { base: "come", past: "came", participle: "come", es: "venir", irregular: true },
  { base: "want", past: "wanted", participle: "wanted", es: "querer", irregular: false },
  { base: "look", past: "looked", participle: "looked", es: "mirar / parecer", irregular: false },
  { base: "use", past: "used", participle: "used", es: "usar", irregular: false },
  { base: "find", past: "found", participle: "found", es: "encontrar", irregular: true },
  { base: "give", past: "gave", participle: "given", es: "dar", irregular: true },
  { base: "tell", past: "told", participle: "told", es: "contar / decir", irregular: true },
  { base: "work", past: "worked", participle: "worked", es: "trabajar / funcionar", irregular: false },
  { base: "call", past: "called", participle: "called", es: "llamar", irregular: false },
  { base: "try", past: "tried", participle: "tried", es: "intentar / probar", irregular: false },
  { base: "ask", past: "asked", participle: "asked", es: "preguntar / pedir", irregular: false },
  { base: "need", past: "needed", participle: "needed", es: "necesitar", irregular: false },
  { base: "feel", past: "felt", participle: "felt", es: "sentir", irregular: true },
  { base: "become", past: "became", participle: "become", es: "convertirse en / llegar a ser", irregular: true },
  { base: "leave", past: "left", participle: "left", es: "salir / dejar", irregular: true },
  { base: "put", past: "put", participle: "put", es: "poner", irregular: true },
  { base: "mean", past: "meant", participle: "meant", es: "significar / querer decir", irregular: true },
  { base: "keep", past: "kept", participle: "kept", es: "mantener / guardar", irregular: true },
  { base: "let", past: "let", participle: "let", es: "dejar / permitir", irregular: true },
  { base: "begin", past: "began", participle: "begun", es: "empezar", irregular: true },
  { base: "seem", past: "seemed", participle: "seemed", es: "parecer", irregular: false },
  { base: "help", past: "helped", participle: "helped", es: "ayudar", irregular: false },
  { base: "talk", past: "talked", participle: "talked", es: "hablar / conversar", irregular: false },
  { base: "turn", past: "turned", participle: "turned", es: "girar / volverse", irregular: false },
  { base: "start", past: "started", participle: "started", es: "empezar", irregular: false },
  { base: "show", past: "showed", participle: "shown", es: "mostrar", irregular: true },
  { base: "hear", past: "heard", participle: "heard", es: "oír", irregular: true },
  { base: "play", past: "played", participle: "played", es: "jugar / tocar (música)", irregular: false },
  { base: "run", past: "ran", participle: "run", es: "correr", irregular: true },
  { base: "move", past: "moved", participle: "moved", es: "mover / mudarse", irregular: false },
  { base: "like", past: "liked", participle: "liked", es: "gustar", irregular: false },
  { base: "live", past: "lived", participle: "lived", es: "vivir", irregular: false },
  { base: "believe", past: "believed", participle: "believed", es: "creer", irregular: false },
  { base: "hold", past: "held", participle: "held", es: "sostener / sujetar", irregular: true },
  { base: "bring", past: "brought", participle: "brought", es: "traer", irregular: true },
  { base: "happen", past: "happened", participle: "happened", es: "pasar / suceder", irregular: false },
  { base: "write", past: "wrote", participle: "written", es: "escribir", irregular: true },
  { base: "provide", past: "provided", participle: "provided", es: "proporcionar", irregular: false },
  { base: "sit", past: "sat", participle: "sat", es: "sentarse", irregular: true },
  { base: "stand", past: "stood", participle: "stood", es: "estar de pie / pararse", irregular: true },
  { base: "lose", past: "lost", participle: "lost", es: "perder", irregular: true },
  { base: "pay", past: "paid", participle: "paid", es: "pagar", irregular: true },
  { base: "meet", past: "met", participle: "met", es: "conocer / reunirse", irregular: true },
  { base: "include", past: "included", participle: "included", es: "incluir", irregular: false },
  { base: "continue", past: "continued", participle: "continued", es: "continuar", irregular: false },
  { base: "set", past: "set", participle: "set", es: "poner / establecer", irregular: true },
  { base: "learn", past: "learned", participle: "learned", es: "aprender", irregular: false },
  { base: "change", past: "changed", participle: "changed", es: "cambiar", irregular: false },
  { base: "lead", past: "led", participle: "led", es: "liderar / guiar", irregular: true },
  { base: "understand", past: "understood", participle: "understood", es: "entender", irregular: true },
  { base: "watch", past: "watched", participle: "watched", es: "ver / observar", irregular: false },
  { base: "follow", past: "followed", participle: "followed", es: "seguir", irregular: false },
  { base: "stop", past: "stopped", participle: "stopped", es: "parar / detener", irregular: false },
  { base: "create", past: "created", participle: "created", es: "crear", irregular: false },
  { base: "speak", past: "spoke", participle: "spoken", es: "hablar", irregular: true },
  { base: "read", past: "read", participle: "read", es: "leer", irregular: true },
  { base: "spend", past: "spent", participle: "spent", es: "gastar / pasar tiempo", irregular: true },
  { base: "grow", past: "grew", participle: "grown", es: "crecer / cultivar", irregular: true },
  { base: "open", past: "opened", participle: "opened", es: "abrir", irregular: false },
  { base: "walk", past: "walked", participle: "walked", es: "caminar", irregular: false },
  { base: "win", past: "won", participle: "won", es: "ganar", irregular: true },
  { base: "teach", past: "taught", participle: "taught", es: "enseñar", irregular: true },
  { base: "offer", past: "offered", participle: "offered", es: "ofrecer", irregular: false },
  { base: "remember", past: "remembered", participle: "remembered", es: "recordar", irregular: false },
  { base: "consider", past: "considered", participle: "considered", es: "considerar", irregular: false },
  { base: "buy", past: "bought", participle: "bought", es: "comprar", irregular: true },
  { base: "serve", past: "served", participle: "served", es: "servir / atender", irregular: false },
  { base: "send", past: "sent", participle: "sent", es: "enviar", irregular: true },
  { base: "build", past: "built", participle: "built", es: "construir", irregular: true },
  { base: "stay", past: "stayed", participle: "stayed", es: "quedarse", irregular: false },
  { base: "fall", past: "fell", participle: "fallen", es: "caer", irregular: true },
  { base: "cut", past: "cut", participle: "cut", es: "cortar", irregular: true },
  { base: "reach", past: "reached", participle: "reached", es: "alcanzar / llegar a", irregular: false },
  { base: "raise", past: "raised", participle: "raised", es: "levantar / criar", irregular: false },
  { base: "pass", past: "passed", participle: "passed", es: "pasar / aprobar", irregular: false },
  { base: "sell", past: "sold", participle: "sold", es: "vender", irregular: true },
  { base: "decide", past: "decided", participle: "decided", es: "decidir", irregular: false },
  { base: "return", past: "returned", participle: "returned", es: "regresar / devolver", irregular: false },
  { base: "explain", past: "explained", participle: "explained", es: "explicar", irregular: false },
  { base: "hope", past: "hoped", participle: "hoped", es: "esperar (deseo)", irregular: false },
  { base: "develop", past: "developed", participle: "developed", es: "desarrollar", irregular: false },
  { base: "carry", past: "carried", participle: "carried", es: "cargar / llevar", irregular: false },
  { base: "break", past: "broke", participle: "broken", es: "romper", irregular: true },
  { base: "receive", past: "received", participle: "received", es: "recibir", irregular: false },
  { base: "agree", past: "agreed", participle: "agreed", es: "estar de acuerdo", irregular: false },
  { base: "drive", past: "drove", participle: "driven", es: "manejar / conducir", irregular: true },
  { base: "eat", past: "ate", participle: "eaten", es: "comer", irregular: true },
  { base: "sleep", past: "slept", participle: "slept", es: "dormir", irregular: true },
  { base: "wait", past: "waited", participle: "waited", es: "esperar", irregular: false },
];
