import type { StorybookEpisode, StorybookScene } from "./types";

/**
 * Base glossary of common/function words used across the storybook episodes.
 * Lets a learner tap ANY word (not just the curated ones) and still get a
 * Spanish meaning. Hand-written: no runtime translation API.
 */
export const BASE_GLOSSARY: Record<string, string> = {
  a: "un / una",
  am: "soy / estoy",
  an: "un / una",
  and: "y",
  are: "eres / están / son",
  at: "en (un lugar)",
  back: "de regreso / atrás",
  be: "ser / estar",
  because: "porque",
  but: "pero",
  can: "poder",
  come: "ven / venir",
  day: "día",
  do: "hacer",
  everyone: "todos",
  for: "para / por",
  friend: "amiga / amigo",
  from: "de (origen)",
  get: "obtener / conseguir",
  girl: "chica",
  go: "ir",
  goes: "va",
  good: "bueno / buena",
  guy: "chavo / tipo",
  has: "tiene",
  have: "tener",
  he: "él",
  hello: "hola",
  her: "su / de ella",
  here: "aquí",
  hi: "hola",
  his: "su / de él",
  how: "cómo",
  i: "yo",
  in: "en / dentro de",
  is: "es / está",
  it: "eso / lo",
  like: "gustar / como",
  look: "mirar",
  looks: "se ve / mira",
  make: "hacer",
  making: "haciendo",
  man: "hombre",
  amazing: "increíble / asombroso",
  awesome: "increíble / genial",
  celebrate: "celebrar",
  diploma: "diploma",
  envelope: "sobre",
  graduation: "graduación",
  proud: "orgulloso / orgullosa",
  disciplined: "disciplinado / disciplinada",
  balloons: "globos",
  confetti: "confeti",
  hugs: "abraza",
  tears: "lágrimas",
  wall: "pared",
  antigua: "Antigua",
  challenges: "retos / desafíos",
  color: "color",
  did: "hizo (pasado de hacer)",
  forgets: "olvida",
  great: "genial / excelente",
  guatemala: "Guatemala",
  live: "vivir",
  love: "amar / encantar",
  mouth: "boca",
  opens: "abre",
  orange: "naranja",
  partners: "compañeros / parejas",
  part: "parte",
  practice: "practicar",
  process: "proceso",
  sees: "ve",
  twenty: "veinte",
  two: "dos",
  words: "palabras",
  me: "me / mí",
  my: "mi",
  new: "nuevo / nueva",
  nice: "agradable / qué gusto",
  no: "no",
  not: "no",
  now: "ahora",
  of: "de",
  ok: "está bien",
  on: "en / encima de / puesto",
  one: "uno / una",
  or: "o",
  out: "afuera",
  people: "gente / personas",
  please: "por favor",
  say: "decir",
  says: "dice",
  she: "ella",
  so: "así que / tan",
  speak: "hablar",
  speaks: "habla",
  take: "tomar",
  takes: "toma",
  thank: "agradecer",
  thanks: "gracias",
  that: "eso / que",
  the: "el / la / los / las",
  their: "su / de ellos",
  them: "ellos / les",
  then: "entonces / después",
  there: "ahí / allá",
  they: "ellos / ellas",
  this: "este / esta / esto",
  time: "tiempo / vez",
  to: "a / para",
  today: "hoy",
  too: "también / demasiado",
  up: "arriba",
  us: "nosotros / nos",
  very: "muy",
  was: "era / estaba / fue",
  we: "nosotros",
  well: "bien / pues",
  what: "qué",
  when: "cuándo",
  where: "dónde",
  who: "quién",
  why: "por qué",
  with: "con",
  woman: "mujer",
  work: "trabajo / trabajar",
  yes: "sí",
  you: "tú / usted",
  your: "tu / tuyo",
  yourself: "a ti misma / a ti mismo",
  // Episodes 4-7
  again: "otra vez / de nuevo",
  always: "siempre",
  answer: "respuesta",
  answers: "contesta / respuestas",
  ask: "preguntar",
  asks: "pregunta",
  awesome: "genial / increíble",
  balloons: "globos",
  believe: "creer",
  big: "grande",
  blue: "azul",
  box: "caja",
  breathes: "respira",
  canada: "Canadá",
  challenge: "reto",
  city: "ciudad",
  claps: "aplaude",
  clear: "clara / claro",
  client: "cliente",
  closes: "cierra",
  cold: "frío / frías",
  colors: "colores",
  curious: "curiosa / curioso",
  dancing: "bailar",
  disciplined: "disciplinada / disciplinado",
  dylan: "Dylan",
  everybody: "todos",
  everywhere: "por todas partes",
  every: "cada / todos los",
  excited: "emocionada / emocionado",
  eyes: "ojos",
  family: "familia",
  fast: "rápido",
  fluent: "fluida / fluido",
  food: "comida",
  forget: "olvidar",
  friendly: "amable / amigable",
  full: "llena / lleno",
  green: "verde",
  happy: "feliz / alegre",
  heart: "corazón",
  hungry: "con hambre",
  introductions: "presentaciones",
  jacket: "chaqueta",
  know: "saber / conocer",
  laughs: "se ríe",
  long: "larga / largo",
  loud: "llamativo / ruidoso",
  meet: "conocer",
  meeting: "reunión",
  message: "mensaje",
  mistakes: "errores",
  more: "más",
  morning: "mañana (parte del día)",
  music: "música",
  nature: "naturaleza",
  nervous: "nerviosa / nervioso",
  news: "noticias",
  nineteen: "diecinueve",
  note: "nota",
  notebook: "cuaderno",
  opportunity: "oportunidad",
  perfect: "perfecto / perfecta",
  phone: "teléfono",
  pizza: "pizza",
  practices: "practica",
  project: "proyecto",
  reason: "razón",
  rings: "suena",
  room: "sala / cuarto",
  screen: "pantalla",
  short: "corta / corto",
  shows: "muestra",
  silence: "silencio",
  soccer: "fútbol",
  sound: "sonar / sonido",
  still: "todavía",
  sun: "sol",
  surprise: "sorpresa",
  team: "equipo",
  thinks: "piensa",
  tomorrow: "mañana",
  toronto: "Toronto",
  try: "intento / intentar",
  turn: "turno",
  voice: "voz",
  warm: "cálida / cálido",
  whole: "todo / entero",
  word: "palabra",
  writes: "escribe",
  yellow: "amarillo",
  // Episodes 8-12
  age: "edad",
  angry: "enojada / enojado",
  another: "otro / otra",
  best: "mejor",
  brave: "valiente",
  brother: "hermano",
  build: "construir",
  business: "negocio",
  cheese: "queso",
  cooking: "cocinar",
  creative: "creativa / creativo",
  dance: "bailar / baile",
  designs: "diseños",
  difficult: "difícil",
  dreams: "sueña / sueños",
  empty: "vacía / vacío",
  embarrassed: "avergonzada / avergonzado",
  excellent: "excelente",
  favorite: "favorito / favorita",
  feels: "siente",
  future: "futuro",
  grow: "crecer",
  hard: "difícil / duro",
  help: "ayuda / ayudar",
  hobbies: "pasatiempos",
  honduras: "Honduras",
  important: "importante",
  interview: "entrevista",
  invitation: "invitación",
  lunch: "almuerzo",
  lives: "vive",
  move: "movimiento / mover",
  own: "propio / propia",
  photos: "fotos",
  presentation: "presentación",
  pupusas: "pupusas",
  purple: "morado",
  ready: "lista / listo",
  records: "graba",
  refrigerator: "refrigerador",
  remind: "recordar",
  reminds: "recuerda",
  san: "San",
  smells: "huele",
  small: "pequeño / poco a poco",
  special: "especial",
  starts: "comienza",
  supervisor: "supervisor / supervisora",
  talent: "talento",
  tamales: "tamales",
  thirty: "treinta",
  videos: "videos",
  watching: "mirando",
  years: "años",
};


/** Lowercase and strip quotes/punctuation so "Says," matches "says". */
export function normalizeWord(word: string): string {
  return word
    .toLowerCase()
    .replace(/[“”"'‘’.,!?;:()¿¡…]/g, "")
    .trim();
}

/** All curated words of an episode (every scene + review words), lowercased. */
export function buildEpisodeGlossary(episode: StorybookEpisode): Map<string, string> {
  const map = new Map<string, string>();
  for (const w of episode.reviewWords ?? []) map.set(normalizeWord(w.word), w.es);
  for (const scene of episode.scenes) {
    for (const w of scene.words) map.set(normalizeWord(w.word), w.es);
  }
  return map;
}

export type WordLookup = {
  /** Spanish meaning, or null when we have no hand-written meaning. */
  meaning: string | null;
  /** True when the word is a curated key word of the current scene. */
  curated: boolean;
};

/**
 * Resolve a tapped word: current scene → rest of the episode → base glossary.
 */
export function lookupWord(
  word: string,
  options: { scene?: StorybookScene | undefined; episodeGlossary?: Map<string, string> | undefined } = {},
): WordLookup {
  const key = normalizeWord(word);
  if (!key) return { meaning: null, curated: false };

  const sceneWord = options.scene?.words.find((w) => normalizeWord(w.word) === key);
  if (sceneWord) return { meaning: sceneWord.es, curated: true };

  const fromEpisode = options.episodeGlossary?.get(key);
  if (fromEpisode) return { meaning: fromEpisode, curated: false };

  return { meaning: BASE_GLOSSARY[key] ?? null, curated: false };
}
