import type { StorybookEpisode, StorybookScene } from "./types";
import { globalExpressionMap } from "./expressions";

/**
 * Base glossary of common/function words used across the storybook episodes.
 * Lets a learner tap ANY word (not just the curated ones) and still get a
 * Spanish meaning. Hand-written: no runtime translation API.
 */
export const BASE_GLOSSARY: Record<string, string> = {
  'annoys': 'molesta; fastidia',
  'shape': 'forma; dar forma',
  'plenty': 'bastante; de sobra',
  'disaster': 'desastre',
  'touched': 'tocó; conmovió',
  'text': 'texto; mensaje',
  'replies': 'responde; respuestas',
  'simply': 'simplemente',
  'assignment': 'tarea asignada',
  'eighty-two': 'ochenta y dos',
  'sixty-one': 'sesenta y uno',
  'instinct': 'instinto',
  'file': 'archivo',
  'unique': 'único',
  'codes': 'códigos',
  'colour': 'color',
  'cell': 'celda',
  'reader': 'lector',
  'enjoying': 'disfrutando',
  'mentioned': 'mencionó; mencionado',
  'impressed': 'impresionado',
  'material': 'material',
  'four-week': 'de cuatro semanas',
  'visible': 'visible',
  'staff': 'personal; equipo de trabajo',
  'approve': 'aprobar',
  'june': 'junio',
  'comment': 'comentario',
  'marta': 'Marta (nombre de persona)',
  'nelson': 'Nelson (nombre de persona)',
  'elena': 'Elena (nombre de persona)',
  'promoted': 'ascendido',
  'head': 'cabeza; jefe/a',
  'intensive': 'intensivo',
  'actual': 'real; verdadero',
  'uncomfortable': 'incómodo',
  'practised': 'practicó; practicado',
  'practise': 'practicar',
  'phone-call': 'llamada telefónica',
  'description': 'descripción',
  'rewritten': 'reescrito',
  'whenever': 'cada vez que; cuando sea',
  'hate': 'odiar',
  'truth': 'verdad',
  'structure': 'estructura',
  'whatever': 'lo que sea',
  'throw': 'lanzar; tirar',
  'rebuilt': 'reconstruyó; reconstruido',
  'seventy': 'setenta',
  'eighty-four': 'ochenta y cuatro',
  'remain': 'permanecer; seguir siendo',
  'movie': 'película',
  'unless': 'a menos que',
  'though': 'aunque; sin embargo',
  'paint': 'pintar; describir',
  'however': 'sin embargo',
  'employee': 'empleado/a',
  'chance': 'oportunidad',
  'script': 'guion',
  'weak': 'débil',
  'communication': 'comunicación',
  'leak': 'filtración',
  'investment': 'inversión',
  'agreement': 'acuerdo',
  'headlines': 'titulares',
  'executive': 'ejecutivo/a',
  'scalable': 'escalable',
  'educational': 'educativo',
  'whiteboard': 'pizarra',
  'sheet': 'hoja',
  'check-in': 'reunión de seguimiento',
  'fall': 'caer',
  'newest': 'más nuevo',
  'propose': 'proponer',
  'crisis': 'crisis',
  'carrying': 'cargando',
  'monterrey': 'Monterrey',
  'confession': 'confesión',
  'letter': 'carta',
  'debts': 'deudas',
  'outage': 'corte / interrupción',
  'froze': 'se congeló',
  'double': 'el doble',
  'ads': 'anuncios',
  'april': 'abril',
  'clicks': 'clics',
  'builders': 'quienes construyen',
  'loyal': 'leales',
  'scare': 'asustan',
  'train': 'capacitar',
  'command': 'mandar',
  'prefers': 'prefiere',
  'matters': 'importa',
  'wonder': 'preguntarse',
  'upset': 'molesta',
  'crazy': 'loca',
  'deserves': 'merece',
  'measure': 'medir',
  'itself': 'por sí sola',
  'improvise': 'improvisar',
  'worse': 'peor',
  'fired': 'se activó',
  'forgive': 'perdonan',
  'exact': 'exacta',
  'quote': 'cito',
  'survive': 'sobrevivir',
  'link': 'enlace',
  'firm': 'firme',
  'fund': 'fondo',
  'acceptable': 'aceptable',
  'access': 'acceso',
  'admit': 'admitir',
  'afterwards': 'después',
  'assumes': 'supone',
  'begin': 'empezar',
  'begins': 'empieza',
  'behave': 'comportarse',
  'burn': 'quemar / agotarse',
  'busier': 'más ocupado',
  'busiest': 'más ocupadas',
  'calendar': 'calendario',
  'calmer': 'más tranquilo',
  'cancel': 'cancelar',
  'capital': 'capital',
  'certificate': 'certificado',
  'child': 'niño',
  'children': 'niños',
  'complained': 'se quejó',
  'coordination': 'coordinación',
  'demanding': 'exigente',
  'designing': 'diseñando',
  'disappear': 'desaparecer',
  'distances': 'distancias',
  'exam': 'examen',
  'explanation': 'explicación',
  'failure': 'fracaso',
  'favor': 'favor',
  'handle': 'manejar',
  'handles': 'maneja',
  'impression': 'impresión',
  'include': 'incluir',
  'november': 'noviembre',
  'observation': 'observación',
  'observing': 'observar',
  'ordinary': 'corriente / común',
  'patient': 'paciente',
  'predicts': 'predice',
  'properly': 'correctamente',
  'reach': 'alcanzar',
  'reaching': 'alcanzar',
  'refusal': 'negativa',
  'repair': 'reparar',
  'repaired': 'reparado',
  'returned': 'regresaron',
  'reveal': 'revelar',
  'reward': 'recompensa',
  'rough': 'imperfecto / difícil',
  'score': 'nota / puntaje',
  'stricter': 'más estrictos',
  'summary': 'resumen',
  'survives': 'sobrevive',
  'task': 'tarea',
  'tasks': 'tareas',
  'touches': 'toca',
  'unusual': 'inusual',
  'useful': 'útil',
  'usually': 'usualmente',
  'valuable': 'valioso',
  'verbal': 'verbal',
  'vibrating': 'vibrando',
  'whether': 'si / si acaso',
  'immediate': 'inmediato',
  'long-term': 'a largo plazo',
  'consequence': 'consecuencia',
  'several': 'varios',
  'realistically': 'de manera realista',
  'although': 'aunque',
  'describe': 'describir',
  'detail': 'detalle',
  'moment': 'momento',
  'direction': 'dirección',
  'define': 'definir',
  'timeline': 'cronograma',
  'delivery': 'entrega / cumplimiento',
  'specific': 'específico',
  'ignore': 'ignorar',
  'pretending': 'fingiendo',
  'solution': 'solución',
  'goal': 'meta',
  'respond': 'responder',
  'attempt': 'intento',
  'response': 'respuesta',
  'earn': 'ganar',
  'direct': 'directo',
  'focused': 'enfocado',
  'confusion': 'confusión',
  'measuring': 'midiendo',
  'suggests': 'sugiere',
  'confirm': 'confirmar',
  'practical': 'práctico',
  'partner': 'socio',
  'whose': 'de quién / cuyo',
  'payment': 'pago',
  'clause': 'cláusula',
  'ninety': 'noventa',
  'push': 'presionar / oponerse',
  'finance': 'financiar',
  'global': 'global',
  'delay': 'retrasar',
  'worldwide': 'a nivel mundial',
  'adapt': 'adaptarse',
  'refuse': 'negarse',
  'risk': 'arriesgar',
  'salaries': 'salarios',
  'cash': 'efectivo',
  'flow': 'flujo',
  'rejecting': 'rechazando',
  'deal': 'trato',
  'workable': 'viable',
  'automatic': 'automático',
  'approval': 'aprobación',
  'launch': 'lanzamiento',
  'forward': 'hacia adelante',
  'emergencies': 'emergencias',
  'sort': 'ordenar / resolver',
  'incomplete': 'incompleto',
  'account': 'cuenta',
  'separate': 'separar',
  'urgent': 'urgente',
  'set': 'establecer / configurar',
  'accounts': 'cuentas',
  'restore': 'restaurar',
  'sorted': 'resolvió / ordenó',
  'conflict': 'conflicto',
  'update': 'actualización',
  'contact': 'contacto',
  'counteroffer': 'contraoferta',
  'setup': 'configuración',
  'fee': 'tarifa',
  'during': 'durante',
  'rushed': 'apresuró',
  'drop': 'bajar / caer',
  'provider': 'proveedor',
  'failed': 'fallido',
  'careful': 'cuidadoso',
  'terms': 'términos',
  'reduce': 'reducir',
  'advance': 'adelanto',
  'halfway': 'a mitad de camino',
  'risking': 'arriesgando',
  'condition': 'condición',
  'hire': 'contratar',
  'lucía': 'Lucía',
  'town': 'pueblo',
  'crowded': 'concurrido',
  'settle': 'adaptarse',
  'role': 'puesto / función',
  'larger': 'más grande',
  'precise': 'preciso',
  'hit': 'golpear / empezar',
  'ground': 'suelo',
  'parallel': 'paralelo',
  'tracked': 'registró / monitoreó',
  'attendance': 'asistencia',
  'observed': 'observó',
  'falls': 'cae',
  'recovery': 'recuperación',
  'growth': 'crecimiento',
  'coaching': 'acompañamiento',
  'coaches': 'entrena, acompaña',
  'bar': 'estándar / barra',
  'scale': 'escala',
  'publish': 'publicar',
  'standard': 'estándar',
  'connect': 'conectarse',
  'catch': 'alcanzar / ponerse al día',
  'adult': 'adulto',
  'generation': 'generación',
  'movement': 'movimiento',
  'brand': 'marca',
  'spell': 'explicar / deletrear',
  'model': 'modelo',
  'wires': 'cables / comunicación',
  'crossed': 'cruzados / confundidos',
  'franchises': 'franquicias',
  'compare': 'comparar',
  'franchise': 'franquicia',
  'provide': 'proporcionar',
  'curriculum': 'currículo',
  'forever': 'para siempre',
  'license': 'licencia',
  'annual': 'anual',
  'based': 'basado',
  'active': 'activo',
  'partnership': 'alianza',
  'tools': 'herramientas',
  'owner': 'dueño',
  'clearer': 'más claro',
  'control': 'controlar',
  'compete': 'competir',
  'invoice': 'factura',
  'exclusivity': 'exclusividad',
  'approved': 'aprobado',
  'exclusive': 'exclusivo',
  'react': 'reaccionar',
  'facts': 'hechos',
  'receive': 'recibir',
  'files': 'archivos',
  'renata': 'Renata',
  'error': 'error',
  'document': 'documento',
  'assumed': 'supuso',
  'assumption': 'suposición',
  'straighten': 'aclarar / enderezar',
  'against': 'contra',
  'decide': 'decidir',
  'discuss': 'discutir',
  'hidden': 'oculto',
  'prove': 'demostrar',
  'takeover': 'adquisición / toma de control',

  // Sharks episodios 11-20
  'affected': 'afectado / afectados',
  'apologize': 'disculparse / pedir perdón',
  'root': 'raíz / origen',
  'cause': 'causa',
  'guess': 'suponer / adivinar',
  'glitch': 'falla técnica',
  'server': 'servidor',
  'downtime': 'tiempo fuera de servicio',
  'escalated': 'escaló / elevó a un nivel superior',
  'apology': 'disculpa',
  'accountable': 'responsable / que responde por algo',
  'attached': 'adjunto / adjuntó',
  'quarterly': 'trimestral',
  'percent': 'por ciento',
  'flat': 'plano / sin cambios',
  'average': 'promedio',
  'retention': 'retención',
  'ninety-four': 'noventa y cuatro',
  'churn': 'pérdida de clientes',
  'themselves': 'ellos mismos / ellas mismas',
  'spreadsheet': 'hoja de cálculo',
  'spreadsheets': 'hojas de cálculo',
  'forecast': 'pronóstico / proyección',
  'quarters': 'trimestres',
  'quarter': 'trimestre',
  'budget': 'presupuesto',
  'estimate': 'estimación / estimar',
  'chase': 'perseguir',
  'hope': 'esperar / esperanza',
  'investor': 'inversionista',
  'investors': 'inversionistas',
  'concession': 'concesión',
  'deposit': 'depósito / anticipo',
  'drive': 'impulsar / conducir',
  'bargain': 'negociar / ganga',
  'signature': 'firma',
  'relationship': 'relación',
  'deadline': 'fecha límite',
  'extension': 'prórroga / extensión',
  'hold': 'sostener / mantener',
  'lawyer': 'abogado',
  'notice': 'aviso / notar',
  'canceling': 'cancelando',
  'cancellation': 'cancelación',
  'trainers': 'instructores / capacitadores',
  'pull': 'jalar / retirar',
  'revenue': 'ingresos',
  'wake-up': 'llamada de atención',
  'funeral': 'funeral',
  'complaint': 'queja',
  'satisfaction': 'satisfacción',
  'survey': 'encuesta',
  'stay': 'quedarse / permanecer',
  'proof': 'prueba',
  'measurable': 'medible',
  'permanent': 'permanente',
  'guarantee': 'garantía / garantizar',
  'dashboard': 'panel de control',
  'data': 'datos',
  'transparent': 'transparente',
  'reliable': 'confiable',
  'extra': 'extra / adicional',
  'mile': 'milla',
  'slow': 'lento',
  'three-month': 'de tres meses',
  'commitment': 'compromiso',
  'rebuild': 'reconstruir',
  'credibility': 'credibilidad',
  'timezones': 'zonas horarias',
  'headquarters': 'oficina central / sede',
  'overlap': 'coincidir / traslape de horarios',
  'onboarding': 'proceso de integración',
  'policy': 'política / norma',
  'details': 'detalles',
  'workload': 'carga de trabajo',
  'delegate': 'delegar',
  'delegates': 'delega',
  'leader': 'líder',
  'salary': 'salario',
  'wavelength': 'sintonía / longitud de onda',
  'remote': 'remoto / a distancia',
  'coordinate': 'coordinar',
  'resigned': 'renunció',
  'invest': 'invertir',
  'equity': 'participación accionaria',
  'valuation': 'valoración',
  'fact': 'hecho',
  'profitable': 'rentable',
  'funding': 'financiamiento',
  'stake': 'participación / parte de la empresa',
  'seat': 'asiento / puesto',
  'ownership': 'propiedad',
  'expect': 'esperar',
  'veto': 'veto',
  'power': 'poder',
  'decision-makers': 'quienes toman las decisiones',
  'fail': 'fallar / fracasar',
  'ambition': 'ambición',
  'ambitious': 'ambicioso',
  'bite': 'morder / bocado',
  'chew': 'masticar',
  'quality': 'calidad',
  'harm': 'dañar',
  'reputation': 'reputación',
  'solid': 'sólidos',
  'certain': 'ciertos',
  'subsidiary': 'filial',
  'inconsistency': 'inconsistencia',
  'phased': 'por etapas',
  'brilliant': 'brillante',
  'jump': 'saltar',
  'body': 'cuerpo',
  'dinosaur': 'dinosaurio',
  'film': 'filmar / película',
  'further': 'más allá / más lejos',
  'fuentes': 'Fuentes (apellido)',
  'internet': 'internet',
  'apart': 'separado / aparte',
  'chess': 'ajedrez',
  'ourselves': 'nosotros mismos',
  'figure': 'cifra / figura',
  'secrets': 'secretos',
  'partners-to-be': 'futuros socios',
  'rivals': 'rivales',
  'least': 'menos / mínimo',
  'fight': 'pelear / lucha',
  'grandmother': 'abuela',
  'zone': 'zona',
  'deliver': 'entregar / cumplir',
  'one-page': 'de una página',
  'closer': 'más cerca',
  'ticket': 'boleto',
  'safe': 'seguro',
  'trip': 'viaje',
  'thin': 'delgado / ajustado',
  'refund': 'reembolso',
  'refunds': 'reembolsos',
  'bucket': 'cubeta',
  'hole': 'agujero',
  'ruined': 'arruinado',
  'insurance': 'seguro (póliza)',
  'emergency': 'emergencia',
  'funny': 'gracioso',
  'marco': 'Marco (nombre)',
  "marco's": 'de Marco',
  'metric': 'métrica',
  'column': 'columna',
  'feedback': 'retroalimentación',
  'shot': 'oportunidad / intento',
  'opposite': 'lo contrario',
  'feelings': 'sentimientos',
  'title': 'título / puesto',
  'matter': 'importar / asunto',
  'quits': 'renuncia',
  'disagree': 'estar en desacuerdo',
  'disagreeing': 'estar en desacuerdo',
  'wish': 'desear',
  'hey': 'oye',
  'thank-you': 'de agradecimiento',
  'miguel': 'Miguel (nombre)',
  'race': 'carrera',
  'appreciate': 'agradecer / valorar',
  'somewhere': 'en algún lugar',
  'along': 'a lo largo / junto',
  'truly': 'de verdad',
  'happier': 'más feliz',
  'consider': 'considerar',
  'lie': 'mentira / mentir',
  'pack': 'empacar',
  'packed': 'empacado / lleno',
  'speed': 'velocidad',
  'untrained': 'sin capacitación',
  'fluency': 'fluidez',
  'slogan': 'eslogan',
  'unhappy': 'insatisfecho',
  'receptionist': 'recepcionista',
  'tuition': 'colegiatura',
  'poetry': 'poesía',
  'matches': 'coincide',
  'abandoning': 'abandonar',
  'handoff': 'entrega / traspaso',
  'blame': 'culpar / culpa',
  'redesign': 'rediseñar',
  'internal': 'interno',
  'management': 'gestión / dirección',
  'exchange': 'intercambio',
  'vision': 'visión',
  'pedagogy': 'pedagogía',
  'sometimes': 'a veces',
  'definitely': 'definitivamente',
  'entrepreneurs': 'emprendedores',
  'lottery': 'lotería',
  'percentage': 'porcentaje',
  'fantasy': 'fantasía',
  'math': 'matemáticas',
  'accelerates': 'acelera',
  'distracts': 'distrae',
  'attach': 'adjuntar',
  'margins': 'márgenes',
  'silent': 'silencioso',
  'soon': 'pronto',
  'judgment': 'criterio / juicio',
  'huge': 'enorme',
  'exciting': 'emocionante',
  'admire': 'admirar',
  'nice-sounding': 'que suena bonito',
  'beats': 'supera / late',
  'realize': 'darse cuenta',
  'fully': 'completamente',
  'affiliated': 'afiliado',
  'pauses': 'pausa / se detiene',
  'supervise': 'supervisar',
  'track': 'seguir / rastrear',
  'mexican': 'mexicano',
  'ceremony': 'ceremonia',
  'false': 'falso',
  'release': 'comunicado / publicar',
  'politics': 'política',
  'somehow': 'de alguna manera',
  'someday': 'algún día',
  'alternative': 'alternativa',
  'september': 'septiembre',
  'december': 'diciembre',
  'boundary': 'límite / frontera',
  'simultaneously': 'simultáneamente',
  'legal': 'legal',
  'framework': 'marco / estructura',
  'territory': 'territorio',
  'regional': 'regional',
  'annex': 'anexo',
  'adaptations': 'adaptaciones',
  'roll': 'lanzar / desplegar',
  'compliance': 'cumplimiento normativo',
  'simpler': 'más simple',
  'milestone': 'hito / meta importante',
  'negotiable': 'negociable',
  'seal': 'sellar / cerrar',
  'press': 'prensa / presionar',
  'determination': 'determinación',
  'wrap': 'envolver / cerrar',
  'legacy': 'legado',
  'responsibility': 'responsabilidad',
  'negotiate': 'negociar',
  'confidence': 'confianza',
  'limit': 'límite',
  'leverage': 'ventaja / poder de negociación',
  'parent': 'padre / madre',
  'mandatory': 'obligatorio',
  'registration': 'inscripción',
  'operates': 'opera',
  'public': 'público',
  'clarify': 'aclarar',
  'negotiator': 'negociador / negociadora',
  'massive': 'masivo',
  'worth': 'vale / valor',


  a: "un / una",
  around: "alrededor / cerca de",
  below: "debajo / por debajo de",
  bottom: "fondo / parte de abajo",
  easily: "fácilmente",
  executives: "ejecutivos",
  "fifty-eight": "cincuenta y ocho",
  fly: "volar",
  flying: "volando",
  lands: "aterriza",
  mattered: "importó (pasado de \"matter\")",
  memorized: "memorizado / memoricé",
  outcomes: "resultados",
  rather: "más bien / preferiblemente",
  scream: "gritar / grito",
  shook: "sacudió / estrechó (pasado de \"shake\")",
  staying: "quedándose / hospedándose",
  strangest: "más extraño",
  suitcase: "maleta",
  wrong: "equivocado / mal",
  am: "soy / estoy",
  an: "un / una",
  and: "y",
  are: "eres / están / son",
  at: "en (un lugar)",
  back: "de regreso / atrás",
  be: "ser / estar",
  because: "porque",
  but: "pero",
  can: "poder",
  come: "ven / venir",
  day: "día",
  do: "hacer",
  everyone: "todos",
  for: "para / por",
  friend: "amiga / amigo",
  from: "de (origen)",
  get: "obtener / conseguir",
  girl: "chica",
  go: "ir",
  goes: "va",
  good: "bueno / buena",
  guy: "chavo / tipo",
  has: "tiene",
  have: "tener",
  he: "él",
  hello: "hola",
  her: "su / de ella",
  here: "aquí",
  hi: "hola",
  his: "su / de él",
  how: "cómo",
  i: "yo",
  in: "en / dentro de",
  is: "es / está",
  it: "eso / lo",
  like: "gustar / como",
  look: "mirar",
  looks: "se ve / mira",
  make: "hacer",
  making: "haciendo",
  man: "hombre",
  amazing: "increíble / asombroso",
  celebrate: "celebrar",
  diploma: "diploma",
  envelope: "sobre",
  graduation: "graduación",
  proud: "orgulloso / orgullosa",
  confetti: "confeti",
  hugs: "abraza",
  tears: "lágrimas",
  wall: "pared",
  antigua: "Antigua",
  challenges: "retos / desafíos",
  color: "color",
  did: "hizo (pasado de hacer)",
  forgets: "olvida",
  great: "genial / excelente",
  guatemala: "Guatemala",
  live: "vivir",
  love: "amar / encantar",
  mouth: "boca",
  opens: "abre",
  orange: "naranja",
  partners: "compañeros / parejas",
  part: "parte",
  practice: "practicar",
  polish: "perfeccionar; pulir",
  process: "proceso",
  sees: "ve",
  twenty: "veinte",
  two: "dos",
  words: "palabras",
  me: "me / mí",
  my: "mi",
  new: "nuevo / nueva",
  nice: "agradable / qué gusto",
  no: "no",
  not: "no",
  now: "ahora",
  of: "de",
  ok: "está bien",
  on: "en / encima de / puesto",
  one: "uno / una",
  or: "o",
  out: "afuera",
  people: "gente / personas",
  please: "por favor",
  say: "decir",
  says: "dice",
  she: "ella",
  so: "así que / tan",
  speak: "hablar",
  speaks: "habla",
  take: "tomar",
  takes: "toma",
  thank: "agradecer",
  thanks: "gracias",
  that: "eso / que",
  the: "el / la / los / las",
  their: "su / de ellos",
  them: "ellos / les",
  then: "entonces / después",
  there: "ahí / allá",
  they: "ellos / ellas",
  this: "este / esta / esto",
  time: "tiempo / vez",
  to: "a / para",
  today: "hoy",
  too: "también / demasiado",
  up: "arriba",
  us: "nosotros / nos",
  very: "muy",
  was: "era / estaba / fue",
  we: "nosotros",
  well: "bien / pues",
  what: "qué",
  when: "cuándo",
  where: "dónde",
  who: "quién",
  why: "por qué",
  with: "con",
  woman: "mujer",
  work: "trabajo / trabajar",
  yes: "sí",
  you: "tú / usted",
  your: "tu / tuyo",
  yourself: "a ti misma / a ti mismo",
  // Episodes 4-7
  again: "otra vez / de nuevo",
  always: "siempre",
  answer: "respuesta",
  answers: "contesta / respuestas",
  ask: "preguntar",
  asks: "pregunta",
  awesome: "genial / increíble",
  balloons: "globos",
  believe: "creer",
  big: "grande",
  blue: "azul",
  box: "caja",
  breathes: "respira",
  canada: "Canadá",
  challenge: "reto",
  city: "ciudad",
  claps: "aplaude",
  clear: "clara / claro",
  client: "cliente",
  closes: "cierra",
  cold: "frío / frías",
  colors: "colores",
  curious: "curiosa / curioso",
  dancing: "bailar",
  disciplined: "disciplinada / disciplinado",
  dylan: "Dylan",
  dani: "Dani",
  everybody: "todos",
  everywhere: "por todas partes",
  every: "cada / todos los",
  excited: "emocionada / emocionado",
  eyes: "ojos",
  family: "familia",
  fast: "rápido",
  fluent: "fluida / fluido",
  food: "comida",
  forget: "olvidar",
  friendly: "amable / amigable",
  full: "llena / lleno",
  green: "verde",
  happy: "feliz / alegre",
  heart: "corazón",
  hungry: "con hambre",
  introductions: "presentaciones",
  jacket: "chaqueta",
  know: "saber / conocer",
  laughs: "se ríe",
  long: "larga / largo",
  loud: "llamativo / ruidoso",
  meet: "conocer",
  meeting: "reunión",
  message: "mensaje",
  mistakes: "errores",
  more: "más",
  morning: "mañana (parte del día)",
  music: "música",
  nature: "naturaleza",
  confident: "seguro / segura de sí",
  natural: "natural",
  rising: "subiendo / en aumento",
  credit: "crédito / mérito",
  route: "ruta / camino",
  listener: "quien escucha / oyente",
  analysis: "análisis",
  gap: "brecha / diferencia",
  pause: "pausa",
  audited: "auditado / revisado",
  force: "obligar / forzar",
  rambled: "divagué / divagó",
  nervous: "nerviosa / nervioso",
  news: "noticias",
  nineteen: "diecinueve",
  note: "nota",
  notebook: "cuaderno",
  opportunity: "oportunidad",
  perfect: "perfecto / perfecta",
  phone: "teléfono",
  pizza: "pizza",
  practices: "practica",
  project: "proyecto",
  reason: "razón",
  rings: "suena",
  room: "sala / cuarto",
  screen: "pantalla",
  short: "corta / corto",
  shows: "muestra",
  silence: "silencio",
  soccer: "fútbol",
  sound: "sonar / sonido",
  still: "todavía",
  sun: "sol",
  surprise: "sorpresa",
  team: "equipo",
  thinks: "piensa",
  tomorrow: "mañana",
  toronto: "Toronto",
  try: "intento / intentar",
  turn: "turno",
  voice: "voz",
  warm: "cálida / cálido",
  whole: "todo / entero",
  word: "palabra",
  writes: "escribe",
  yellow: "amarillo",
  // Episodes 8-12
  age: "edad",
  angry: "enojada / enojado",
  another: "otro / otra",
  best: "mejor",
  brave: "valiente",
  brother: "hermano",
  build: "construir",
  business: "negocio",
  cheese: "queso",
  cooking: "cocinar",
  creative: "creativa / creativo",
  dance: "bailar / baile",
  designs: "diseños",
  difficult: "difícil",
  dreams: "sueña / sueños",
  empty: "vacía / vacío",
  embarrassed: "avergonzada / avergonzado",
  excellent: "excelente",
  favorite: "favorito / favorita",
  feels: "siente",
  future: "futuro",
  grow: "crecer",
  hard: "difícil / duro",
  help: "ayuda / ayudar",
  hobbies: "pasatiempos",
  honduras: "Honduras",
  important: "importante",
  interview: "entrevista",
  invitation: "invitación",
  lunch: "almuerzo",
  lives: "vive",
  move: "movimiento / mover",
  own: "propio / propia",
  photos: "fotos",
  presentation: "presentación",
  pupusas: "pupusas",
  purple: "morado",
  ready: "lista / listo",
  records: "graba",
  refrigerator: "refrigerador",
  remind: "recordar",
  reminds: "recuerda",
  san: "San",
  smells: "huele",
  small: "pequeño / poco a poco",
  special: "especial",
  starts: "comienza",
  supervisor: "supervisor / supervisora",
  talent: "talento",
  tamales: "tamales",
  thirty: "treinta",
  videos: "videos",
  watching: "mirando",
  years: "años",
  // Season 2 words
  activities: "actividades",
  bilingual: "bilingüe",
  bring: "traer / llevar",
  busy: "ocupado / ocupada",
  cafe: "café",
  champion: "campeón / campeona",
  clock: "reloj",
  college: "universidad / colegio",
  company: "empresa",
  director: "director / directora",
  dream: "sueño",
  early: "temprano",
  event: "evento",
  exercise: "ejercicio / hacer ejercicio",
  grant: "apoyo financiero / beca",
  idea: "idea",
  invite: "invitar",
  join: "unirse",
  lead: "liderar",
  markers: "marcadores",
  media: "medios / redes",
  month: "mes",
  notes: "apuntes",
  opportunities: "oportunidades",
  organizers: "organizadores / organizadoras",
  persistent: "persistente",
  plan: "plan",
  posters: "carteles",
  relax: "descansar / relajarse",

  review: "repasar",
  saturday: "sábado",
  serious: "serio / seria",
  sleep: "dormir",
  social: "social",
  step: "paso",
  study: "estudiar",
  travel: "viajar",
  wake: "despertar",
  workshop: "taller",
  worried: "preocupado / preocupada",
  write: "escribir",
  young: "joven / jóvenes",
  // Season 3 routines
  three: "tres",
  four: "cuatro",
  five: "cinco",
  six: "seis",
  seven: "siete",
  eight: "ocho",
  nine: "nueve",
  ten: "diez",
  mom: "mamá",
  dad: "papá",
  sunday: "domingo",
  office: "oficina",
  "o'clock": "en punto",
  ball: "pelota / balón",
  flashlight: "linterna",
  block: "cuadra",
  heavy: "pesado / pesada",
  neighbors: "vecinos / vecinas",
  tourists: "turistas",
  often: "a menudo / seguido",
  song: "canción",
  casting: "audición",
  queue: "cola / fila",
  shouts: "grita / gritan",
  // --- Cobertura general de todas las temporadas ---
  will: "va a (futuro)",
  first: "primero / primera",
  second: "segundo / segunda",
  next: "siguiente / próximo",
  last: "último / pasado",
  class: "clase",
  about: "sobre / acerca de",
  night: "noche",
  afternoon: "tarde",
  name: "nombre",
  school: "escuela",
  call: "llamada / llamar",
  him: "él / lo / le",
  after: "después de",
  before: "antes de",
  student: "estudiante",
  job: "trabajo / empleo",
  little: "pequeño / poquito",
  all: "todo / todos",
  teacher: "maestra / maestro",
  need: "necesitar",
  smile: "sonrisa / sonreír",
  red: "rojo / roja",
  white: "blanco / blanca",
  black: "negro / negra",
  gold: "oro / dorado",
  golden: "dorado / dorada",
  home: "casa / hogar",
  house: "casa",
  door: "puerta",
  el: "El (parte de «El Salvador»)",
  start: "empezar",
  front: "frente",
  want: "querer",
  story: "historia / cuento",
  stories: "historias",
  our: "nuestro / nuestra",
  hand: "mano",
  week: "semana",
  than: "que (en comparaciones)",
  book: "libro",
  walk: "caminar",
  fifty: "cincuenta",
  forty: "cuarenta",
  twelve: "doce",
  eleven: "once",
  fourteen: "catorce",
  hundred: "cien",
  open: "abrir / abierto",
  boss: "jefe / jefa",
  lot: "montón (a lot = mucho)",
  minute: "minuto",
  option: "opción",
  old: "viejo / mayor",
  older: "mayor / más grande",
  under: "debajo de",
  over: "sobre / encima",
  video: "video",
  into: "hacia dentro de",
  okay: "está bien",
  alright: "muy bien / de acuerdo",
  real: "real / de verdad",
  nobody: "nadie",
  somebody: "alguien",
  someone: "alguien",
  something: "algo",
  anything: "algo / nada (en preguntas)",
  everything: "todo",
  right: "correcto / derecha",
  eat: "comer",
  drink: "beber / tomar",
  coffee: "café",
  year: "año",
  finally: "por fin / finalmente",
  grandma: "abuela",
  ago: "hace (tiempo)",
  myself: "yo mismo / a mí mismo",
  herself: "ella misma",
  himself: "él mismo",
  thing: "cosa",
  give: "dar",
  some: "algunos / un poco",
  think: "pensar",
  friday: "viernes",
  monday: "lunes",
  tuesday: "martes",
  wednesday: "miércoles",
  thursday: "jueves",
  see: "ver",
  table: "mesa",
  boy: "niño / muchacho",
  sandwich: "sándwich",
  explain: "explicar",
  tell: "decir / contar",
  quiet: "callado / tranquilo",
  talk: "hablar",
  while: "mientras",
  arrive: "llegar",
  sales: "ventas",
  course: "curso (of course = claro)",
  support: "apoyo / apoyar",
  other: "otro / otra",
  others: "otros / otras",
  stop: "parar / detener",
  person: "persona",
  app: "aplicación",
  problem: "problema",
  bus: "autobús / camioneta",
  same: "mismo / igual",
  send: "enviar / mandar",
  much: "mucho",
  many: "muchos / muchas",
  most: "la mayoría / el más",
  half: "mitad",
  check: "revisar / checar",
  sit: "sentarse",
  breakfast: "desayuno",
  dinner: "cena",
  yesterday: "ayer",
  play: "jugar / tocar",
  game: "juego / partido",
  floor: "piso",
  better: "mejor (comparativo)",
  father: "padre",
  mother: "madre",
  sister: "hermana",
  son: "hijo",
  daughter: "hija",
  kitchen: "cocina",
  shake: "temblar / sacudir",
  teach: "enseñar",
  listen: "escuchar",
  hear: "oír / escuchar",
  once: "una vez",
  upon: "sobre (once upon a time = había una vez)",
  hour: "hora",
  question: "pregunta",
  by: "por / junto a",
  already: "ya",
  also: "también",
  pedro: "Pedro (nombre)",
  sula: "Sula (parte de «San Pedro Sula»)",
  wet: "mojado / mojada",
  cannot: "no puede",
  star: "estrella",
  easy: "fácil",
  bad: "malo / mala",
  suddenly: "de repente",
  together: "juntos / juntas",
  outside: "afuera",
  inside: "adentro",
  order: "orden / pedir",
  enter: "entrar",
  piece: "pedazo / pieza",
  customer: "cliente",
  water: "agua",
  close: "cerrar / cerca",
  demo: "demostración",
  way: "manera / camino",
  laugh: "reír",
  computer: "computadora",
  finish: "terminar",
  egg: "huevo",
  end: "final / terminar",
  raise: "levantar / subir",
  late: "tarde",
  free: "gratis / libre",
  pm: "p. m. (de la tarde/noche)",
  am_time: "a. m. (de la mañana)",
  past: "pasado",
  breathe: "respirar",
  deeply: "profundamente",
  deep: "profundo",
  breath: "respiración",
  light: "luz",
  street: "calle",
  hide: "esconderse",
  wait: "esperar",
  place: "lugar",
  energy: "energía",
  simple: "simple / sencillo",
  ai: "IA (inteligencia artificial)",
  board: "pizarra / tablero",
  quick: "rápido",
  spring: "primavera",
  honestly: "honestamente / la verdad",
  buzz: "vibrar / zumbar",
  use: "usar",
  low: "bajo / baja",
  amarillo: "amarillo (palabra en español)",
  oh: "oh (expresión)",
  ah: "ah (expresión)",
  wow: "wow / ¡guau!",
  introduce: "presentar(se)",
  appear: "aparecer",
  folder: "carpeta",
  mexico: "México",
  candidate: "candidato / candidata",
  program: "programa",
  button: "botón",
  each: "cada",
  interviewer: "entrevistador / entrevistadora",
  shirt: "camisa",
  bench: "banca",

  juice: "jugo",
  strong: "fuerte",
  stronger: "más fuerte",
  tight: "apretado / fuerte",
  flyer: "volante / folleto",
  single: "solo / único",
  pupusa: "pupusa (comida salvadoreña)",
  hot: "caliente",
  colorful: "colorido / lleno de color",
  "piñata": "piñata",
  memory: "recuerdo / memoria",
  desk: "escritorio",
  level: "nivel",
  shine: "brillar",
  top: "arriba / lo más alto",
  anymore: "ya no",
  cry: "llorar",
  window: "ventana",
  add: "agregar / añadir",
  santa: "Santa (parte de un nombre)",
  cheer: "animar / echar porras",
  prepare: "preparar",
  sell: "vender",
  must: "deber (obligación)",
  find: "encontrar",
  phrase: "frase",
  whisper: "susurrar",
  watch: "mirar / ver",
  international: "internacional",
  face: "cara",
  park: "parque",
  change: "cambiar",
  sky: "cielo",
  few: "pocos / unos pocos",
  remember: "recordar",
  run: "correr",
  dressed: "vestido / vestida",
  shift: "turno (de trabajo)",
  leave: "salir / dejar",
  behind: "detrás",
  calm: "calmado / calmar",
  soda: "gaseosa / refresco",
  don: "Don (título de respeto)",
  bag: "bolsa",
  sing: "cantar",
  routine: "rutina",
  understand: "entender",
  manual: "manual",
  luck: "suerte",
  chat: "chat / platicar",
  later: "después / más tarde",
  headset: "diadema con micrófono",
  stand: "estar de pie / pararse",
  priority: "prioridad",
  sir: "señor",
  alive: "vivo / viva",
  bean: "frijol",
  tv: "tele / televisión",
  sentence: "oración / frase",
  united: "unidos",
  state: "estado",
  cook: "cocinar",
  mine: "mío / mía",
  hang: "colgar",
  mango: "mango",
  market: "mercado",
  hug: "abrazar",
  as: "como / mientras",
  arm: "brazo",
  worry: "preocuparse",
  just: "solo / apenas",
  ice: "hielo",
  cream: "crema (ice cream = helado)",
  off: "apagado / fuera",
  bathroom: "baño",
  corner: "esquina",
  store: "tienda",
  break: "romper / descanso",
  sick: "enfermo / enferma",
  away: "lejos / fuera",
  share: "compartir",
  shout: "gritar",
  becoming: "convirtiéndose en",
  follow: "seguir",
  photo: "foto",
  paper: "papel",
  sad: "triste",
  sweet: "dulce",
  count: "contar (números)",
  wash: "lavar",
  feel: "sentir",
  center: "centro",
  enough: "suficiente",
  magic: "magia / mágico",
  poor: "pobre",
  terrified: "aterrado / con mucho miedo",
  pick: "recoger / escoger",
  party: "fiesta",
  down: "abajo",
  shorter: "más corto",
  road: "carretera / camino",
  lying: "acostado / mintiendo",
  strange: "extraño / raro",
  stupid: "tonto / tonta",
  wolf: "lobo",
  through: "a través de",
  forest: "bosque",
  fine: "bien",
  bread: "pan",
  save: "salvar / ahorrar",
  recording: "grabación",
  beginning: "principio / comienzo",
  choose: "elegir / escoger",
  imagine: "imaginar",
  storyteller: "narrador / cuentacuentos",
  toward: "hacia",
  alarm: "alarma",
  win: "ganar",
  thumb: "pulgar (thumbs up = pulgar arriba)",
  emoji: "emoji",
  never: "nunca",
  keep: "mantener / seguir",
  god: "Dios",
  clean: "limpiar / limpio",
  without: "sin",
  latin: "latino / latina",
  america: "América",
  grammar: "gramática",
  ahead: "adelante",
  protect: "proteger",
  which: "cuál / que",
  general: "general",
  situation: "situación",
  show: "mostrar / enseñar",
  side: "lado",
  point: "punto",
  if: "si (condición)",
  "six-month": "de seis meses",
  explode: "explotar",
  celebration: "celebración",
  ceo: "director general (CEO)",
  smooth: "suave / sin problemas",
  professional: "profesional",
  life: "vida",
  tiktok: "TikTok",
  repeat: "repetir",
  lose: "perder",
  started: "empezó",
  spend: "pasar (tiempo) / gastar",
  // Eagles (temporada 6) vocabulario adicional
  adjectives: "adjetivos",
  almost: "casi",
  anywhere: "en cualquier lugar",
  bigger: "más grande",
  both: "ambos / los dos",
  buy: "comprar",
  car: "carro",
  chair: "silla",
  classroom: "salón de clases",
  contract: "contrato",
  corporate: "corporativo / de empresa",
  costs: "cuesta / costos",
  could: "podría",
  crosses: "cruza / tacha",
  cut: "cortar / recortar",
  different: "diferente",
  either: "tampoco / cualquiera",
  evening: "la tarde-noche",
  exist: "existir",
  freeze: "congelarse / quedarse en blanco",
  group: "grupo",
  holds: "sostiene",
  less: "menos",
  let: "dejar / permitir",
  might: "tal vez / podría",
  module: "módulo",
  money: "dinero",
  newer: "más nuevo",
  online: "en línea",
  opinion: "opinión",
  page: "página",
  panicked: "entró en pánico",
  panicking: "entrando en pánico",
  presses: "presiona",
  price: "precio",
  prices: "precios",
  promise: "prometer / promesa",
  proposal: "propuesta",
  proposes: "propone",
  rang: "sonó",
  record: "grabar",
  risky: "arriesgado",
  should: "debería",
  signing: "firmando",
  sixty: "sesenta",
  speaker: "altavoz / quien habla",
  stays: "se queda",
  sure: "seguro / claro",
  these: "estos / estas",
  those: "esos / esas",
  tired: "cansada",
  tonight: "esta noche",
  trust: "confiar",
  valentina: "Valentina (nombre)",
  website: "sitio web",
  yet: "todavía",
  "two-minute": "de dos minutos",
  "twenty-two": "veintidós",
  "twenty-six": "veintiséis",
  adults: "adultos",
  alone: "solo / sola",
  american: "estadounidense",
  americans: "estadounidenses",
  between: "entre",
  card: "tarjeta",
  clothes: "ropa",
  collects: "colecciona / recoge",
  complains: "se queja",
  directly: "directamente",
  ever: "alguna vez",
  fifteen: "quince",
  fix: "arreglar / resolver",
  happened: "pasó / sucedió",
  hotel: "hotel",
  includes: "incluye",
  information: "información",
  instead: "en vez de eso",
  learned: "aprendí / aprendido",
  louder: "más ruidoso",
  manager: "gerente",
  miami: "Miami (ciudad)",
  neighbor: "vecino",
  none: "ninguno",
  normal: "normal",
  nothing: "nada",
  platform: "plataforma",
  rule: "regla",
  schedule: "horario",
  schedules: "horarios",
  scheduling: "programación de horarios",
  services: "servicios",
  signed: "firmó / firmado",
  since: "desde",
  slot: "espacio / turno",
  solve: "resolver",
  split: "dividir",
  sweated: "sudé / sudado",
  temperature: "temperatura",
  tests: "pone a prueba / pruebas",
  translate: "traducir",
  twice: "dos veces",
  versions: "versiones",
  zero: "cero",
  accident: "accidente",
  afraid: "con miedo / temeroso",
  agenda: "agenda",
  agrees: "está de acuerdo",
  air: "aire",
  airplane: "avión",
  anybody: "alguien / nadie",
  anyway: "de todos modos",
  argues: "discute",
  argument: "discusión / argumento",
  assistant: "asistente",
  attacks: "ataca",
  audience: "público",
  become: "convertirse en / llegar a ser",
  becomes: "se convierte en",
  belongs: "pertenece",
  care: "cuidado / importar",
  chart: "gráfico / cuadro",
  cheap: "barato",
  cheaper: "más barato",
  cheapest: "el más barato",
  checklist: "lista de verificación",
  choice: "elección / opción",
  columns: "columnas",
  contagious: "contagioso",
  continue: "continuar",
  conversation: "conversación",
  convince: "convencer",
  copies: "copias",
  correct: "correcto / corregir",
  cost: "costo / costar",
  criteria: "criterios",
  date: "fecha / cita",
  deciding: "decidiendo",
  decision: "decisión",
  skip: "saltarse / omitir",
  calmest: "más calmada",
  houston: "Houston (ciudad de EE. UU.)",
  rest: "resto",
  weekend: "fin de semana",
  unexpected: "inesperado",
  sense: "sentido",
  version: "versión",
  calculated: "calculé / calculó",
  healthy: "sano / saludable",
  shark: "tiburón",
  sharks: "tiburones",
  reed: "Reed (apellido)",
  received: "recibí / recibió",
  pushed: "presionó / empujó",
  smell: "oler",
  bluffing: "fanfarroneando / faroleando",
  lower: "más bajo",
  argue: "discutir / debatir",
  difference: "diferencia",
  panic: "pánico / entrar en pánico",
  defend: "defender",
  defends: "defiende",
  die: "morir",
  doubting: "dudando",
  draws: "dibuja / traza",
  easiest: "el más fácil",
  effort: "esfuerzo",
  eighteen: "dieciocho",
  exactly: "exactamente",
  expensive: "caro",
  far: "lejos",
  faster: "más rápido",
  fastest: "el más rápido",
  grid: "cuadrícula",
  happen: "pasar / suceder",
  happens: "pasa / sucede",
  hardest: "el más difícil",
  heavier: "más pesado",
  heroic: "heroico",
  high: "alto",
  honest: "honesto",
  optimism: "optimismo",
  measurement: "medición",
  vocabulary: "vocabulario",
  criticism: "crítica",
  colleague: "colega",
  rehearsing: "ensayando",
  hurting: "lastimando / doliendo",
  immediately: "inmediatamente",
  immigration: "migración",
  interrupt: "interrumpir",
  kids: "niños / hijos",
  language: "idioma",
  laptop: "computadora portátil",
  learn: "aprender",
  lesson: "lección",
  line: "línea / fila",
  lines: "líneas / filas",
  list: "lista",
  local: "local",
  may: "puede que / poder",
  midnight: "medianoche",
  mirror: "espejo",
  neither: "ninguno de los dos / tampoco",
  number: "número",
  numbers: "números",
  offers: "ofrece / ofertas",
  officer: "oficial / agente",
  paperwork: "papeleo",
  parents: "padres",
  pay: "pagar",
  pen: "bolígrafo",
  pilot: "piloto",
  position: "puesto / posición",
  possible: "posible",
  projector: "proyector",
  recognizes: "reconoce",
  rehearsal: "ensayo",
  report: "informe / reportar",
  reports: "informes / reporta",
  results: "resultados",
  ring: "sonar (el teléfono) / anillo",
  safest: "el más seguro",
  scared: "asustado",
  season: "temporada",
  shoes: "zapatos",
  skill: "habilidad",
  slides: "diapositivas",
  slower: "más lento",
  smart: "inteligente",
  spoken: "hablado",
  strongest: "el más fuerte",
  taken: "tomado",
  technical: "técnico",
  third: "tercero",
  "thirty-eight": "treinta y ocho",
  traffic: "tráfico",
  tricks: "trucos",
  uniform: "uniforme",
  until: "hasta",
  volunteers: "se ofrece de voluntario / voluntarios",
  votes: "vota / votos",
  wears: "usa (ropa)",
  welcome: "bienvenido",
  worst: "el peor",
  would: "(condicional: -ía)",
  absolute: "absoluto / total",
  academic: "académico",
  academies: "academias",
  academy: "academia",
  accept: "aceptar",
  accepted: "aceptó / aceptado",
  achievement: "logro",
  achievements: "logros",
  across: "a través de / al otro lado",
  action: "acción",
  actually: "en realidad",
  agree: "estar de acuerdo",
  agreed: "estuvo de acuerdo",
  annoying: "molesto",
  any: "algún / ninguno",
  anyone: "alguien / cualquiera",
  article: "artículo",
  balloon: "globo",
  beautiful: "hermoso / hermosa",
  bicycle: "bicicleta",
  biggest: "el más grande",
  born: "nacido / nacida",
  broken: "roto",
  career: "carrera",
  carefully: "con cuidado",
  case: "caso",
  chain: "cadena",
  chains: "cadenas",
  chicken: "pollo",
  circle: "círculo",
  community: "comunidad",
  compared: "comparado",
  comparison: "comparación",
  competition: "competencia",
  competitor: "competidor",
  complete: "completo / completar",
  completion: "finalización",
  conditioning: "acondicionamiento",
  congratulations: "felicidades",
  coordinator: "coordinador",
  coordinators: "coordinadores",
  copied: "copió / copiado",
  copy: "copiar / copia",
  copying: "copiando",
  countries: "países",
  country: "país",
  cute: "lindo / lindа",
  dangerous: "peligroso",
  daylight: "luz del día",
  decided: "decidió",
  decides: "decide",
  delivered: "entregó / entregado",
  designed: "diseñó / diseñado",
  destroy: "destruir",
  doctor: "doctor / doctora",
  dog: "perro",
  dollar: "dólar",
  draw: "dibujar",
  drew: "dibujó",
  easier: "más fácil",
  eaten: "comido",
  education: "educación",
  elegant: "elegante",
  else: "más / otra cosa",
  email: "correo electrónico",
  emails: "correos electrónicos",
  enemy: "enemigo",
  enormous: "enorme",
  especially: "especialmente",
  evaluated: "evaluó / evaluado",
  even: "incluso",
  example: "ejemplo",
  excuse: "disculpa",
  expansion: "expansión",
  expected: "esperaba / esperado",
  experience: "experiencia",
  external: "externo",
  fair: "justo",
  fan: "admirador / ventilador",
  fear: "miedo",
  "fifty-fifty": "mitad y mitad",
  filled: "llenó / lleno",
  final: "final",
  finale: "cierre final",
  flexibility: "flexibilidad",
  floated: "flotó",
  football: "fútbol",
  forgot: "olvidó",
  "forty-five": "cuarenta y cinco",
  fourth: "cuarto",
  fruit: "fruta",
  funniest: "el más divertido",
  garage: "garaje / cochera",
  gentlemen: "señores",
  giant: "gigante",
  gift: "regalo",
  goodbye: "adiós",
  "goodbye ": "adiós",
  grey: "gris",
  guests: "invitados",
  ha: "ja (risa)",
  "hand-written": "escrito a mano",
  hates: "odia",
  hired: "contrató / contratado",
  history: "historia",
  hm: "mmm (duda)",
  hmm: "mmm (duda)",
  homework: "tarea",
  human: "humano",
  humans: "humanos",
  "hundred-student": "de cien estudiantes",
  improve: "mejorar",
  interested: "interesado",
  interesting: "interesante",
  introduction: "presentación",
  january: "enero",
  kid: "niño / chavo",
  kill: "matar",
  kind: "amable / tipo",
  lady: "señora",
  laughter: "risa",
  leadership: "liderazgo",
  learner: "estudiante",
  legs: "piernas",
  lemonade: "limonada",
  letters: "cartas / letras",
  longer: "más largo / más tiempo",
  machine: "máquina",
  manage: "manejar / administrar",
  map: "mapa",
  march: "marzo",
  mark: "marca / marcar",
  materials: "materiales",
  maybe: "tal vez",
  mean: "significar / malo",
  member: "miembro",
  members: "miembros",
  method: "método",
  middle: "medio",
  mija: "mija (cariño)",
  mind: "mente",
  mistake: "error",
  mixed: "mezclado",
  motorcycle: "motocicleta",
  national: "nacional",
  neighborhood: "colonia / vecindario",
  newspaper: "periódico",
  noon: "mediodía",
  obviously: "obviamente",
  offer: "oferta / ofrecer",
  offered: "ofreció",
  official: "oficial",
  officially: "oficialmente",
  operation: "operación",
  organize: "organizar",
  organized: "organizó / organizado",
  painted: "pintó / pintado",
  pale: "pálido",
  pass: "pasar / aprobar",
  passed: "pasó / aprobó",
  patience: "paciencia",
  peace: "paz",
  per: "por (cada)",
  personal: "personal",
  personality: "personalidad",
  picture: "foto / imagen",
  plant: "planta",
  plants: "plantas",
  pleasure: "placer / gusto",
  plus: "más",
  possibilities: "posibilidades",
  possibility: "posibilidad",
  present: "presente / presentar",
  pressure: "presión",
  print: "imprimir",
  printed: "impreso",
  probably: "probablemente",
  progress: "progreso",
  pronunciation: "pronunciación",
  purchase: "compra",
  quietest: "el más callado",
  rate: "tarifa / ritmo",
  reception: "recepción",
  regular: "regular / normal",
  rehearsed: "ensayó / ensayado",
  renewal: "renovación",
  respect: "respeto",
  section: "sección",
  cover: "cubrir / alcanzar",
  term: "plazo / término",
  vague: "vago / impreciso",
  aggressive: "agresivo",
  mute: "silencio (silenciar)",
  hurts: "daña / afecta",
  lowest: "el más bajo",
  reasonable: "razonable",
  within: "dentro de",
  "forty-eight": "cuarenta y ocho",
  request: "petición / solicitud",
  restaurant: "restaurante",
  result: "resultado",
  rice: "arroz",
  sale: "venta",
  salespeople: "vendedores",
  salesperson: "vendedor",
  science: "ciencia",
  screamed: "gritó",
  service: "servicio",
  session: "sesión",
  shhh: "shhh (silencio)",
  shoe: "zapato",
  shop: "tienda",
  shops: "tiendas",
  shyest: "el más tímido",
  sign: "firmar / letrero",
  signs: "firma / letreros",
  "sixty-eight": "sesenta y ocho",
  slowly: "despacio",
  smaller: "más pequeño",
  smallest: "el más pequeño",
  sorry: "lo siento",
  stayed: "se quedó",
  success: "éxito",
  suit: "traje",
  summarize: "resumir",
  superlative: "superlativo",
  system: "sistema",
  tall: "alto",
  teeth: "dientes",
  tense: "tiempo verbal / tenso",
  terrible: "terrible",
  test: "prueba / examen",
  thousand: "mil",
  "three-million-dollar": "de tres millones de dólares",
  toasted: "tostado",
  tomatoes: "tomates",
  tourist: "turista",
  tradition: "tradición",
  trained: "entrenó / capacitado",
  training: "capacitación",
  trees: "árboles",
  truck: "camión",
  true: "verdadero / cierto",
  "twenty-eight": "veintiocho",
  "twenty-five": "veinticinco",
  ugly: "feo",
  universe: "universo",
  unofficially: "de manera no oficial",
  verbs: "verbos",
  victory: "victoria",
  visit: "visita / visitar",
  visited: "visitó",
  visitor: "visitante",
  vote: "voto / votar",
  vs: "contra",
  world: "mundo",
  strategy: "estrategia",
  references: "referencias",
  demonstrates: "demuestra",
  purpose: "propósito",
  written: "escrito",
  accountant: "contador / contadora",
  asleep: "dormido",
  bank: "banco",
  bet: "apuesta / apostar",
  boring: "aburrido",
  caught: "detectó / atrapó (pasado de \"catch\")",
  committee: "comité",
  "double-check": "revisar dos veces",
  fit: "caber / encajar",
  forced: "forzado / obligado",
  formula: "fórmula",
  founder: "fundador / fundadora",
  greatest: "el más grande / mayor",
  harder: "más difícil",
  interruptions: "interrupciones",
  invent: "inventar",
  meant: "quiso decir / significó (pasado de \"mean\")",
  mix: "mezcla / mezclar",
  mode: "modo",
  paints: "pinta",
  perfectionism: "perfeccionismo",
  pretty: "bastante / bonito",
  progressive: "progresivo",
  rain: "lluvia / llover",
  rainy: "lluvioso",
  recruiter: "reclutador / reclutadora",
  region: "región",
  removes: "quita / elimina",
  round: "ronda",
  ruins: "arruina",
  shy: "tímido",
  strength: "fortaleza",
  strengths: "fortalezas",
  traditional: "tradicional",
  trouble: "problema",
  value: "valor",
  wearing: "usando / llevando puesto",
  winners: "ganadores",
  wonderful: "maravilloso",
  adjective: "adjetivo",
  announced: "anunció / anunciado",
  assume: "asumir / suponer",
  carried: "llevó / cargó",
  chosen: "elegido / escogido",
  commercially: "comercialmente",
  correction: "corrección",
  create: "crear",
  curveball: "pregunta inesperada / bola curva",
  dig: "escarbar / profundizar",
  digging: "escarbando / profundizando",
  doorway: "puerta / entrada",
  enjoyed: "disfrutó / disfrutado",
  except: "excepto / salvo",
  "follow-up": "seguimiento",
  fewer: "menos (en cantidad contable)",
  fill: "llenar",
  fire: "despedir / fuego",
  habit: "hábito / costumbre",
  hostile: "hostil",
  increase: "aumentar / aumento",
  kinder: "más amable",
  land: "conseguir / aterrizar",
  lecture: "sermón / clase magistral",
  loop: "ciclo / círculo",
  loyalty: "lealtad",
  nearly: "casi",
  obvious: "obvio / evidente",
  offends: "ofende",
  onto: "sobre / hacia",
  operator: "operador / operadora",
  pain: "dolor",
  principle: "principio",
  produced: "produjo / producido",
  produces: "produce",
  recommendation: "recomendación",
  remove: "quitar / eliminar",
  rescued: "rescató / rescatado",
  strangers: "desconocidos / extraños",
  suspect: "sospechar",
  threw: "lanzó / tiró",
  yourselves: "ustedes mismos",
};


/** Character, place and language names used across the seasons. */
export const PROPER_NOUNS: Record<string, string> = {
  vale: "Vale (nombre de persona)",
  valeria: "Valeria (nombre completo de Vale)",
  "vale's": "de Vale",
  dani: "Dani (nombre de persona)",
  "dani's": "de Dani",
  kat: "Kat (nombre de persona)",
  ana: "Ana (nombre de persona)",
  luis: "Luis (nombre de persona)",
  mateo: "Mateo (nombre de persona)",
  camila: "Camila (nombre de persona)",
  beto: "Beto (nombre de persona)",
  tito: "Tito (nombre de persona)",
  dylan: "Dylan (nombre de persona)",
  morgan: "Morgan (nombre de persona)",
  reyes: "Reyes (apellido)",
  mr: "Sr. (señor)",
  mrs: "Sra. (señora)",
  ms: "Srta. / Sra.",
  miss: "señorita",
  salvador: "Salvador (parte de «El Salvador»)",
  guatemala: "Guatemala (país)",
  antigua: "Antigua (ciudad de Guatemala)",
  london: "Londres",
  northline: "Northline (nombre de la empresa)",
  english: "inglés (el idioma)",
  spanish: "español (el idioma)",
  dallas: "Dallas (ciudad de Texas)",
  florida: "Florida (estado de EE. UU.)",
  bigtalk: "BigTalk (la academia competidora)",
  "bigtalk's": "de BigTalk",
  "sofía": "Sofía (personaje)",
  "sofía's": "de Sofía",
  "sofia": "Sofía (personaje)",
  bryan: "Bryan (personaje)",
  gabi: "Gabi (personaje)",
  herrera: "Mr. Herrera (personaje)",
  rosa: "Rosa (personaje)",
  rosario: "Rosario (personaje)",
  lidia: "Lidia (personaje)",
  barrett: "Ms. Barrett (personaje)",
  crown: "Crown (empresa del cuento)",
  "crown's": "de Crown",
  warns: "advierte",
  positive: "positivo / afirmativo",
  frame: "enmarcar / plantear",
  sinks: "se hunde",
  context: "contexto",
  operating: "funcionando / operando",
  led: "dirigido / liderado (pasado de lead)",
  sake: "bien / causa (for the sake of: por el bien de)",
  given: "dado / entregado (pasado de give)",
  former: "anterior / antiguo",
  size: "tamaño",
  site: "sitio / lugar",
  whom: "a quién / a quien",
  product: "producto",
  honesty: "honestidad",
  "forty-one": "cuarenta y uno",
  cent: "por ciento (per cent)",
  "eighty-eight": "ochenta y ocho",
  shut: "cerrar / cerré",
  exit: "salida",
  quit: "renunciar / dejar",
  whoever: "quienquiera que",
  agent: "agente",
  agents: "agentes",
  "ninety-day": "de noventa días",
  openings: "vacantes / puestos disponibles",
  comfort: "comodidad",
  above: "por encima de / arriba de",
  treat: "tratar",
  sixth: "sexto",
  able: "capaz (be able to: poder)",
  panel: "panel / comité",
  interruption: "interrupción",
  performance: "desempeño / rendimiento",
  "call-handling": "manejo de llamadas",
  band: "rango / banda (salarial)",
  replacing: "reemplazando",
  programme: "programa",
  senior: "sénior / con más experiencia",
  teenagers: "adolescentes",
  "bogotá": "Bogotá (ciudad de Colombia)",
  february: "febrero",
  "seventy-five": "setenta y cinco",
  current: "actual",
};

/** Contractions keep their apostrophe after normalizeWord. */
export const CONTRACTIONS: Record<string, string> = {
  "i'm": "yo soy / yo estoy",
  "i'll": "yo voy a / yo (futuro)",
  "i'd": "yo (condicional: yo would)",
  "you'd": "tú (condicional: you would)",
  "we'd": "nosotros (condicional: we would)",
  "i've": "yo he (ya hice)",
  "you're": "tú eres / tú estás",
  "you'll": "tú vas a",
  "you've": "tú has (ya hiciste)",
  "he's": "él es / él está",
  "she's": "ella es / ella está",
  "it's": "es / está",
  "that's": "eso es",
  "there's": "hay",
  "here's": "aquí está",
  "we're": "nosotros somos / estamos",
  "we'll": "nosotros vamos a",
  "we've": "nosotros hemos",
  "they're": "ellos son / están",
  "they'll": "ellos van a",
  "they've": "ellos han",
  "they'd": "ellos (condicional: they would)",
  "let's": "vamos a (hagamos)",
  "don't": "no (negación con do)",
  "doesn't": "no (negación con does)",
  "didn't": "no (negación en pasado)",
  "isn't": "no es / no está",
  "aren't": "no son / no están",
  "wasn't": "no era / no estaba",
  "weren't": "no eran / no estaban",
  "won't": "no va a (futuro negativo)",
  "can't": "no puede / no puedo",
  "couldn't": "no pudo / no podía",
  "hadn't": "no había / no habías (negación en pasado perfecto)",
  "shouldn't": "no debería",
  "wouldn't": "no lo haría",
  "haven't": "no he / no han",
  "hasn't": "no ha",
  "doesnt": "no (negación con does)",
};

/** Frequent irregular past forms: [Spanish meaning, base form]. */
export const IRREGULAR_PAST: Record<string, [string, string]> = {
  said: ["dijo / dije", "say"],
  went: ["fue / fui", "go"],
  came: ["vino / vine", "come"],
  took: ["tomó / tomé", "take"],
  got: ["consiguió / recibió", "get"],
  saw: ["vio / vi", "see"],
  made: ["hizo / hice", "make"],
  gave: ["dio / di", "give"],
  knew: ["sabía / conocía", "know"],
  felt: ["sintió / sentí", "feel"],
  told: ["le dijo / le dije", "tell"],
  found: ["encontró / encontré", "find"],
  thought: ["pensó / pensé", "think"],
  heard: ["escuchó / escuché", "hear"],
  left: ["se fue / dejó", "leave"],
  kept: ["mantuvo / guardó", "keep"],
  sent: ["envió / envié", "send"],
  spoke: ["habló / hablé", "speak"],
  wrote: ["escribió / escribí", "write"],
  read: ["leer / leyó", "read"],
  ran: ["corrió / corrí", "run"],
  won: ["ganó / gané", "win"],
  lost: ["perdió / perdí", "lose"],
  brought: ["trajo / traje", "bring"],
  bought: ["compró / compré", "buy"],
  paid: ["pagó / pagué", "pay"],
  put: ["puso / puse", "put"],
  met: ["conoció / se reunió con", "meet"],
  held: ["sostuvo / tuvo", "hold"],
  stood: ["se paró / estaba de pie", "stand"],
  sat: ["se sentó", "sit"],
  ate: ["comió / comí", "eat"],
  drank: ["bebió / bebí", "drink"],
  slept: ["durmió / dormí", "sleep"],
  woke: ["despertó / desperté", "wake"],
  began: ["empezó / empecé", "begin"],
  became: ["se convirtió en", "become"],
  chose: ["eligió / elegí", "choose"],
  taught: ["enseñó / enseñé", "teach"],
  understood: ["entendió / entendí", "understand"],
  grew: ["creció / crecí", "grow"],
  built: ["construyó / construí", "build"],
  broke: ["rompió / rompí", "break"],
  drove: ["manejó / manejé", "drive"],
  flew: ["voló / volé", "fly"],
  sold: ["vendió / vendí", "sell"],
  did: ["hizo / hice", "do"],
  had: ["tenía / tuvo", "have"],
  was: ["era / estaba / fue", "be"],
  were: ["eran / estaban / fueron", "be"],
  been: ["sido / estado", "be"],
  gone: ["ido", "go"],
  done: ["hecho", "do"],
  seen: ["visto", "see"],
  spent: ["gastó / pasó (tiempo)", "spend"],
  hung: ["colgó", "hang"],

};

/** Lowercase and strip quotes/punctuation so "Says," matches "says". */
export function normalizeWord(word: string): string {
  return word
    .toLowerCase()
    .replace(/[’‘]/g, "'")
    .replace(/[“”".,!?;:()¿¡…—–]/g, "")
    .trim()
    .replace(/^'+|'+$/g, "");
}

/** All curated words of an episode (every scene + review words), lowercased. */
export function buildEpisodeGlossary(episode: StorybookEpisode): Map<string, string> {
  const map = new Map<string, string>();
  // Global phrasal verbs / idioms first: the episode's own words and
  // expressions below can always override them.
  for (const [phrase, es] of globalExpressionMap()) map.set(phrase, es);
  for (const w of episode.reviewWords ?? []) map.set(normalizeWord(w.word), w.es);
  for (const scene of episode.scenes) {
    for (const w of scene.words) map.set(normalizeWord(w.word), w.es);
  }
  for (const expression of episode.expressions ?? []) {
    map.set(normalizeWord(expression.phrase), expression.es);
    for (const variant of expression.variants ?? []) {
      map.set(normalizeWord(variant), expression.es);
    }
  }
  return map;
}

export type WordLookup = {
  /** Spanish meaning, or null when we have no hand-written meaning. */
  meaning: string | null;
  /** True when the word is a curated key word of the current scene. */
  curated: boolean;
};

/** Candidate base forms for a possibly inflected word. */
function baseForms(key: string): string[] {
  const out: string[] = [];
  const push = (w: string) => {
    if (w.length >= 2 && !out.includes(w)) out.push(w);
  };
  const doubled = /(.)\1$/.test(key.slice(0, -2));

  if (key.endsWith("ies")) push(key.slice(0, -3) + "y");
  if (key.endsWith("es")) push(key.slice(0, -2));
  if (key.endsWith("s") && !key.endsWith("ss")) push(key.slice(0, -1));
  if (key.endsWith("ied")) push(key.slice(0, -3) + "y");
  if (key.endsWith("ed")) {
    push(key.slice(0, -1)); // liked -> like
    push(key.slice(0, -2)); // asked -> ask
    if (doubled) push(key.slice(0, -3)); // stopped -> stop
  }
  if (key.endsWith("ing")) {
    push(key.slice(0, -3)); // asking -> ask
    push(key.slice(0, -3) + "e"); // making -> make
    if (/(.)\1$/.test(key.slice(0, -3))) push(key.slice(0, -4)); // running -> run
  }
  if (key.endsWith("ly")) push(key.slice(0, -2));
  if (key.endsWith("'s")) push(key.slice(0, -2));
  return out;
}

/** Label a derived form so the learner sees the base word too. */
function describeForm(key: string, base: string, baseMeaning: string): string {
  if (key.endsWith("ing")) return `${baseMeaning} — forma -ing de "${base}"`;
  if (key.endsWith("ed") || key.endsWith("ied")) return `${baseMeaning} — pasado de "${base}"`;
  if (key.endsWith("ly")) return `${baseMeaning} — de forma "${base}"`;
  if (key.endsWith("'s")) return `de ${base} (posesivo)`;
  if (key.endsWith("s")) return `${baseMeaning} — forma de "${base}"`;
  return baseMeaning;
}

/**
 * Resolve a tapped word: current scene → rest of the episode → base glossary →
 * proper nouns / contractions / irregular past → derived form of a known word.
 */
export function lookupWord(
  word: string,
  options: { scene?: StorybookScene | undefined; episodeGlossary?: Map<string, string> | undefined } = {},
): WordLookup {
  const key = normalizeWord(word);
  if (!key) return { meaning: null, curated: false };

  // Numbers and single letters ("option B", "8:57") get a plain explanation.
  if (/^\d+([:.]\d+)?$/.test(key)) {
    return { meaning: key.includes(":") ? `la hora ${key}` : `el número ${key}`, curated: false };
  }
  if (key.length === 1 && /[a-z]/.test(key)) {
    return { meaning: `la letra "${key.toUpperCase()}"`, curated: false };
  }

  const sceneWord = options.scene?.words.find((w) => normalizeWord(w.word) === key);
  if (sceneWord) return { meaning: sceneWord.es, curated: true };

  const fromEpisode = options.episodeGlossary?.get(key);
  if (fromEpisode) return { meaning: fromEpisode, curated: key.includes(" ") };

  // Complete expressions (phrasal verbs / idioms) always win over the words.
  const fromExpressions = globalExpressionMap().get(key);
  if (fromExpressions) return { meaning: fromExpressions, curated: true };


  const direct =
    BASE_GLOSSARY[key] ??
    PROPER_NOUNS[key] ??
    CONTRACTIONS[key] ??
    (IRREGULAR_PAST[key] ? `${IRREGULAR_PAST[key]![0]} (pasado de "${IRREGULAR_PAST[key]![1]}")` : undefined);
  if (direct) return { meaning: direct, curated: false };

  for (const base of baseForms(key)) {
    const baseMeaning =
      options.episodeGlossary?.get(base) ??
      BASE_GLOSSARY[base] ??
      PROPER_NOUNS[base] ??
      (IRREGULAR_PAST[base] ? IRREGULAR_PAST[base]![0] : undefined);
    if (baseMeaning) return { meaning: describeForm(key, base, baseMeaning), curated: false };
  }

  return { meaning: null, curated: false };
}

