import type { StorybookEpisode } from "./types";
import cover from "@/assets/storybook/vale-ep18/cover.jpg";
import s1 from "@/assets/storybook/vale-ep18/s1.jpg"; import s2 from "@/assets/storybook/vale-ep18/s2.jpg"; import s3 from "@/assets/storybook/vale-ep18/s3.jpg"; import s4 from "@/assets/storybook/vale-ep18/s4.jpg"; import s5 from "@/assets/storybook/vale-ep18/s5.jpg"; import s6 from "@/assets/storybook/vale-ep18/s6.jpg"; import s7 from "@/assets/storybook/vale-ep18/s7.jpg"; import s8 from "@/assets/storybook/vale-ep18/s8.jpg"; import s9 from "@/assets/storybook/vale-ep18/s9.jpg"; import s10 from "@/assets/storybook/vale-ep18/s10.jpg";

export const VALE_FIRST_MONTH: StorybookEpisode = {
  id: "vale-first-month", moduleId: "basic-zero", week: 4, title: "Vale's first month", titleEs: "El primer mes de Vale", episodeLabel: { en: "Episode 18", es: "Episodio 18" },
  previously: [{ en: "Luis has a new job. The family celebrates.", es: "Luis tiene un trabajo nuevo. La familia celebra." }, { en: "Luis says: everything is possible with effort.", es: "Luis dice: todo es posible con esfuerzo." }, { en: "Now Ana calls Vale to her office…", es: "Ahora Ana llama a Vale a su oficina…" }],
  reviewWords: [{ word: "office", es: "oficina" }, { word: "important", es: "importante" }, { word: "proud", es: "orgullosa" }],
  blurb: { en: "One month of work. One big surprise in Ana's office.", es: "Un mes de trabajo. Una gran sorpresa en la oficina de Ana." }, cover, voice: "girl",
  scenes: [
    { id: "s1", image: s1, imageAlt: "Vale nerviosa frente a Ana en la oficina.", text: "Vale is a little nervous. Why is she in Ana's office?", es: "Vale está un poco nerviosa. ¿Por qué está en la oficina de Ana?", words: [{ word: "nervous", es: "nerviosa" }, { word: "why", es: "por qué" }] },
    { id: "s2", image: s2, imageAlt: "Ana muestra los resultados de Vale.", text: '"Vale, look. One month. Your numbers are very good," says Ana.', es: "«Vale, mira. Un mes. Tus números son muy buenos», dice Ana.", speaker: "ana", words: [{ word: "month", es: "mes" }, { word: "numbers", es: "números" }] },
    { id: "s3", image: s3, imageAlt: "Vale recuerda su primer día asustada.", text: "This is Vale on her first day. She is scared in front of the big door.", es: "Esta es Vale en su primer día. Está asustada frente a la puerta grande.", words: [{ word: "scared", es: "asustada" }, { word: "door", es: "puerta" }] },
    { id: "s4", image: s4, imageAlt: "Vale hoy, segura, ayudando a un cliente.", text: "Today, Vale helps clients every day. She is calm and strong.", es: "Hoy, Vale ayuda a clientes todos los días. Está tranquila y fuerte.", words: [{ word: "every day", es: "todos los días" }, { word: "calm", es: "tranquila" }] },
    { id: "s5", image: s5, imageAlt: "Ana habla de la disciplina de Vale.", text: '"You practice English every day at six. You are disciplined," says Ana.', es: "«Practicas inglés todos los días a las seis. Eres disciplinada», dice Ana.", speaker: "ana", words: [{ word: "practice", es: "practicas" }, { word: "disciplined", es: "disciplinada" }] },
    { id: "s6", image: s6, imageAlt: "Vale practica en casa por la noche.", text: "It is true. Every night, Vale practices with her notebook and her phone.", es: "Es verdad. Cada noche, Vale practica con su cuaderno y su teléfono.", words: [{ word: "true", es: "verdad" }, { word: "night", es: "noche" }] },
    { id: "s7", image: s7, imageAlt: "Ana le da una estrella dorada a Vale.", text: '"This star is for you. You are the student of the month," says Ana.', es: "«Esta estrella es para ti. Eres la estudiante del mes», dice Ana.", speaker: "ana", words: [{ word: "star", es: "estrella" }, { word: "student", es: "estudiante" }] },
    { id: "s8", image: s8, imageAlt: "El equipo aplaude a Vale.", text: "Mateo, Kat and Ana clap for Vale. The team is happy for her.", es: "Mateo, Kat y Ana aplauden a Vale. El equipo está feliz por ella.", words: [{ word: "clap", es: "aplauden" }, { word: "for", es: "por" }] },
    { id: "s9", image: s9, imageAlt: "Mamá abraza a Vale en casa.", text: "At home, Vale shows the star to her mom. Her mom hugs her tight.", es: "En casa, Vale le muestra la estrella a su mamá. Su mamá la abraza fuerte.", words: [{ word: "shows", es: "muestra" }, { word: "hugs", es: "abraza" }] },
    { id: "s10", image: s10, imageAlt: "Vale ve un anuncio de fiesta en la pared.", text: "The next day, Vale sees a big flyer on the wall. A party? For the team?", es: "Al día siguiente, Vale ve un gran anuncio en la pared. ¿Una fiesta? ¿Para el equipo?", words: [{ word: "party", es: "fiesta" }, { word: "wall", es: "pared" }] },
  ],
  quizzes: [
    { id: "q1", afterScene: "s2", questionEn: "How are Vale's numbers?", questionEs: "¿Cómo son los números de Vale?", options: [{ label: "Very good", emoji: "📈" }, { label: "Very bad", emoji: "📉" }, { label: "There are none", emoji: "🚫" }], answer: 0, sayIt: "My numbers are very good.", sayItEs: "Repite: «Mis números son muy buenos.»" },
    { id: "q2", afterScene: "s6", questionEn: "When does Vale practice English?", questionEs: "¿Cuándo practica inglés Vale?", options: [{ label: "Every day", emoji: "📆" }, { label: "Never", emoji: "🙅" }, { label: "Only on Sundays", emoji: "⛪" }], answer: 0, sayIt: "I practice English every day.", sayItEs: "Repite: «Practico inglés todos los días.»" },
    { id: "q3", afterScene: "s7", questionEn: "What is the star for?", questionEs: "¿Para qué es la estrella?", options: [{ label: "Student of the month", emoji: "⭐" }, { label: "A birthday", emoji: "🎂" }, { label: "The door", emoji: "🚪" }], answer: 0, sayIt: "I am the student of the month.", sayItEs: "Repite: «Soy la estudiante del mes.»" },
  ],
  mindsetCard: { afterScene: "s5", phrase: "I am disciplined.", es: "Soy disciplinada." },
  continuePrompt: { en: "Talk about your month: what do you do every day?", es: "Habla de tu mes: ¿qué haces todos los días?" }, continueWith: ["I practice every day.", "I am disciplined.", "I am calm and strong.", "This star is for me."],
  cliffhanger: { en: "A party for the team! But who has the idea… and why?", es: "¡Una fiesta para el equipo! ¿Pero quién tiene la idea… y por qué?" },
};
