import type { StorybookEpisode } from "./types";
import cover from "@/assets/storybook/vale-ep13/cover.jpg";
import s1 from "@/assets/storybook/vale-ep13/s1.jpg"; import s2 from "@/assets/storybook/vale-ep13/s2.jpg"; import s3 from "@/assets/storybook/vale-ep13/s3.jpg"; import s4 from "@/assets/storybook/vale-ep13/s4.jpg"; import s5 from "@/assets/storybook/vale-ep13/s5.jpg"; import s6 from "@/assets/storybook/vale-ep13/s6.jpg"; import s7 from "@/assets/storybook/vale-ep13/s7.jpg"; import s8 from "@/assets/storybook/vale-ep13/s8.jpg"; import s9 from "@/assets/storybook/vale-ep13/s9.jpg"; import s10 from "@/assets/storybook/vale-ep13/s10.jpg";

export const VALE_NEW_SUPERVISOR: StorybookEpisode = {
  id: "vale-new-supervisor", moduleId: "basic-zero", week: 4, title: "Who is the new supervisor?", titleEs: "¿Quién es la nueva supervisora?", episodeLabel: { en: "Episode 13", es: "Episodio 13" },
  previously: [{ en: "Vale introduced Camila to the team.", es: "Vale presentó a Camila al equipo." }, { en: "Camila is from Honduras.", es: "Camila es de Honduras." }, { en: "A red folder arrived for the new supervisor.", es: "Llegó una carpeta roja para la nueva supervisora." }],
  reviewWords: [{ word: "introduce", es: "presentar" }, { word: "from", es: "de (origen)" }, { word: "team", es: "equipo" }],
  blurb: { en: "The new supervisor arrives with a red folder. It is about Vale.", es: "Llega la nueva supervisora con una carpeta roja. Es sobre Vale." }, cover, voice: "girl",
  scenes: [
    { id: "s1", image: s1, imageAlt: "El equipo mira una carpeta roja en el escritorio.", text: "Today the red folder is on the desk. Everybody looks at it.", es: "Hoy la carpeta roja está en el escritorio. Todos la miran.", words: [{ word: "folder", es: "carpeta" }, { word: "desk", es: "escritorio" }] },
    { id: "s2", image: s2, imageAlt: "Vale nerviosa junto a Mateo.", text: '"I am nervous. Who is the new supervisor?" says Vale.', es: "«Estoy nerviosa. ¿Quién es la nueva supervisora?», dice Vale.", speaker: "vale", words: [{ word: "nervous", es: "nerviosa" }, { word: "supervisor", es: "supervisora" }] },
    { id: "s3", image: s3, imageAlt: "Ana entra a la oficina con la carpeta roja.", text: "A woman with a red folder comes into the office.", es: "Una mujer con una carpeta roja entra a la oficina.", words: [{ word: "woman", es: "mujer" }, { word: "office", es: "oficina" }] },
    { id: "s4", image: s4, imageAlt: "Ana se presenta al equipo.", text: '"Hello, everyone. My name is Ana. I am from Mexico City," she says.', es: "«Hola a todos. Me llamo Ana. Soy de Ciudad de México», dice ella.", speaker: "ana", words: [{ word: "hello", es: "hola" }, { word: "city", es: "ciudad" }] },
    { id: "s5", image: s5, imageAlt: "El señor Reyes presenta a Ana.", text: '"This is Ana. She is our new supervisor. She works here now," says Mr. Reyes.', es: "«Esta es Ana. Ella es nuestra nueva supervisora. Ahora trabaja aquí», dice el señor Reyes.", speaker: "boss", words: [{ word: "new", es: "nueva" }, { word: "works", es: "trabaja" }] },
    { id: "s6", image: s6, imageAlt: "Ana abre la carpeta roja.", text: '"This folder is about one person here. Her name is Vale," says Ana.', es: "«Esta carpeta es sobre una persona de aquí. Su nombre es Vale», dice Ana.", speaker: "ana", words: [{ word: "about", es: "sobre / acerca de" }, { word: "person", es: "persona" }] },
    { id: "s7", image: s7, imageAlt: "Vale asustada con las manos frías.", text: "Vale is scared. Her hands are cold.", es: "Vale está asustada. Sus manos están frías.", words: [{ word: "scared", es: "asustada" }, { word: "cold", es: "frías" }] },
    { id: "s8", image: s8, imageAlt: "Vale respira y se dice una afirmación.", text: '"I am calm. I am ready. Mistakes are part of the process," says Vale.', es: "«Estoy tranquila. Estoy lista. Los errores son parte del proceso», dice Vale.", speaker: "vale", words: [{ word: "calm", es: "tranquila" }, { word: "ready", es: "lista" }] },
    { id: "s9", image: s9, imageAlt: "Ana le entrega una hoja a Vale.", text: '"Good news, Vale. You are a candidate for our leaders program," says Ana.', es: "«Buenas noticias, Vale. Eres candidata para nuestro programa de líderes», dice Ana.", speaker: "ana", words: [{ word: "news", es: "noticias" }, { word: "leaders", es: "líderes" }] },
    { id: "s10", image: s10, imageAlt: "Ana señala un cliente molesto en la pantalla.", text: '"But first, a difficult client calls tomorrow. His name is Dylan," says Ana.', es: "«Pero primero, mañana llama un cliente difícil. Su nombre es Dylan», dice Ana.", speaker: "ana", words: [{ word: "difficult", es: "difícil" }, { word: "client", es: "cliente" }] },
  ],
  quizzes: [
    { id: "q1", afterScene: "s4", questionEn: "What is her name?", questionEs: "¿Cómo se llama ella?", options: [{ label: "Ana", emoji: "👩‍💼" }, { label: "Kat", emoji: "🧡" }, { label: "Camila", emoji: "💜" }], answer: 0, sayIt: "Her name is Ana.", sayItEs: "Repite: «Su nombre es Ana.»" },
    { id: "q2", afterScene: "s5", questionEn: "Where is Ana from?", questionEs: "¿De dónde es Ana?", options: [{ label: "Mexico City", emoji: "🇲🇽" }, { label: "Honduras", emoji: "🇭🇳" }, { label: "Canada", emoji: "🇨🇦" }], answer: 0, sayIt: "She is from Mexico City.", sayItEs: "Repite: «Ella es de Ciudad de México.»" },
    { id: "q3", afterScene: "s9", questionEn: "Is the news good or bad?", questionEs: "¿La noticia es buena o mala?", options: [{ label: "Good news", emoji: "🎉" }, { label: "Bad news", emoji: "😢" }, { label: "No news", emoji: "🤔" }], answer: 0, sayIt: "This is my supervisor. Her name is…", sayItEs: "Ahora presenta a tu supervisora." },
  ],
  mindsetCard: { afterScene: "s8", phrase: "I am calm. I am ready. Mistakes are part of the process.", es: "Estoy tranquila. Estoy lista. Los errores son parte del proceso." },
  continuePrompt: { en: "Introduce a leader you know: name, city and job.", es: "Presenta a un líder que conozcas: nombre, ciudad y trabajo." }, continueWith: ["This is…", "Her or his name is…", "She or he is from…", "She or he works here."],
  cliffhanger: { en: "Tomorrow the phone rings. Dylan has a big problem.", es: "Mañana suena el teléfono. Dylan tiene un gran problema." },
};
