import type { StorybookEpisode } from "./types";
import cover from "@/assets/storybook/vale-ep20/cover.jpg";
import s1 from "@/assets/storybook/vale-ep20/s1.jpg"; import s2 from "@/assets/storybook/vale-ep20/s2.jpg"; import s3 from "@/assets/storybook/vale-ep20/s3.jpg"; import s4 from "@/assets/storybook/vale-ep20/s4.jpg"; import s5 from "@/assets/storybook/vale-ep20/s5.jpg"; import s6 from "@/assets/storybook/vale-ep20/s6.jpg"; import s7 from "@/assets/storybook/vale-ep20/s7.jpg"; import s8 from "@/assets/storybook/vale-ep20/s8.jpg"; import s9 from "@/assets/storybook/vale-ep20/s9.jpg"; import s10 from "@/assets/storybook/vale-ep20/s10.jpg";

export const VALE_GRADUATION: StorybookEpisode = {
  id: "vale-graduation", moduleId: "basic-zero", week: 4, title: "Graduation day", titleEs: "El día de graduación", episodeLabel: { en: "Episode 20", es: "Episodio 20" },
  previously: [{ en: "The team has a surprise party for Vale.", es: "El equipo hace una fiesta sorpresa para Vale." }, { en: "There are balloons, pupusas and a piñata.", es: "Hay globos, pupusas y una piñata." }, { en: "At the end, Mr. Reyes has a white envelope with her name.", es: "Al final, Mr. Reyes tiene un sobre blanco con su nombre." }],
  reviewWords: [{ word: "envelope", es: "sobre" }, { word: "party", es: "fiesta" }, { word: "team", es: "equipo" }],
  blurb: { en: "The last day of Level One. What is inside the envelope?", es: "El último día del Nivel Uno. ¿Qué hay dentro del sobre?" }, cover, voice: "girl",
  scenes: [
    { id: "s1", image: s1, imageAlt: "Vale abre el sobre blanco.", text: "Vale opens the white envelope. Her hands are a little nervous.", es: "Vale abre el sobre blanco. Sus manos están un poco nerviosas.", words: [{ word: "opens", es: "abre" }, { word: "nervous", es: "nerviosas" }] },
    { id: "s2", image: s2, imageAlt: "Vale ve su diploma con una estrella dorada.", text: "It is a diploma! \"Vale finishes Level One.\" A golden star shines on top.", es: "¡Es un diploma! «Vale termina el Nivel Uno». Una estrella dorada brilla arriba.", words: [{ word: "diploma", es: "diploma" }, { word: "finishes", es: "termina" }] },
    { id: "s3", image: s3, imageAlt: "Recuerdo del primer día de Vale nerviosa frente a la puerta.", text: "Vale remembers her first day. She is so small and nervous in front of the big door.", es: "Vale recuerda su primer día. Está tan pequeña y nerviosa frente a la puerta grande.", words: [{ word: "remembers", es: "recuerda" }, { word: "first day", es: "primer día" }] },
    { id: "s4", image: s4, imageAlt: "Vale hoy, segura en su escritorio ayudando a un cliente.", text: "And now? She helps clients every day. She is not afraid anymore.", es: "¿Y ahora? Ayuda a clientes todos los días. Ya no tiene miedo.", words: [{ word: "clients", es: "clientes" }, { word: "afraid", es: "con miedo" }] },
    { id: "s5", image: s5, imageAlt: "Mr. Reyes entrega el diploma a Vale.", text: "Mr. Reyes gives her the diploma. \"Good job, Vale. We are proud of you.\"", es: "Mr. Reyes le entrega el diploma. «Buen trabajo, Vale. Estamos orgullosos de ti.»", speaker: "boss", words: [{ word: "gives", es: "entrega" }, { word: "proud", es: "orgullosos" }] },
    { id: "s6", image: s6, imageAlt: "El equipo celebra con confeti.", text: "Confetti! The team is so happy. \"You are amazing!\" shouts Kat.", es: "¡Confeti! El equipo está muy feliz. «¡Eres increíble!», grita Kat.", speaker: "kat", words: [{ word: "confetti", es: "confeti" }, { word: "shouts", es: "grita" }] },
    { id: "s7", image: s7, imageAlt: "Luis abraza a Vale en casa.", text: "At home, Luis hugs his little sister. Mom cries happy tears.", es: "En casa, Luis abraza a su hermanita. Mamá llora lágrimas de felicidad.", words: [{ word: "hugs", es: "abraza" }, { word: "tears", es: "lágrimas" }] },
    { id: "s8", image: s8, imageAlt: "Vale pone su diploma en la pared de su cuarto.", text: "At night, Vale puts the diploma on her wall, next to her golden star.", es: "Por la noche, Vale pone el diploma en su pared, junto a su estrella dorada.", words: [{ word: "puts", es: "pone" }, { word: "wall", es: "pared" }] },
    { id: "s9", image: s9, imageAlt: "Vale da un pequeño discurso de gracias.", text: "\"Thank you, team. English is easy when you practice every day. I can do it — and you can do it too!\"", es: "«Gracias, equipo. El inglés es fácil cuando practicas todos los días. ¡Yo puedo hacerlo, y ustedes también!»", speaker: "vale", words: [{ word: "practice", es: "practicas" }, { word: "too", es: "también" }] },
    { id: "s10", image: s10, imageAlt: "Ana habla por teléfono al atardecer con una sonrisa misteriosa.", text: "At the window, Ana answers her phone. \"Yes… she is ready.\" A new challenge is coming.", es: "En la ventana, Ana contesta su teléfono. «Sí… ella está lista». Un nuevo reto viene en camino.", words: [{ word: "answers", es: "contesta" }, { word: "ready", es: "lista" }] },
  ],
  quizzes: [
    { id: "q1", afterScene: "s2", questionEn: "What is inside the envelope?", questionEs: "¿Qué hay dentro del sobre?", options: [{ label: "A diploma", emoji: "🎓" }, { label: "Money", emoji: "💵" }, { label: "A photo", emoji: "📷" }], answer: 0, sayIt: "It is a diploma!", sayItEs: "Repite: «¡Es un diploma!»" },
    { id: "q2", afterScene: "s5", questionEn: "How does the team feel?", questionEs: "¿Cómo se siente el equipo?", options: [{ label: "Proud of Vale", emoji: "🥹" }, { label: "Angry", emoji: "😠" }, { label: "Sleepy", emoji: "😴" }], answer: 0, sayIt: "We are proud of you.", sayItEs: "Repite: «Estamos orgullosos de ti.»" },
    { id: "q3", afterScene: "s9", questionEn: "What is Vale's secret?", questionEs: "¿Cuál es el secreto de Vale?", options: [{ label: "She practices every day", emoji: "📆" }, { label: "She is lucky", emoji: "🍀" }, { label: "She never works", emoji: "🛋️" }], answer: 0, sayIt: "I practice every day.", sayItEs: "Repite: «Practico todos los días.»" },
  ],
  mindsetCard: { afterScene: "s4", phrase: "English is easy. I can do it.", es: "El inglés es fácil. Yo puedo hacerlo." },
  continuePrompt: { en: "Talk about your first month: what can you do now?", es: "Habla de tu primer mes: ¿qué puedes hacer ahora?" }, continueWith: ["My name is…", "I can…", "I am proud of…", "English is easy."],
  cliffhanger: { en: "\"She is ready.\" Ready for what? Season 2 is coming!", es: "«Ella está lista». ¿Lista para qué? ¡La Temporada 2 viene!" },
};
