import type { InteractiveStory } from "./types";

/** Pilot interactive story — simple present, A1/A2, ~180 words. */
export const LUNA_AND_THE_LOST_PHONE: InteractiveStory = {
  id: "luna-and-the-lost-phone",
  title: "Luna and the Lost Phone",
  titleEs: "Luna y el teléfono perdido",
  level: "basic",
  voice: "female",
  blurb: {
    en: "A cat finds a phone in the park and looks for its owner.",
    es: "Una gata encuentra un teléfono en el parque y busca a su dueño.",
  },
  lines: [
    { id: "l1", text: "Luna is a small gray cat.", es: "Luna es una gata pequeña y gris." },
    { id: "l2", text: "She lives near a green park.", es: "Ella vive cerca de un parque verde." },
    { id: "l3", text: "Every morning, Luna walks on the grass.", es: "Cada mañana, Luna camina sobre el césped." },
    { id: "l4", text: "Today she finds a shiny phone under a bench.", es: "Hoy ella encuentra un teléfono brillante debajo de una banca." },
    { id: "l5", text: "The phone rings loudly.", es: "El teléfono suena fuerte." },
    { id: "l6", text: "Luna jumps and hides behind a tree.", es: "Luna salta y se esconde detrás de un árbol." },
    { id: "l7", text: "Then she looks again.", es: "Luego mira otra vez." },
    { id: "l8", text: "The screen shows a picture of a boy.", es: "La pantalla muestra la foto de un niño." },
    { id: "l9", text: "The boy smiles and holds a red ball.", es: "El niño sonríe y sostiene una pelota roja." },
    { id: "l10", text: "Luna wants to help him.", es: "Luna quiere ayudarlo." },
    { id: "l11", text: "She pushes the phone with her nose.", es: "Ella empuja el teléfono con la nariz." },
    { id: "l12", text: "She carries it across the park.", es: "Lo lleva por todo el parque." },
    { id: "l13", text: "Near the gate, a boy cries.", es: "Cerca de la entrada, un niño llora." },
    { id: "l14", text: "He looks for something in his bag.", es: "Él busca algo en su mochila." },
    { id: "l15", text: "Luna drops the phone next to his shoes.", es: "Luna deja caer el teléfono junto a sus zapatos." },
    { id: "l16", text: "The boy laughs and says, \"Thank you, little cat!\"", es: "El niño ríe y dice: «¡Gracias, gatita!»" },
    { id: "l17", text: "Now Luna has a new friend.", es: "Ahora Luna tiene un nuevo amigo." },
    { id: "l18", text: "They meet in the park every day.", es: "Se encuentran en el parque todos los días." },
  ],
  vocab: [
    { word: "park", es: "parque", from: "She lives near a green park." },
    { word: "grass", es: "césped, pasto", from: "Every morning, Luna walks on the grass." },
    { word: "bench", es: "banca", from: "Today she finds a shiny phone under a bench." },
    { word: "shiny", es: "brillante", from: "Today she finds a shiny phone under a bench." },
    { word: "loudly", es: "fuerte, en voz alta", from: "The phone rings loudly." },
    { word: "hides", es: "se esconde", from: "Luna jumps and hides behind a tree." },
    { word: "screen", es: "pantalla", from: "The screen shows a picture of a boy." },
    { word: "holds", es: "sostiene", from: "The boy smiles and holds a red ball." },
    { word: "pushes", es: "empuja", from: "She pushes the phone with her nose." },
    { word: "carries", es: "lleva, carga", from: "She carries it across the park." },
    { word: "gate", es: "entrada, portón", from: "Near the gate, a boy cries." },
    { word: "drops", es: "deja caer", from: "Luna drops the phone next to his shoes." },
  ],
  questions: [
    { id: "q1", en: "Who is Luna and where does she live?", es: "¿Quién es Luna y dónde vive?" },
    { id: "q2", en: "What does Luna find in the park?", es: "¿Qué encuentra Luna en el parque?" },
    { id: "q3", en: "Why does the boy say thank you?", es: "¿Por qué el niño dice gracias?" },
  ],
  continueWith: ["park", "friend", "phone", "every day", "happy"],
};
